//! Collision-safe numbering transport for package coexistence.
//!
//! `w:numId` and `w:abstractNumId` are package-local identities. This operation
//! rewrites a target package and its typed document together when a source
//! package already uses the same IDs for a different list definition. It does
//! not infer correspondence or author revisions; downstream callers decide how
//! to switch the resulting references through native Word carriers.

use std::collections::{HashMap, HashSet};
use std::io::Cursor;

use xmltree::{Element, XMLNode};

use crate::docx_package::DocxPackage;
use crate::runtime::{ErrorCode, ErrorDetails, RuntimeError};
use crate::word_xml::{self, is_w_tag};
use crate::xml_attrs::{attr_get, attr_set};

const NUMBERING_REL_TYPE: &str =
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering";

fn error(code: ErrorCode, message: impl Into<String>, context: impl Into<String>) -> RuntimeError {
    RuntimeError {
        code,
        message: message.into(),
        details: ErrorDetails {
            context: Some(context.into()),
            ..ErrorDetails::default()
        },
    }
}

fn numbering_part(
    package: &DocxPackage,
    label: &str,
) -> Result<Option<(String, Element)>, RuntimeError> {
    let Some(relationship) = package
        .document_rels
        .entries
        .iter()
        .find(|relationship| relationship.rel_type == NUMBERING_REL_TYPE)
    else {
        return Ok(None);
    };
    if relationship.target_mode.as_deref() == Some("External") {
        return Err(error(
            ErrorCode::InvalidDocx,
            "numbering relationship must target an internal package part",
            format!(
                "label={label} relationship_id={} target={}",
                relationship.id, relationship.target
            ),
        ));
    }
    let path = package
        .document_rels
        .resolve_internal_target(&relationship.target);
    let bytes = package.get_part(&path).ok_or_else(|| {
        error(
            ErrorCode::InvalidDocx,
            "numbering relationship resolves to an absent package part",
            format!(
                "label={label} relationship_id={} resolved_part={path}",
                relationship.id
            ),
        )
    })?;
    let root = Element::parse(Cursor::new(bytes)).map_err(|source| {
        error(
            ErrorCode::InvalidDocx,
            format!("failed to parse {label} numbering part"),
            format!("part={path} parse_error={source}"),
        )
    })?;
    Ok(Some((path, root)))
}

fn abstract_num_id(num: &Element) -> Option<u32> {
    num.children.iter().find_map(|child| {
        let XMLNode::Element(element) = child else {
            return None;
        };
        is_w_tag(element, "abstractNumId")
            .then(|| attr_get(element, "val")?.parse::<u32>().ok())
            .flatten()
    })
}

fn numbered_instance(root: &Element, num_id: u32) -> Option<&Element> {
    root.children.iter().find_map(|child| {
        let XMLNode::Element(element) = child else {
            return None;
        };
        (is_w_tag(element, "num")
            && attr_get(element, "numId").and_then(|value| value.parse::<u32>().ok())
                == Some(num_id))
        .then_some(element)
    })
}

/// Compare numbering behavior while excluding only closed transport/provenance
/// identities generated by Word.
fn semantic_definition(root: &Element, num_id: u32) -> Option<(Element, Element)> {
    let mut num = numbered_instance(root, num_id)?.clone();
    let abstract_id = abstract_num_id(&num)?;
    let mut abstract_num = root.children.iter().find_map(|child| {
        let XMLNode::Element(element) = child else {
            return None;
        };
        (is_w_tag(element, "abstractNum")
            && attr_get(element, "abstractNumId").and_then(|value| value.parse::<u32>().ok())
                == Some(abstract_id))
        .then(|| element.clone())
    })?;

    attr_set(&mut num, "w:numId", "0");
    num.attributes
        .retain(|name, _| name.local_name != "durableId");
    if let Some(reference) = num.children.iter_mut().find_map(|child| {
        let XMLNode::Element(element) = child else {
            return None;
        };
        is_w_tag(element, "abstractNumId").then_some(element)
    }) {
        attr_set(reference, "w:val", "0");
    }
    attr_set(&mut abstract_num, "w:abstractNumId", "0");
    abstract_num.children.retain(|child| {
        !matches!(child, XMLNode::Element(element) if is_w_tag(element, "nsid") || is_w_tag(element, "tmpl"))
    });
    for child in &mut abstract_num.children {
        let XMLNode::Element(level) = child else {
            continue;
        };
        if is_w_tag(level, "lvl") {
            level.attributes.retain(|name, _| name.local_name != "tplc");
        }
    }
    Some((num, abstract_num))
}

fn ids(root: &Element) -> (HashSet<u32>, HashSet<u32>) {
    let mut num_ids = HashSet::new();
    let mut abstract_ids = HashSet::new();
    for child in &root.children {
        let XMLNode::Element(element) = child else {
            continue;
        };
        if is_w_tag(element, "num") {
            if let Some(id) = attr_get(element, "numId").and_then(|value| value.parse().ok()) {
                num_ids.insert(id);
            }
        } else if is_w_tag(element, "abstractNum")
            && let Some(id) =
                attr_get(element, "abstractNumId").and_then(|value| value.parse().ok())
        {
            abstract_ids.insert(id);
        }
    }
    (num_ids, abstract_ids)
}

fn allocate(used: &mut HashSet<u32>, kind: &str) -> Result<u32, RuntimeError> {
    let next = used
        .iter()
        .copied()
        .max()
        .unwrap_or(0)
        .checked_add(1)
        .ok_or_else(|| {
            error(
                ErrorCode::UnsupportedEdit,
                format!("cannot allocate a collision-safe {kind} transport identity"),
                "numbering transport identity space is exhausted",
            )
        })?;
    used.insert(next);
    Ok(next)
}

fn rewrite_numbering_part(
    root: &mut Element,
    num_remap: &HashMap<u32, u32>,
    abstract_remap: &HashMap<u32, u32>,
) {
    for child in &mut root.children {
        let XMLNode::Element(element) = child else {
            continue;
        };
        if is_w_tag(element, "abstractNum") {
            if let Some(old_id) =
                attr_get(element, "abstractNumId").and_then(|value| value.parse::<u32>().ok())
                && let Some(new_id) = abstract_remap.get(&old_id)
            {
                attr_set(element, "w:abstractNumId", new_id.to_string());
            }
            continue;
        }
        if !is_w_tag(element, "num") {
            continue;
        }
        if let Some(old_id) = attr_get(element, "numId").and_then(|value| value.parse::<u32>().ok())
            && let Some(new_id) = num_remap.get(&old_id)
        {
            attr_set(element, "w:numId", new_id.to_string());
        }
        if let Some(reference) = element.children.iter_mut().find_map(|child| {
            let XMLNode::Element(reference) = child else {
                return None;
            };
            is_w_tag(reference, "abstractNumId").then_some(reference)
        }) && let Some(old_id) =
            attr_get(reference, "val").and_then(|value| value.parse::<u32>().ok())
            && let Some(new_id) = abstract_remap.get(&old_id)
        {
            attr_set(reference, "w:val", new_id.to_string());
        }
    }
}

fn rewrite_num_id_references(element: &mut Element, remap: &HashMap<u32, u32>) -> bool {
    let mut changed = false;
    if is_w_tag(element, "numId")
        && let Some(old_id) = attr_get(element, "val").and_then(|value| value.parse::<u32>().ok())
        && let Some(new_id) = remap.get(&old_id)
    {
        attr_set(element, "w:val", new_id.to_string());
        changed = true;
    }
    for child in &mut element.children {
        if let XMLNode::Element(child) = child {
            changed |= rewrite_num_id_references(child, remap);
        }
    }
    changed
}

fn rewrite_package(
    package: &mut DocxPackage,
    numbering_path: &str,
    mut numbering_root: Element,
    num_remap: &HashMap<u32, u32>,
    abstract_remap: &HashMap<u32, u32>,
) -> Result<(), RuntimeError> {
    rewrite_numbering_part(&mut numbering_root, num_remap, abstract_remap);
    package.set_part(
        numbering_path,
        word_xml::write_document_xml(&numbering_root).map_err(|source| {
            error(
                ErrorCode::InvalidDocx,
                "failed to serialize remapped numbering part",
                format!("{source:?}"),
            )
        })?,
    );

    let mut part_names: Vec<String> = package
        .part_names()
        .filter(|name| !name.eq_ignore_ascii_case(numbering_path))
        .filter(|name| name.to_ascii_lowercase().ends_with(".xml"))
        .map(str::to_string)
        .collect();
    part_names.sort();
    for part_name in part_names {
        let bytes = package
            .get_part(&part_name)
            .expect("part_names returns existing package parts");
        if !bytes
            .windows(b"numId".len())
            .any(|window| window == b"numId")
        {
            continue;
        }
        let mut root = Element::parse(Cursor::new(bytes)).map_err(|source| {
            error(
                ErrorCode::InvalidDocx,
                "failed to parse an XML part while remapping numbering references",
                format!("part={part_name} parse_error={source}"),
            )
        })?;
        if rewrite_num_id_references(&mut root, num_remap) {
            package.set_part(
                &part_name,
                word_xml::write_document_xml(&root).map_err(|source| {
                    error(
                        ErrorCode::InvalidDocx,
                        "failed to serialize remapped numbering reference part",
                        format!("part={part_name} serialize_error={source:?}"),
                    )
                })?,
            );
        }
    }
    Ok(())
}

/// Rewrite the target side of a source-based package union when active
/// numbering transport identities collide. The returned map must be applied
/// to the target's typed document by the caller before the package and model
/// are used again.
pub(crate) fn remap_target_for_coexistence(
    source: &DocxPackage,
    target: &mut DocxPackage,
) -> Result<Option<HashMap<u32, u32>>, RuntimeError> {
    let Some((_, source_root)) = numbering_part(source, "source")? else {
        return Ok(None);
    };
    let Some((target_path, target_root)) = numbering_part(target, "target")? else {
        return Ok(None);
    };
    let (source_num_ids, source_abstract_ids) = ids(&source_root);
    let (target_num_ids, target_abstract_ids) = ids(&target_root);
    let mut used_num_ids: HashSet<u32> = source_num_ids.union(&target_num_ids).copied().collect();
    let mut used_abstract_ids: HashSet<u32> = source_abstract_ids
        .union(&target_abstract_ids)
        .copied()
        .collect();
    let mut num_remap = HashMap::new();
    let mut abstract_remap = HashMap::new();
    let mut shared_ids: Vec<u32> = source_num_ids
        .intersection(&target_num_ids)
        .copied()
        .collect();
    shared_ids.sort_unstable();
    for num_id in shared_ids {
        let source_definition = semantic_definition(&source_root, num_id).ok_or_else(|| {
            error(
                ErrorCode::InvalidDocx,
                "source numbering instance does not resolve to an abstract definition",
                format!("numId={num_id}"),
            )
        })?;
        let target_definition = semantic_definition(&target_root, num_id).ok_or_else(|| {
            error(
                ErrorCode::InvalidDocx,
                "target numbering instance does not resolve to an abstract definition",
                format!("numId={num_id}"),
            )
        })?;
        if source_definition == target_definition {
            continue;
        }
        num_remap.insert(num_id, allocate(&mut used_num_ids, "numbering-instance")?);
        let target_abstract_id = numbered_instance(&target_root, num_id)
            .and_then(abstract_num_id)
            .ok_or_else(|| {
                error(
                    ErrorCode::InvalidDocx,
                    "target numbering instance lacks an abstractNumId reference",
                    format!("numId={num_id}"),
                )
            })?;
        if let std::collections::hash_map::Entry::Vacant(entry) =
            abstract_remap.entry(target_abstract_id)
        {
            entry.insert(allocate(&mut used_abstract_ids, "abstract-numbering")?);
        }
    }
    if num_remap.is_empty() {
        return Ok(None);
    }

    rewrite_package(
        target,
        &target_path,
        target_root,
        &num_remap,
        &abstract_remap,
    )?;
    Ok(Some(num_remap))
}
