//! Integration tests: Normalization pipeline (RFC: DOCX Compare Baseline via Final Projection)
//!
//! These tests use real DOCX fixture files (generated by
//! `testdata/spec-compliance/normalize/create_fixtures.py`) to verify the
//! preflight scanner and normalizer work correctly on actual ZIP archives.
//!
//! The critical invariant: after normalization, a preflight scan of the output
//! must report zero revision elements.

use std::fs;

use stemma::docx::DocxArchive;
use stemma::normalize::{normalize_docx, preflight_scan};

const FIXTURES: &str = "testdata/spec-compliance/normalize";

// ── helpers ──────────────────────────────────────────────────────────────

fn load_fixture(name: &str) -> DocxArchive {
    let path = format!("{FIXTURES}/{name}/input.docx");
    let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    DocxArchive::read(&bytes).unwrap_or_else(|e| panic!("parse {path}: {e:?}"))
}

/// Assert that a preflight scan of the archive finds zero revision elements.
/// This is the critical post-normalization invariant.
fn assert_no_revision_elements(archive: &DocxArchive) {
    let report = preflight_scan(archive).expect("preflight scan should succeed");
    assert_eq!(
        report.totals.revisions.total(),
        0,
        "Expected zero revision elements after normalization, but found: \
         ins={}, del={}, moveFrom={}, moveTo={}, delText={}, formatPrChange={}",
        report.totals.revisions.ins,
        report.totals.revisions.del,
        report.totals.revisions.move_from,
        report.totals.revisions.move_to,
        report.totals.revisions.del_text,
        report.totals.revisions.format_pr_change,
    );
}

/// Count occurrences of a substring in the given XML bytes (for quick assertions).
fn count_substring_occurrences(xml_bytes: &[u8], needle: &str) -> usize {
    let xml_str = std::str::from_utf8(xml_bytes).expect("XML should be valid UTF-8");
    xml_str.matches(needle).count()
}

// =========================================================================
// Preflight scan tests (using real DOCX fixtures)
// =========================================================================

#[test]
fn preflight_main_ins_del_counts_correctly() {
    let archive = load_fixture("main-ins-del");
    let report = preflight_scan(&archive).unwrap();

    assert_eq!(report.totals.revisions.ins, 1, "expected 1 w:ins");
    assert_eq!(report.totals.revisions.del, 1, "expected 1 w:del");
    assert_eq!(report.totals.revisions.del_text, 1, "expected 1 w:delText");
    assert_eq!(report.totals.revisions.move_from, 0);
    assert_eq!(report.totals.revisions.move_to, 0);
    assert_eq!(report.totals.revisions.format_pr_change, 0);
    assert_eq!(report.totals.comments.anchors, 0);
}

#[test]
fn preflight_main_moves_counts_correctly() {
    let archive = load_fixture("main-moves");
    let report = preflight_scan(&archive).unwrap();

    assert_eq!(
        report.totals.revisions.move_from, 1,
        "expected 1 w:moveFrom"
    );
    assert_eq!(report.totals.revisions.move_to, 1, "expected 1 w:moveTo");
    assert_eq!(report.totals.revisions.ins, 0);
    assert_eq!(report.totals.revisions.del, 0);
}

#[test]
fn preflight_main_format_changes_counts_correctly() {
    let archive = load_fixture("main-format-changes");
    let report = preflight_scan(&archive).unwrap();

    assert_eq!(
        report.totals.revisions.format_pr_change, 2,
        "expected 2 format changes (pPrChange + rPrChange)"
    );
    assert_eq!(report.totals.revisions.ins, 0);
    assert_eq!(report.totals.revisions.del, 0);
}

#[test]
fn preflight_header_tracked_changes_reports_per_part() {
    let archive = load_fixture("header-tracked-changes");
    let report = preflight_scan(&archive).unwrap();

    // Main document body should have zero revisions
    let doc_part = report
        .parts
        .iter()
        .find(|p| p.part == "word/document.xml")
        .expect("should have document.xml part");
    assert_eq!(
        doc_part.revisions.total(),
        0,
        "main document body should have zero revisions"
    );

    // Header should have the tracked changes
    let header_part = report
        .parts
        .iter()
        .find(|p| p.part == "word/header1.xml")
        .expect("should have header1.xml part");
    assert_eq!(header_part.revisions.ins, 1);
    assert_eq!(header_part.revisions.del, 1);
    assert_eq!(header_part.revisions.del_text, 1);

    // Totals should match
    assert_eq!(report.totals.revisions.ins, 1);
    assert_eq!(report.totals.revisions.del, 1);
}

#[test]
fn preflight_comments_basic_counts_anchors() {
    let archive = load_fixture("comments-basic");
    let report = preflight_scan(&archive).unwrap();

    // Should find comment anchors in document.xml
    // commentRangeStart + commentRangeEnd + commentReference = 3 anchors
    assert_eq!(
        report.totals.comments.anchors, 3,
        "expected 3 comment anchor elements"
    );
    // No revision elements
    assert_eq!(report.totals.revisions.total(), 0);
}

#[test]
fn preflight_sdt_with_revisions_counts_inside_sdt() {
    let archive = load_fixture("sdt-with-revisions");
    let report = preflight_scan(&archive).unwrap();

    assert_eq!(report.totals.revisions.ins, 1);
    assert_eq!(report.totals.revisions.del, 1);
    assert_eq!(report.totals.revisions.del_text, 1);
}

// =========================================================================
// Normalization tests (using real DOCX fixtures)
// =========================================================================

#[test]
fn normalize_main_ins_del_accepts_and_removes() {
    let archive = load_fixture("main-ins-del");
    let (result, stats) = normalize_docx(&archive).unwrap();

    assert!(
        stats.revisions_resolved >= 2,
        "should resolve at least ins + del"
    );
    assert!(
        stats
            .parts_normalized
            .contains(&"word/document.xml".to_string()),
        "document.xml should be in parts_normalized"
    );

    let doc_xml = result.get("word/document.xml").unwrap();
    let doc_str = std::str::from_utf8(doc_xml).unwrap();

    // Inserted text should remain (unwrapped)
    assert!(doc_str.contains("inserted"), "inserted text should be kept");
    // Deleted text should be gone
    assert!(
        !doc_str.contains("deleted"),
        "deleted text should be removed"
    );
    // No revision wrappers
    assert_eq!(count_substring_occurrences(doc_xml, "w:ins"), 0);
    assert_eq!(count_substring_occurrences(doc_xml, "w:del"), 0);
    assert_eq!(count_substring_occurrences(doc_xml, "delText"), 0);

    // Critical invariant
    assert_no_revision_elements(&result);
}

#[test]
fn normalize_main_moves_drops_from_keeps_to() {
    let archive = load_fixture("main-moves");
    let (result, stats) = normalize_docx(&archive).unwrap();

    assert!(stats.revisions_resolved >= 2);

    let doc_xml = result.get("word/document.xml").unwrap();
    let doc_str = std::str::from_utf8(doc_xml).unwrap();

    // moveTo content should remain (unwrapped)
    assert!(
        doc_str.contains("moved text"),
        "moveTo text should be kept in output"
    );
    // moveFrom and moveTo wrappers should be gone
    assert_eq!(count_substring_occurrences(doc_xml, "moveFrom"), 0);
    assert_eq!(count_substring_occurrences(doc_xml, "moveTo"), 0);

    assert_no_revision_elements(&result);
}

#[test]
fn normalize_main_format_changes_strips_pr_change_keeps_props() {
    let archive = load_fixture("main-format-changes");
    let (result, stats) = normalize_docx(&archive).unwrap();

    assert_eq!(
        stats.revisions_resolved, 2,
        "should resolve pPrChange + rPrChange"
    );

    let doc_xml = result.get("word/document.xml").unwrap();
    let doc_str = std::str::from_utf8(doc_xml).unwrap();

    // Property changes should be removed
    assert_eq!(count_substring_occurrences(doc_xml, "pPrChange"), 0);
    assert_eq!(count_substring_occurrences(doc_xml, "rPrChange"), 0);

    // Current property values should be preserved
    assert!(doc_str.contains("center"), "jc=center should be preserved");
    assert!(
        doc_str.contains("<w:b"),
        "bold property should be preserved"
    );
    assert!(
        doc_str.contains("Bold centered text"),
        "text content should be preserved"
    );

    assert_no_revision_elements(&result);
}

#[test]
fn normalize_header_tracked_changes_normalizes_header_part() {
    let archive = load_fixture("header-tracked-changes");
    let (result, stats) = normalize_docx(&archive).unwrap();

    assert!(stats.revisions_resolved >= 2);
    assert!(
        stats
            .parts_normalized
            .contains(&"word/header1.xml".to_string()),
        "header1.xml should be in parts_normalized"
    );

    // Header should be normalized
    let header_xml = result.get("word/header1.xml").unwrap();
    let header_str = std::str::from_utf8(header_xml).unwrap();
    assert_eq!(count_substring_occurrences(header_xml, "w:ins"), 0);
    assert_eq!(count_substring_occurrences(header_xml, "w:del"), 0);
    assert!(
        header_str.contains("new"),
        "inserted header text should remain"
    );

    // Main body should be untouched (no revisions to resolve)
    let doc_xml = result.get("word/document.xml").unwrap();
    let doc_str = std::str::from_utf8(doc_xml).unwrap();
    assert!(doc_str.contains("Clean body content"));

    assert_no_revision_elements(&result);
}

#[test]
fn normalize_comments_basic_preserves_comments() {
    let archive = load_fixture("comments-basic");
    let (result, stats) = normalize_docx(&archive).unwrap();

    // No revisions to resolve (only comments)
    assert_eq!(stats.revisions_resolved, 0);

    let doc_xml = result.get("word/document.xml").unwrap();

    // Comment markers must be preserved
    assert!(
        count_substring_occurrences(doc_xml, "commentRangeStart") > 0,
        "commentRangeStart should be preserved"
    );
    assert!(
        count_substring_occurrences(doc_xml, "commentRangeEnd") > 0,
        "commentRangeEnd should be preserved"
    );
    assert!(
        count_substring_occurrences(doc_xml, "commentReference") > 0,
        "commentReference should be preserved"
    );

    // comments.xml should be untouched
    let comments_xml = result.get("word/comments.xml").unwrap();
    let comments_str = std::str::from_utf8(comments_xml).unwrap();
    assert!(
        comments_str.contains("This is a comment."),
        "comments.xml content should be preserved"
    );

    // Post-condition: still zero revisions
    assert_no_revision_elements(&result);
}

#[test]
fn normalize_sdt_with_revisions_resolves_inside_content_control() {
    let archive = load_fixture("sdt-with-revisions");
    let (result, stats) = normalize_docx(&archive).unwrap();

    // Revisions inside sdt should be counted as opaque
    assert!(
        stats.opaque_nodes_resolved_revisions_count >= 2,
        "should resolve revisions inside sdt as opaque: got {}",
        stats.opaque_nodes_resolved_revisions_count
    );

    let doc_xml = result.get("word/document.xml").unwrap();
    let doc_str = std::str::from_utf8(doc_xml).unwrap();

    // sdt structure should be preserved
    assert!(
        count_substring_occurrences(doc_xml, "w:sdt") > 0,
        "w:sdt element should be preserved"
    );
    assert!(
        count_substring_occurrences(doc_xml, "sdtContent") > 0,
        "sdtContent should be preserved"
    );

    // Inserted text inside sdt should remain
    assert!(
        doc_str.contains("added"),
        "inserted text in sdt should remain"
    );
    // Deleted text inside sdt should be gone
    assert!(
        !doc_str.contains("removed"),
        "deleted text in sdt should be removed"
    );

    // No revision wrappers
    assert_eq!(count_substring_occurrences(doc_xml, "w:ins"), 0);
    assert_eq!(count_substring_occurrences(doc_xml, "w:del"), 0);

    assert_no_revision_elements(&result);
}

// =========================================================================
// Critical invariant: normalize → scan → zero revisions (all fixtures)
// =========================================================================

/// Parameterized test: every fixture, when normalized, must have zero
/// revision elements in the output.
#[test]
fn invariant_all_fixtures_zero_revisions_after_normalize() {
    let fixture_names = [
        "main-ins-del",
        "main-moves",
        "main-format-changes",
        "header-tracked-changes",
        "comments-basic",
        "sdt-with-revisions",
    ];

    for name in &fixture_names {
        let archive = load_fixture(name);
        let (result, _) = normalize_docx(&archive)
            .unwrap_or_else(|e| panic!("normalize_docx failed for {name}: {e:?}"));

        let report = preflight_scan(&result)
            .unwrap_or_else(|e| panic!("preflight_scan failed for {name}: {e:?}"));

        assert_eq!(
            report.totals.revisions.total(),
            0,
            "INVARIANT VIOLATED for fixture '{name}': \
             found {} revision elements after normalization \
             (ins={}, del={}, moveFrom={}, moveTo={}, delText={}, format={})",
            report.totals.revisions.total(),
            report.totals.revisions.ins,
            report.totals.revisions.del,
            report.totals.revisions.move_from,
            report.totals.revisions.move_to,
            report.totals.revisions.del_text,
            report.totals.revisions.format_pr_change,
        );
    }
}

// =========================================================================
// Idempotency: normalizing an already-normalized archive is a no-op
// =========================================================================

#[test]
fn normalize_is_idempotent() {
    let fixture_names = [
        "main-ins-del",
        "main-moves",
        "main-format-changes",
        "header-tracked-changes",
        "sdt-with-revisions",
    ];

    for name in &fixture_names {
        let archive = load_fixture(name);
        let (first_pass, _first_stats) = normalize_docx(&archive)
            .unwrap_or_else(|e| panic!("first normalize failed for {name}: {e:?}"));

        let (second_pass, second_stats) = normalize_docx(&first_pass)
            .unwrap_or_else(|e| panic!("second normalize failed for {name}: {e:?}"));

        assert_eq!(
            second_stats.revisions_resolved, 0,
            "Second normalization of '{name}' should resolve zero revisions, got {}",
            second_stats.revisions_resolved
        );
        assert_eq!(
            second_stats.opaque_nodes_resolved_revisions_count, 0,
            "Second normalization of '{name}' should resolve zero opaque revisions, got {}",
            second_stats.opaque_nodes_resolved_revisions_count
        );

        // The document.xml content should be byte-identical after second pass
        let first_doc = first_pass.get("word/document.xml").unwrap();
        let second_doc = second_pass.get("word/document.xml").unwrap();
        assert_eq!(
            first_doc, second_doc,
            "Idempotency check failed for '{name}': document.xml differs between first and second normalization"
        );
    }
}

// =========================================================================
// Clean document scan: no-revision document should report all zeros
// =========================================================================

#[test]
fn preflight_clean_document_reports_zeros() {
    // The comments-basic fixture has no revision elements (only comments)
    let archive = load_fixture("comments-basic");
    let report = preflight_scan(&archive).unwrap();

    assert_eq!(report.totals.revisions.ins, 0);
    assert_eq!(report.totals.revisions.del, 0);
    assert_eq!(report.totals.revisions.move_from, 0);
    assert_eq!(report.totals.revisions.move_to, 0);
    assert_eq!(report.totals.revisions.del_text, 0);
    assert_eq!(report.totals.revisions.format_pr_change, 0);
    assert_eq!(report.totals.revisions.total(), 0);
}

// =========================================================================
// Normalize clean document is a no-op
// =========================================================================

#[test]
fn normalize_clean_document_is_noop() {
    let archive = load_fixture("comments-basic");
    let (_result, stats) = normalize_docx(&archive).unwrap();

    assert_eq!(stats.revisions_resolved, 0);
    assert_eq!(stats.opaque_nodes_resolved_revisions_count, 0);
    assert!(
        stats.parts_normalized.is_empty(),
        "no parts should be in parts_normalized for a clean document"
    );
}
