//! Spec-compliance tests: paragraph border serialization ordering and
//! conditional formatting application order.
//!
//! Constraint 1 — pBdr element order:
//!   ECMA-376 Annex A defines CT_PBdr as a sequence: top, left, bottom,
//!   right, between, bar.
//!
//! Constraint 2 — conditional formatting precedence:
//!   MS-OI29500 §2.1.246: Word applies conditional formatting in this order
//!   (later overrides earlier): bands < firstCol/lastCol < firstRow/lastRow
//!   < corners. Key: firstRow overrides firstCol at corner cells.
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-border-serialization/create_docs.py`

use std::io::Cursor;

use stemma::{BlockNode, CanonDoc, DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-border-serialization";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

/// Import a fixture, run diff_and_redline (identity: same doc as both base
/// and target), then export. This forces the code through the full
/// serialization pipeline (`serialize_canonical_docx` / `build_paragraph_properties`),
/// unlike plain `export_docx` which is a passthrough of the original XML.
///
/// Returns the raw word/document.xml from the exported DOCX bytes.
fn serialize_roundtrip_xml(fixtures: &str, name: &str) -> String {
    let path = format!("{fixtures}/{name}/input.docx");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));

    let runtime = SimpleRuntime::new();
    let import_base = runtime
        .import_docx(&bytes)
        .unwrap_or_else(|e| panic!("import base {path}: {e:?}"));
    let import_target = runtime
        .import_docx(&bytes)
        .unwrap_or_else(|e| panic!("import target {path}: {e:?}"));

    let meta = TransactionMeta {
        author: "spec_table_border_serialization".to_string(),
        reason: Some("serialization ordering test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&import_base.doc_handle, &import_target.doc_handle, meta)
        .expect("diff_and_redline should succeed");
    assert!(apply.applied, "redline should be applied");

    let exported = runtime
        .export_docx(&import_base.doc_handle, ExportMode::Redline)
        .expect("export should succeed");

    extract_document_xml(&exported)
}

fn extract_document_xml(docx_bytes: &[u8]) -> String {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = zip::ZipArchive::new(cursor).unwrap_or_else(|e| panic!("open exported zip: {e}"));
    let mut doc_xml = String::new();
    {
        use std::io::Read;
        let mut entry = zip
            .by_name("word/document.xml")
            .unwrap_or_else(|e| panic!("find word/document.xml in export: {e}"));
        entry
            .read_to_string(&mut doc_xml)
            .unwrap_or_else(|e| panic!("read word/document.xml: {e}"));
    }
    doc_xml
}

/// Extract the local tag name from a qualified XML tag like `{ns}local` or `prefix:local`.
fn local_name(full_name: &str) -> &str {
    if let Some(pos) = full_name.rfind('}') {
        &full_name[pos + 1..]
    } else if let Some(pos) = full_name.rfind(':') {
        &full_name[pos + 1..]
    } else {
        full_name
    }
}

/// Find child element tag names (local part only) of the first occurrence
/// of `target_local` in the XML string, using xmltree parsing.
fn child_element_order(xml: &str, target_local: &str) -> Vec<String> {
    let root = xmltree::Element::parse(xml.as_bytes()).unwrap_or_else(|e| panic!("parse XML: {e}"));
    let mut result = Vec::new();
    find_element_children(&root, target_local, &mut result);
    result
}

fn find_element_children(el: &xmltree::Element, target_local: &str, out: &mut Vec<String>) {
    if !out.is_empty() {
        return; // Already found
    }
    if local_name(&el.name) == target_local {
        for child in &el.children {
            if let xmltree::XMLNode::Element(child_el) = child {
                out.push(local_name(&child_el.name).to_string());
            }
        }
        return;
    }
    for child in &el.children {
        if let xmltree::XMLNode::Element(child_el) = child {
            find_element_children(child_el, target_local, out);
            if !out.is_empty() {
                return;
            }
        }
    }
}

// =============================================================================
// 1. pBdr serialization ordering
//    (ECMA-376 Annex A, CT_PBdr)
// =============================================================================

/// Verifies ECMA-376 Annex A CT_PBdr sequence: top, left, bottom, right,
/// between, bar. Imports a paragraph with all 6 border edges, forces
/// re-serialization via `diff_and_redline`, and checks element order.
#[test]
fn spec_pbdr_element_order_matches_schema() {
    let doc_xml = serialize_roundtrip_xml(FIXTURES, "paragraph-borders");

    let children = child_element_order(&doc_xml, "pBdr");
    assert!(
        !children.is_empty(),
        "exported document.xml should contain a w:pBdr element with children"
    );

    // ECMA-376 Annex A CT_PBdr defines this sequence:
    //   top, left, bottom, right, between, bar
    let expected = ["top", "left", "bottom", "right", "between", "bar"];

    // Filter to only the expected border edges (ignore any extras)
    let actual: Vec<&str> = children
        .iter()
        .filter(|name| expected.contains(&name.as_str()))
        .map(|s| s.as_str())
        .collect();

    assert_eq!(
        actual, expected,
        "pBdr child elements must appear in CT_PBdr schema order: \
         top, left, bottom, right, between, bar.\n\
         Got: {actual:?}"
    );
}

/// Verify that all 6 border edges survive the serialization roundtrip
/// (no data loss through import -> serialize -> export).
#[test]
fn spec_pbdr_all_edges_preserved_on_roundtrip() {
    let doc_xml = serialize_roundtrip_xml(FIXTURES, "paragraph-borders");
    let children = child_element_order(&doc_xml, "pBdr");

    let expected_edges = ["top", "left", "bottom", "right", "between", "bar"];
    for edge in &expected_edges {
        assert!(
            children.contains(&edge.to_string()),
            "pBdr should contain {edge} border after serialization roundtrip — \
             edge was present in input but missing in output"
        );
    }
}

// =============================================================================
// 2. Conditional formatting: firstRow wins over firstCol at corner
//    (MS-OI29500 §2.1.246)
// =============================================================================

/// MS-OI29500 §2.1.246: In Word, conditional formatting is applied in this
/// order (later overrides earlier):
///   1. Banded rows/cols
///   2. First/last column
///   3. First/last row
///   4. Corner cells
///
/// At cell (0,0) where both firstRow and firstCol apply, firstRow shading
/// (red FF0000) should win because rows are applied after columns.
#[test]
fn spec_conditional_firstrow_wins_over_firstcol_at_corner() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    // Cell (0,0): both firstRow and firstCol apply.
    // Per MS-OI29500 §2.1.246, firstRow is applied AFTER firstCol,
    // so firstRow shading (red) should win.
    let cell_00_shading = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading — both firstRow and firstCol apply");
    assert_eq!(
        cell_00_shading.fill.as_deref(),
        Some("FF0000"),
        "cell (0,0) shading should be red (FF0000) from firstRow conditional, \
         not blue (0000FF) from firstCol — MS-OI29500 §2.1.246: firstRow is \
         applied after firstCol, so it wins at corners"
    );
}

/// Cell (0,1) is in the first row but NOT the first column.
/// Only firstRow conditional applies: shading should be red (FF0000).
#[test]
fn spec_conditional_firstrow_only_cell() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    let cell_01_shading = table.rows[0].cells[1]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,1) should have shading from firstRow conditional");
    assert_eq!(
        cell_01_shading.fill.as_deref(),
        Some("FF0000"),
        "cell (0,1) shading should be red (FF0000) — firstRow only"
    );
}

/// Cell (1,0) is in the first column but NOT the first row.
/// Only firstCol conditional applies: shading should be blue (0000FF).
#[test]
fn spec_conditional_firstcol_only_cell() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    let cell_10_shading = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (1,0) should have shading from firstCol conditional");
    assert_eq!(
        cell_10_shading.fill.as_deref(),
        Some("0000FF"),
        "cell (1,0) shading should be blue (0000FF) — firstCol only"
    );
}

// =============================================================================
// 3. Non-corner cells get only their single conditional
//    (MS-OI29500 §2.1.246)
// =============================================================================

/// Cell (1,1) is a plain data cell. With banding disabled (noHBand=1,
/// noVBand=1), no conditional applies. It should have no conditional shading.
#[test]
fn spec_conditional_non_corner_cells_single_conditional_data_cell() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    // Cell (1,1): data cell with no conditional — should have no shading
    // (banding is disabled via noHBand=1, noVBand=1)
    let cell_11_shading = table.rows[1].cells[1].formatting.shading.as_ref();
    if let Some(s) = cell_11_shading {
        // If shading exists, it should not be red or blue from conditionals
        assert!(
            s.fill.as_deref() != Some("FF0000") && s.fill.as_deref() != Some("0000FF"),
            "cell (1,1) is a plain data cell with banding disabled — should not \
             have firstRow (red) or firstCol (blue) conditional shading. Got: {:?}",
            s.fill
        );
    }
    // No shading at all is also acceptable for a data cell with banding off
}

/// Cell (0,2) is in firstRow only (not firstCol, not lastCol).
/// Should have red shading from firstRow conditional.
#[test]
fn spec_conditional_firstrow_non_corner() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    let cell_02_shading = table.rows[0].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,2) should have shading from firstRow conditional");
    assert_eq!(
        cell_02_shading.fill.as_deref(),
        Some("FF0000"),
        "cell (0,2) shading should be red (FF0000) — firstRow only"
    );
}

/// Cell (2,0) is in firstCol only (not firstRow, not lastRow).
/// Should have blue shading from firstCol conditional.
#[test]
fn spec_conditional_firstcol_non_corner() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-row-beats-column");
    let table = first_table(&doc);

    let cell_20_shading = table.rows[2].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (2,0) should have shading from firstCol conditional");
    assert_eq!(
        cell_20_shading.fill.as_deref(),
        Some("0000FF"),
        "cell (2,0) shading should be blue (0000FF) — firstCol only"
    );
}
