//! Spec-compliance tests: Section and Header/Footer Behavioral Constraints
//! (ISO 29500-1 sections 17.6.22, 17.10.2, 17.10.5, 17.10.6)
//!
//! These tests verify behavioral constraints around section properties:
//! - Header/footer inheritance across sections
//! - titlePg interaction with first-page headers
//! - Continuous section property inheritance
//!
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_section_constraints.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-constraints";

// -- helpers ----------------------------------------------------------------

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&stemma::SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(
    blocks: &'a [BlockNode],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// HEADER INHERITANCE (ISO 29500-1 sections 17.10.2 / 17.10.5)
// ==========================================================================

/// ISO 29500-1 sections 17.10.2 / 17.10.5: Header inheritance across sections.
///
/// Section 1 defines a default header "Section 1 Header". Section 2 does
/// NOT define a header reference. Per spec, Section 2 should inherit the
/// header from Section 1.
///
/// This test verifies the fixture loads correctly and that the document
/// has exactly one header story (the one defined by Section 1). Whether
/// the model computes inheritance for Section 2 is tested separately.
#[test]
fn spec_section_has_header_from_section_1() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-inheritance");

    // The document should have at least one header (the one from Section 1)
    assert!(
        !doc.headers.is_empty(),
        "document should have at least one header story"
    );

    // Verify the header contains "Section 1 Header"
    let default_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Default);
    assert!(
        default_hdr.is_some(),
        "should have a Default-kind header, got kinds: {:?}",
        doc.headers.iter().map(|h| &h.kind).collect::<Vec<_>>()
    );

    let text = blocks_text(&default_hdr.unwrap().blocks);
    assert!(
        text.contains("Section 1 Header"),
        "Default header should contain 'Section 1 Header', got: '{text}'"
    );
}

/// ISO 29500-1 sections 17.10.2 / 17.10.5: Section 2 inherits header from Section 1.
///
/// When a section does not define its own headerReference, the spec says it
/// inherits the header from the previous section. The model resolves this
/// inheritance during import, populating `header_refs` on each section.
#[test]
fn spec_section_inherits_header_from_previous() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-inheritance");

    // Document has 2 sections, 1 header part.
    assert_eq!(doc.headers.len(), 1);
    let header_part = &doc.headers[0].part_name;

    // Section 1 (mid-document): declares the default header
    let all_paras = common::all_paragraphs(&doc);
    let sect1_para = all_paras
        .iter()
        .find(|p| p.section_properties.is_some())
        .expect("should find a paragraph with section_properties");
    let sect1_sp = sect1_para.section_properties.as_ref().unwrap();
    assert_eq!(sect1_sp.header_refs.len(), 1);
    assert_eq!(sect1_sp.header_refs[0].kind, HeaderFooterKind::Default);
    assert_eq!(&sect1_sp.header_refs[0].part_path, header_part);

    // Section 2 (body-level): inherits default header from Section 1
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");
    assert_eq!(body_sp.header_refs.len(), 1);
    assert_eq!(body_sp.header_refs[0].kind, HeaderFooterKind::Default);
    assert_eq!(
        &body_sp.header_refs[0].part_path, header_part,
        "Section 2 should inherit Section 1's default header"
    );
}

/// ISO 29500-1 §17.10.2: Per-kind header inheritance across 3 sections.
///
/// S1 declares default + first headers. S2 declares only first (overrides S1's
/// first, inherits S1's default). S3 declares nothing (inherits both from S2).
#[test]
fn spec_section_partial_header_inheritance() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "partial-header-inheritance");

    // 3 header parts in the document
    assert_eq!(doc.headers.len(), 3, "should have 3 header parts");

    let all_paras = common::all_paragraphs(&doc);
    let sect_paras: Vec<_> = all_paras
        .iter()
        .filter(|p| p.section_properties.is_some())
        .collect();
    assert_eq!(sect_paras.len(), 2, "should have 2 mid-document sections");

    let s1_sp = sect_paras[0].section_properties.as_ref().unwrap();
    let s2_sp = sect_paras[1].section_properties.as_ref().unwrap();
    let s3_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body section properties");

    // S1: 2 effective refs (default + first)
    assert_eq!(s1_sp.header_refs.len(), 2, "S1 should have 2 header refs");

    // S2: 2 effective refs (inherited default from S1 + own first)
    assert_eq!(
        s2_sp.header_refs.len(),
        2,
        "S2 should have 2 header refs (own first + inherited default)"
    );

    // S3: 2 effective refs (inherited from S2)
    assert_eq!(
        s3_sp.header_refs.len(),
        2,
        "S3 should have 2 header refs (both inherited)"
    );

    // S2's default part_path == S1's default part_path (inherited)
    let s1_default = s1_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .unwrap();
    let s2_default = s2_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .unwrap();
    assert_eq!(
        s1_default.part_path, s2_default.part_path,
        "S2 should inherit S1's default header"
    );

    // S2's first part_path != S1's first part_path (overridden)
    let s1_first = s1_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .unwrap();
    let s2_first = s2_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .unwrap();
    assert_ne!(
        s1_first.part_path, s2_first.part_path,
        "S2 should override S1's first header"
    );

    // S3 inherits exactly what S2 has
    let s3_default = s3_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .unwrap();
    let s3_first = s3_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .unwrap();
    assert_eq!(
        s3_default.part_path, s2_default.part_path,
        "S3 inherits default from S2"
    );
    assert_eq!(
        s3_first.part_path, s2_first.part_path,
        "S3 inherits first from S2"
    );
}

/// ISO 29500-1 sections 17.10.2: If the first section has no header at all,
/// the spec says to create a blank header.
///
/// Conceptual test stub for blank header synthesis.
#[test]
fn spec_first_section_without_header_gets_blank() {
    // This is a conceptual constraint test. When Section 1 has no header
    // reference at all, ISO 29500-1 sections 17.10.2 says the application should
    // create an empty (blank) header. Our model does not synthesize
    // headers -- it only represents what is explicitly present in the
    // document package.
    //
    // A future implementation might:
    // 1. Add per-section header resolution to the model
    // 2. Synthesize blank headers when no reference exists
    //
    // For now this test documents the spec requirement.
    // TODO: create fixture with first section lacking any header reference,
    // verify model synthesizes a blank header per §17.10.2
}

// ==========================================================================
// TITLE PAGE INTERACTION (ISO 29500-1 sections 17.10.6 / 17.6.18)
// ==========================================================================

/// ISO 29500-1 sections 17.10.6 / 17.6.18: titlePg enables first-page header.
///
/// The fixture has titlePg=true in the body-level sectPr, with both a
/// default header ("Default Header") and a first-page header
/// ("First Page Header"). This test verifies the headers are parsed
/// and the titlePg flag is present.
#[test]
fn spec_title_page_enables_first_page_header() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "title-page-interaction");

    // Should have at least 2 headers: default + first
    assert!(
        doc.headers.len() >= 2,
        "should have at least 2 headers (default + first), got {}",
        doc.headers.len()
    );

    // Verify first-page header exists with correct content
    let first_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::First);
    assert!(
        first_hdr.is_some(),
        "should have a First-kind header, got kinds: {:?}",
        doc.headers.iter().map(|h| &h.kind).collect::<Vec<_>>()
    );
    let text = blocks_text(&first_hdr.unwrap().blocks);
    assert!(
        text.contains("First Page Header"),
        "First header should contain 'First Page Header', got: '{text}'"
    );

    // Verify default header exists with correct content
    let default_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Default);
    assert!(
        default_hdr.is_some(),
        "should have a Default-kind header, got kinds: {:?}",
        doc.headers.iter().map(|h| &h.kind).collect::<Vec<_>>()
    );
    let text = blocks_text(&default_hdr.unwrap().blocks);
    assert!(
        text.contains("Default Header"),
        "Default header should contain 'Default Header', got: '{text}'"
    );

    // Verify titlePg flag is parsed in body_section_properties
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should be Some -- body-level sectPr has titlePg");
    assert_eq!(
        body_sp.title_page,
        Some(true),
        "body_section_properties.title_page should be Some(true), got {:?}",
        body_sp.title_page
    );
}

/// ISO 29500-1 sections 17.10.6: When titlePg is false (or absent), first-page
/// headers should be ignored and the default header used for all pages.
///
/// Conceptual test stub for titlePg-based header selection. The model
/// preserves all header parts for roundtripping; header selection based
/// on titlePg is a rendering-time decision.
#[test]
fn spec_title_page_false_ignores_first_header() {
    // When titlePg is absent or false, the first-page header should be
    // ignored at rendering time. The model currently stores all headers
    // regardless of the titlePg flag.
    //
    // This is a rendering-layer concern: the model preserves all header
    // parts for roundtripping, but the renderer should consult titlePg
    // to decide which header to display on the first page.
    //
    // A future implementation might add a resolved_header_for_page(n)
    // method that checks titlePg.
    // TODO: create fixture with titlePg=false and first-page header,
    // verify that the model or renderer ignores the first-page header
}

// ==========================================================================
// CONTINUOUS SECTION INHERITANCE (ISO 29500-1 sections 17.6.22)
// ==========================================================================

/// ISO 29500-1 sections 17.6.22: Continuous section inherits page properties.
///
/// Section 1 has explicit margins (top=1440, bottom=1440, left=1800,
/// right=1800). Section 2 is a continuous section break with NO margins
/// specified. Per spec, Section 2 should inherit Section 1's margins.
///
/// The import pipeline propagates page-level properties (margins, page size)
/// from the preceding section into continuous sections that omit them.
#[test]
fn spec_continuous_section_inherits_page_properties() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "continuous-section");

    // Section 1 is a mid-document sectPr with explicit margins
    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section (Section 1)"
    );

    // Verify Section 1 has its explicit margins
    let s1 = section_props[0];
    assert_eq!(
        s1.margin_top,
        Some(1440),
        "Section 1 margin_top should be 1440, got {:?}",
        s1.margin_top
    );
    assert_eq!(
        s1.margin_left,
        Some(1800),
        "Section 1 margin_left should be 1800, got {:?}",
        s1.margin_left
    );

    // Section 2 is the body-level sectPr with continuous type
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should be Some for the continuous section");

    assert_eq!(
        body_sp.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "Section 2 should be continuous, got {:?}",
        body_sp.section_type
    );

    // Per spec, Section 2 (continuous) should inherit margins from Section 1
    // since it doesn't define its own.
    assert_eq!(
        body_sp.margin_top,
        Some(1440),
        "Section 2 (continuous) margin_top should inherit 1440 from Section 1, got {:?}",
        body_sp.margin_top
    );
    assert_eq!(
        body_sp.margin_left,
        Some(1800),
        "Section 2 (continuous) margin_left should inherit 1800 from Section 1, got {:?}",
        body_sp.margin_left
    );
    assert_eq!(
        body_sp.margin_bottom,
        Some(1440),
        "Section 2 (continuous) margin_bottom should inherit 1440 from Section 1, got {:?}",
        body_sp.margin_bottom
    );
    assert_eq!(
        body_sp.margin_right,
        Some(1800),
        "Section 2 (continuous) margin_right should inherit 1800 from Section 1, got {:?}",
        body_sp.margin_right
    );
}
