//! AUTO-GENERATED by the spec-word-compliance workflow.
//!
//! Area: "Cell margins: defaults, per-cell, and exception precedence".
//!
//! Each `#[test]` encodes a Word-consumption / serializer-emission rule mined
//! from ECMA-376 / ISO 29500 / MS-OI29500 for table cell margins (tcMar,
//! tblCellMar, tblPrEx/tblCellMar, tblCellSpacing). A FAILING assertion is NOT a
//! flake to be silenced: it encodes a real Word-compliance gap in the stemma
//! engine. Do not weaken an assertion to make it pass; a fail is the finding.
//!
//! Methodology notes (see workflow brief):
//!  - `xmlContains/xmlOmits/<ordered>` on the re-serialized document.xml are only
//!    valid for markup the serializer ACTIVELY generates/restructures (child
//!    ordering, structural synthesis) or for opens-clean validity. stemma
//!    round-trips UNTOUCHED content byte-verbatim, so these assertions reflect
//!    the verbatim-preservation contract, not Word's render-time normalization.
//!  - Consumption semantics ("pct means width 0", "nil means ignored") are
//!    tested on the READ side (read_accepted/read_rejected text) or via
//!    opens-clean, NOT by asserting the XML drops a verbatim-preserved value.

use std::io::{Read, Write};

use stemma::api::Document;
use zip::write::FileOptions;

// ─── Prelude: zip plumbing + observation helpers ─────────────────────────────

/// Build a minimal valid `.docx` whose `word/document.xml` body is `body_xml`
/// (wrapped in `<w:document><w:body>…</w:body></w:document>`). `extra_parts` are
/// additional `(part_name, xml)` entries (e.g. `word/styles.xml`) that also get
/// a Content-Types override.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );

    // Content-Types: the base defaults + document override, plus an override per
    // extra part (content type derived from the part's file name).
    let mut overrides = String::from(
        r#"<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>"#,
    );
    for (name, _) in extra_parts {
        let ct = if name.ends_with("styles.xml") {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
        } else if name.ends_with("numbering.xml") {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
        } else {
            "application/xml"
        };
        overrides.push_str(&format!(
            r#"<Override PartName="/{name}" ContentType="{ct}"/>"#
        ));
    }
    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>{overrides}</Types>"#
    );

    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;
    let doc_rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>"#;

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (name, xml) in extra_parts {
            zip.start_file(*name, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip `docx` and return `word/document.xml` as a String.
fn document_xml_of(docx: &[u8]) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(docx)).expect("open zip");
    let mut file = archive
        .by_name("word/document.xml")
        .expect("word/document.xml present");
    let mut out = String::new();
    file.read_to_string(&mut out).expect("read document.xml");
    out
}

/// Parse `bytes`, re-serialize via the default export options, and return the
/// resulting `word/document.xml`.
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse");
    let out = doc
        .serialize(&stemma::ExportOptions::default())
        .expect("serialize");
    document_xml_of(&out)
}

/// Position-only ordering: every token appears in `haystack` in sequence, with
/// no constraint on what lies between them. Used to assert child-element ORDER
/// where the tokens are open-tag prefixes (e.g. `<w:top`), so the bytes between
/// consecutive tokens are the remainder of the preceding element, not whitespace.
fn in_order(haystack: &str, tokens: &[&str]) -> bool {
    let mut from = 0usize;
    for tok in tokens {
        match haystack[from..].find(tok) {
            Some(rel) => from += rel + tok.len(),
            None => return false,
        }
    }
    true
}

/// Assert `stemma::api::validate` reports no errors for `bytes`.
fn assert_opens_clean(bytes: &[u8], msg: &str) {
    let report = stemma::api::validate(bytes);
    assert!(
        report.ok,
        "{msg} — validate reported issues: {:?}",
        report.issues
    );
}

// ─── Specs ───────────────────────────────────────────────────────────────────

/// tcmar_pct_width_margin_ignored_not_relabeled_dxa
/// ISO 29500-1 §17.4.34, §17.4.5; MS-OI29500 §2.1.154
/// A pct/auto-typed per-cell margin SHALL be ignored (width 0 / fall back to
/// default), never reinterpreted as a dxa value. Opens-clean is the daily check;
/// the layout consequence is an oracle question.
#[test]
fn tcmar_pct_width_margin_ignored_not_relabeled_dxa() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/><w:tcMar><w:start w:w="500" w:type="pct"/></w:tcMar></w:tcPr><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "tcmar_pct_width_margin_ignored_not_relabeled_dxa: a cell whose only tcMar entry is a pct-typed leading margin is well-formed; Word ignores the pct value but opens without repair (ISO 29500-1 §17.4.34 / MS-OI29500 §2.1.154)",
    );
}

/// tblcellmar_default_bottom_only_applies_and_roundtrips
/// ISO 29500-1 §17.4.42, §17.4.5
/// A bottom-only tblCellMar default must round-trip as exactly one w:bottom child
/// (value 360), not fabricate the other sides nor drop the value.
///
/// NOTE: this asserts on reserialize() of an unedited document. For a value
/// stemma preserves verbatim this is a valid preservation check (the 360 must
/// survive). The "exactly one child" shape is likewise a structural-fidelity
/// claim: the engine must not synthesize the missing sides.
#[test]
fn tblcellmar_default_bottom_only_applies_and_roundtrips() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:bottom w:w="360" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"<w:bottom w:w="360" w:type="dxa"/>"#),
        "tblcellmar_default_bottom_only_applies_and_roundtrips: the bottom-only table default (ISO 29500-1 §17.4.5) must survive regeneration with its exact value 360. XML was: {xml}"
    );
    // Exactly one bottom child, no fabricated top/left/right sides: the canonical
    // bottom-only tblCellMar must appear verbatim (adjacent, single child).
    assert!(
        xml.contains(r#"<w:tblCellMar><w:bottom w:w="360" w:type="dxa"/></w:tblCellMar>"#),
        "tblcellmar_default_bottom_only_applies_and_roundtrips: only the bottom side was specified; the engine must not fabricate top/left/right defaults — tblCellMar contains exactly the one bottom child (ISO 29500-1 §17.4.5 example). XML was: {xml}"
    );
    assert_opens_clean(
        &b,
        "tblcellmar_default_bottom_only_applies_and_roundtrips: tblCellMar with a single bottom child is schema-valid CT_TblCellMar; Word opens without repair (ISO 29500-1 §17.4.5)",
    );
}

/// tcmar_overrides_table_default_per_side_independently
/// ISO 29500-1 §17.4.68, §17.4.42
/// A per-cell tcMar overrides the table tblCellMar default. The override values
/// (720), not the table default (144), govern the cell. Opens-clean is the daily
/// check.
#[test]
fn tcmar_overrides_table_default_per_side_independently() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:top w:w="144" w:type="dxa"/><w:left w:w="144" w:type="dxa"/><w:bottom w:w="144" w:type="dxa"/><w:right w:w="144" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/><w:tcMar><w:top w:w="720" w:type="dxa"/><w:left w:w="720" w:type="dxa"/><w:bottom w:w="720" w:type="dxa"/><w:right w:w="720" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "tcmar_overrides_table_default_per_side_independently: a table default plus a per-cell override are both schema-valid; Word opens without repair (ISO 29500-1 §17.4.68 / §17.4.42)",
    );
}

/// cell_margin_default_side_pct_type_opens_clean
/// ISO 29500-1 §17.4.34; MS-OI29500 §2.1.146
/// A pct-typed table-default leading margin is accepted (width 0), document opens
/// clean, and cell text content is untouched.
#[test]
fn cell_margin_default_side_pct_type_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:start w:w="50" w:type="pct"/><w:top w:w="100" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="2500"/><w:gridCol w:w="2500"/></w:tblGrid><w:tr><w:tc><w:tcPr/><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc><w:tc><w:tcPr/><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "cell_margin_default_side_pct_type_opens_clean: MS-OI29500 §2.1.146 — Word treats a pct-typed margin width as 0 rather than failing, so the document is valid (ISO 29500-1 §17.4.34)",
    );
    let accepted = Document::parse(&b)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text();
    // The spec's "AB" is the concatenation of the two cell texts; stemma's read
    // view separates cells with whitespace (a rendering choice, not content), so
    // compare with inter-cell whitespace collapsed away.
    assert_eq!(
        accepted.split_whitespace().collect::<String>(),
        "AB",
        "cell_margin_default_side_pct_type_opens_clean: the pct-typed margin affects only layout width (Word reads it as 0); cell text content is untouched, so the accepted read view yields the two cell texts (ISO 29500-1 §17.4.34 / MS-OI29500 §2.1.146). Got: {accepted:?}"
    );
}

/// cell_margin_default_bottom_pct_type_opens_clean
/// ISO 29500-1 §17.4.5; MS-OI29500 §2.1.119, §2.1.177
/// An auto/pct-typed table-default bottom margin is accepted (width 0), opens
/// clean.
#[test]
fn cell_margin_default_bottom_pct_type_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:bottom w:w="120" w:type="auto"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr/><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "cell_margin_default_bottom_pct_type_opens_clean: MS-OI29500 §2.1.119 -> §17.4.77(a) — Word interprets an auto/pct bottom margin width as 0 rather than failing, so validate must find no errors (ISO 29500-1 §17.4.5)",
    );
}

/// cell_spacing_default_pct_type_opens_clean
/// ISO 29500-1 §17.4.43; MS-OI29500 §2.1.154
/// A pct/auto tblCellSpacing is accepted (width 0), opens clean, content
/// untouched.
#[test]
fn cell_spacing_default_pct_type_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellSpacing w:w="100" w:type="pct"/></w:tblPr><w:tblGrid><w:gridCol w:w="2500"/><w:gridCol w:w="2500"/></w:tblGrid><w:tr><w:tc><w:tcPr/><w:p><w:r><w:t>X</w:t></w:r></w:p></w:tc><w:tc><w:tcPr/><w:p><w:r><w:t>Y</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "cell_spacing_default_pct_type_opens_clean: MS-OI29500 §2.1.154 — Word substitutes width 0 for a pct cell-spacing type rather than failing, so validate must find no errors (ISO 29500-1 §17.4.43)",
    );
    let accepted = Document::parse(&b)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text();
    // Cell texts concatenated; stemma separates cells with whitespace in the read
    // view, so collapse it (the separator is rendering, not content).
    assert_eq!(
        accepted.split_whitespace().collect::<String>(),
        "XY",
        "cell_spacing_default_pct_type_opens_clean: cell spacing affects only layout, not content; the accepted read view yields the two cell texts unchanged (ISO 29500-1 §17.4.43 / MS-OI29500 §2.1.154). Got: {accepted:?}"
    );
}

/// tcmar_nil_side_ignored_opens_clean
/// ISO 29500-1 §17.4.68; MS-OI29500 §2.1.177
/// A nil-typed per-cell margin side is ignored (falls back to default), opens
/// clean, content untouched.
#[test]
fn tcmar_nil_side_ignored_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:top w:w="150" w:type="dxa"/><w:left w:w="150" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcMar><w:top w:w="0" w:type="nil"/><w:left w:w="400" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "tcmar_nil_side_ignored_opens_clean: MS-OI29500 §2.1.177 — Word ignores the nil-typed top side and applies the dxa left side; the document is valid so validate must find no errors (ISO 29500-1 §17.4.68)",
    );
    let accepted = Document::parse(&b)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text();
    assert_eq!(
        accepted.trim(),
        "cell",
        "tcmar_nil_side_ignored_opens_clean: margin types affect layout, not content; the cell text survives the accepted read view (ISO 29500-1 §17.4.68 / MS-OI29500 §2.1.177). Got: {accepted:?}"
    );
}

/// tblprex_cell_margin_exception_opens_clean
/// ISO 29500-1 §17.4.41, §17.4.42
/// Row-level tblCellMar inside tblPrEx is valid markup; opens clean, both rows'
/// cell texts survive.
#[test]
fn tblprex_cell_margin_exception_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:top w:w="100" w:type="dxa"/><w:left w:w="100" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:trPr/><w:tc><w:tcPr/><w:p><w:r><w:t>row1</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tblPrEx><w:tblCellMar><w:top w:w="400" w:type="dxa"/><w:left w:w="400" w:type="dxa"/></w:tblCellMar></w:tblPrEx><w:tc><w:tcPr/><w:p><w:r><w:t>row2</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "tblprex_cell_margin_exception_opens_clean: ISO 29500-1 §17.4.41 — tblCellMar inside tblPrEx is valid markup; stemma::api::validate must report no errors",
    );
    let accepted = Document::parse(&b)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text();
    assert_eq!(
        accepted.split_whitespace().collect::<String>(),
        "row1row2",
        "tblprex_cell_margin_exception_opens_clean: the exception layer changes only margins; both rows' cell texts survive in the accepted read view (ISO 29500-1 §17.4.41 / §17.4.42). Got: {accepted:?}"
    );
}

/// tblprex_cell_margin_exception_applied_to_row
/// ISO 29500-1 §17.4.41, §17.4.42
/// A row-level tblPrEx/tblCellMar (144) overrides the table default (50) for that
/// row and must not be silently dropped. stemma has no tblPrEx parse/serialize
/// path, so the 144 exception is expected to be lost on structural reserialize —
/// this is the gap the spec hunts.
///
/// NOTE: a verbatim passthrough would preserve the 144 too, so this xmlContains
/// is a real test of whether stemma drops tblPrEx. A PASS means the 144 survived
/// (verbatim or modeled); a FAIL means it was dropped, the documented gap.
#[test]
fn tblprex_cell_margin_exception_applied_to_row() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblCellMar><w:top w:w="50" w:type="dxa"/><w:start w:w="50" w:type="dxa"/><w:bottom w:w="50" w:type="dxa"/><w:end w:w="50" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tblPrEx><w:tblCellMar><w:top w:w="144" w:type="dxa"/><w:start w:w="144" w:type="dxa"/><w:bottom w:w="144" w:type="dxa"/><w:end w:w="144" w:type="dxa"/></w:tblCellMar></w:tblPrEx><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:w="144""#),
        "tblprex_cell_margin_exception_applied_to_row: the row's tblPrEx/tblCellMar exception (144tw) governs that row's cell margins (ISO 29500-1 §17.4.41); a faithful engine must preserve the 144 exception, not drop it back to the table default 50tw. XML was: {xml}"
    );
    assert_opens_clean(
        &b,
        "tblprex_cell_margin_exception_applied_to_row: the serialized table with row exceptions must open in Word without repair (ISO 29500-1 §17.4.41 / §17.4.42)",
    );
}

/// tcmar_serialized_side_order_top_left_bottom_right
/// ISO 29500-1 §A.1 (CT_TcMar), §17.4.68
/// When the engine emits w:tcMar its side children must be in schema order: top,
/// leading (start/left), bottom, trailing (end/right).
#[test]
fn tcmar_serialized_side_order_top_left_bottom_right() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/><w:tcMar><w:top w:w="100" w:type="dxa"/><w:start w:w="200" w:type="dxa"/><w:bottom w:w="300" w:type="dxa"/><w:end w:w="400" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    // CT_TcMar mandates top, then leading (left|start), then bottom, then
    // trailing (right|end). stemma normalizes start->left / end->right, so accept
    // either spelling at the leading/trailing positions.
    let order_left = in_order(
        &xml,
        &[
            "<w:tcMar>",
            "<w:top",
            "<w:left",
            "<w:bottom",
            "<w:right",
            "</w:tcMar>",
        ],
    );
    let order_start = in_order(
        &xml,
        &[
            "<w:tcMar>",
            "<w:top",
            "<w:start",
            "<w:bottom",
            "<w:end",
            "</w:tcMar>",
        ],
    );
    assert!(
        order_left || order_start,
        "tcmar_serialized_side_order_top_left_bottom_right: CT_TcMar mandates the side sequence top, leading, bottom, trailing; the serialized tcMar must match this order to be schema-valid (ISO 29500-1 §A.1 / §17.4.68). XML was: {xml}"
    );
    assert_opens_clean(
        &b,
        "tcmar_serialized_side_order_top_left_bottom_right: a schema-ordered tcMar opens in Word without repair (ISO 29500-1 §A.1)",
    );
}

/// tcmar_start_end_aliases_accepted_and_applied
/// ISO 29500-1 §A.1 (CT_TcMar transitional), §17.4.68, §17.4.34
/// The leading/trailing margins authored with w:start / w:end must be accepted,
/// applied, and the values (720 / 360) preserved through serialization (stemma
/// maps start->left, end->right).
#[test]
fn tcmar_start_end_aliases_accepted_and_applied() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/><w:tcMar><w:start w:w="720" w:type="dxa"/><w:end w:w="360" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:w="720""#),
        "tcmar_start_end_aliases_accepted_and_applied: the leading-margin value authored via w:start (720tw) must be preserved through serialization; dropping it would lose the cell's leading margin (ISO 29500-1 §17.4.34, CT_TcMar §A.1). XML was: {xml}"
    );
    assert!(
        xml.contains(r#"w:w="360""#),
        "tcmar_start_end_aliases_accepted_and_applied: the trailing-margin value authored via w:end (360tw) must likewise be preserved; the alias is schema-valid and not ignorable (ISO 29500-1 §17.4.68, CT_TcMar §A.1). XML was: {xml}"
    );
    assert_opens_clean(
        &b,
        "tcmar_start_end_aliases_accepted_and_applied: a tcMar using start/end (or normalized to left/right) must open in Word without repair (ISO 29500-1 §A.1)",
    );
}

// ─── Oracle-resolved verbatim-passthrough guards ────────────────
// These three pin the consumption-vs-save boundary: an UNEDITED parse->serialize
// round-trips document.xml byte-verbatim, so out-of-CT_TblCellMar/CT_TcMar-order
// margin children and w:start/w:end aliases survive un-normalized. The open
// question was whether real Word repairs such a verbatim doc. ORACLE-CONFIRMED
// (Word /validate: repaired=false for all three) — Word opens clean, so the
// verbatim contract is correct and validate() must NOT flag these. (The
// regeneration path — project/apply/diff — independently emits canonical schema
// order; that is covered by tcmar_serialized_side_order_top_left_bottom_right.)

/// Table-default `tblCellMar` children authored out of CT_TblCellMar sequence
/// (bottom, right, top, left) open clean — Word does not repair the verbatim doc.
#[test]
fn tblcellmar_out_of_schema_order_opens_clean_verbatim() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:bottom w:w="111" w:type="dxa"/><w:right w:w="222" w:type="dxa"/><w:top w:w="333" w:type="dxa"/><w:left w:w="444" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr/><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "out-of-order table-default tblCellMar children are well-formed; an unedited doc round-trips verbatim and real Word opens it without repair (oracle /validate: repaired=false). validate() must not flag the verbatim path (ISO 29500-1 §17.4.42, §A.1)",
    );
}

/// Table-default `tblCellMar` using `w:start`/`w:end` aliases (un-normalized to
/// left/right on the verbatim path) opens clean — Word does not repair.
#[test]
fn tblcellmar_start_end_aliases_open_clean_verbatim() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="dxa"/><w:tblCellMar><w:start w:w="240" w:type="dxa"/><w:end w:w="480" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr/><w:p><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "w:start/w:end are transitional-valid aliases; stemma round-trips an unedited table verbatim (no normalization) and real Word opens it without repair (oracle /validate: repaired=false) (ISO 29500-1 §17.4.42, §A.1)",
    );
}

/// Per-cell `tcMar` children authored out of CT_TcMar sequence open clean — Word
/// does not repair the verbatim doc.
#[test]
fn tcmar_out_of_schema_order_opens_clean_verbatim() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="5000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="5000" w:type="dxa"/><w:tcMar><w:right w:w="9" w:type="dxa"/><w:bottom w:w="42" w:type="dxa"/><w:left w:w="76" w:type="dxa"/><w:top w:w="108" w:type="dxa"/></w:tcMar></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert_opens_clean(
        &b,
        "out-of-order per-cell tcMar children are well-formed; an unedited doc round-trips verbatim and real Word opens it without repair (oracle /validate: repaired=false) (ISO 29500-1 §17.4.68, §A.1)",
    );
}
