//! Spec-compliance tests: Run Serialization (theme fonts & rPr element ordering)
//!
//! These tests verify two categories of serialization correctness:
//! 1. Theme font roundtrip fidelity — do theme font references (asciiTheme,
//!    hAnsiTheme, eastAsiaTheme) survive import → diff_and_redline → export?
//! 2. rPr element ordering — does the serializer emit child elements of
//!    w:rPr in the order mandated by ECMA-376 Annex A (CT_RPr)?
//!
//! Each fixture is a before/after DOCX pair with a text change in a separate
//! paragraph. This forces the code through `serialize_canonical_docx` (which
//! calls `build_rpr`). An identity diff takes an early-return path that
//! preserves the original XML bytes and would bypass the serializer entirely.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/run-serialization/create_docs.py`.

use std::fs;
use std::io::{Cursor, Read};

use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
use xmltree::{Element, XMLNode};
use zip::ZipArchive;

const FIXTURES: &str = "testdata/spec-compliance/run-serialization";

// ── helpers ──────────────────────────────────────────────────────────────

/// Diff-and-redline a before/after pair, export, return raw DOCX bytes.
///
/// The text change between before and after forces the code through
/// `serialize_canonical_docx`, which rebuilds the XML from the domain model.
fn redline_export(before_path: &str, after_path: &str) -> Vec<u8> {
    let before = fs::read(before_path).unwrap_or_else(|e| panic!("read {before_path}: {e}"));
    let after = fs::read(after_path).unwrap_or_else(|e| panic!("read {after_path}: {e}"));

    let runtime = SimpleRuntime::new();
    let ib = runtime.import_docx(&before).expect("import before");
    let ia = runtime.import_docx(&after).expect("import after");

    let meta = TransactionMeta {
        author: "spec_run_serialization".to_string(),
        reason: Some("run-serialization spec test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&ib.doc_handle, &ia.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");

    runtime
        .export_docx(&ib.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

/// Extract word/document.xml from a DOCX byte buffer.
fn extract_document_xml(docx_bytes: &[u8]) -> String {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("DOCX must contain word/document.xml");
    let mut out = String::new();
    file.read_to_string(&mut out)
        .expect("read word/document.xml");
    out
}

fn parse_xml(xml: &str) -> Element {
    Element::parse(Cursor::new(xml.as_bytes())).expect("parse XML")
}

fn local_name(name: &str) -> &str {
    match name.rsplit_once(':') {
        Some((_, local)) => local,
        None => name,
    }
}

const WORD_NS: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

fn is_w_tag(element: &Element, local: &str) -> bool {
    let name = local_name(&element.name);
    if name != local {
        return false;
    }
    if element.prefix.as_deref() == Some("w") {
        return true;
    }
    if element.namespace.as_deref() == Some(WORD_NS) {
        return true;
    }
    element.name == local || element.name == format!("w:{local}")
}

fn attr_value<'a>(element: &'a Element, qname: &str) -> Option<&'a str> {
    let (_prefix, local) = match qname.split_once(':') {
        Some((p, l)) if !p.is_empty() && !l.is_empty() => (Some(p), l),
        _ => (None, qname),
    };

    for (name, value) in &element.attributes {
        if name.local_name == local {
            return Some(value);
        }
    }

    for (name, value) in &element.attributes {
        if name.local_name == qname {
            return Some(value);
        }
    }

    None
}

/// Find all elements matching a w: tag, recursively.
fn find_all_w_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if is_w_tag(root, tag) {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_w_elements(el, tag, out);
        }
    }
}

/// Find a direct w: child element with a given tag.
#[allow(dead_code)]
fn find_w_child<'a>(parent: &'a Element, tag: &str) -> Option<&'a Element> {
    parent.children.iter().find_map(|child| match child {
        XMLNode::Element(el) if is_w_tag(el, tag) => Some(el),
        _ => None,
    })
}

/// Get all direct child element local names (w: namespace) of an element, in order.
fn child_element_names(parent: &Element) -> Vec<String> {
    parent
        .children
        .iter()
        .filter_map(|child| match child {
            XMLNode::Element(el) => Some(local_name(&el.name).to_string()),
            _ => None,
        })
        .collect()
}

/// Format rFonts attributes for diagnostic output.
fn rfonts_attr_summary(elements: &[&Element]) -> Vec<Vec<String>> {
    elements
        .iter()
        .map(|el| {
            el.attributes
                .iter()
                .map(|(k, v)| format!("{}={}", k.local_name, v))
                .collect::<Vec<_>>()
        })
        .collect()
}

// =========================================================================
// Test 1: Theme font reference preserved on roundtrip (asciiTheme)
// ISO 29500-1 §17.3.2.26
// =========================================================================

/// ISO 29500-1 §17.3.2.26: Theme font references (asciiTheme/hAnsiTheme)
/// should survive import → diff_and_redline → export.
///
/// `StyleProps` carries theme font reference strings alongside resolved font
/// names. On export, `build_rpr` emits both the theme attribute (for
/// theme-aware readers) and the direct attribute (as fallback).
#[test]
fn spec_theme_font_reference_preserved_on_roundtrip() {
    let before_path = format!("{FIXTURES}/theme-font-ascii/before.docx");
    let after_path = format!("{FIXTURES}/theme-font-ascii/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Find all rFonts elements in the output
    let mut rfonts_elements = Vec::new();
    find_all_w_elements(&root, "rFonts", &mut rfonts_elements);

    // There should be at least one rFonts (our run's font reference)
    assert!(
        !rfonts_elements.is_empty(),
        "exported DOCX should contain at least one w:rFonts element"
    );

    // Check if any rFonts has asciiTheme or hAnsiTheme attributes
    let has_ascii_theme = rfonts_elements
        .iter()
        .any(|el| attr_value(el, "w:asciiTheme").is_some());
    let has_hansi_theme = rfonts_elements
        .iter()
        .any(|el| attr_value(el, "w:hAnsiTheme").is_some());

    assert!(
        has_ascii_theme,
        "ISO 29500-1 §17.3.2.26: rFonts should preserve w:asciiTheme='minorHAnsi' \
         on roundtrip, but no rFonts element has an asciiTheme attribute. \
         The theme reference was resolved to an explicit font name and lost. \
         Found rFonts attributes: {:?}",
        rfonts_attr_summary(&rfonts_elements)
    );
    assert!(
        has_hansi_theme,
        "ISO 29500-1 §17.3.2.26: rFonts should preserve w:hAnsiTheme='minorHAnsi' \
         on roundtrip, but no rFonts element has an hAnsiTheme attribute. \
         Found rFonts attributes: {:?}",
        rfonts_attr_summary(&rfonts_elements)
    );
}

// =========================================================================
// Test 2: Theme font eastAsia reference preserved
// ISO 29500-1 §17.3.2.26
// =========================================================================

/// ISO 29500-1 §17.3.2.26: eastAsiaTheme reference should survive roundtrip.
///
/// `StyleProps.font_east_asia_theme` carries the theme reference string
/// alongside the resolved font name in `font_east_asia`.
#[test]
fn spec_theme_font_eastasia_reference_preserved() {
    let before_path = format!("{FIXTURES}/theme-font-eastasia/before.docx");
    let after_path = format!("{FIXTURES}/theme-font-eastasia/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut rfonts_elements = Vec::new();
    find_all_w_elements(&root, "rFonts", &mut rfonts_elements);

    // The fixture has eastAsiaTheme="minorEastAsia".
    // After roundtrip through the serializer, eastAsiaTheme must be preserved.

    let has_east_asia_theme = rfonts_elements
        .iter()
        .any(|el| attr_value(el, "w:eastAsiaTheme").is_some());

    assert!(
        has_east_asia_theme,
        "ISO 29500-1 §17.3.2.26: rFonts should preserve w:eastAsiaTheme='minorEastAsia' \
         on roundtrip, but no rFonts element has an eastAsiaTheme attribute. \
         The theme reference was resolved to an explicit font name and lost. \
         Found rFonts attributes: {:?}",
        rfonts_attr_summary(&rfonts_elements)
    );
}

// =========================================================================
// Test 3: Explicit font name survives roundtrip
// ISO 29500-1 §17.3.2.26
// =========================================================================

/// ISO 29500-1 §17.3.2.26: Explicit font names (w:ascii, w:hAnsi) should
/// survive import → diff_and_redline → export.
///
/// Unlike theme fonts, explicit font names are stored in `StyleProps.font_family`
/// and serialized back as `w:ascii`/`w:hAnsi` attributes by `build_rpr`.
#[test]
fn spec_explicit_font_survives_roundtrip() {
    let before_path = format!("{FIXTURES}/explicit-font/before.docx");
    let after_path = format!("{FIXTURES}/explicit-font/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut rfonts_elements = Vec::new();
    find_all_w_elements(&root, "rFonts", &mut rfonts_elements);

    // Find an rFonts with ascii="Courier New"
    let has_courier = rfonts_elements.iter().any(|el| {
        attr_value(el, "w:ascii")
            .or_else(|| attr_value(el, "ascii"))
            .is_some_and(|v| v == "Courier New")
    });

    assert!(
        has_courier,
        "ISO 29500-1 §17.3.2.26: rFonts with w:ascii='Courier New' should survive \
         roundtrip through the serializer. Found rFonts attributes: {:?}",
        rfonts_attr_summary(&rfonts_elements)
    );

    // Also verify hAnsi matches
    let has_hansi_courier = rfonts_elements.iter().any(|el| {
        attr_value(el, "w:hAnsi")
            .or_else(|| attr_value(el, "hAnsi"))
            .is_some_and(|v| v == "Courier New")
    });

    assert!(
        has_hansi_courier,
        "ISO 29500-1 §17.3.2.26: rFonts with w:hAnsi='Courier New' should survive roundtrip. \
         Found rFonts attributes: {:?}",
        rfonts_attr_summary(&rfonts_elements)
    );
}

// =========================================================================
// Test 4: bdr element ordered correctly in rPr
// ECMA-376 Annex A CT_RPr
// =========================================================================

/// Verifies that w:bdr (run border) is emitted at sequence position 29
/// per ECMA-376 Annex A CT_RPr, between w:u (27) and w:vertAlign (32).
#[test]

fn spec_rpr_bdr_element_ordered_correctly() {
    let before_path = format!("{FIXTURES}/rpr-bdr-ordering/before.docx");
    let after_path = format!("{FIXTURES}/rpr-bdr-ordering/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Find rPr elements that contain bdr
    let mut rpr_elements = Vec::new();
    find_all_w_elements(&root, "rPr", &mut rpr_elements);

    let rpr_with_bdr: Vec<_> = rpr_elements
        .iter()
        .filter(|rpr| {
            rpr.children.iter().any(|c| match c {
                XMLNode::Element(el) => is_w_tag(el, "bdr"),
                _ => false,
            })
        })
        .collect();

    assert!(
        !rpr_with_bdr.is_empty(),
        "exported DOCX should contain at least one w:rPr with a w:bdr child \
         (the fixture has a run with a border). \
         All rPr child names: {:?}",
        rpr_elements
            .iter()
            .map(|rpr| child_element_names(rpr))
            .collect::<Vec<_>>()
    );

    for rpr in &rpr_with_bdr {
        let child_names = child_element_names(rpr);

        let bdr_pos = child_names.iter().position(|n| n == "bdr");
        let vert_align_pos = child_names.iter().position(|n| n == "vertAlign");
        let u_pos = child_names.iter().position(|n| n == "u");
        let highlight_pos = child_names.iter().position(|n| n == "highlight");

        // bdr must come BEFORE vertAlign (if both present)
        if let (Some(bdr), Some(va)) = (bdr_pos, vert_align_pos) {
            assert!(
                bdr < va,
                "ECMA-376 Annex A CT_RPr: w:bdr (pos 28) must come before w:vertAlign (pos 31), \
                 but bdr is at index {bdr} and vertAlign is at index {va} in rPr children. \
                 Actual order: {child_names:?}"
            );
        }

        // bdr must come AFTER u (if both present)
        if let (Some(u), Some(bdr)) = (u_pos, bdr_pos) {
            assert!(
                u < bdr,
                "ECMA-376 Annex A CT_RPr: w:u (pos 27) must come before w:bdr (pos 28), \
                 but u is at index {u} and bdr is at index {bdr} in rPr children. \
                 Actual order: {child_names:?}"
            );
        }

        // bdr must come AFTER highlight (if both present)
        if let (Some(hl), Some(bdr)) = (highlight_pos, bdr_pos) {
            assert!(
                hl < bdr,
                "ECMA-376 Annex A CT_RPr: w:highlight (pos 26) must come before w:bdr (pos 28), \
                 but highlight is at index {hl} and bdr is at index {bdr}. \
                 Actual order: {child_names:?}"
            );
        }
    }
}

// =========================================================================
// Test 5: Complete rPr element ordering
// ECMA-376 Annex A CT_RPr
// =========================================================================

/// ECMA-376 Annex A CT_RPr: All child elements of rPr must be in the correct
/// sequence order.
///
/// Expected order (positions from the schema):
///   rStyle(1), rFonts(2), b(3), bCs(4), i(5), iCs(6), caps(7), smallCaps(8),
///   strike(9), dstrike(10), outline(11), shadow(12), emboss(13), imprint(14),
///   ..., vanish(17), ..., color(19), spacing(20), w(21), kern(22),
///   position(23), sz(24), szCs(25), highlight(26), u(27), bdr(28), ...,
///   vertAlign(31), rtl(32), cs(33), ..., lang(35), ..., rPrChange(40)
///
/// This test verifies that all emitted elements appear in non-decreasing
/// position order. The fixture has a run with b, i, rFonts, color, sz, szCs,
/// highlight, u, vertAlign, rtl, cs, lang.
///
/// This test catches any ordering violation in the serializer's output.
/// Note: the fixture does not include bdr, which is tested separately in
/// `spec_rpr_bdr_element_ordered_correctly`.
#[test]
fn spec_rpr_element_ordering_complete() {
    let before_path = format!("{FIXTURES}/rpr-full-ordering/before.docx");
    let after_path = format!("{FIXTURES}/rpr-full-ordering/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // ECMA-376 Annex A CT_RPr element ordering (position number -> element name)
    let ordering: &[(&str, u32)] = &[
        ("rStyle", 1),
        ("rFonts", 2),
        ("b", 3),
        ("bCs", 4),
        ("i", 5),
        ("iCs", 6),
        ("caps", 7),
        ("smallCaps", 8),
        ("strike", 9),
        ("dstrike", 10),
        ("outline", 11),
        ("shadow", 12),
        ("emboss", 13),
        ("imprint", 14),
        ("noProof", 15),
        ("snapToGrid", 16),
        ("vanish", 17),
        ("webHidden", 18),
        ("color", 19),
        ("spacing", 20),
        ("w", 21),
        ("kern", 22),
        ("position", 23),
        ("sz", 24),
        ("szCs", 25),
        ("highlight", 26),
        ("u", 27),
        ("effect", 28),
        ("bdr", 29),
        ("shd", 30),
        ("fitText", 31),
        ("vertAlign", 32),
        ("rtl", 33),
        ("cs", 34),
        ("em", 35),
        ("lang", 36),
        ("eastAsianLayout", 37),
        ("specVanish", 38),
        ("oMath", 39),
        ("rPrChange", 40),
    ];

    fn position_of(name: &str, ordering: &[(&str, u32)]) -> Option<u32> {
        ordering.iter().find(|(n, _)| *n == name).map(|(_, p)| *p)
    }

    // Find all rPr elements
    let mut rpr_elements = Vec::new();
    find_all_w_elements(&root, "rPr", &mut rpr_elements);

    // Find the rPr with the most known children (our test run)
    let rpr = rpr_elements
        .iter()
        .max_by_key(|rpr| {
            child_element_names(rpr)
                .iter()
                .filter(|n| position_of(n, ordering).is_some())
                .count()
        })
        .expect("exported DOCX should contain at least one w:rPr element");

    let child_names = child_element_names(rpr);

    // Sanity check: the rPr should have a meaningful number of elements
    let known_count = child_names
        .iter()
        .filter(|n| position_of(n, ordering).is_some())
        .count();
    assert!(
        known_count >= 5,
        "expected the test rPr to have at least 5 known elements, got {known_count}. \
         Child names: {child_names:?}"
    );

    // Verify all elements appear in non-decreasing position order
    let mut last_pos: u32 = 0;
    let mut last_name = String::new();

    for name in &child_names {
        if let Some(pos) = position_of(name, ordering) {
            assert!(
                pos >= last_pos,
                "ECMA-376 Annex A CT_RPr ordering violation: \
                 w:{name} (position {pos}) appears after w:{last_name} (position {last_pos}). \
                 Elements must be in ascending position order. \
                 Full rPr child order: {child_names:?}"
            );
            last_pos = pos;
            last_name = name.clone();
        }
        // Elements not in our ordering table are ignored (e.g., extension elements)
    }
}

// =========================================================================
// Test 6: w:webHidden survives the authoring (model-rebuild) path
// ISO/IEC 29500-1 §17.3.2.44
// =========================================================================

/// Build a minimal in-memory `.docx` wrapping `body_xml` in
/// `<w:document><w:body>…</w:body></w:document>`.
fn make_docx(body_xml: &str) -> Vec<u8> {
    use std::io::Write;
    use zip::write::FileOptions;

    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );
    let content_types = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>"#;
    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;
    let doc_rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>"#;

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

/// Diff-and-redline an in-memory before/after pair, export, return DOCX bytes.
/// Mirrors `redline_export` but takes bytes so the test is self-contained.
fn redline_export_bytes(before: &[u8], after: &[u8]) -> Vec<u8> {
    let runtime = SimpleRuntime::new();
    let ib = runtime.import_docx(before).expect("import before");
    let ia = runtime.import_docx(after).expect("import after");
    let meta = TransactionMeta {
        author: "spec_run_serialization".to_string(),
        reason: Some("webHidden authoring-path spec test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&ib.doc_handle, &ia.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");
    runtime
        .export_docx(&ib.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

/// ISO/IEC 29500-1 §17.3.2.44: `w:webHidden` is a CT_OnOff run property that
/// hides a run when the document is displayed as a web page. It is a real
/// formatting property, not packaging noise, so it must survive an edit that
/// rebuilds the run from the domain model — not merely the verbatim-bytes path.
///
/// The before document carries a run with `<w:webHidden/>` in a paragraph that
/// is left untouched; the edit changes the text of a *different* paragraph.
/// `diff_and_redline` + export forces the whole body through
/// `serialize_canonical_docx` → `build_rpr`, so a model that dropped webHidden
/// (verbatim-passthrough only) would lose it here. This is the authoring-path
/// regression guard for the webHidden model.
#[test]
fn spec_web_hidden_survives_authoring_rebuild() {
    let before = make_docx(
        r#"<w:p><w:r><w:rPr><w:webHidden/></w:rPr><w:t>hidden on web</w:t></w:r></w:p>
<w:p><w:r><w:t>edit me</w:t></w:r></w:p><w:sectPr/>"#,
    );
    let after = make_docx(
        r#"<w:p><w:r><w:rPr><w:webHidden/></w:rPr><w:t>hidden on web</w:t></w:r></w:p>
<w:p><w:r><w:t>edited!</w:t></w:r></w:p><w:sectPr/>"#,
    );

    let exported = redline_export_bytes(&before, &after);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // The webHidden run was rebuilt by the serializer; webHidden must remain.
    let mut rpr_elements = Vec::new();
    find_all_w_elements(&root, "rPr", &mut rpr_elements);
    let has_web_hidden = rpr_elements.iter().any(|rpr| {
        rpr.children.iter().any(|c| match c {
            XMLNode::Element(el) => is_w_tag(el, "webHidden"),
            _ => false,
        })
    });

    assert!(
        has_web_hidden,
        "ISO/IEC 29500-1 §17.3.2.44: w:webHidden must survive an edit that \
         rebuilds the run through build_rpr, but no w:webHidden child was found. \
         All rPr child names: {:?}",
        rpr_elements
            .iter()
            .map(|rpr| child_element_names(rpr))
            .collect::<Vec<_>>()
    );
}
