//! Spec-compliance tests: Table Border Conflict Edge Cases
//!
//! These tests cover two gaps in border conflict resolution:
//! 1. One-sided border conflicts — when one cell has a border and the adjacent
//!    cell has `None`, the existing border should propagate (MS-OI29500 §2.1.169).
//! 2. Color brightness tiebreaker — when two borders have equal weight, the
//!    darker color wins per brightness formula R + B + 2*G (MS-OI29500 §2.1.169).
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-border-conflict-edge-cases/create_docs.py`

use stemma::{BlockNode, BorderStyle, CanonDoc};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-border-conflict-edge-cases";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

// =============================================================================
// 1. One-sided border propagates to neighbor
//    MS-OI29500 §2.1.169: When one cell has a border and the adjacent cell has
//    none, "the opposing border shall be displayed."
// =============================================================================

/// MS-OI29500 §2.1.169: When one cell has a border on a shared edge and the
/// adjacent cell has `None`, the existing border should be propagated to the
/// neighbor. The code currently `continue`s when one side is `None`, skipping
/// resolution entirely.
///
/// Cell (0,0) has right border = single sz=12 red.
/// Cell (0,1) has no tcBorders at all (so left = None after table fallback).
/// After conflict resolution, cell (0,1)'s left border should also be the
/// red border — "none" means the opposing border wins.
#[test]
fn spec_one_sided_border_propagates_to_neighbor() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "one-sided-border-propagates");
    let table = first_table(&doc);

    // Precondition: cell (0,0) should have its explicit right border.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border should be red"
    );
    assert_eq!(
        cell_00_right.size,
        Some(12),
        "cell (0,0) right border size should be 12"
    );
    assert_eq!(
        cell_00_right.style,
        BorderStyle::Single,
        "cell (0,0) right border style should be Single"
    );

    // The key assertion: cell (0,1) had no borders, so its left border was
    // None. Per MS-OI29500 §2.1.169, when one side has none, the opposing
    // border displays. After conflict resolution, cell (0,1)'s left border
    // should be the red border from cell (0,0).
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref());
    assert!(
        cell_01_left.is_some(),
        "cell (0,1) left border should exist after conflict resolution — \
         MS-OI29500 SS2.1.169: when one cell has none, the opposing border wins"
    );
    let cell_01_left = cell_01_left.unwrap();
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (propagated from cell (0,0) right) — \
         MS-OI29500 SS2.1.169: the opposing border shall be displayed"
    );
    assert_eq!(
        cell_01_left.size,
        Some(12),
        "cell (0,1) left border size should be 12 (from cell (0,0) right)"
    );
    assert_eq!(
        cell_01_left.style,
        BorderStyle::Single,
        "cell (0,1) left border style should be Single (from cell (0,0) right)"
    );
}

// =============================================================================
// 2. Table insideV fallback — both cells at shared edge agree
//    ISO 29500-1 §17.4.66: insideV from table-level should cascade to interior
//    cells and both cells at a shared edge should agree after resolution.
// =============================================================================

/// ISO 29500-1 §17.4.66: insideV from table-level cascades to interior cells.
/// Both cells at a shared vertical edge should have matching borders after
/// table-to-cell fallback and conflict resolution.
///
/// 2x2 table with only insideV = blue single sz=8. No cell-level borders.
/// Cell (0,0) right and cell (0,1) left should both be blue after resolution.
#[test]
fn spec_table_insidv_fallback_both_cells_agree() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "one-sided-table-fallback");
    let table = first_table(&doc);

    // Precondition: table has insideV border.
    let tbl_borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have borders");
    let inside_v = tbl_borders
        .inside_v
        .as_ref()
        .expect("table should have insideV border");
    assert_eq!(
        inside_v.color.as_deref(),
        Some("0000FF"),
        "table insideV should be blue"
    );

    // Cell (0,0) right border should be insideV (blue).
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect(
            "cell (0,0) should have a right border (from insideV fallback) — \
             ISO 29500-1 SS17.4.66: interior cells inherit insideV",
        );
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) right border should be blue (from insideV)"
    );
    assert_eq!(
        cell_00_right.size,
        Some(8),
        "cell (0,0) right border size should be 8 (from insideV)"
    );

    // Cell (0,1) left border should also be insideV (blue).
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect(
            "cell (0,1) should have a left border (from insideV fallback) — \
             ISO 29500-1 SS17.4.66: interior cells inherit insideV",
        );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("0000FF"),
        "cell (0,1) left border should be blue (from insideV)"
    );
    assert_eq!(
        cell_01_left.size,
        Some(8),
        "cell (0,1) left border size should be 8 (from insideV)"
    );

    // Both sides of the shared edge should agree.
    assert_eq!(
        cell_00_right.color, cell_01_left.color,
        "both cells at the shared edge should agree on border color"
    );
    assert_eq!(
        cell_00_right.size, cell_01_left.size,
        "both cells at the shared edge should agree on border size"
    );
    assert_eq!(
        cell_00_right.style, cell_01_left.style,
        "both cells at the shared edge should agree on border style"
    );
}

// =============================================================================
// 3. Color brightness tiebreaker — darker wins
//    MS-OI29500 §2.1.169: Equal weight → brightness = R + B + 2*G,
//    smaller (darker) wins.
// =============================================================================

/// Verifies MS-OI29500 §2.1.169 color brightness tiebreaker: when two
/// borders have equal weight, the darker color wins (brightness = R + B + 2*G).
///
/// Cell (0,0) right: single sz=8 color="000080" (dark blue, brightness=128)
/// Cell (0,1) left:  single sz=8 color="80FF80" (light green, brightness=766)
/// Same style (single) and size (8), so weight is equal (8*1=8).
/// Dark blue (brightness=128) < light green (brightness=766), so dark blue wins.
#[test]
fn spec_color_tiebreaker_darker_wins() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "color-tiebreaker-darker-wins");
    let table = first_table(&doc);

    // Precondition: verify both cells have their initial borders.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // Both borders have weight 8 (single * sz=8).
    // Per MS-OI29500 §2.1.169, the tiebreaker is color brightness:
    //   brightness = R + B + 2*G
    //   000080: R=0, G=0, B=128 -> brightness = 0 + 128 + 0 = 128
    //   80FF80: R=128, G=255, B=128 -> brightness = 128 + 128 + 510 = 766
    // Darker (smaller brightness) wins: 000080 (dark blue).

    // After resolution, both cells should show dark blue (000080).
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("000080"),
        "cell (0,0) right border should be dark blue (000080) — the darker color wins"
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("000080"),
        "cell (0,1) left border should be dark blue (000080) — \
         MS-OI29500 SS2.1.169: equal weight, brightness tiebreaker: \
         000080 (brightness=128) < 80FF80 (brightness=766), darker wins"
    );
    assert_eq!(
        cell_00_right.size, cell_01_left.size,
        "both cells should agree on border size at shared edge"
    );
    assert_eq!(
        cell_00_right.style, cell_01_left.style,
        "both cells should agree on border style at shared edge"
    );
}

// =============================================================================
// 4. Color brightness tiebreaker — secondary brightness (B + 2*G)
//    MS-OI29500 §2.1.169: When primary brightness is equal, secondary
//    brightness (B + 2*G) is used. Smaller wins.
// =============================================================================

/// Verifies MS-OI29500 §2.1.169 secondary brightness tiebreaker: when
/// primary brightness (R + B + 2*G) is equal, secondary brightness (B + 2*G)
/// is used. Smaller wins.
///
/// Cell (0,0) right: single sz=8 color="FF0000"
///   (pure red: R=255, G=0, B=0, primary=255, secondary=0)
/// Cell (0,1) left:  single sz=8 color="0000FF"
///   (pure blue: R=0, G=0, B=255, primary=255, secondary=255)
///
/// Same style, size, and primary brightness (255).
/// Secondary: red (B+2G = 0+0 = 0) < blue (B+2G = 255+0 = 255).
/// Red wins.
#[test]
fn spec_color_tiebreaker_secondary_brightness() {
    let (_runtime, doc) =
        common::import_fixture(FIXTURES, "color-tiebreaker-same-style-same-weight");
    let table = first_table(&doc);

    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // Both borders have weight 8 (single * sz=8).
    // Primary brightness (R + B + 2*G):
    //   FF0000: 255 + 0 + 0 = 255
    //   0000FF: 0 + 255 + 0 = 255
    // Primary equal. Secondary brightness (B + 2*G):
    //   FF0000: 0 + 0 = 0
    //   0000FF: 255 + 0 = 255
    // Red (secondary=0) < blue (secondary=255), so red wins.

    // After resolution, both cells should show red (FF0000).
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border should be red (FF0000) — the darker secondary color wins"
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (FF0000) — \
         MS-OI29500 SS2.1.169: equal weight + equal primary brightness, \
         secondary brightness (B+2G) tiebreaker: \
         FF0000 (secondary=0) < 0000FF (secondary=255), red wins"
    );
    assert_eq!(
        cell_00_right.size, cell_01_left.size,
        "both cells should agree on border size at shared edge"
    );
    assert_eq!(
        cell_00_right.style, cell_01_left.style,
        "both cells should agree on border style at shared edge"
    );
}

// =============================================================================
// 5. Color brightness tiebreaker — darker on RIGHT cell
//    Same as #3 but with colors swapped so the darker color is on cell (0,1).
// =============================================================================

/// Verifies MS-OI29500 §2.1.169 brightness tiebreaker when the darker color
/// is on the right cell.
///
/// Cell (0,0) right: single sz=8 color="80FF80" (light green, brightness=766)
/// Cell (0,1) left:  single sz=8 color="000080" (dark blue, brightness=128)
/// Dark blue (128 < 766) should win.
#[test]
fn spec_color_tiebreaker_darker_on_right_cell() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "color-tiebreaker-darker-on-right");
    let table = first_table(&doc);

    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // Both single sz=8 → weight 8.
    // Brightness: 80FF80 = 128+128+510 = 766, 000080 = 0+128+0 = 128.
    // Darker (000080, brightness=128) should win.

    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("000080"),
        "cell (0,0) right should be dark blue (000080) — the darker color wins"
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("000080"),
        "cell (0,1) left should be dark blue (000080) — \
         MS-OI29500 SS2.1.169: brightness tiebreaker, darker wins"
    );
}

// =============================================================================
// 6. Secondary brightness tiebreaker — winning color on RIGHT cell
//    Same as #4 but with colors swapped so the winning color is on cell (0,1).
// =============================================================================

/// Verifies MS-OI29500 §2.1.169 secondary brightness tiebreaker when the
/// winning color is on the right cell.
///
/// Cell (0,0) right: single sz=8 color="0000FF" (blue, primary=255, secondary=255)
/// Cell (0,1) left:  single sz=8 color="FF0000" (red, primary=255, secondary=0)
/// Red (secondary=0 < 255) should win.
#[test]
fn spec_color_tiebreaker_secondary_reversed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "color-tiebreaker-secondary-reversed");
    let table = first_table(&doc);

    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // Both single sz=8 → weight 8. Primary brightness both 255.
    // Secondary: 0000FF → B+2G = 255+0 = 255. FF0000 → B+2G = 0+0 = 0.
    // Red (secondary=0 < 255) should win.

    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right should be red (FF0000) — the winning secondary brightness"
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left should be red (FF0000) — \
         MS-OI29500 SS2.1.169: secondary brightness (B+2G) tiebreaker, smaller wins"
    );
}
