//! Spec-compliance tests: Stories — Headers, Footers, Footnotes, Endnotes
//! (ISO 29500-1 §17.10, §17.11)
//!
//! These tests verify our implementation against specific OOXML story
//! constructs. Tests marked `#[ignore]` document known gaps.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, Mark, NoteType, OpaqueKind};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/stories";

// ── helpers ──────────────────────────────────────────────────────────────
/// Extract plain text from blocks.
fn blocks_text(blocks: &[stemma::TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Check if blocks contain a text node with the Bold mark.
fn blocks_have_bold(blocks: &[stemma::TrackedBlock]) -> bool {
    blocks.iter().any(|tb| {
        if let BlockNode::Paragraph(p) = &tb.block {
            p.all_inlines().any(|inline| {
                if let InlineNode::Text(t) = inline {
                    t.marks.contains(&Mark::Bold)
                } else {
                    false
                }
            })
        } else {
            false
        }
    })
}

/// Find a FootnoteReference opaque in body blocks, return its reference_id.
fn find_footnote_ref_in_body(doc: &CanonDoc) -> Option<String> {
    for tb in &doc.blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::OpaqueInline(oi) = inline
                    && let OpaqueKind::FootnoteReference(ref_data) = &oi.kind
                {
                    return Some(ref_data.reference_id.clone());
                }
            }
        }
    }
    None
}

/// Find an EndnoteReference opaque in body blocks, return its reference_id.
fn find_endnote_ref_in_body(doc: &CanonDoc) -> Option<String> {
    for tb in &doc.blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::OpaqueInline(oi) = inline
                    && let OpaqueKind::EndnoteReference(ref_data) = &oi.kind
                {
                    return Some(ref_data.reference_id.clone());
                }
            }
        }
    }
    None
}

// ── Header types (§17.10.5) ─────────────────────────────────────────────

/// ISO 29500-1 §17.10.5: Three header types — default, first page, even page.
/// Verify that all three HeaderStory entries are parsed with correct kinds.
#[test]
fn spec_header_types_count() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-types");
    assert_eq!(
        doc.headers.len(),
        3,
        "should have 3 headers (default, first, even)"
    );
}

/// Verify header kinds are correctly assigned from w:type attribute.
#[test]
fn spec_header_types_kinds() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-types");
    let kinds: Vec<&HeaderFooterKind> = doc.headers.iter().map(|h| &h.kind).collect();
    assert!(
        kinds.contains(&&HeaderFooterKind::Default),
        "should have Default header, got kinds: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::First),
        "should have First header, got kinds: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::Even),
        "should have Even header, got kinds: {kinds:?}"
    );
}

/// Verify each header has content matching its type.
#[test]
fn spec_header_types_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-types");

    let default_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Default)
        .expect("should have Default header");
    let text = blocks_text(&default_hdr.blocks);
    assert!(
        text.contains("Default Header"),
        "Default header text should contain 'Default Header', got: '{text}'"
    );

    let first_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::First)
        .expect("should have First header");
    let text = blocks_text(&first_hdr.blocks);
    assert!(
        text.contains("First Page Header"),
        "First header text should contain 'First Page Header', got: '{text}'"
    );

    let even_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Even)
        .expect("should have Even header");
    let text = blocks_text(&even_hdr.blocks);
    assert!(
        text.contains("Even Page Header"),
        "Even header text should contain 'Even Page Header', got: '{text}'"
    );
}

// ── Footer types (§17.10.3) ─────────────────────────────────────────────

/// ISO 29500-1 §17.10.3: Three footer types — default, first page, even page.
#[test]
fn spec_footer_types_count() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footer-types");
    assert_eq!(
        doc.footers.len(),
        3,
        "should have 3 footers (default, first, even)"
    );
}

/// Verify footer kinds are correctly assigned from w:type attribute.
#[test]
fn spec_footer_types_kinds() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footer-types");
    let kinds: Vec<&HeaderFooterKind> = doc.footers.iter().map(|f| &f.kind).collect();
    assert!(
        kinds.contains(&&HeaderFooterKind::Default),
        "should have Default footer, got kinds: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::First),
        "should have First footer, got kinds: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::Even),
        "should have Even footer, got kinds: {kinds:?}"
    );
}

/// Verify each footer has content matching its type.
#[test]
fn spec_footer_types_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footer-types");

    let default_ftr = doc
        .footers
        .iter()
        .find(|f| f.kind == HeaderFooterKind::Default)
        .expect("should have Default footer");
    let text = blocks_text(&default_ftr.blocks);
    assert!(
        text.contains("Default Footer"),
        "Default footer text should contain 'Default Footer', got: '{text}'"
    );
}

// ── Footnote references (§17.11.13) ─────────────────────────────────────

/// ISO 29500-1 §17.11.13: Body contains footnoteReference linking to
/// FootnoteStory by ID.
#[test]
fn spec_footnote_reference_in_body() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-references");
    let ref_id = find_footnote_ref_in_body(&doc);
    assert_eq!(
        ref_id.as_deref(),
        Some("1"),
        "body should contain footnoteReference with id=1"
    );
}

/// Footnote story with id=1 should exist and be Normal type.
#[test]
fn spec_footnote_reference_story_exists() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-references");
    let normal_notes: Vec<_> = doc
        .footnotes
        .iter()
        .filter(|fn_| fn_.note_type == NoteType::Normal)
        .collect();
    assert!(
        !normal_notes.is_empty(),
        "should have at least one Normal footnote"
    );
    let fn1 = normal_notes.iter().find(|fn_| fn_.id == "1");
    assert!(
        fn1.is_some(),
        "should have FootnoteStory with id=1, got ids: {:?}",
        normal_notes.iter().map(|n| &n.id).collect::<Vec<_>>()
    );
}

/// Footnote content should be parsed.
#[test]
fn spec_footnote_reference_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-references");
    let fn1 = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.id == "1")
        .expect("should have footnote id=1");
    let text = blocks_text(&fn1.blocks);
    assert!(
        text.contains("This is footnote one"),
        "footnote 1 text should contain 'This is footnote one', got: '{text}'"
    );
}

// ── Endnote references (§17.11.2) ───────────────────────────────────────

/// ISO 29500-1 §17.11.2: Body contains endnoteReference linking to
/// EndnoteStory by ID.
#[test]
fn spec_endnote_reference_in_body() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "endnote-references");
    let ref_id = find_endnote_ref_in_body(&doc);
    assert_eq!(
        ref_id.as_deref(),
        Some("1"),
        "body should contain endnoteReference with id=1"
    );
}

/// Endnote story with id=1 should exist and be Normal type.
#[test]
fn spec_endnote_reference_story_exists() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "endnote-references");
    let normal_notes: Vec<_> = doc
        .endnotes
        .iter()
        .filter(|en| en.note_type == NoteType::Normal)
        .collect();
    assert!(
        !normal_notes.is_empty(),
        "should have at least one Normal endnote"
    );
    let en1 = normal_notes.iter().find(|en| en.id == "1");
    assert!(
        en1.is_some(),
        "should have EndnoteStory with id=1, got ids: {:?}",
        normal_notes.iter().map(|n| &n.id).collect::<Vec<_>>()
    );
}

/// Endnote content should be parsed.
#[test]
fn spec_endnote_reference_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "endnote-references");
    let en1 = doc
        .endnotes
        .iter()
        .find(|en| en.id == "1")
        .expect("should have endnote id=1");
    let text = blocks_text(&en1.blocks);
    assert!(
        text.contains("This is endnote one"),
        "endnote 1 text should contain 'This is endnote one', got: '{text}'"
    );
}

// ── Footnote/endnote types (§17.11.20) ──────────────────────────────────

/// ISO 29500-1 §17.11.20: Footnote types — separator, continuationSeparator, normal.
#[test]
fn spec_footnote_types_all_present() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-types");
    assert!(
        doc.footnotes.len() >= 3,
        "should have at least 3 footnotes, got {}",
        doc.footnotes.len()
    );

    let separator = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.note_type == NoteType::Separator);
    assert!(separator.is_some(), "should have Separator footnote");

    let cont_sep = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.note_type == NoteType::ContinuationSeparator);
    assert!(
        cont_sep.is_some(),
        "should have ContinuationSeparator footnote"
    );

    let normal = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.note_type == NoteType::Normal);
    assert!(normal.is_some(), "should have Normal footnote");
}

/// Normal footnote should have content.
#[test]
fn spec_footnote_types_normal_has_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-types");
    let normal = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.note_type == NoteType::Normal)
        .expect("should have Normal footnote");
    let text = blocks_text(&normal.blocks);
    assert!(
        text.contains("Normal footnote content"),
        "Normal footnote text should contain 'Normal footnote content', got: '{text}'"
    );
}

// ── Multiple sections with headers (§17.10.5) ──────────────────────────

/// ISO 29500-1 §17.10.5: Three sections, each with a different header.
/// All three should be parsed.
#[test]
fn spec_multi_section_headers_count() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "multi-section-headers");
    assert!(
        doc.headers.len() >= 3,
        "should have at least 3 headers (one per section), got {}",
        doc.headers.len()
    );
}

/// Each header should have distinct content.
#[test]
fn spec_multi_section_headers_distinct_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "multi-section-headers");
    let texts: Vec<String> = doc.headers.iter().map(|h| blocks_text(&h.blocks)).collect();
    assert!(
        texts.iter().any(|t| t.contains("Section 1")),
        "should have header for Section 1, got: {texts:?}"
    );
    assert!(
        texts.iter().any(|t| t.contains("Section 2")),
        "should have header for Section 2, got: {texts:?}"
    );
    assert!(
        texts.iter().any(|t| t.contains("Section 3")),
        "should have header for Section 3, got: {texts:?}"
    );
}

// ── First page header with titlePg (§17.10.6) ──────────────────────────

/// ISO 29500-1 §17.10.6: With titlePg flag, first page uses 'first' type header.
#[test]
fn spec_first_page_header_count() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "first-page-header");
    assert!(
        doc.headers.len() >= 2,
        "should have at least 2 headers (default + first), got {}",
        doc.headers.len()
    );
}

/// First-page header should have kind=First.
#[test]
fn spec_first_page_header_kind() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "first-page-header");
    let first = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::First);
    assert!(first.is_some(), "should have a First-kind header");

    let first = first.unwrap();
    let text = blocks_text(&first.blocks);
    assert!(
        text.contains("Title Page Header"),
        "First header should contain 'Title Page Header', got: '{text}'"
    );
}

/// Default header should also be present.
#[test]
fn spec_first_page_header_default_also_present() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "first-page-header");
    let default_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Default);
    assert!(default_hdr.is_some(), "should have a Default-kind header");

    let default_hdr = default_hdr.unwrap();
    let text = blocks_text(&default_hdr.blocks);
    assert!(
        text.contains("Default Header"),
        "Default header should contain 'Default Header', got: '{text}'"
    );
}

// ── Footnote content formatting (§17.11) ────────────────────────────────

/// ISO 29500-1 §17.11: Footnote content preserves formatting (bold).
#[test]
fn spec_footnote_content_text() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-content");
    let fn1 = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.id == "1")
        .expect("should have footnote id=1");
    let text = blocks_text(&fn1.blocks);
    assert!(
        text.contains("Bold footnote content"),
        "footnote 1 text should contain 'Bold footnote content', got: '{text}'"
    );
}

/// Bold formatting should be preserved in footnote content.
#[test]
fn spec_footnote_content_bold_mark() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-content");
    let fn1 = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.id == "1")
        .expect("should have footnote id=1");
    assert!(
        blocks_have_bold(&fn1.blocks),
        "footnote 1 should have bold formatting"
    );
}

// ── Header/footer content (§17.10) ──────────────────────────────────────

/// ISO 29500-1 §17.10: Header paragraphs are properly parsed with formatting.
#[test]
fn spec_header_footer_content_header_blocks() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-footer-content");
    assert!(!doc.headers.is_empty(), "should have at least one header");

    let header = &doc.headers[0];
    assert!(
        header.blocks.len() >= 2,
        "header should have at least 2 block paragraphs, got {}",
        header.blocks.len()
    );

    let text = blocks_text(&header.blocks);
    assert!(
        text.contains("Bold Header Text"),
        "header should contain 'Bold Header Text', got: '{text}'"
    );
}

/// Footer should have parsed content.
#[test]
fn spec_header_footer_content_footer_blocks() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-footer-content");
    assert!(!doc.footers.is_empty(), "should have at least one footer");

    let footer = &doc.footers[0];
    let text = blocks_text(&footer.blocks);
    assert!(
        text.contains("Page Footer"),
        "footer should contain 'Page Footer', got: '{text}'"
    );
}

/// Header bold formatting should be preserved.
#[test]
fn spec_header_footer_content_bold_preserved() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "header-footer-content");
    let header = &doc.headers[0];
    assert!(
        blocks_have_bold(&header.blocks),
        "header should have bold formatting preserved"
    );
}

// ── Footnote with multiple paragraphs (§17.11) ─────────────────────────

/// ISO 29500-1 §17.11: A footnote can contain multiple paragraphs.
#[test]
fn spec_footnote_multi_paragraph_count() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-multi-paragraph");
    let fn1 = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.id == "1")
        .expect("should have footnote id=1");
    assert!(
        fn1.blocks.len() >= 3,
        "footnote 1 should have at least 3 blocks (paragraphs), got {}",
        fn1.blocks.len()
    );
}

/// All three paragraphs should have their text preserved.
#[test]
fn spec_footnote_multi_paragraph_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-multi-paragraph");
    let fn1 = doc
        .footnotes
        .iter()
        .find(|fn_| fn_.id == "1")
        .expect("should have footnote id=1");
    let text = blocks_text(&fn1.blocks);
    assert!(
        text.contains("First paragraph"),
        "should contain 'First paragraph', got: '{text}'"
    );
    assert!(
        text.contains("Second paragraph"),
        "should contain 'Second paragraph', got: '{text}'"
    );
    assert!(
        text.contains("Third paragraph"),
        "should contain 'Third paragraph', got: '{text}'"
    );
}
