//! Spec-compliance tests: Numbering Behavioral Constraints
//! (ISO 29500-1 §17.9, MS-OI29500)
//!
//! These tests verify numbering behaviors derived directly from the OOXML
//! specification that are not yet covered by existing spec_numbering* tests.
//! Focus: counter continuity across interleaved lists, forward reference
//! handling, default values, and restart cascade behavior.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/numbering-spec-audit/create_docs.py`.

use stemma::{BlockNode, CanonDoc, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/numbering-spec-audit";

// ── helpers ──────────────────────────────────────────────────────────────

/// Extract the numbering prefix from each paragraph.
fn numbering_prefixes(doc: &CanonDoc) -> Vec<Option<String>> {
    let mut prefixes = Vec::new();
    collect_prefixes_tracked(&doc.blocks, &mut prefixes);
    prefixes
}

fn collect_prefixes_tracked(blocks: &[TrackedBlock], out: &mut Vec<Option<String>>) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_prefixes_bare(blocks: &[BlockNode], out: &mut Vec<Option<String>>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn extract_prefix(p: &stemma::ParagraphNode) -> Option<String> {
    if let Some(ref num_info) = p.numbering
        && !num_info.synthesized_text.is_empty()
    {
        return Some(num_info.synthesized_text.clone());
    }
    if let Some(ref lp) = p.literal_prefix {
        return Some(lp.clone());
    }
    if let Some(ref rt) = p.rendered_text
        && let Some(idx) = rt.find('\t')
    {
        let prefix = rt[..idx].to_string();
        if !prefix.is_empty() {
            return Some(prefix);
        }
    }
    None
}

// ── 1. Interleaved lists — counter continuity (§17.9.15) ────────────────

/// ISO 29500-1 §17.9.15 (num element, which defines numId instances):
/// Cross-numId counter persistence is an implementation behavior not
/// explicitly specified by the base ECMA-376 spec.
/// (§17.9.11 is lvlText — about %N expansion within a single definition,
/// not about cross-numId counter persistence.)
///
/// When two different numId lists are interleaved, switching back to a
/// previous numId must CONTINUE its counter, not restart it. Each numId
/// is a distinct numbering instance whose counter state persists across
/// the entire document.
///
/// Sequence: numId=1(×2), numId=2(×2), numId=1(×2)
/// Expected: 1., 2., a), b), 3., 4.
///
/// Bug: NumberingState clears counters for numId=1 when switching from
/// numId=2 back to numId=1, causing a restart to "1." instead of "3.".
#[test]
fn spec_interleaved_lists_preserve_counters() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "interleaved-lists");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 6,
        "should have at least 6 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // First run of numId=1
    assert_eq!(
        numbered[0], "1.",
        "numId=1 first should be '1.', got '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "2.",
        "numId=1 second should be '2.', got '{}'",
        numbered[1]
    );

    // numId=2 interlude
    assert_eq!(
        numbered[2], "a)",
        "numId=2 first should be 'a)', got '{}'",
        numbered[2]
    );
    assert_eq!(
        numbered[3], "b)",
        "numId=2 second should be 'b)', got '{}'",
        numbered[3]
    );

    // Return to numId=1 — must CONTINUE at 3, not restart at 1.
    // Per §17.9.15: each num element (numId instance) maintains its own
    // counter state. Cross-numId counter persistence is implementation
    // behavior (not explicitly specified), but Word preserves it.
    // The counter for (numId=1, ilvl=0) was at 2; the next use should produce 3.
    assert_eq!(
        numbered[4], "3.",
        "numId=1 after interleave should CONTINUE at '3.' (counter persistence \
         across numId switches per §17.9.15), but got '{}'. The counter for \
         numId=1 was destroyed when switching to numId=2 and back.",
        numbered[4]
    );
    assert_eq!(
        numbered[5], "4.",
        "numId=1 continuation should be '4.', got '{}'",
        numbered[5]
    );
}

// ── 2. Interleaved multi-level (legal doc pattern) ──────────────────────

/// §17.9.15: Legal document pattern — numbered clauses interrupted by
/// a bullet list, then clauses continue. Cross-numId counter persistence
/// is implementation behavior, not explicitly specified (see note on
/// spec_interleaved_lists_preserve_counters).
///
/// Sequence: numId=1@0(×2), numId=1@1(×1), numId=2(bullets×2), numId=1@0(×2)
/// Expected: 1., 2., a), •, •, 3., 4.
///
/// Same bug as above: counter for numId=1 is destroyed by the numId=2
/// interruption.
#[test]
fn spec_interleaved_multi_level_legal_pattern() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "interleaved-multi-level");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 7,
        "should have at least 7 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    assert_eq!(numbered[0], "1.", "clause 1");
    assert_eq!(numbered[1], "2.", "clause 2");
    assert_eq!(numbered[2], "a)", "sub-item under clause 2");

    // Bullets (numId=2)
    assert_eq!(numbered[3], "•", "first bullet");
    assert_eq!(numbered[4], "•", "second bullet");

    // Return to numId=1 — clause numbering continues
    assert_eq!(
        numbered[5], "3.",
        "clause numbering should continue at '3.' after bullet interruption \
         per §17.9.15 (counter persistence). Got '{}'. This is a common legal \
         doc pattern: numbered clauses with interspersed bullet notes.",
        numbered[5]
    );
    assert_eq!(
        numbered[6], "4.",
        "clause 4 should follow, got '{}'",
        numbered[6]
    );
}

// ── 3. lvlText forward reference — entire text ignored (MS-OI29500) ─────

/// MS-OI29500 §17.9.11c: If lvlText at level N contains %M where
/// M > N+1 (referencing a level deeper than current), Word ignores
/// the ENTIRE lvlText and produces empty synthesized text.
///
/// Level 0 has lvlText="%1.%3" — %3 references level 2, which is
/// higher than level 0. The entire lvlText should be invalidated.
///
/// Level 1 has lvlText="%1.%2" — normal multi-level, should work.
#[test]
fn spec_lvltext_forward_ref_invalidates_entire_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "lvltext-forward-ref");

    let paras = common::all_paragraphs(&doc);

    // Find paragraphs with numbering
    let numbered_paras: Vec<_> = paras.iter().filter(|p| p.numbering.is_some()).collect();

    assert!(
        numbered_paras.len() >= 2,
        "should have at least 2 numbered paragraphs, got {}",
        numbered_paras.len()
    );

    // Level 0 paragraph: forward reference should produce empty text
    let level0_para = numbered_paras[0];
    let level0_text = &level0_para.numbering.as_ref().unwrap().synthesized_text;
    assert!(
        level0_text.is_empty(),
        "level 0 with lvlText='%1.%3' should produce empty text per \
         MS-OI29500 §17.9.11c (forward %3 reference invalidates entire lvlText). \
         Got '{level0_text}'."
    );

    // Level 1 paragraph: normal multi-level should work
    let level1_para = numbered_paras[1];
    let level1_text = &level1_para.numbering.as_ref().unwrap().synthesized_text;
    // Level 0 counter was incremented (value = 1), but produced empty text.
    // Level 1's %1.%2 should reference level 0's counter (1) and level 1's counter (1).
    // Note: since level 0 used numFmt=decimal and rendered empty due to forward ref,
    // the counter still incremented. %1 = counter(0) = 1, %2 = counter(1) = 1.
    assert_eq!(
        level1_text, "1.1",
        "level 1 with lvlText='%1.%2' should be '1.1' (normal multi-level), got '{level1_text}'"
    );
}

// ── 4. numFmt omitted defaults to decimal (§17.9.17) ────────────────────

/// ISO 29500-1 §17.9.17: "If this element is omitted, the level shall
/// be assumed to be of level type decimal."
///
/// Level 0 has no w:numFmt element. It should produce decimal numbers.
#[test]
fn spec_numfmt_omitted_defaults_to_decimal() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "numfmt-default-decimal");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "should have at least 3 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Level 0: no numFmt → decimal default
    assert_eq!(
        numbered[0], "1.",
        "level 0 with omitted numFmt should default to decimal per §17.9.17. \
         Got '{}'.",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "2.",
        "second decimal item should be '2.', got '{}'",
        numbered[1]
    );

    // Level 1: explicit lowerLetter (control)
    assert_eq!(
        numbered[2], "a)",
        "level 1 (explicit lowerLetter) should be 'a)', got '{}'",
        numbered[2]
    );
}

// ── 5. lvlRestart default cascade — 3 levels (§17.9.10) ────────────────

/// ISO 29500-1 §17.9.10: When lvlRestart is omitted, "the numbering
/// level shall restart each time the previous numbering level or any
/// earlier level is used."
///
/// 3-level list with default restart behavior:
///   1. / a) / i) / ii) / b) / i) / 2. / a) / i)
///
/// Key assertions:
///   - After "b)" at level 1, level 2 restarts to "i)" (level 1 triggers)
///   - After "2." at level 0, both level 1 and level 2 restart
#[test]
fn spec_lvl_restart_default_cascade_3_levels() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "lvl-restart-default-cascade");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 9,
        "should have at least 9 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Group 1: 1. / a) / i) / ii)
    assert_eq!(numbered[0], "1.", "level 0 first");
    assert_eq!(numbered[1], "a)", "level 1 first");
    assert_eq!(numbered[2], "i)", "level 2 first");
    assert_eq!(numbered[3], "ii)", "level 2 second");

    // Level 1 returns — level 2 should restart (default: any higher level triggers)
    assert_eq!(numbered[4], "b)", "level 1 second");
    assert_eq!(
        numbered[5], "i)",
        "level 2 should restart to 'i)' after level 1 'b)' per default \
         lvlRestart behavior (§17.9.10: restart when any earlier level used). \
         Got '{}'.",
        numbered[5]
    );

    // Level 0 returns — both level 1 and level 2 restart
    assert_eq!(numbered[6], "2.", "level 0 second");
    assert_eq!(
        numbered[7], "a)",
        "level 1 should restart to 'a)' after level 0, got '{}'",
        numbered[7]
    );
    assert_eq!(
        numbered[8], "i)",
        "level 2 should restart to 'i)' after level 0, got '{}'",
        numbered[8]
    );
}

// ── 6. numFmt=bullet uses literal lvlText (§17.9.17) ───────────────────

/// ISO 29500-1 §17.9.17: When numFmt is bullet, "the literal text of
/// the level text string is used."
///
/// %N expansion does NOT happen for bullet format. The lvlText content
/// is used as-is as the bullet character.
///
/// Level 0: lvlText="→", Level 1: lvlText="–"
#[test]
fn spec_bullet_format_uses_literal_lvl_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "bullet-literal-text");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "should have at least 3 bullet paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    assert_eq!(
        numbered[0], "→",
        "bullet level 0 should display literal '→' from lvlText, got '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "→",
        "second bullet should also be '→', got '{}'",
        numbered[1]
    );
    assert_eq!(
        numbered[2], "–",
        "bullet level 1 should display literal '–' from lvlText, got '{}'",
        numbered[2]
    );
}
