//! Spec-compliance tests: Section Properties Deep Audit (ISO 29500-1 §17.6)
//!
//! These tests probe section property features NOT covered by the existing
//! `spec_sections.rs` or `spec_section_compat_audit.rs` tests. They target
//! elements like titlePg, bidi, formProt, noEndnote, pgSz code, cols sep,
//! pgNumType chapStyle/chapSep, oddPage/evenPage types, body-level section
//! properties, and combined multi-property sections.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/sections-audit/create_docs.py`.

use stemma::{BlockNode, CanonDoc, SectionProperties, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/sections-audit";

// -- helpers ----------------------------------------------------------------
/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(blocks: &'a [BlockNode], out: &mut Vec<&'a SectionProperties>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// oddPage / evenPage section types (§17.6.22)
// ==========================================================================

/// ISO 29500-1 §17.6.22: oddPage and evenPage section break types.
///
/// The fixture has two mid-document sections: the first with type="oddPage",
/// the second with type="evenPage". These less-common break types should be
/// parsed just like nextPage and continuous.
#[test]
fn audit_odd_even_page_section_types() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "odd-even-page-sections");

    let section_props = section_paragraphs(&doc);
    assert!(
        section_props.len() >= 2,
        "should have at least 2 mid-document sections with oddPage and evenPage, got {}",
        section_props.len()
    );

    assert_eq!(
        section_props[0].section_type,
        Some(stemma::domain::SectionType::OddPage),
        "first section should have type 'oddPage', got {:?}",
        section_props[0].section_type
    );
    assert_eq!(
        section_props[1].section_type,
        Some(stemma::domain::SectionType::EvenPage),
        "second section should have type 'evenPage', got {:?}",
        section_props[1].section_type
    );
}

// ==========================================================================
// Body-level section properties (§17.6)
// ==========================================================================

/// ISO 29500-1 §17.6: The final section is defined by w:body/w:sectPr.
///
/// The fixture has custom margins (top=2160, left=1440) and vAlign="both"
/// on the body-level sectPr. These should appear in
/// CanonDoc.body_section_properties, not in paragraph section_properties.
#[test]
fn audit_body_section_properties_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "body-section-props");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should be Some — body-level w:sectPr should be parsed");

    assert_eq!(
        body_sp.margin_top,
        Some(2160),
        "body section margin_top should be 2160, got {:?}",
        body_sp.margin_top
    );
    assert_eq!(
        body_sp.margin_left,
        Some(1440),
        "body section margin_left should be 1440, got {:?}",
        body_sp.margin_left
    );
    assert_eq!(
        body_sp.v_align,
        Some(stemma::domain::SectionVAlign::Both),
        "body section vAlign should be 'both', got {:?}",
        body_sp.v_align
    );
}

// ==========================================================================
// Unequal columns in mid-document section (§17.6.4)
// ==========================================================================

/// ISO 29500-1 §17.6.4: equalWidth=false with individual w:col definitions.
///
/// The fixture has 3 columns: 2400+480, 4800+480, 2400+0. The column_defs
/// vec should have exactly 3 entries with the correct widths and spacing.
#[test]
fn audit_unequal_columns_mid_document() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "unequal-columns");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with column definitions"
    );

    let props = section_props[0];
    assert_eq!(
        props.columns,
        Some(3),
        "should parse num=3 from w:cols, got {:?}",
        props.columns
    );

    assert_eq!(
        props.column_defs.len(),
        3,
        "should have 3 column definitions, got {}",
        props.column_defs.len()
    );

    assert_eq!(
        props.column_defs[0].width, 2400,
        "column 0 width should be 2400"
    );
    assert_eq!(
        props.column_defs[0].space, 480,
        "column 0 space should be 480"
    );
    assert_eq!(
        props.column_defs[1].width, 4800,
        "column 1 width should be 4800"
    );
    assert_eq!(
        props.column_defs[1].space, 480,
        "column 1 space should be 480"
    );
    assert_eq!(
        props.column_defs[2].width, 2400,
        "column 2 width should be 2400"
    );
    assert_eq!(
        props.column_defs[2].space, 0,
        "column 2 space should default to 0"
    );
}

// ==========================================================================
// Combined section properties (§17.6 integration)
// ==========================================================================

/// ISO 29500-1 §17.6: Multiple section properties combined in one sectPr.
///
/// The fixture has: landscape A4 (16838x11906), margins, continuous type,
/// 2 columns, vAlign=center, pgNumType=upperLetter start=1, docGrid linePitch=360.
/// All properties should coexist without interference.
#[test]
fn audit_combined_section_properties() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "combined-section-props");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section"
    );

    let props = section_props[0];

    // Page size: landscape A4
    assert_eq!(
        props.page_width,
        Some(16838),
        "page width should be 16838 (A4 landscape), got {:?}",
        props.page_width
    );
    assert_eq!(
        props.page_height,
        Some(11906),
        "page height should be 11906 (A4 landscape), got {:?}",
        props.page_height
    );
    assert_eq!(
        props.orientation,
        Some(stemma::PageOrientation::Landscape),
        "orientation should be Landscape, got {:?}",
        props.orientation
    );

    // Margins
    assert_eq!(props.margin_top, Some(1440), "margin_top should be 1440");
    assert_eq!(props.margin_left, Some(1800), "margin_left should be 1800");

    // Section type
    assert_eq!(
        props.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "section type should be 'continuous', got {:?}",
        props.section_type
    );

    // Columns
    assert_eq!(props.columns, Some(2), "should have 2 columns");
    assert_eq!(props.column_space, Some(720), "column space should be 720");

    // Vertical alignment
    assert_eq!(
        props.v_align,
        Some(stemma::domain::SectionVAlign::Center),
        "vAlign should be 'center', got {:?}",
        props.v_align
    );

    // Page number type
    let pg = props
        .page_number_type
        .as_ref()
        .expect("should have page number type");
    assert_eq!(
        pg.fmt.as_deref(),
        Some("upperLetter"),
        "pgNumType fmt should be 'upperLetter'"
    );
    assert_eq!(pg.start, Some(1), "pgNumType start should be 1");

    // Document grid
    assert_eq!(
        props.doc_grid_line_pitch,
        Some(360),
        "docGrid linePitch should be 360, got {:?}",
        props.doc_grid_line_pitch
    );
}

// ==========================================================================
// Section boolean flags and extended attributes
// ==========================================================================

// -- titlePg (§17.6.18) ---------------------------------------------------

/// ISO 29500-1 §17.6.18: w:titlePg enables distinct first-page header/footer.
///
/// The fixture has a sectPr with w:titlePg element. This boolean flag should
/// be accessible in SectionProperties so the renderer knows to use different
/// headers/footers for the first page of the section.
#[test]
fn audit_title_page_flag() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "title-page");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with titlePg"
    );

    let props = section_props[0];
    assert_eq!(
        props.title_page,
        Some(true),
        "titlePg should be parsed as Some(true)"
    );
}

// -- bidi (§17.6.1) -------------------------------------------------------

/// ISO 29500-1 §17.6.1: w:bidi makes the section right-to-left.
///
/// The fixture has a sectPr with w:bidi element. This boolean flag controls
/// the layout direction of the section (RTL vs LTR).
#[test]
fn audit_bidi_section_flag() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "bidi-section");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with bidi"
    );

    let props = section_props[0];
    assert_eq!(
        props.bidi,
        Some(true),
        "bidi should be parsed as Some(true)"
    );
}

// -- formProt (§17.6.6) ---------------------------------------------------

/// ISO 29500-1 §17.6.6: w:formProt enables section-level form protection.
///
/// When present, only form fields can be edited in this section.
#[test]
fn audit_form_protection_flag() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "form-prot");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with formProt"
    );

    let props = section_props[0];
    assert_eq!(
        props.form_prot,
        Some(true),
        "formProt should be parsed as Some(true)"
    );
}

// -- noEndnote (§17.6.9) --------------------------------------------------

/// ISO 29500-1 §17.6.9: w:noEndnote suppresses endnotes in this section.
#[test]
fn audit_no_endnote_flag() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "no-endnote");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with noEndnote"
    );

    let props = section_props[0];
    assert_eq!(
        props.no_endnote,
        Some(true),
        "noEndnote should be parsed as Some(true)"
    );
}

// -- pgSz w:code (§17.6.14) -----------------------------------------------

/// ISO 29500-1 §17.6.14: pgSz code attribute specifies standard paper size.
///
/// The fixture has pgSz with code=9 (A4). The code attribute supplements
/// the explicit w/h dimensions and identifies the standard paper size.
#[test]
fn audit_paper_size_code() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "paper-size-code");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with pgSz code"
    );

    let props = section_props[0];

    // Width/height should be parsed (already works)
    assert_eq!(
        props.page_width,
        Some(11906),
        "page width should be 11906 (A4), got {:?}",
        props.page_width
    );
    assert_eq!(
        props.page_height,
        Some(16838),
        "page height should be 16838 (A4), got {:?}",
        props.page_height
    );

    assert_eq!(
        props.paper_size_code,
        Some(9),
        "paper_size_code should be Some(9) for A4, got {:?}",
        props.paper_size_code
    );
}

// -- cols w:sep (§17.6.4) -------------------------------------------------

/// ISO 29500-1 §17.6.4: cols sep attribute draws a vertical separator line.
///
/// The fixture has cols with sep=1 and num=2. The sep flag should be
/// accessible in SectionProperties for rendering.
#[test]
fn audit_column_separator_flag() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "column-separator");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with column separator"
    );

    let props = section_props[0];
    assert_eq!(props.columns, Some(2), "should have 2 columns");

    assert_eq!(
        props.column_separator,
        Some(true),
        "column_separator should be Some(true), got {:?}",
        props.column_separator
    );
}

// -- pgNumType chapStyle/chapSep (§17.6.12) --------------------------------

/// ISO 29500-1 §17.6.12: pgNumType chapStyle and chapSep attributes for
/// chapter-relative page numbering (e.g., "2-3" for page 3 of chapter 2).
///
/// The fixture has pgNumType with fmt=decimal, start=1, chapStyle=1,
/// chapSep=hyphen.
#[test]
fn audit_chapter_page_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "chapter-page-numbering");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section with chapter page numbering"
    );

    let props = section_props[0];
    let pg = props
        .page_number_type
        .as_ref()
        .expect("should have page number type");

    // fmt and start should work (already implemented)
    assert_eq!(
        pg.fmt.as_deref(),
        Some("decimal"),
        "pgNumType fmt should be 'decimal'"
    );
    assert_eq!(pg.start, Some(1), "pgNumType start should be 1");

    assert_eq!(pg.chap_style, Some(1), "chapStyle should be Some(1)");
    assert_eq!(
        pg.chap_sep.as_deref(),
        Some("hyphen"),
        "chapSep should be Some(\"hyphen\"), got {:?}",
        pg.chap_sep
    );
}
