//! Spec-compliance edge cases: Table Structure & Borders
//!
//! These tests target behavioral edge cases in OOXML table handling where
//! parsers commonly misinterpret the spec.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, DocxRuntime, InlineNode, TableNode};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/edge-cases";

// ── helpers ──────────────────────────────────────────────────────────────
fn first_table(doc: &CanonDoc) -> &TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .expect("document should contain at least one table")
}

/// Collect all tables from the document body in order.
fn all_tables(doc: &CanonDoc) -> Vec<&TableNode> {
    doc.blocks
        .iter()
        .filter_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .collect()
}

fn cell_text(table: &TableNode, row: usize, col: usize) -> String {
    let cell = &table.rows[row].cells[col];
    let mut text = String::new();
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            let inlines = p.all_inlines_owned();
            for inline in &inlines {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

// ── EC-14: Table border conflict resolution ─────────────────────────────

/// ISO 29500-1 §17.4.38: Cell-level borders override table-level borders.
///
/// Fixture has thick red (sz=24) table-level borders on all edges.
/// Cell (0,0) overrides with thin blue (sz=4) cell-level borders.
#[test]
fn ec14_border_conflict_parses_without_error() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-conflict");
    let table = first_table(&doc);
    assert_eq!(table.rows.len(), 2, "should have 2 rows");
    assert_eq!(table.rows[0].cells.len(), 2, "should have 2 cells per row");
}

/// Table-level borders should be present on the table formatting.
#[test]
fn ec14_table_level_borders_are_present() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-conflict");
    let table = first_table(&doc);

    let borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have table-level borders");

    // All table-level borders should be red/sz=24
    for (name, edge) in [
        ("top", &borders.top),
        ("bottom", &borders.bottom),
        ("left", &borders.left),
        ("right", &borders.right),
        ("insideH", &borders.inside_h),
        ("insideV", &borders.inside_v),
    ] {
        let border = edge
            .as_ref()
            .unwrap_or_else(|| panic!("table border edge '{name}' should be present"));
        assert_eq!(
            border.style,
            stemma::domain::BorderStyle::Single,
            "table {name} border style"
        );
        assert_eq!(
            border.size,
            Some(24),
            "table {name} border size should be 24 (3pt)"
        );
        assert_eq!(
            border.color.as_deref(),
            Some("FF0000"),
            "table {name} border color should be red"
        );
    }
}

/// MS-OI29500 §2.1.169: Cell border vs table border weight resolution.
///
/// Cell (0,0) has explicit tcBorders (blue/sz=4, weight=4). Table has
/// direct tblBorders (red/sz=24, weight=24). Per MS implementation,
/// weight-based resolution applies to all edges (including table edges).
/// The heavier table border (weight=24) wins over the lighter cell border
/// (weight=4) on every edge.
#[test]
fn ec14_cell_borders_override_table_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-conflict");
    let table = first_table(&doc);

    let cell_00 = &table.rows[0].cells[0];
    let cell_borders = cell_00
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders after conflict resolution");

    // MS-OI29500 §2.1.169: table border (red/24, weight=24) wins over cell
    // border (blue/4, weight=4) on ALL edges (weight-based resolution).
    for (name, edge) in [
        ("top", &cell_borders.top),
        ("bottom", &cell_borders.bottom),
        ("left", &cell_borders.left),
        ("right", &cell_borders.right),
    ] {
        let border = edge
            .as_ref()
            .unwrap_or_else(|| panic!("cell border edge '{name}' should be present"));
        assert_eq!(
            border.style,
            stemma::domain::BorderStyle::Single,
            "cell {name} border style"
        );
        assert_eq!(
            border.size,
            Some(24),
            "cell {name} border should be sz=24 — table red (weight=24) beats cell blue (weight=4)"
        );
        assert_eq!(
            border.color.as_deref(),
            Some("FF0000"),
            "cell {name} border should be red (table wins by weight)"
        );
    }
}

/// Cell (0,1) has no explicit tcBorders in XML, but after table-level border
/// cascade and adjacent cell conflict resolution (§17.4.66 rule 3), it gets
/// borders: table fallback on non-shared edges, and the winner from cell (0,0)
/// on the shared left edge.
#[test]
fn ec14_cell_without_tcborders_gets_cascade_and_conflict_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-conflict");
    let table = first_table(&doc);

    let cell_01 = &table.rows[0].cells[1];
    // After cascade + conflict resolution, cell (0,1) should have borders.
    let borders = cell_01
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,1) should have borders after table cascade + conflict resolution");
    // Cell (0,1) gets table-level red/sz=24 borders from cascade.
    // At the shared left edge: cell (0,0) has blue/sz=4 (weight=4),
    // cell (0,1) has red/sz=24 (weight=24) from table cascade.
    // Red wins because 24 > 4.
    let left = borders
        .left
        .as_ref()
        .expect("cell (0,1) left border should exist from table cascade");
    assert_eq!(
        left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (table-level sz=24 beats cell (0,0) blue sz=4)"
    );
}

// ── EC-16: gridSpan="1" vs absent gridSpan ──────────────────────────────

/// ISO 29500-1 §17.4.17: explicit gridSpan="1" is equivalent to absent gridSpan.
#[test]
fn ec16_gridspan_explicit_vs_absent_parses() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-explicit-vs-absent");
    let tables = all_tables(&doc);
    assert!(
        tables.len() >= 2,
        "should have at least 2 tables, got {}",
        tables.len()
    );
}

/// Both tables should produce grid_span=1 on every cell.
#[test]
fn ec16_both_tables_have_gridspan_1() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-explicit-vs-absent");
    let tables = all_tables(&doc);

    let tbl_no_gridspan = tables[0];
    let tbl_explicit_gridspan = tables[1];

    // Table 1 (no gridSpan): every cell should have grid_span=1
    for (r, row) in tbl_no_gridspan.rows.iter().enumerate() {
        for (c, cell) in row.cells.iter().enumerate() {
            assert_eq!(
                cell.grid_span, 1,
                "table 1 cell ({r},{c}) grid_span should be 1 (default)"
            );
        }
    }

    // Table 2 (explicit gridSpan="1"): every cell should also have grid_span=1
    for (r, row) in tbl_explicit_gridspan.rows.iter().enumerate() {
        for (c, cell) in row.cells.iter().enumerate() {
            assert_eq!(
                cell.grid_span, 1,
                "table 2 cell ({r},{c}) grid_span should be 1 (explicit)"
            );
        }
    }
}

/// Both tables should have identical structure (same row/cell counts).
#[test]
fn ec16_both_tables_have_identical_structure() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-explicit-vs-absent");
    let tables = all_tables(&doc);

    let tbl1 = tables[0];
    let tbl2 = tables[1];

    assert_eq!(
        tbl1.rows.len(),
        tbl2.rows.len(),
        "both tables should have the same number of rows"
    );

    for (r, (row1, row2)) in tbl1.rows.iter().zip(tbl2.rows.iter()).enumerate() {
        assert_eq!(
            row1.cells.len(),
            row2.cells.len(),
            "row {r}: both tables should have the same number of cells"
        );
    }
}

// ── EC-17: Empty table cells are rejected ───────────────────────────────

/// ISO 29500-1 §17.4.73 CT_Tc requires `(p|tbl)+` — a cell with zero
/// block-level children is invalid OOXML and must be rejected at import.
#[test]
fn ec17_empty_cell_rejected_on_import() {
    let path = format!("{FIXTURES}/empty-table-cells/input.docx");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let runtime = stemma::SimpleRuntime::new();
    let err = runtime
        .import_docx(&bytes)
        .expect_err("import should reject a cell with no block elements");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("must contain at least one block element"),
        "error should cite the CT_Tc content-model violation, got: {msg}"
    );
}

// ── EC-18: Table width types ────────────────────────────────────────────

/// ISO 29500-1 §17.4.61: Table width with different type values.
#[test]
fn ec18_table_width_types_parse_without_error() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    assert_eq!(
        tables.len(),
        4,
        "should have 4 tables (pct, auto, dxa, nil)"
    );
}

/// Table 1: pct width (5000 = 50%).
#[test]
fn ec18_pct_width() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    let width = tables[0]
        .formatting
        .width
        .as_ref()
        .expect("pct table should have width");
    assert_eq!(
        width.width_type,
        stemma::domain::WidthType::Pct,
        "width type should be 'pct'"
    );
    assert_eq!(width.w, 5000, "pct width should be 5000 (50%)");
}

/// Table 2: auto width.
#[test]
fn ec18_auto_width() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    let width = tables[1]
        .formatting
        .width
        .as_ref()
        .expect("auto table should have width");
    assert_eq!(
        width.width_type,
        stemma::domain::WidthType::Auto,
        "width type should be 'auto'"
    );
    assert_eq!(width.w, 0, "auto width value should be 0");
}

/// Table 3: dxa width (9360 twips = 6.5 inches).
#[test]
fn ec18_dxa_width() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    let width = tables[2]
        .formatting
        .width
        .as_ref()
        .expect("dxa table should have width");
    assert_eq!(
        width.width_type,
        stemma::domain::WidthType::Dxa,
        "width type should be 'dxa'"
    );
    assert_eq!(width.w, 9360, "dxa width should be 9360 twips");
}

/// Table 4: nil width (no width specified).
#[test]
fn ec18_nil_width() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    let width = tables[3]
        .formatting
        .width
        .as_ref()
        .expect("nil table should have width measurement");
    assert_eq!(
        width.width_type,
        stemma::domain::WidthType::Nil,
        "width type should be 'nil'"
    );
    assert_eq!(width.w, 0, "nil width value should be 0");
}

// ── EC-19: Row with gridBefore/gridAfter ────────────────────────────────

/// ISO 29500-1 §17.4.14: gridBefore offsets cells in the grid.
#[test]
fn ec19_grid_before_parses_without_error() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "grid-before-edge");
    let table = first_table(&doc);
    assert_eq!(table.rows.len(), 2, "should have 2 rows");
}

/// Row 0 should have 3 cells and no grid offset.
#[test]
fn ec19_row0_has_3_cells_no_offset() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "grid-before-edge");
    let table = first_table(&doc);

    assert_eq!(table.rows[0].cells.len(), 3, "row 0 should have 3 cells");
    assert_eq!(
        table.rows[0].grid_before, 0,
        "row 0 should have grid_before=0"
    );
}

/// Row 1 should have 2 cells with gridBefore=1.
#[test]
fn ec19_row1_has_grid_before() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "grid-before-edge");
    let table = first_table(&doc);

    assert_eq!(table.rows[1].cells.len(), 2, "row 1 should have 2 cells");
    assert_eq!(
        table.rows[1].grid_before, 1,
        "row 1 should have grid_before=1"
    );
}

/// Row 1 cell content should reflect the offset positioning.
#[test]
fn ec19_row1_cell_content() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "grid-before-edge");
    let table = first_table(&doc);

    let first_cell = cell_text(table, 1, 0);
    assert!(
        first_cell.contains("Y2"),
        "row 1 first cell should contain 'Y2' (offset by gridBefore=1), got: '{first_cell}'"
    );

    let second_cell = cell_text(table, 1, 1);
    assert!(
        second_cell.contains("Z2"),
        "row 1 second cell should contain 'Z2', got: '{second_cell}'"
    );
}

// ── EC-20: Nested tables ────────────────────────────────────────────────

/// ISO 29500-1 §17.4.38: A table cell can contain another table.
#[test]
fn ec20_nested_table_parses_without_error() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let table = first_table(&doc);
    assert_eq!(table.rows.len(), 2, "outer table should have 2 rows");
    assert_eq!(
        table.rows[0].cells.len(),
        2,
        "outer table should have 2 cells per row"
    );
}

/// Cell (0,0) of the outer table should contain a nested table in its blocks.
#[test]
fn ec20_nested_table_in_cell_blocks() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let outer = first_table(&doc);

    let cell_00 = &outer.rows[0].cells[0];

    // Find the nested table in cell blocks
    let nested_tables: Vec<&TableNode> = cell_00
        .blocks
        .iter()
        .filter_map(|b| match b {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .collect();

    assert_eq!(
        nested_tables.len(),
        1,
        "cell (0,0) should contain exactly 1 nested table, got {}",
        nested_tables.len()
    );
}

/// The nested table should have the correct structure (2 rows x 1 col).
#[test]
fn ec20_nested_table_structure() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let outer = first_table(&doc);

    let cell_00 = &outer.rows[0].cells[0];
    let nested = cell_00
        .blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .expect("cell (0,0) should contain a nested table");

    assert_eq!(nested.rows.len(), 2, "nested table should have 2 rows");
    assert_eq!(
        nested.rows[0].cells.len(),
        1,
        "nested table should have 1 cell per row"
    );
}

/// The nested table cells should contain the correct text.
#[test]
fn ec20_nested_table_content() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let outer = first_table(&doc);

    let cell_00 = &outer.rows[0].cells[0];
    let nested = cell_00
        .blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .expect("cell (0,0) should contain a nested table");

    // Read text from nested table cells
    let nested_r0_text = cell_text(nested, 0, 0);
    assert!(
        nested_r0_text.contains("Nested R1"),
        "nested table row 0 should contain 'Nested R1', got: '{nested_r0_text}'"
    );

    let nested_r1_text = cell_text(nested, 1, 0);
    assert!(
        nested_r1_text.contains("Nested R2"),
        "nested table row 1 should contain 'Nested R2', got: '{nested_r1_text}'"
    );
}

/// Cell (0,0) should also contain paragraphs alongside the nested table.
#[test]
fn ec20_cell_has_paragraphs_around_nested_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let outer = first_table(&doc);

    let cell_00 = &outer.rows[0].cells[0];

    let paragraph_count = cell_00
        .blocks
        .iter()
        .filter(|b| matches!(b, BlockNode::Paragraph(_)))
        .count();

    // Should have at least the "Before nested" paragraph and the trailing empty one
    assert!(
        paragraph_count >= 1,
        "cell (0,0) should have at least 1 paragraph alongside the nested table, got {paragraph_count}"
    );

    // The "Before nested" paragraph text
    let first_para_text: String = cell_00
        .blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Paragraph(p) => {
                let inlines = p.all_inlines_owned();
                let text: String = inlines
                    .iter()
                    .filter_map(|i| match i {
                        InlineNode::Text(t) => Some(t.text.as_str()),
                        _ => None,
                    })
                    .collect();
                if !text.is_empty() { Some(text) } else { None }
            }
            _ => None,
        })
        .unwrap_or_default();

    assert!(
        first_para_text.contains("Before nested"),
        "first paragraph in cell (0,0) should contain 'Before nested', got: '{first_para_text}'"
    );
}

// ── EC-21: Empty table (zero rows) is accepted and preserved ────────────

// An earlier revision of this test asserted REJECTION, reading the §17.4.37
// prose ("an arbitrary non-zero number of rows") as normative over the
// schema. That expectation was wrong: the transitional XSD's CT_Tbl puts the
// row group (EG_ContentRowContent) at minOccurs="0", so tblPr + tblGrid with
// zero w:tr children is schema-valid; wild Word-authored documents contain
// such tables and Word opens them without repair. The schema and Word agree
// — a conforming consumer must accept and preserve the table, not refuse
// the document.

/// Import a document containing a zero-row table (tblPr + tblGrid only):
/// the import succeeds and the canonical model carries the table as a
/// TableNode with empty rows, its width and grid intact.
#[test]
fn ec21_empty_table_zero_rows_imports() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "empty-table-zero-rows");
    let table = first_table(&doc);
    assert!(
        table.rows.is_empty(),
        "the zero-row table must import with empty rows, got {} rows",
        table.rows.len()
    );
    assert_eq!(
        table.formatting.grid_cols,
        vec![4680, 4680],
        "tblGrid must be preserved on the empty table"
    );
    let width = table
        .formatting
        .width
        .as_ref()
        .expect("tblW must be preserved on the empty table");
    assert_eq!(width.w, 5000);
    assert_eq!(width.width_type, stemma::WidthType::Pct);
    // The surrounding paragraphs are intact.
    let texts: Vec<String> = common::all_paragraphs(&doc)
        .iter()
        .map(|p| paragraph_text(p))
        .collect();
    assert!(texts.iter().any(|t| t.contains("Before the empty table")));
    assert!(texts.iter().any(|t| t.contains("After the empty table")));
}

/// Roundtrip: import → export → reimport. The empty table (tblPr + tblGrid,
/// zero rows) and the surrounding text survive both directions.
#[test]
fn ec21_empty_table_zero_rows_roundtrips() {
    use stemma::api::Document;
    let path = format!("{FIXTURES}/empty-table-zero-rows/input.docx");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));

    let doc = Document::parse(&bytes).expect("parse doc with zero-row table");
    let exported = doc
        .serialize(&stemma::ExportOptions::default())
        .expect("serialize doc with zero-row table");

    // The re-emitted document must still parse (Word-openable output is
    // gated elsewhere; reparse is the in-repo proxy) and still contain the
    // empty table with its grid and the surrounding text.
    let (_runtime2, doc2) = {
        let runtime = stemma::SimpleRuntime::new();
        let import = runtime.import_docx(&exported).expect("reimport export");
        let view = runtime.view(&import.doc_handle).expect("view");
        let canon = std::sync::Arc::unwrap_or_clone(view.canonical);
        (runtime, canon)
    };
    let table = first_table(&doc2);
    assert!(
        table.rows.is_empty(),
        "empty table must survive the roundtrip with zero rows"
    );
    assert_eq!(
        table.formatting.grid_cols,
        vec![4680, 4680],
        "tblGrid must survive the roundtrip"
    );
    let texts: Vec<String> = common::all_paragraphs(&doc2)
        .iter()
        .map(|p| paragraph_text(p))
        .collect();
    assert!(texts.iter().any(|t| t.contains("Before the empty table")));
    assert!(texts.iter().any(|t| t.contains("After the empty table")));
}

/// Redline path: edit a DIFFERENT paragraph via diff_and_redline and export.
/// The untouched empty table must survive the tracked-changes export and the
/// reparse of its output.
#[test]
fn ec21_empty_table_zero_rows_survives_redline() {
    use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
    let path = format!("{FIXTURES}/empty-table-zero-rows/input.docx");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let edited_bytes = rezip_with_patched_document_xml(
        &bytes,
        "After the empty table.",
        "After the empty table, now edited.",
    );

    let runtime = SimpleRuntime::new();
    let base = runtime.import_docx(&bytes).expect("import base");
    let edited = runtime.import_docx(&edited_bytes).expect("import edited");
    let meta = TransactionMeta {
        author: "spec_edge_tables".to_string(),
        reason: Some("zero-row table redline survival".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&base.doc_handle, &edited.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");
    let redline = runtime
        .export_docx(&base.doc_handle, ExportMode::Redline)
        .expect("export redline");

    // Reparse the redline output: the empty table is still there, untouched,
    // and the paragraph edit is present.
    let runtime2 = SimpleRuntime::new();
    let import2 = runtime2.import_docx(&redline).expect("reimport redline");
    let view = runtime2.view(&import2.doc_handle).expect("view");
    let doc2 = std::sync::Arc::unwrap_or_clone(view.canonical);
    let table = first_table(&doc2);
    assert!(
        table.rows.is_empty(),
        "empty table must survive the redline export with zero rows"
    );
    assert_eq!(
        table.formatting.grid_cols,
        vec![4680, 4680],
        "tblGrid must survive the redline export"
    );
    let texts: Vec<String> = common::all_paragraphs(&doc2)
        .iter()
        .map(|p| paragraph_text(p))
        .collect();
    assert!(
        texts.iter().any(|t| t.contains("now edited")),
        "the paragraph edit must be present in the redline output, got: {texts:?}"
    );
}

/// Extract text from a paragraph node (test-local convenience).
fn paragraph_text(p: &stemma::ParagraphNode) -> String {
    p.all_inlines_owned()
        .iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(t.text.clone()),
            _ => None,
        })
        .collect()
}

/// Rebuild a DOCX byte-for-byte, replacing `from` with `to` inside
/// word/document.xml (test-local; used to author the "edited elsewhere"
/// counterpart of a fixture).
fn rezip_with_patched_document_xml(docx: &[u8], from: &str, to: &str) -> Vec<u8> {
    use std::io::{Cursor, Read, Write};
    let mut zip = zip::ZipArchive::new(Cursor::new(docx)).expect("open fixture zip");
    let mut out = Vec::new();
    {
        let mut writer = zip::ZipWriter::new(Cursor::new(&mut out));
        for i in 0..zip.len() {
            let mut entry = zip.by_index(i).expect("zip entry");
            let name = entry.name().to_string();
            let mut contents = Vec::new();
            entry.read_to_end(&mut contents).expect("read zip entry");
            if name == "word/document.xml" {
                let xml = String::from_utf8(contents).expect("document.xml utf8");
                assert!(
                    xml.contains(from),
                    "patch target '{from}' not found in fixture document.xml"
                );
                contents = xml.replace(from, to).into_bytes();
            }
            writer
                .start_file(name, zip::write::FileOptions::default())
                .expect("start zip entry");
            writer.write_all(&contents).expect("write zip entry");
        }
        writer.finish().expect("finish zip");
    }
    out
}

/// Outer table's other cells should have their expected content.
#[test]
fn ec20_outer_table_other_cells() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table");
    let outer = first_table(&doc);

    let b1 = cell_text(outer, 0, 1);
    assert!(
        b1.contains("Outer B1"),
        "outer cell (0,1) should contain 'Outer B1', got: '{b1}'"
    );

    let a2 = cell_text(outer, 1, 0);
    assert!(
        a2.contains("Outer A2"),
        "outer cell (1,0) should contain 'Outer A2', got: '{a2}'"
    );

    let b2 = cell_text(outer, 1, 1);
    assert!(
        b2.contains("Outer B2"),
        "outer cell (1,1) should contain 'Outer B2', got: '{b2}'"
    );
}
