//! Spec-compliance tests: Run Property Resolution (ISO 29500-1 §17.3.2, §17.7.3, §17.8)
//!
//! These tests audit edge cases in run property resolution through the style
//! hierarchy: theme font references, toggle RESET in deep basedOn chains,
//! default character styles, linked styles, font slot cascade, and paragraph
//! mark formatting.
//!
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{InlineNode, Mark};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/run-resolution";

// -- helpers ----------------------------------------------------------------
fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}
// -- Theme font references ----------------------------------------

/// ISO 29500-1 §17.3.2.26: When rFonts specifies only asciiTheme/hAnsiTheme
/// (no explicit w:ascii/w:hAnsi), the font family should be resolved from the
/// document's theme (theme1.xml majorFont/minorFont definitions).
///
/// parse_rpr_marks only reads w:ascii/w:hAnsi attributes. The
/// asciiTheme/hAnsiTheme attributes are silently ignored, so a run with
/// theme-only font references will have font_family=None.
#[test]
fn spec_theme_font_reference_resolves_font_family() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "theme-font-references");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run_a = nodes
        .iter()
        .find(|n| n.text.contains("Theme-only"))
        .expect("should find theme-only run");

    // With theme resolution, this should be the majorHAnsi font from the
    // theme (typically "Calibri Light" in default python-docx themes).
    assert!(
        run_a.style_props.font_family.is_some(),
        "theme-only rFonts (asciiTheme=majorHAnsi) should resolve to a font name. \
         Got font_family=None. The asciiTheme/hAnsiTheme attributes need to be read \
         and resolved against theme1.xml."
    );
}

/// ISO 29500-1 §17.3.2.26: When rFonts has both explicit ascii/hAnsi AND
/// asciiTheme/hAnsiTheme, the explicit value takes precedence.
///
/// POSITIVE: Even without theme resolution, explicit fonts are read correctly.
#[test]
fn spec_explicit_font_wins_over_theme() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "theme-font-references");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run_b = nodes
        .iter()
        .find(|n| n.text.contains("Explicit plus"))
        .expect("should find explicit+theme run");

    assert_eq!(
        run_b.style_props.font_family.as_deref(),
        Some("Courier New"),
        "explicit w:ascii should be used when both explicit and theme are present"
    );
}

// -- Toggle RESET in multi-level basedOn chain --------------------

/// MS-OI29500 §2.1.258: Toggle properties use RESET (simple override)
/// semantics across hierarchy levels, not XOR. Character style overrides
/// paragraph style.
///
/// CharA3 sets bold=on. Para sets bold=on. RESET: char wins → bold=on.
#[test]
fn spec_toggle_reset_3level_run1_char_a() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "toggle-xor-3level-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("CharA3"))
        .expect("should find test paragraph");

    let nodes = text_nodes(p);
    let run1 = nodes
        .iter()
        .find(|n| n.text.contains("CharA3"))
        .expect("should find run 1");

    // CharA3 bold=on overrides para bold=on → bold=on (RESET semantics)
    assert!(
        run1.marks.contains(&Mark::Bold),
        "CharA3 (bold=on) should override para (bold=on) via RESET → bold=on (MS-OI29500 §2.1.258)"
    );
}

/// CharB3 basedOn CharA3, own bold=on. Para bold=on. RESET: char wins → bold=on.
#[test]
fn spec_toggle_reset_3level_run2_char_b() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "toggle-xor-3level-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("CharB3"))
        .expect("should find test paragraph");

    let nodes = text_nodes(p);
    let run2 = nodes
        .iter()
        .find(|n| n.text.contains("CharB3"))
        .expect("should find run 2");

    // CharB3 resolved bold=on (from B, first in chain). Overrides para bold=on → bold=on.
    assert!(
        run2.marks.contains(&Mark::Bold),
        "CharB3 (bold=on via basedOn chain) should override para (bold=on) via RESET → bold=on (MS-OI29500 §2.1.258)"
    );
}

/// CharC3 basedOn CharB3, does NOT set bold. Walk chain: C→B (bold=on).
/// Char level = on. RESET: char wins → bold=on.
#[test]
fn spec_toggle_reset_3level_run3_char_c_inherited() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "toggle-xor-3level-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("CharC3"))
        .expect("should find test paragraph");

    let nodes = text_nodes(p);
    let run3 = nodes
        .iter()
        .find(|n| n.text.contains("CharC3"))
        .expect("should find run 3");

    // CharC3 inherits bold=on from B. Overrides para bold=on → bold=on.
    assert!(
        run3.marks.contains(&Mark::Bold),
        "CharC3 (inherited bold=on from B) should override para (bold=on) via RESET → bold=on (MS-OI29500 §2.1.258)"
    );
}

/// Run with no char style, para bold=on. No XOR partner, so bold=on.
#[test]
fn spec_toggle_xor_3level_run4_no_char_style() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "toggle-xor-3level-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("No char style"))
        .expect("should find no-char-style paragraph");

    let nodes = text_nodes(p);
    let run4 = nodes
        .iter()
        .find(|n| n.text.contains("No char style"))
        .expect("should find run 4");

    assert!(
        run4.marks.contains(&Mark::Bold),
        "no char style + para bold=on should produce bold=on"
    );
}

// -- Default character style --------------------------------------

/// ISO 29500-1 §17.7.4.17: A character style with w:default="1" should apply
/// to all runs that have no explicit rStyle, providing a baseline for the
/// character formatting cascade.
///
/// StyleDefinitions has no default_char_style_id field. The resolve()
/// method receives None for char_style_id when a run has no rStyle, so the
/// default character style's properties are never consulted.
///
/// NOTE: Per MS-OI29500 §17.7.4.17(a), Word ignores
/// children of styles with IDs "DefaultParagraphFont", "NoList", and
/// "TableNormal". Since this fixture's default char style uses ID
/// "DefaultParagraphFont", its children (including color=0000FF) are
/// correctly ignored per MS behavior.
#[test]
fn spec_default_char_style_applies_to_unstyled_run() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "default-char-style");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run1 = nodes
        .iter()
        .find(|n| n.text.contains("No rStyle"))
        .expect("should find unstyled run");

    // Per MS behavior, DefaultParagraphFont's children are
    // ignored, so the run does NOT inherit color from it.
    assert_eq!(
        run1.style_props.color.as_deref(),
        None,
        "unstyled run should NOT inherit color from DefaultParagraphFont \
         per MS-OI29500 §17.7.4.17(a) — its children are ignored."
    );
}

/// When an explicit rStyle is present, it should override the default char style.
///
/// POSITIVE: explicit char styles work regardless of default char style handling.
#[test]
fn spec_explicit_char_style_overrides_default() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "default-char-style");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run2 = nodes
        .iter()
        .find(|n| n.text.contains("Explicit rStyle"))
        .expect("should find explicitly styled run");

    assert_eq!(
        run2.style_props.color.as_deref(),
        Some("FF0000"),
        "run with rStyle=RedChar should have color=FF0000, got {:?}",
        run2.style_props.color
    );
}

// -- Linked styles: cross-paragraph application ----------------------------

/// ISO 29500-1 §17.7.4.6: A linked character style applied to a run should
/// provide the char style's rPr properties, even when the paragraph uses a
/// different paragraph style.
///
/// POSITIVE: linked char styles are stored as regular char styles, so applying
/// LinkedChar2 to a run should give it bold + color=2E74B5.
#[test]
fn spec_linked_char_style_gives_own_rpr() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "linked-style-cross-para");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run2 = nodes
        .iter()
        .find(|n| n.text.contains("LinkedChar2"))
        .expect("should find linked-char-styled run");

    assert_eq!(
        run2.style_props.color.as_deref(),
        Some("2E74B5"),
        "linked char style run should have color=2E74B5 from char style definition, got {:?}",
        run2.style_props.color
    );
}

/// A run with no char style in the same paragraph should get the paragraph
/// style's rPr (OtherPara: italic, color=red).
#[test]
fn spec_linked_style_para_only_run_gets_para_formatting() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "linked-style-cross-para");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run1 = nodes
        .iter()
        .find(|n| n.text.contains("OtherPara only"))
        .expect("should find para-only run");

    assert_eq!(
        run1.style_props.color.as_deref(),
        Some("FF0000"),
        "run without char style should get color=FF0000 from OtherPara paragraph style, got {:?}",
        run1.style_props.color
    );
}

// -- Font slot cascade through style chain ---------------------------------

/// ISO 29500-1 §17.3.2.26: Each rFonts slot (ascii, hAnsi, eastAsia, cs)
/// cascades independently through the style hierarchy. A char style setting
/// ascii/hAnsi should not prevent the para style's eastAsia from cascading.
///
/// POSITIVE: font slots are stored as independent Optional fields and each
/// resolves through resolve_option independently.
#[test]
fn spec_font_slot_cascade_independent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "font-slot-style-resolution");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);
    assert!(!nodes.is_empty(), "should have at least one text run");

    let run = &nodes[0];

    // font_family (ascii/hAnsi) from char style
    assert_eq!(
        run.style_props.font_family.as_deref(),
        Some("Courier New"),
        "font_family should come from char style (ascii/hAnsi='Courier New'), got {:?}",
        run.style_props.font_family
    );

    // font_east_asia from para style
    assert_eq!(
        run.style_props.font_east_asia.as_deref(),
        Some("MS Mincho"),
        "font_east_asia should cascade from para style ('MS Mincho'), got {:?}",
        run.style_props.font_east_asia
    );

    // font_cs from direct formatting
    assert_eq!(
        run.style_props.font_cs.as_deref(),
        Some("David"),
        "font_cs should come from direct formatting ('David'), got {:?}",
        run.style_props.font_cs
    );
}

// -- Paragraph mark rPr (informational) ------------------------------------

/// ISO 29500-1 §17.3.1.29: The rPr inside pPr specifies formatting for the
/// paragraph mark only. Text runs within the paragraph should NOT inherit
/// these properties.
///
/// POSITIVE: our code correctly does not apply pPr/rPr to text runs.
#[test]
fn spec_para_mark_rpr_does_not_leak_to_runs() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "para-mark-rpr");
    let paras = common::all_paragraphs(&doc);
    let nodes = text_nodes(paras[0]);

    let run = nodes
        .iter()
        .find(|n| n.text.contains("Normal text"))
        .expect("should find normal text run");

    // The paragraph mark has bold + color=FF0000, but the text run should not
    assert!(
        !run.marks.contains(&Mark::Bold),
        "text run should NOT inherit bold from paragraph mark's rPr"
    );
    assert!(
        run.style_props.color.is_none() || run.style_props.color.as_deref() != Some("FF0000"),
        "text run should NOT inherit color=FF0000 from paragraph mark's rPr, got {:?}",
        run.style_props.color
    );
}

/// ISO 29500-1 §17.3.1.29: the rPr inside pPr is still real formatting data
/// for the paragraph mark itself and must be preserved in the paragraph model.
#[test]
fn spec_para_mark_rpr_is_preserved_on_paragraph() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "para-mark-rpr");
    let paras = common::all_paragraphs(&doc);
    let para = paras[0];

    assert!(
        para.paragraph_mark_marks.contains(&Mark::Bold),
        "paragraph mark should preserve direct bold from pPr/rPr"
    );
    assert_eq!(
        para.paragraph_mark_style_props.color.as_deref(),
        Some("FF0000"),
        "paragraph mark should preserve direct color from pPr/rPr"
    );
}
