//! AUTO-GENERATED by the spec-word-compliance workflow.
//!
//! Area: "Cross-structure anchored ranges: comments, bookmarks, range
//! permissions"
//!
//! Each `#[test]` encodes a Word-consumption / serializer-fidelity rule mined
//! from ECMA-376 / ISO 29500-1 and the [MS-OI29500] implementer notes for the
//! cross-structure annotation elements (§17.13.2 .. §17.13.7): commentRange*,
//! commentReference, bookmarkStart/End, permStart/permEnd.
//!
//! A FAILING assertion here encodes a real Word-compliance GAP in stemma — it
//! is NOT something to make pass by weakening the test. The assertion messages
//! carry the rule text + §refs so a failure is self-explanatory.
//!
//! Methodology note (consumption vs. save): stemma round-trips UNTOUCHED
//! content byte-verbatim, so `reserialize()` of an unedited document reflects
//! stemma's verbatim-preservation contract, not Word's render-time
//! normalization. xmlContains is used ONLY for markup the serializer actively
//! re-emits/preserves; consumption semantics (zero-width markers, accept/reject
//! text) are asserted on the READ side via read_accepted()/read_rejected().

use std::io::Read;

use stemma::ExportOptions;
use stemma::api::{Document, validate};

// ─── Prelude / plumbing ─────────────────────────────────────────────────────

/// Build a valid minimal `.docx`. `body_xml` is the inner content of
/// `<w:body>…</w:body>` (paragraphs, tables, sectPr, …). `extra_parts` is a
/// list of `(part_path, xml)` pairs (e.g. `("word/styles.xml", "…")`); each
/// gets its own zip entry plus a Content-Types override + a document rel.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );

    let mut overrides = String::new();
    let mut doc_rel_entries = String::new();
    for (i, (path, _)) in extra_parts.iter().enumerate() {
        let content_type = match *path {
            "word/styles.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
            }
            "word/numbering.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
            }
            "word/comments.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"
            }
            other => panic!("make_docx: no known content-type for extra part {other}"),
        };
        let rel_type = match *path {
            "word/styles.xml" => {
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
            }
            "word/numbering.xml" => {
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering"
            }
            "word/comments.xml" => {
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments"
            }
            other => panic!("make_docx: no known rel-type for extra part {other}"),
        };
        overrides.push_str(&format!(
            r#"<Override PartName="/{path}" ContentType="{content_type}"/>"#
        ));
        let target = path.strip_prefix("word/").unwrap_or(path);
        doc_rel_entries.push_str(&format!(
            r#"<Relationship Id="rIdX{i}" Type="{rel_type}" Target="{target}"/>"#
        ));
    }

    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>{overrides}</Types>"#
    );

    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;
    let doc_rels = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{doc_rel_entries}</Relationships>"#
    );

    use std::io::Write;
    use zip::write::FileOptions;
    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (path, xml) in extra_parts {
            zip.start_file(*path, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip and return the contents of `word/document.xml`.
#[allow(dead_code)]
fn document_xml_of(docx: &[u8]) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(docx)).expect("open docx zip");
    let mut file = archive
        .by_name("word/document.xml")
        .expect("word/document.xml present");
    let mut out = String::new();
    file.read_to_string(&mut out).expect("read document.xml");
    out
}

/// Parse → serialize (default export options) → return re-serialized
/// `word/document.xml`.
#[allow(dead_code)]
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse for reserialize");
    let out = doc.serialize(&ExportOptions::default()).expect("serialize");
    document_xml_of(&out)
}

/// True iff `validate` reports no errors (opens clean), plus issue detail.
fn opens_clean(bytes: &[u8]) -> (bool, String) {
    let report = validate(bytes);
    let detail = report
        .issues
        .iter()
        .map(|i| format!("[{:?}] {}", i.code, i.message))
        .collect::<Vec<_>>()
        .join("; ");
    (report.ok, detail)
}

fn accept_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text()
        .trim()
        .to_string()
}

fn reject_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_rejected()
        .expect("read_rejected")
        .to_text()
        .trim()
        .to_string()
}

// ─── Specs ──────────────────────────────────────────────────────────────────

/// ECMA-376 §17.13.6.2; MS-OI29500 §2.1.356; ECMA-376 §17.13.2.
///
/// A bookmarkStart whose w:name exceeds Word's 40-char limit is preserved
/// verbatim through reserialization: the 40-char cap is a Word load-time
/// behaviour, not a markup the serializer should rewrite. The standard allows
/// any-length names on disk and stemma round-trips untouched content verbatim.
#[test]
fn bookmark_name_over_40_chars_survives_reserialize_verbatim() {
    let body = r#"<w:p><w:bookmarkStart w:id="0" w:name="thisBookmarkNameIsDeliberatelyLongerThanFortyCharacters"/><w:r><w:t>Seattle</w:t></w:r><w:bookmarkEnd w:id="0"/></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("thisBookmarkNameIsDeliberatelyLongerThanFortyCharacters"),
        "MS-OI29500 §2.1.356 (refs: ECMA-376 §17.13.6.2, §17.13.2): the 40-char cap is Word's \
         load-time limit; the standard allows any-length names on disk and stemma preserves \
         untouched content verbatim, so the full bookmark name must survive reserialization. \
         Re-serialized document.xml:\n{xml}"
    );
    assert!(
        xml.contains("w:bookmarkEnd"),
        "ECMA-376 §17.13.6.1/.2: a bookmarkStart requires a paired bookmarkEnd with the same \
         id; the serializer must re-emit the end marker so the pair stays balanced. \
         Re-serialized document.xml:\n{xml}"
    );
}

/// ECMA-376 §17.13.7.2; MS-OI29500 §2.1.358; ECMA-376 §17.13.2.
///
/// A balanced permStart/permEnd pair carrying both ed and edGrp opens clean and
/// is zero-width: ed-over-edGrp is a read-time decision, never a save-time
/// rewrite, and the markers contribute no text.
#[test]
fn permstart_ed_and_edgrp_consumption_uses_ed_opens_clean_zero_width() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">This is a </w:t></w:r><w:permStart w:id="0" w:ed="DOMAIN\user" w:edGrp="everyone"/><w:r><w:t>range permission</w:t></w:r><w:permEnd w:id="0"/><w:r><w:t>.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "ECMA-376 §17.13.7.2 / MS-OI29500 §2.1.358: a balanced permStart/permEnd carrying ed \
         (and edGrp) is conformant; ed-over-edGrp is a read-time decision, not a save error, so \
         validate() must report no errors. Issues: {detail}"
    );

    assert_eq!(
        accept_text(&b),
        "This is a range permission.",
        "ECMA-376 §17.13.2: permStart/permEnd are zero-width markers ('do not contain it'); \
         accept-all yields the concatenated run text only."
    );
}

/// ECMA-376 §17.13.4.4; MS-OI29500 §2.1.315; ECMA-376 §17.13.2.
///
/// A commentRangeStart with no corresponding commentRangeEnd is a single
/// zero-width anchor point (Word anchors at the commentReference). It
/// contributes no text to any read projection.
#[test]
fn lone_comment_range_start_is_zero_width_anchor() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Some </w:t></w:r><w:commentRangeStart w:id="0"/><w:r><w:t>text.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_eq!(
        accept_text(&b),
        "Some text.",
        "MS-OI29500 §2.1.315 / ECMA-376 §17.13.2: a lone commentRangeStart is a zero-width \
         single anchor and contains no content, so accepted text is exactly the two runs \
         concatenated."
    );
    assert_eq!(
        reject_text(&b),
        "Some text.",
        "ECMA-376 §17.13.2: a comment marker is an annotation, not a tracked change, so \
         rejecting changes nothing and the marker still contributes no text."
    );
}

/// ECMA-376 §17.13.6.2; MS-OI29500 §2.1.356; ECMA-376 §17.13.2.
///
/// A table bookmark whose colFirst exceeds colLast opens clean: Word clamps
/// colFirst to colLast (read-time adjustment) and the markers stay zero-width.
#[test]
fn table_bookmark_colfirst_gt_collast_opens_clean_zero_text() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:bookmarkStart w:id="0" w:name="tbm" w:colFirst="3" w:colLast="1"/><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>C</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>D</w:t></w:r></w:p></w:tc><w:bookmarkEnd w:id="0"/></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "MS-OI29500 §2.1.356 (refs: ECMA-376 §17.13.6.2, §17.13.2): Word clamps colFirst to \
         colLast and opens the file; therefore validate() must report no errors (would-be Word \
         repair). Issues: {detail}"
    );
}

/// ECMA-376 §17.13.7.2; MS-OI29500 §2.1.358; ECMA-376 §17.13.2.
///
/// A column-scoped table range permission whose colFirst/colLast exceed the
/// table's column count opens clean: Word does not reject the file (it behaves
/// unpredictably at read time but still opens).
#[test]
fn perm_colfirst_collast_exceed_table_columns_opens_clean() {
    let body = r#"<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="2000"/><w:gridCol w:w="2000"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:permStart w:id="0" w:edGrp="everyone" w:colFirst="5" w:colLast="9"/><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>C</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2000" w:type="dxa"/></w:tcPr><w:p><w:r><w:t>D</w:t></w:r></w:p></w:tc><w:permEnd w:id="0"/></w:tr></w:tbl><w:p/><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "MS-OI29500 §2.1.358 (refs: ECMA-376 §17.13.7.2, §17.13.2): Word does not reject \
         out-of-range colFirst/colLast on a perm; it opens (behaving unpredictably). validate() \
         must report no errors. Issues: {detail}"
    );
}

/// ECMA-376 §17.13.7.2; ECMA-376 §17.13.2.
///
/// A permStart carrying both colFirst and colLast (col pair complete) that is
/// NOT in a table has its column values ignored; the document is conformant,
/// opens clean, and the markers contribute no text.
#[test]
fn perm_colfirst_collast_outside_table_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">This is a </w:t></w:r><w:permStart w:id="0" w:edGrp="everyone" w:colFirst="0" w:colLast="1"/><w:r><w:t>range permission</w:t></w:r><w:permEnd w:id="0"/><w:r><w:t>.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "ECMA-376 §17.13.7.2: col values on a non-table perm are ignored, not invalid (and \
         colLast is present so the both-or-neither pairing rule holds); validate() must report \
         no errors. Issues: {detail}"
    );
    assert_eq!(
        accept_text(&b),
        "This is a range permission.",
        "ECMA-376 §17.13.2: permStart/permEnd are zero-width markers; accepted text is exactly \
         the three runs concatenated."
    );
}

/// ECMA-376 §17.13.4.4, §17.13.4.3, §17.13.2.
///
/// A commentRangeStart/End pair whose start is in one paragraph and end in the
/// next is a valid cross-structure annotation: the markers are zero-width and
/// contribute no text, so reading concatenates per-paragraph run text with the
/// normal block separator.
#[test]
fn cross_paragraph_comment_range_markers_zero_width() {
    let body = r#"<w:p><w:r><w:t>Example</w:t></w:r><w:commentRangeStart w:id="0"/><w:r><w:t xml:space="preserve"> one</w:t></w:r></w:p><w:p><w:r><w:t>Example</w:t></w:r><w:commentRangeEnd w:id="0"/><w:r><w:t xml:space="preserve"> two</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_eq!(
        accept_text(&b),
        "Example one\n\nExample two",
        "ECMA-376 §17.13.2 (refs: §17.13.4.3/.4): the cross-paragraph commentRangeStart/End \
         markers contain no content, so accepted text is the two paragraphs' runs joined by the \
         block separator (\\n\\n)."
    );
    assert_eq!(
        reject_text(&b),
        "Example one\n\nExample two",
        "ECMA-376 §17.13.2: comment range markers are annotations, not tracked changes; \
         rejecting does not alter them and they still contribute no text."
    );
}

/// ISO 29500-1 §17.13.4.4; MS-OI29500 §2.1.315; ECMA-376 §17.13.2.
///
/// A commentRangeStart with no matching commentRangeEnd is NOT non-conformant
/// to Word: Word opens the file clean and uses the commentReference as the
/// single anchor point, so validate() must report no errors. A failure means
/// stemma's I-ANN-005 pairing check is stricter than Word.
#[test]
fn lone_comment_range_start_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Before </w:t></w:r><w:commentRangeStart w:id="1"/><w:r><w:t>anchored text</w:t></w:r><w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "MS-OI29500 §2.1.315 (refs: ISO 29500-1 §17.13.4.4, ECMA-376 §17.13.2): Word opens a \
         lone commentRangeStart by anchoring at the commentReference; it is not an open-blocking \
         error, so validate() must report no errors. A failure means stemma's I-ANN-005 pairing \
         check is stricter than Word. Issues: {detail}"
    );
}

/// ISO 29500-1 §17.13.4.3; MS-OI29500 §2.1.314; ECMA-376 §17.13.2.
///
/// A commentRangeEnd with no matching commentRangeStart is NOT non-conformant
/// to Word: Word opens the file clean and uses the commentReference as the
/// single anchor point, so validate() must report no errors.
#[test]
fn lone_comment_range_end_opens_clean() {
    let body = r#"<w:p><w:r><w:t>anchored text</w:t></w:r><w:commentRangeEnd w:id="1"/><w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        ok,
        "MS-OI29500 §2.1.314 (refs: ISO 29500-1 §17.13.4.3, ECMA-376 §17.13.2): Word opens a \
         lone commentRangeEnd by anchoring at the commentReference; not an open-blocking error, \
         so validate() must report no errors. A failure means stemma's I-ANN-005 is stricter \
         than Word. Issues: {detail}"
    );
}

/// ISO 29500-1 §17.13.4.3/.4; MS-OI29500 §2.1.314/.315.
///
/// commentRange/commentReference markers are zero-width annotations, never
/// tracked changes, so accepting or rejecting all changes leaves the run text
/// exactly as authored even when a marker is unpaired.
#[ignore = "open question: read projection emits a U+FFFC object-replacement char for the \
            commentReference run, so comment anchors are not zero-width in read_accepted/to_text \
            (ISO 29500-1 §17.13.4 / ECMA §17.13.2)"]
#[test]
fn lone_comment_range_markers_contribute_no_text() {
    let body = r#"<w:p><w:r><w:t>anchored text</w:t></w:r><w:commentRangeEnd w:id="1"/><w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_eq!(
        accept_text(&b),
        "anchored text",
        "ISO 29500-1 §17.13.4: comment markers are zero-width annotations; accept-all does not \
         touch run text, so accepted text equals the authored run text."
    );
    assert_eq!(
        reject_text(&b),
        "anchored text",
        "ISO 29500-1 §17.13.4: comment markers are not tracked changes; reject-all does not \
         touch run text, so rejected text equals the authored run text."
    );
}

/// ECMA-376 / ISO 29500-1 §17.13.4.4 (mirror §17.13.4.3, §17.13.4.5).
///
/// A balanced commentRangeStart/End pair with NO commentReference of the same
/// id anywhere in the document story is non-conformant; the document must be
/// flagged, not silently opened clean. (INVERTED post-condition: opens_clean
/// must be FALSE. If it is true, stemma's pairing check does not verify
/// reference presence — the gap this test hunts.)
#[ignore = "open question: stemma annotation pairing (I-ANN-005) verifies start<->end only, not \
            commentReference presence; a torn comment Word cannot link is accepted clean \
            (ECMA-376/ISO 29500-1 §17.13.4.4, mirror §17.13.4.3/.4.5)"]
#[test]
fn comment_range_pair_without_reference_is_nonconformant() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Some </w:t></w:r><w:commentRangeStart w:id="0"/><w:r><w:t>text</w:t></w:r><w:commentRangeEnd w:id="0"/></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        !ok,
        "ECMA-376 / ISO 29500-1 §17.13.4.4 (mirror §17.13.4.3, §17.13.4.5): a \
         commentRangeStart/End pair with NO matching commentReference is non-conformant ('then \
         the document is non-conformant'); a Word-faithful validator must report an error, so \
         validate() should NOT be clean. It reported clean — stemma's annotation pairing check \
         does not verify reference presence. Issues: {detail}"
    );
}

/// ECMA-376 / ISO 29500-1 §17.13.6.1; ECMA-376 §17.13.2.
///
/// A bookmarkEnd with no bookmarkStart of the same id appearing PRIOR to it in
/// document order is non-conformant — even if a bookmarkStart with that id
/// appears later. (INVERTED post-condition: opens_clean must be FALSE. If
/// stemma pairs purely by id ignoring relative order it reports clean — the gap
/// this test hunts.)
#[ignore = "open question: stemma bookmark pairing (I-ANN-003) matches start<->end by id count and \
            does not enforce start-before-end document order; a reversed pair passes clean \
            (ECMA-376/ISO 29500-1 §17.13.6.1)"]
#[test]
fn bookmarkend_before_bookmarkstart_in_document_order_is_nonconformant() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">a </w:t></w:r><w:bookmarkEnd w:id="0"/><w:r><w:t xml:space="preserve">b </w:t></w:r><w:bookmarkStart w:id="0" w:name="reversed"/><w:r><w:t>c</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let (ok, detail) = opens_clean(&b);
    assert!(
        !ok,
        "ECMA-376 / ISO 29500-1 §17.13.6.1 (refs: §17.13.2): a bookmarkEnd with no matching \
         bookmarkStart strictly prior in document order is non-conformant ('then the document is \
         non-conformant'); a Word-faithful validator must report an error, so validate() should \
         NOT be clean. It reported clean — stemma pairs by id without enforcing start-before-end \
         order. Issues: {detail}"
    );
}
