//! Audit tests: Table Style Cascade + Conditional Formatting Interactions
//!
//! These tests probe INTERACTION bugs between table styles, conditional
//! formatting, tblLook, banding, merges, and property cascade.
//!
//! Spec references: ISO 29500-1 §17.7.6, §17.4, MS-OI29500 §2.1.246–253.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, InlineNode, TableNode};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-cascade-audit";

// ── helpers ──────────────────────────────────────────────────────────────
fn first_table(doc: &CanonDoc) -> &TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .expect("document should contain at least one table")
}

fn all_tables(doc: &CanonDoc) -> Vec<&TableNode> {
    doc.blocks
        .iter()
        .filter_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t.as_ref()),
            _ => None,
        })
        .collect()
}

fn cell_first_paragraph(table: &TableNode, row: usize, col: usize) -> &stemma::ParagraphNode {
    let cell = &table.rows[row].cells[col];
    cell.blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Paragraph(p) => Some(p),
            _ => None,
        })
        .expect("cell should contain at least one paragraph")
}

fn cell_first_text_node(table: &TableNode, row: usize, col: usize) -> &stemma::TextNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    return t;
                }
            }
        }
    }
    panic!("cell ({row},{col}) should contain at least one text node")
}

/// Find the first nested table inside a table cell.
fn cell_nested_table(table: &TableNode, row: usize, col: usize) -> &TableNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Table(t) = block {
            return t;
        }
    }
    panic!("cell ({row},{col}) should contain a nested table")
}

// ── Band size > 1 with correct row grouping (§17.7.6.7) ──

/// ECMA-376 §17.7.6.7: tblStyleRowBandSize=2 means rows group in pairs.
///
/// With band size 2 and 6 data rows (no firstRow/lastRow):
///   rows 0-1: band1Horz (BDD7EE)
///   rows 2-3: band2Horz (C6EFCE)
///   rows 4-5: band1Horz (BDD7EE)
///
/// This tests that the banding algorithm correctly divides by band_size
/// before computing modulo alternation.
#[test]
fn spec_band_size_2_first_pair() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-size-2");
    let table = first_table(&doc);

    // Rows 0-1: band1Horz (BDD7EE)
    for row_idx in 0..2 {
        let shading = table.rows[row_idx].cells[0]
            .formatting
            .shading
            .as_ref()
            .unwrap_or_else(|| panic!("cell ({row_idx},0) should have shading from band1Horz"));
        assert_eq!(
            shading.fill.as_deref(),
            Some("BDD7EE"),
            "cell ({row_idx},0): band1Horz with bandSize=2 should be BDD7EE"
        );
    }
}

#[test]
fn spec_band_size_2_second_pair() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-size-2");
    let table = first_table(&doc);

    // Rows 2-3: band2Horz (C6EFCE)
    for row_idx in 2..4 {
        let shading = table.rows[row_idx].cells[0]
            .formatting
            .shading
            .as_ref()
            .unwrap_or_else(|| panic!("cell ({row_idx},0) should have shading from band2Horz"));
        assert_eq!(
            shading.fill.as_deref(),
            Some("C6EFCE"),
            "cell ({row_idx},0): band2Horz with bandSize=2 should be C6EFCE"
        );
    }
}

#[test]
fn spec_band_size_2_third_pair() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-size-2");
    let table = first_table(&doc);

    // Rows 4-5: band1Horz (BDD7EE) again
    for row_idx in 4..6 {
        let shading = table.rows[row_idx].cells[0]
            .formatting
            .shading
            .as_ref()
            .unwrap_or_else(|| panic!("cell ({row_idx},0) should have shading from band1Horz"));
        assert_eq!(
            shading.fill.as_deref(),
            Some("BDD7EE"),
            "cell ({row_idx},0): band1Horz (wrap-around) with bandSize=2 should be BDD7EE"
        );
    }
}

// ── vMerge spanning firstRow into normal rows (§17.7.6, §17.4.84) ──

/// ISO 29500-1 §17.7.6: firstRow conditional is determined by row_idx.
/// A vertically merged cell with restart in row 0 gets firstRow shading.
/// The continuation cell in row 1 should NOT get firstRow shading because
/// it is in row 1, which is not the first row.
///
/// Verifies that vMerge continuation cells do not inherit
/// the conditional formatting of their anchor row.
#[test]
fn spec_vmerge_firstrow_anchor_gets_conditional() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-firstrow-span");
    let table = first_table(&doc);

    // Cell (0,0): vMerge restart in row 0 — should get firstRow blue
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading from firstRow conditional");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("4472C4"),
        "cell (0,0): vMerge restart in firstRow should get blue (4472C4)"
    );

    // Cell (0,1): normal cell in row 0 — should get firstRow blue
    let shading_01 = table.rows[0].cells[1]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,1) should have shading from firstRow conditional");
    assert_eq!(
        shading_01.fill.as_deref(),
        Some("4472C4"),
        "cell (0,1): firstRow should get blue (4472C4)"
    );
}

/// ISO 29500-1 §17.7.6: vMerge continue cell in row 1 should NOT get
/// firstRow conditional formatting because row_idx=1 is not the first row.
#[test]
fn spec_vmerge_continuation_no_firstrow() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-firstrow-span");
    let table = first_table(&doc);

    // Cell (1,0): vMerge continue — row 1, not firstRow
    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): vMerge continue in row 1 should NOT get firstRow shading"
    );

    // Cell (2,0): normal row — no shading
    assert!(
        table.rows[2].cells[0].formatting.shading.is_none(),
        "cell (2,0): normal row should have no conditional shading"
    );
}

// ── gridSpan spanning firstCol into interior (§17.7.6, §17.4.17) ──

/// ISO 29500-1 §17.7.6: A cell with gridSpan=2 starting at col 0 should
/// get firstCol conditional formatting because cell_col==0.
///
/// This tests that gridSpan does not prevent firstCol detection.
#[test]
fn spec_gridspan_firstcol_merged_cell() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-firstcol");
    let table = first_table(&doc);

    // Row 0: merged cell at col 0 (gridSpan=2) — should get firstCol green
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("merged cell (0,0) should have shading from firstCol conditional");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("70AD47"),
        "merged cell (0,0) gridSpan=2: firstCol should get green (70AD47)"
    );

    // Verify the merged cell has gridSpan=2
    assert_eq!(
        table.rows[0].cells[0].grid_span, 2,
        "cell (0,0) should have gridSpan=2"
    );
}

/// ISO 29500-1 §17.7.6: Normal cells in row 1 — firstCol applies to col 0 only.
#[test]
fn spec_gridspan_firstcol_normal_row() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-firstcol");
    let table = first_table(&doc);

    // Row 1: cell (1,0) should get firstCol green
    let shading_10 = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (1,0) should have shading from firstCol conditional");
    assert_eq!(
        shading_10.fill.as_deref(),
        Some("70AD47"),
        "cell (1,0): firstCol should get green (70AD47)"
    );

    // Row 1: cell (1,1) no conditional
    assert!(
        table.rows[1].cells[1].formatting.shading.is_none(),
        "cell (1,1): interior cell should have no conditional shading"
    );

    // Row 1: cell (1,2) no conditional
    assert!(
        table.rows[1].cells[2].formatting.shading.is_none(),
        "cell (1,2): last cell should have no conditional shading (lastCol disabled)"
    );
}

// ── Direct paragraph alignment overrides conditional pPr (§17.7.6.1) ──

/// ISO 29500-1 §17.7.6.1: Conditional pPr provides alignment=center for
/// firstRow cells. But cell (0,0) has DIRECT paragraph alignment=right.
/// Direct formatting always overrides conditional formatting.
///
/// Resolved: has_direct_align ensures direct paragraph alignment takes precedence.
#[test]
fn spec_direct_para_alignment_overrides_conditional() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-para-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,0): direct right alignment should override conditional center
    let para_00 = cell_first_paragraph(table, 0, 0);
    assert_eq!(
        para_00.align,
        Some(stemma::Alignment::Right),
        "cell (0,0) paragraph: direct Right should override conditional Center"
    );

    // Cell (0,1): no direct alignment — conditional center applies
    let para_01 = cell_first_paragraph(table, 0, 1);
    assert_eq!(
        para_01.align,
        Some(stemma::Alignment::Center),
        "cell (0,1) paragraph: no direct, should get conditional Center"
    );
}

/// ISO 29500-1 §17.7.6.1: Data row paragraphs should have no
/// conditional alignment (only default/left).
#[test]
fn spec_direct_para_data_rows_no_conditional() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-para-overrides-conditional");
    let table = first_table(&doc);

    // Data row: no conditional pPr applies
    let para_10 = cell_first_paragraph(table, 1, 0);
    // Data rows get default alignment (Left or None depending on implementation)
    assert!(
        para_10.align.is_none() || para_10.align == Some(stemma::Alignment::Left),
        "cell (1,0) paragraph: data row should have no conditional alignment"
    );
}

// ── Direct run font size overrides conditional rPr (§17.7.6.2) ──

/// ISO 29500-1 §17.7.6.2: Conditional rPr provides sz=28 (14pt) for
/// firstRow. Cell (0,0) has a run with DIRECT sz=20 (10pt).
/// Direct formatting should override conditional formatting.
///
/// Resolved: has_direct_font_size ensures direct run font size takes precedence.
#[test]
fn spec_direct_font_size_overrides_conditional() {
    let (_runtime, doc) =
        common::import_fixture(FIXTURES, "direct-font-size-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,0): direct font_size=20 should override conditional 28
    let text_00 = cell_first_text_node(table, 0, 0);
    assert_eq!(
        text_00.style_props.font_size,
        Some(20),
        "cell (0,0) text: direct font_size=20 (10pt) should override conditional 28 (14pt)"
    );
}

/// ISO 29500-1 §17.7.6.2: Cell (0,1) has no direct font size — should
/// get conditional sz=28. Both firstRow cells should get bold.
#[test]
fn spec_conditional_font_size_when_no_direct() {
    let (_runtime, doc) =
        common::import_fixture(FIXTURES, "direct-font-size-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,1): no direct font size — conditional 28 applies
    let text_01 = cell_first_text_node(table, 0, 1);
    assert_eq!(
        text_01.style_props.font_size,
        Some(28),
        "cell (0,1) text: should get conditional font_size=28 (14pt)"
    );

    // Both firstRow cells should be bold from conditional rPr
    assert!(
        text_01.marks.contains(&stemma::Mark::Bold),
        "cell (0,1) text: should be bold from conditional rPr"
    );
}

// ── Nested table style independence (§17.7.6) ───────────────────

/// ISO 29500-1 §17.7.6: Each table resolves its own style independently.
/// The outer table has OuterStyle (firstRow=blue 4472C4).
/// The inner table (nested in outer cell (1,0)) has InnerStyle (firstRow=red FF0000).
///
/// Verify inner table conditional formatting is independent.
#[test]
fn spec_nested_table_outer_firstrow() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table-independence");
    let table = first_table(&doc);

    // Outer row 0 cells: blue from outer firstRow
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("outer cell (0,0) should have shading from firstRow");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("4472C4"),
        "outer cell (0,0): firstRow should be blue (4472C4)"
    );
}

/// The inner table should resolve its own style (InnerStyle) and apply
/// its own firstRow conditional (red FF0000), NOT the outer table's blue.
#[test]
fn spec_nested_table_inner_firstrow_independent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table-independence");
    let outer = first_table(&doc);

    // Inner table is inside outer cell (1,0)
    let inner = cell_nested_table(outer, 1, 0);

    // Inner row 0: should get red (FF0000) from InnerStyle firstRow
    let inner_shading_00 = inner.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("inner cell (0,0) should have shading from inner firstRow");
    assert_eq!(
        inner_shading_00.fill.as_deref(),
        Some("FF0000"),
        "inner cell (0,0): inner firstRow should be red (FF0000), NOT outer blue"
    );

    // Inner row 1: should have no conditional shading
    assert!(
        inner.rows[1].cells[0].formatting.shading.is_none(),
        "inner cell (1,0): data row should have no conditional shading"
    );
}

// ── Conditional border vs table border conflict (§17.4.66) ──────

/// MS-OI29500 §17.4.66(a): After conditional formatting applies cell borders,
/// the border conflict resolver compares cell borders vs table borders.
/// The border with higher weight wins: weight = size * style_rank.
///
/// firstRow conditional: thick red (sz=12, style_rank=2 → weight=24)
/// Table border: single black (sz=4, style_rank=1 → weight=4)
/// Conditional border should win.
#[test]
fn spec_conditional_border_wins_over_table_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-border-vs-table-border");
    let table = first_table(&doc);

    // Cell (0,0): should have conditional thick red borders after conflict resolution
    let borders_00 = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders");
    let top = borders_00
        .top
        .as_ref()
        .expect("cell (0,0) should have top border");
    assert_eq!(
        top.size,
        Some(12),
        "cell (0,0) top border: conditional thick (sz=12) should win over table single (sz=4)"
    );
    assert_eq!(
        top.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) top border color: conditional red should win"
    );
    assert_eq!(
        top.style.to_xml_str(),
        "thick",
        "cell (0,0) top border style: should be thick from conditional"
    );
}

/// Data row cells should NOT get borders from conditional formatting.
/// Per MS-OI29500 §2.1.169 cascade, they get table-level borders (black/4)
/// as fallback, NOT conditional borders (red/12).
#[test]
fn spec_data_row_no_conditional_cell_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-border-vs-table-border");
    let table = first_table(&doc);

    // Cell (1,0): data row — should NOT have conditional borders (red/12).
    // Per MS-OI29500 cascade, gets table-level borders (black/4) as fallback.
    let borders_10 = table.rows[1].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (1,0) should have borders from table cascade");

    // Non-shared edges (left for col-0 cell) should be from table cascade (black/4).
    let left = borders_10
        .left
        .as_ref()
        .expect("cell (1,0) left should have table-cascaded border");
    assert_eq!(
        left.color.as_deref(),
        Some("000000"),
        "cell (1,0) left: should be black (table cascade), NOT red (conditional)"
    );
    assert_eq!(
        left.size,
        Some(4),
        "cell (1,0) left: should be sz=4 (table cascade), NOT sz=12 (conditional)"
    );

    // The table itself should have borders
    assert!(
        table.formatting.borders.is_some(),
        "table should have table-level borders"
    );
}

// ── Table width type parsing (§17.4.63) ─────────────────────────

/// ISO 29500-1 §17.4.63: tblW specifies table width. The type attribute
/// controls interpretation: 'dxa' (twips), 'pct' (50ths of percent), 'auto'.
///
/// This tests that all three width types are correctly parsed.
#[test]
fn spec_table_width_dxa() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    assert!(tables.len() >= 3, "should have at least 3 tables");

    // Table 1: width=5000 type=dxa
    let width_dxa = tables[0]
        .formatting
        .width
        .as_ref()
        .expect("table 1 should have width");
    assert_eq!(width_dxa.w, 5000, "table 1 width value should be 5000");
    assert_eq!(
        width_dxa.width_type.to_xml_str(),
        "dxa",
        "table 1 width type should be 'dxa'"
    );
}

#[test]
fn spec_table_width_pct() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    assert!(tables.len() >= 3, "should have at least 3 tables");

    // Table 2: width=2500 type=pct
    let width_pct = tables[1]
        .formatting
        .width
        .as_ref()
        .expect("table 2 should have width");
    assert_eq!(width_pct.w, 2500, "table 2 width value should be 2500");
    assert_eq!(
        width_pct.width_type.to_xml_str(),
        "pct",
        "table 2 width type should be 'pct'"
    );
}

#[test]
fn spec_table_width_auto() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "table-width-types");
    let tables = all_tables(&doc);
    assert!(tables.len() >= 3, "should have at least 3 tables");

    // Table 3: width=0 type=auto
    let width_auto = tables[2]
        .formatting
        .width
        .as_ref()
        .expect("table 3 should have width");
    assert_eq!(width_auto.w, 0, "table 3 width value should be 0");
    assert_eq!(
        width_auto.width_type.to_xml_str(),
        "auto",
        "table 3 width type should be 'auto'"
    );
}
