//! Spec-compliance regression tests: Numbering (ECMA-376 section 17.9)
//!
//! Each test targets a specific numbering bug that was previously present in
//! the implementation. Tests assert the CORRECT behavioral outcome per the
//! ECMA-376 spec. All four bugs have since been fixed, so these tests serve
//! as regression guards -- if any of them fail, a previously-fixed bug has
//! been reintroduced.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/numbering-bugs/create_fixtures.py`.
//!
//! Bugs covered (all now fixed):
//!   1. suff (suffix) was parsed but not used in rendered_text (section 17.9.28)
//!   2. pStyle reverse binding was not wired up in import pipeline (section 17.9.23)
//!   3. start defaulted to 1 instead of 0 when w:start omitted (section 17.9.25)
//!   4. numStyleLink chain resolution was not working (section 17.9.21/27)

use stemma::{BlockNode, CanonDoc, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/numbering-bugs";

// -- helpers ----------------------------------------------------------------

/// Extract numbering prefixes from all paragraphs in a document.
///
/// Returns the synthesized_text from NumberingInfo (preferred), or
/// literal_prefix, or the prefix portion of rendered_text split on tab.
fn numbering_prefixes(doc: &CanonDoc) -> Vec<Option<String>> {
    let mut prefixes = Vec::new();
    collect_prefixes_tracked(&doc.blocks, &mut prefixes);
    prefixes
}

fn collect_prefixes_tracked(blocks: &[TrackedBlock], out: &mut Vec<Option<String>>) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_prefixes_bare(blocks: &[BlockNode], out: &mut Vec<Option<String>>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

/// Extract the numbering prefix from a paragraph.
///
/// Prefers NumberingInfo.synthesized_text; falls back to literal_prefix;
/// falls back to splitting rendered_text on tab.
fn extract_prefix(p: &stemma::ParagraphNode) -> Option<String> {
    if let Some(ref num_info) = p.numbering
        && !num_info.synthesized_text.is_empty()
    {
        return Some(num_info.synthesized_text.clone());
    }
    if let Some(ref lp) = p.literal_prefix {
        return Some(lp.clone());
    }
    if let Some(ref rt) = p.rendered_text
        && let Some(idx) = rt.find('\t')
    {
        let prefix = rt[..idx].to_string();
        if !prefix.is_empty() {
            return Some(prefix);
        }
    }
    None
}

// == Bug 1: suff (suffix) types (ECMA-376 section 17.9.28) =================

/// ECMA-376 section 17.9.28: The suff element controls the separator between
/// the numbering text and the paragraph body.
///
/// When suff="space", rendered_text must use a space (not tab) between the
/// synthesized number and the body text.
///
/// Regression guard: Previously the LevelDef.suffix field was parsed from
/// w:suff but never referenced when building rendered_text -- a tab was
/// always used. Now fixed: import.rs uses l.suffix.separator().
#[test]
fn bug1_suff_space_uses_space_separator() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "suff-space");
    let paras = common::all_paragraphs(&doc);

    // Filter to numbered paragraphs only
    let numbered_paras: Vec<_> = paras.iter().filter(|p| p.numbering.is_some()).collect();
    assert!(
        numbered_paras.len() >= 6,
        "should have at least 6 numbered paragraphs (2 per numId), got {}",
        numbered_paras.len()
    );

    // numId=1 (first two paragraphs): suff="space"
    // rendered_text should use space separator, NOT tab
    let space_para = &numbered_paras[0];
    let space_rendered = space_para
        .rendered_text
        .as_ref()
        .expect("space-suffix paragraph should have rendered_text");
    let space_prefix = space_para
        .numbering
        .as_ref()
        .unwrap()
        .synthesized_text
        .as_str();

    // The rendered_text should be "1. Space suffix first" (space after prefix)
    assert!(
        !space_rendered.contains('\t'),
        "ECMA-376 section 17.9.28: suff='space' means rendered_text must use a space \
         separator, not a tab. Got rendered_text='{}' which contains a tab.",
        space_rendered
    );
    let expected_space_start = format!("{} ", space_prefix);
    assert!(
        space_rendered.starts_with(&expected_space_start),
        "ECMA-376 section 17.9.28: suff='space' rendered_text should start with \
         '{}', got '{}'",
        expected_space_start,
        space_rendered
    );
}

/// ECMA-376 section 17.9.28: suff="nothing" means no separator between
/// the numbering text and the paragraph body.
#[test]
fn bug1_suff_nothing_has_no_separator() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "suff-space");
    let paras = common::all_paragraphs(&doc);

    let numbered_paras: Vec<_> = paras.iter().filter(|p| p.numbering.is_some()).collect();
    assert!(
        numbered_paras.len() >= 6,
        "should have at least 6 numbered paragraphs, got {}",
        numbered_paras.len()
    );

    // numId=2 (paragraphs 2-3, 0-indexed): suff="nothing"
    let nothing_para = &numbered_paras[2];
    let nothing_rendered = nothing_para
        .rendered_text
        .as_ref()
        .expect("nothing-suffix paragraph should have rendered_text");
    let nothing_prefix = nothing_para
        .numbering
        .as_ref()
        .unwrap()
        .synthesized_text
        .as_str();

    // The rendered_text should be "1.Nothing suffix first" (no separator at all)
    let expected_nothing_start = format!("{}Nothing", nothing_prefix);
    assert!(
        nothing_rendered.starts_with(&expected_nothing_start),
        "ECMA-376 section 17.9.28: suff='nothing' means no separator between number \
         text and body. Expected rendered_text to start with '{}', got '{}'",
        expected_nothing_start,
        nothing_rendered
    );
}

/// ECMA-376 section 17.9.28: suff="tab" (the default) should use a tab
/// separator. This is a control test.
#[test]
fn bug1_suff_tab_uses_tab_separator() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "suff-space");
    let paras = common::all_paragraphs(&doc);

    let numbered_paras: Vec<_> = paras.iter().filter(|p| p.numbering.is_some()).collect();
    assert!(
        numbered_paras.len() >= 6,
        "should have at least 6 numbered paragraphs, got {}",
        numbered_paras.len()
    );

    // numId=3 (paragraphs 4-5, 0-indexed): suff="tab"
    let tab_para = &numbered_paras[4];
    let tab_rendered = tab_para
        .rendered_text
        .as_ref()
        .expect("tab-suffix paragraph should have rendered_text");

    assert!(
        tab_rendered.contains('\t'),
        "ECMA-376 section 17.9.28: suff='tab' rendered_text should contain a tab. \
         Got '{}'",
        tab_rendered
    );
}

// == Bug 2: pStyle reverse binding (ECMA-376 section 17.9.23) ==============

/// ECMA-376 section 17.9.23: When an abstract numbering level has
/// <w:pStyle w:val="X"/>, any paragraph with style "X" gets numbering
/// from that level -- even if the style itself has no numPr.
///
/// Regression guard: Previously build_pstyle_reverse_map() existed but was
/// never called from the import pipeline. Now fixed: import.rs calls it
/// when effective_num_props is None.
#[test]
fn bug2_pstyle_reverse_binding_applies_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "pstyle-reverse-binding");
    let paras = common::all_paragraphs(&doc);

    // All 3 paragraphs use style "CustomListNum" which has no direct numPr,
    // but numbering level 0 claims that style via pStyle.
    let numbered_paras: Vec<_> = paras.iter().filter(|p| p.numbering.is_some()).collect();

    assert!(
        numbered_paras.len() >= 3,
        "ECMA-376 section 17.9.23: paragraphs with style 'CustomListNum' should get \
         numbering from the pStyle reverse binding. Expected at least 3 numbered \
         paragraphs, got {}. If 0, build_pstyle_reverse_map() is not called from \
         the import pipeline.",
        numbered_paras.len()
    );

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert_eq!(
        numbered[0], "1.",
        "ECMA-376 section 17.9.23: first paragraph via pStyle binding should be '1.', got '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "2.",
        "ECMA-376 section 17.9.23: second paragraph via pStyle binding should be '2.', got '{}'",
        numbered[1]
    );
    assert_eq!(
        numbered[2], "3.",
        "ECMA-376 section 17.9.23: third paragraph via pStyle binding should be '3.', got '{}'",
        numbered[2]
    );
}

// == Bug 3: start default value (ECMA-376 section 17.9.25) =================

/// ECMA-376 section 17.9.25: "If this element is omitted, then the starting
/// value shall be zero (0)."
///
/// When w:start is absent from a level definition, the first numbered
/// paragraph should display "0.", the second "1.", etc.
///
/// Regression guard: Previously the implementation defaulted start to 1
/// instead of the spec-mandated 0. Now fixed: parse_level() in numbering.rs
/// initializes start to 0.
#[test]
fn bug3_start_defaults_to_zero_when_omitted() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "start-omitted");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "should have at least 3 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    assert_eq!(
        numbered[0], "0.",
        "ECMA-376 section 17.9.25: when w:start is omitted, the starting value \
         defaults to 0. First item should be '0.', got '{}'. If this is '1.', \
         the implementation incorrectly defaults to 1.",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "1.",
        "second item should be '1.', got '{}'",
        numbered[1]
    );
    assert_eq!(
        numbered[2], "2.",
        "third item should be '2.', got '{}'",
        numbered[2]
    );
}

// == Bug 4: numStyleLink chain resolution (ECMA-376 section 17.9.21/27) ====

/// ECMA-376 section 17.9.21: When an abstractNum has numStyleLink, it
/// references a numbering style. The levels come from the abstractNum
/// with a matching styleLink (section 17.9.27).
///
/// Regression guard: Previously get_level() did not follow the numStyleLink
/// chain. Now fixed: get_level() in numbering.rs falls through to
/// numStyleLink resolution when no direct levels are found.
#[test]
fn bug4_num_style_link_chain_resolves_levels() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "num-style-link-chain");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "ECMA-376 section 17.9.21: paragraphs using numId=1 (which points to \
         abstractNum 0 with numStyleLink='OutlineList') should follow the chain \
         to abstractNum 1 (which has styleLink='OutlineList' and actual levels). \
         Expected at least 3 numbered paragraphs, got {}: {:?}. \
         If 0, the numStyleLink chain is not followed.",
        numbered.len(),
        numbered
    );

    assert_eq!(
        numbered[0], "1.",
        "ECMA-376 section 17.9.21: first paragraph via numStyleLink chain should be '1.', \
         got '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "2.",
        "second paragraph via numStyleLink chain should be '2.', got '{}'",
        numbered[1]
    );
    assert_eq!(
        numbered[2], "a)",
        "third paragraph (level 1) via numStyleLink chain should be 'a)', got '{}'",
        numbered[2]
    );
}

// == Unit test: LevelDef.suffix field is parsed correctly ====================

/// Direct unit test verifying that the suffix field on LevelDef is parsed
/// from w:suff elements in numbering XML.
///
/// Regression guard: Previously LevelDef had no suffix field at all, meaning
/// suff was silently ignored during parsing.
#[test]
fn bug1_unit_suffix_field_parsed_from_xml() {
    let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="0">
    <w:lvl w:ilvl="0">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%1."/>
      <w:suff w:val="space"/>
    </w:lvl>
    <w:lvl w:ilvl="1">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%2."/>
      <w:suff w:val="nothing"/>
    </w:lvl>
    <w:lvl w:ilvl="2">
      <w:start w:val="1"/>
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%3."/>
    </w:lvl>
  </w:abstractNum>
  <w:num w:numId="1">
    <w:abstractNumId w:val="0"/>
  </w:num>
</w:numbering>"#;

    let defs = stemma::numbering::NumberingDefinitions::parse(xml.as_bytes())
        .expect("should parse numbering XML");

    let level0 = defs.get_level(1, 0).expect("should find level 0");
    let level1 = defs.get_level(1, 1).expect("should find level 1");
    let level2 = defs.get_level(1, 2).expect("should find level 2");

    // Level 0: suff="space"
    assert_eq!(
        level0.suffix,
        stemma::numbering::LevelSuffix::Space,
        "ECMA-376 section 17.9.28: level 0 has suff='space', but suffix field is {:?}",
        level0.suffix
    );

    // Level 1: suff="nothing"
    assert_eq!(
        level1.suffix,
        stemma::numbering::LevelSuffix::Nothing,
        "ECMA-376 section 17.9.28: level 1 has suff='nothing', but suffix field is {:?}",
        level1.suffix
    );

    // Level 2: suff omitted -> default is Tab per section 17.9.28
    assert_eq!(
        level2.suffix,
        stemma::numbering::LevelSuffix::Tab,
        "ECMA-376 section 17.9.28: omitted suff should default to Tab, but suffix field is {:?}",
        level2.suffix
    );
}

/// Direct unit test verifying the LevelSuffix::separator() method returns
/// the correct string for each variant.
#[test]
fn bug1_unit_suffix_separator_strings() {
    assert_eq!(
        stemma::numbering::LevelSuffix::Tab.separator(),
        "\t",
        "Tab suffix separator should be a tab character"
    );
    assert_eq!(
        stemma::numbering::LevelSuffix::Space.separator(),
        " ",
        "Space suffix separator should be a single space"
    );
    assert_eq!(
        stemma::numbering::LevelSuffix::Nothing.separator(),
        "",
        "Nothing suffix separator should be empty"
    );
}

/// Direct unit test verifying start defaults to 0 when w:start is omitted.
#[test]
fn bug3_unit_start_defaults_to_zero() {
    let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="0">
    <w:lvl w:ilvl="0">
      <w:numFmt w:val="decimal"/>
      <w:lvlText w:val="%1."/>
    </w:lvl>
  </w:abstractNum>
  <w:num w:numId="1">
    <w:abstractNumId w:val="0"/>
  </w:num>
</w:numbering>"#;

    let defs = stemma::numbering::NumberingDefinitions::parse(xml.as_bytes())
        .expect("should parse numbering XML");

    let level0 = defs.get_level(1, 0).expect("should find level 0");
    assert_eq!(
        level0.start, 0,
        "ECMA-376 section 17.9.25: when w:start is omitted, start should default to 0. \
         Got {}. The spec says: 'If this element is omitted, then the starting value \
         shall be zero (0).'",
        level0.start
    );
}

/// Direct unit test verifying numStyleLink chain resolution in
/// NumberingDefinitions::get_level().
#[test]
fn bug4_unit_num_style_link_get_level() {
    let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="0">
    <w:numStyleLink w:val="MyOutline"/>
  </w:abstractNum>
  <w:abstractNum w:abstractNumId="1">
    <w:styleLink w:val="MyOutline"/>
    <w:lvl w:ilvl="0">
      <w:start w:val="1"/>
      <w:numFmt w:val="upperRoman"/>
      <w:lvlText w:val="%1."/>
    </w:lvl>
    <w:lvl w:ilvl="1">
      <w:start w:val="1"/>
      <w:numFmt w:val="lowerLetter"/>
      <w:lvlText w:val="%2)"/>
    </w:lvl>
  </w:abstractNum>
  <w:num w:numId="1">
    <w:abstractNumId w:val="0"/>
  </w:num>
</w:numbering>"#;

    let defs = stemma::numbering::NumberingDefinitions::parse(xml.as_bytes())
        .expect("should parse numbering XML");

    // numId=1 -> abstractNum 0 (has numStyleLink, no levels)
    // Should follow chain to abstractNum 1 (has styleLink="MyOutline")
    let level0 = defs.get_level(1, 0);
    assert!(
        level0.is_some(),
        "ECMA-376 section 17.9.21: get_level(1, 0) should follow numStyleLink chain \
         from abstractNum 0 to abstractNum 1 and find level 0. Got None."
    );
    let level0 = level0.unwrap();
    assert_eq!(
        level0.num_fmt,
        stemma::numbering::NumFormat::UpperRoman,
        "Level 0 from chain should have upperRoman format, got {:?}",
        level0.num_fmt
    );

    let level1 = defs.get_level(1, 1);
    assert!(
        level1.is_some(),
        "ECMA-376 section 17.9.21: get_level(1, 1) should follow numStyleLink chain \
         and find level 1. Got None."
    );
    let level1 = level1.unwrap();
    assert_eq!(
        level1.num_fmt,
        stemma::numbering::NumFormat::LowerLetter,
        "Level 1 from chain should have lowerLetter format, got {:?}",
        level1.num_fmt
    );
}
