//! Spec-compliance tests: Table Borders (ISO 29500-1 §17.4.66, MS-OI29500 §17.4.66(a))
//!
//! These tests verify table border cascade, conflict resolution, and nil/none
//! semantics against the OOXML specification. Tests that FAIL expose real bugs
//! in our implementation.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, Border, BorderStyle, CanonDoc};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-borders-spec";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

fn cell_border_top(table: &stemma::TableNode, row: usize, col: usize) -> Option<&Border> {
    table.rows[row].cells[col]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.top.as_ref())
}

fn cell_border_bottom(table: &stemma::TableNode, row: usize, col: usize) -> Option<&Border> {
    table.rows[row].cells[col]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.bottom.as_ref())
}

fn cell_border_left(table: &stemma::TableNode, row: usize, col: usize) -> Option<&Border> {
    table.rows[row].cells[col]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
}

fn cell_border_right(table: &stemma::TableNode, row: usize, col: usize) -> Option<&Border> {
    table.rows[row].cells[col]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
}

// =============================================================================
// Test 1: 3x3 table — insideH/insideV cascade to all 9 cell positions
// ISO 29500-1 §17.4.66 + §17.4.38
// =============================================================================

/// ISO 29500-1 §17.4.66: Corner cell (0,0) should get outer borders on
/// top and left, insideH on bottom, insideV on right.
///
/// tblBorders: outer=double blue sz=24, insideH=single red sz=12,
/// insideV=single green sz=8.
#[test]
fn spec_3x3_corner_cell_00_gets_correct_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "3x3-inside-borders");
    let table = first_table(&doc);

    // Verify table-level borders are parsed
    let tbl_borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have tblBorders");
    assert_eq!(
        tbl_borders.top.as_ref().unwrap().style,
        BorderStyle::Double,
        "table outer border should be double"
    );
    assert_eq!(
        tbl_borders.inside_h.as_ref().unwrap().color.as_deref(),
        Some("FF0000"),
        "table insideH should be red"
    );
    assert_eq!(
        tbl_borders.inside_v.as_ref().unwrap().color.as_deref(),
        Some("00FF00"),
        "table insideV should be green"
    );

    // Cell (0,0): top-left corner
    let top = cell_border_top(table, 0, 0)
        .expect("cell (0,0) should have top border from table outer top");
    assert_eq!(
        top.style,
        BorderStyle::Double,
        "cell (0,0) top should be double (from table outer top)"
    );
    assert_eq!(
        top.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) top should be blue (from table outer top)"
    );

    let left = cell_border_left(table, 0, 0)
        .expect("cell (0,0) should have left border from table outer left");
    assert_eq!(
        left.style,
        BorderStyle::Double,
        "cell (0,0) left should be double (from table outer left)"
    );
    assert_eq!(
        left.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) left should be blue (from table outer left)"
    );

    let bottom =
        cell_border_bottom(table, 0, 0).expect("cell (0,0) should have bottom border from insideH");
    assert_eq!(
        bottom.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) bottom should be red (from insideH, not outer bottom) — \
         §17.4.66: non-bottom-row cells use insideH for bottom border"
    );

    let right =
        cell_border_right(table, 0, 0).expect("cell (0,0) should have right border from insideV");
    assert_eq!(
        right.color.as_deref(),
        Some("00FF00"),
        "cell (0,0) right should be green (from insideV, not outer right) — \
         §17.4.66: non-rightmost cells use insideV for right border"
    );
}

/// ISO 29500-1 §17.4.66: True interior cell (1,1) in a 3x3 table should
/// get insideH on both top and bottom, insideV on both left and right.
/// No outer borders should appear on an interior cell.
#[test]
fn spec_3x3_interior_cell_11_uses_only_inside_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "3x3-inside-borders");
    let table = first_table(&doc);

    // Cell (1,1): true interior — all four edges from inside borders
    let top = cell_border_top(table, 1, 1).expect("cell (1,1) should have top border from insideH");
    assert_eq!(
        top.color.as_deref(),
        Some("FF0000"),
        "cell (1,1) top should be red (from insideH) — \
         §17.4.66: interior cell top uses insideH"
    );
    assert_eq!(
        top.size,
        Some(12),
        "cell (1,1) top size should be 12 (from insideH)"
    );

    let bottom =
        cell_border_bottom(table, 1, 1).expect("cell (1,1) should have bottom border from insideH");
    assert_eq!(
        bottom.color.as_deref(),
        Some("FF0000"),
        "cell (1,1) bottom should be red (from insideH)"
    );

    let left =
        cell_border_left(table, 1, 1).expect("cell (1,1) should have left border from insideV");
    assert_eq!(
        left.color.as_deref(),
        Some("00FF00"),
        "cell (1,1) left should be green (from insideV) — \
         §17.4.66: interior cell left uses insideV"
    );
    assert_eq!(
        left.size,
        Some(8),
        "cell (1,1) left size should be 8 (from insideV)"
    );

    let right =
        cell_border_right(table, 1, 1).expect("cell (1,1) should have right border from insideV");
    assert_eq!(
        right.color.as_deref(),
        Some("00FF00"),
        "cell (1,1) right should be green (from insideV)"
    );
}

/// ISO 29500-1 §17.4.66: Bottom-right corner cell (2,2) should get
/// insideH on top, outer bottom on bottom, insideV on left, outer right on right.
#[test]
fn spec_3x3_corner_cell_22_bottom_right() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "3x3-inside-borders");
    let table = first_table(&doc);

    let top = cell_border_top(table, 2, 2).expect("cell (2,2) should have top border from insideH");
    assert_eq!(
        top.color.as_deref(),
        Some("FF0000"),
        "cell (2,2) top should be red (from insideH)"
    );

    let bottom = cell_border_bottom(table, 2, 2)
        .expect("cell (2,2) should have bottom border from outer bottom");
    assert_eq!(
        bottom.style,
        BorderStyle::Double,
        "cell (2,2) bottom should be double (from table outer bottom)"
    );
    assert_eq!(
        bottom.color.as_deref(),
        Some("0000FF"),
        "cell (2,2) bottom should be blue (from table outer bottom)"
    );

    let left =
        cell_border_left(table, 2, 2).expect("cell (2,2) should have left border from insideV");
    assert_eq!(
        left.color.as_deref(),
        Some("00FF00"),
        "cell (2,2) left should be green (from insideV)"
    );

    let right = cell_border_right(table, 2, 2)
        .expect("cell (2,2) should have right border from outer right");
    assert_eq!(
        right.style,
        BorderStyle::Double,
        "cell (2,2) right should be double (from table outer right)"
    );
    assert_eq!(
        right.color.as_deref(),
        Some("0000FF"),
        "cell (2,2) right should be blue (from table outer right)"
    );
}

// =============================================================================
// Test 2: nil border suppresses table border
// MS-OI29500 §17.4.66(a)
// =============================================================================

/// Verifies MS-OI29500 §17.4.66(a): 'If the conflicting table cell border is
/// nil, then no border shall be displayed.'
///
/// Cell (0,0) has tcBorders with top=nil. Table has single red sz=12 top.
/// The nil cell border suppresses the table border entirely.
/// After import, cell (0,0) top should be Nil (or absent).
#[test]
fn spec_nil_border_suppresses_table_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nil-border-suppresses-table");
    let table = first_table(&doc);

    // Verify table-level borders exist
    let tbl_borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have tblBorders");
    assert!(tbl_borders.top.is_some(), "table should have top border");

    // Cell (0,0) top: should be nil (border suppressed)
    let cell_00_borders = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have a borders struct");

    // Per MS-OI29500: nil means "no border shall be displayed".
    // The cell border with nil should suppress the table border.
    // We accept either: top is None (border removed) or top.style == Nil.
    match &cell_00_borders.top {
        None => {
            // Acceptable: nil border resolved to no border
        }
        Some(border) => {
            assert_eq!(
                border.style,
                BorderStyle::Nil,
                "cell (0,0) top border should be Nil (suppressed) — \
                 MS-OI29500 §17.4.66(a): 'If the conflicting table cell border is nil, \
                 then no border shall be displayed.' \
                 Got style {:?} instead, which means the table border leaked through",
                border.style
            );
        }
    }

    // Cell (0,0) other edges should still inherit from table borders
    // (left from table.left, bottom from table.insideH, right from table.insideV)
    let left = cell_border_left(table, 0, 0);
    assert!(
        left.is_some(),
        "cell (0,0) left should inherit from table left border — \
         only the top edge was set to nil"
    );

    // Cell (0,1) should be completely unaffected — all borders from table
    let cell_01_top = cell_border_top(table, 0, 1);
    assert!(
        cell_01_top.is_some(),
        "cell (0,1) top should inherit from table top border (unaffected by cell (0,0) nil)"
    );
    assert_eq!(
        cell_01_top.unwrap().color.as_deref(),
        Some("FF0000"),
        "cell (0,1) top should be red (from table border)"
    );
}

// =============================================================================
// Test 3: none border yields to opposing table border
// MS-OI29500 §17.4.66(a)
// =============================================================================

/// Verifies MS-OI29500 §17.4.66(a): 'If the conflicting table cell border is
/// none (no border), then the opposing border shall be displayed.'
///
/// Cell (0,0) has tcBorders with top=none. Table has single red sz=12 top.
/// The 'none' cell border means "I have no cell border" — the opposing
/// (table) border wins and is displayed.
#[test]
fn spec_none_border_yields_to_table_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "none-border-yields-to-table");
    let table = first_table(&doc);

    // Table border: single red sz=12
    let tbl_top = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have borders")
        .top
        .as_ref()
        .expect("table should have top border");
    assert_eq!(tbl_top.color.as_deref(), Some("FF0000"));
    assert_eq!(tbl_top.size, Some(12));

    // Cell (0,0) top: has tcBorders top=none.
    // Per MS-OI29500 §17.4.66(a): "If the conflicting table cell border is
    // none (no border), then the opposing border shall be displayed."
    //
    // This means the TABLE border (red single sz=12) should be displayed,
    // NOT the cell's "none" border.
    let cell_00_top = cell_border_top(table, 0, 0).expect(
        "cell (0,0) should have a top border — \
                 the table border should win over the cell's 'none' border per MS-OI29500",
    );

    // The winning border should be the table border (red single sz=12)
    assert_eq!(
        cell_00_top.style,
        BorderStyle::Single,
        "cell (0,0) top should be Single (from table border) — \
         MS-OI29500 §17.4.66(a): 'none' cell border yields to opposing table border. \
         Got {:?} instead.",
        cell_00_top.style
    );
    assert_eq!(
        cell_00_top.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) top should be red (from table border) — \
         MS-OI29500: 'none' means 'no cell border', so table border wins"
    );
    assert_eq!(
        cell_00_top.size,
        Some(12),
        "cell (0,0) top size should be 12 (from table border)"
    );
}

// =============================================================================
// Test 4: Dashed border weight = 1 regardless of size
// MS-OI29500 §17.4.66(a)
// =============================================================================

/// Verifies MS-OI29500 §17.4.66(a): 'The borders with dotted and dashed styles
/// shall be assigned the weight 1 regardless of the border width and number.'
///
/// Cell (0,0) right = dashed sz=48 red. Cell (0,1) left = single sz=4 blue.
///
/// Correct weight calculation:
///   dashed sz=48: weight = 1 (per MS-OI29500, dashed always gets weight 1)
///   single sz=4:  weight = 4 * 1 = 4
///
/// Single sz=4 (weight=4) beats dashed sz=48 (weight=1).
#[test]
fn spec_dashed_border_gets_weight_1_regardless_of_size() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "adjacent-dashed-weight");
    let table = first_table(&doc);

    // Verify the raw cell borders are parsed correctly
    let cell_00_right =
        cell_border_right(table, 0, 0).expect("cell (0,0) should have a right border");
    let cell_01_left = cell_border_left(table, 0, 1).expect("cell (0,1) should have a left border");

    // After adjacent conflict resolution:
    // dashed sz=48 red: weight = 1 (per MS-OI29500 rule)
    // single sz=4 blue: weight = 4 * 1 = 4
    // Winner: single sz=4 blue (weight 4 > 1)
    //
    // Both shared edges should show the winning border.
    assert_eq!(
        cell_01_left.style,
        BorderStyle::Single,
        "cell (0,1) left should be Single (winner) — \
         MS-OI29500 §17.4.66(a): dashed gets weight=1 regardless of size, \
         so single sz=4 (weight=4) beats dashed sz=48 (weight=1). Got {:?}.",
        cell_01_left.style
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("0000FF"),
        "cell (0,1) left should be blue (from winning single border)"
    );
    assert_eq!(
        cell_01_left.size,
        Some(4),
        "cell (0,1) left size should be 4 (from winning single border)"
    );

    // cell (0,0) right should also show the winner (both sides of shared edge agree)
    assert_eq!(
        cell_00_right.style,
        BorderStyle::Single,
        "cell (0,0) right should be Single (winner) — \
         both sides of the shared edge should show the winning border"
    );
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) right should be blue (from winning single border)"
    );
}

// =============================================================================
// Test 5: Cell border overrides table border regardless of weight
// ISO 29500-1 §17.4.38
// =============================================================================

/// MS-OI29500 §2.1.169: Cell border vs table border conflict resolution.
///
/// Per MS implementation, weight-based resolution applies to all border
/// conflicts, including cell-vs-table at table edges (not just adjacent cells).
///
/// Table: double blue sz=48 (weight = 48 * 3 = 144)
/// Cell (0,0): single green sz=4 (weight = 4 * 1 = 4)
///
/// Since the table border is heavier, it wins on all edges of cell (0,0).
/// This overrides the base ISO 29500-1 §17.4.66 rule 6 ("cell always wins")
/// with the MS behavior where weight determines the winner.
#[test]
fn spec_cell_border_overrides_table_border_at_table_edge() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-override-lower-weight");
    let table = first_table(&doc);

    // Table borders: double blue sz=48
    let tbl_top = table
        .formatting
        .borders
        .as_ref()
        .unwrap()
        .top
        .as_ref()
        .unwrap();
    assert_eq!(tbl_top.style, BorderStyle::Double);
    assert_eq!(tbl_top.size, Some(48));

    // Cell (0,0): single green sz=4 (weight=4) vs table double blue sz=48 (weight=144).
    // MS-OI29500 §2.1.169: table border wins by weight on all edges.
    let top = cell_border_top(table, 0, 0).expect("cell (0,0) should have a top border");
    assert_eq!(
        top.style,
        BorderStyle::Double,
        "cell (0,0) top: table double (weight=144) beats cell single (weight=4)"
    );
    assert_eq!(
        top.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) top: table blue wins by weight"
    );
    assert_eq!(
        top.size,
        Some(48),
        "cell (0,0) top: table sz=48 wins by weight"
    );

    let left = cell_border_left(table, 0, 0).expect("cell (0,0) should have a left border");
    assert_eq!(
        left.style,
        BorderStyle::Double,
        "cell (0,0) left: table double wins by weight"
    );
    assert_eq!(
        left.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) left: table blue wins by weight"
    );

    // Shared edges resolve the same way (table border wins everywhere).
    let bottom = cell_border_bottom(table, 0, 0).expect("cell (0,0) should have a bottom border");
    assert_eq!(
        bottom.style,
        BorderStyle::Double,
        "cell (0,0) bottom: table double wins by weight"
    );
    assert_eq!(
        bottom.color.as_deref(),
        Some("0000FF"),
        "cell (0,0) bottom: table blue wins by weight"
    );

    // Cell (0,1): no tcBorders — should get table borders cascaded
    let cell_01_top =
        cell_border_top(table, 0, 1).expect("cell (0,1) should have top border from table");
    assert_eq!(
        cell_01_top.style,
        BorderStyle::Double,
        "cell (0,1) top should be Double (from table border, no cell override)"
    );
    assert_eq!(
        cell_01_top.color.as_deref(),
        Some("0000FF"),
        "cell (0,1) top should be blue (from table border)"
    );
}

// =============================================================================
// Test 6: Empty tblBorders element
// ISO 29500-1 §17.4.38
// =============================================================================

/// ISO 29500-1 §17.4.38: When tblBorders is present but has no child
/// elements, no borders are defined at the table level. Cells should
/// have no inherited borders.
///
/// A present-but-empty <w:tblBorders/> is semantically different from
/// an omitted tblBorders element (which falls back to the table style).
#[test]
fn spec_empty_tbl_borders_means_no_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "empty-tbl-borders");
    let table = first_table(&doc);

    // The table has an empty tblBorders element. After parsing, the
    // BorderSet should exist but have all edges as None.
    let tbl_borders = table.formatting.borders.as_ref();

    if let Some(borders) = tbl_borders {
        // If the BorderSet is present, all edges should be None
        assert!(
            borders.top.is_none(),
            "empty tblBorders: table top border should be None"
        );
        assert!(
            borders.bottom.is_none(),
            "empty tblBorders: table bottom border should be None"
        );
        assert!(
            borders.left.is_none(),
            "empty tblBorders: table left border should be None"
        );
        assert!(
            borders.right.is_none(),
            "empty tblBorders: table right border should be None"
        );
        assert!(
            borders.inside_h.is_none(),
            "empty tblBorders: table insideH border should be None"
        );
        assert!(
            borders.inside_v.is_none(),
            "empty tblBorders: table insideV border should be None"
        );
    }
    // If tbl_borders is None, that's also acceptable — empty element
    // is equivalent to "no borders defined"

    // Cells should have no borders since there's nothing to inherit
    for row_idx in 0..2 {
        for col_idx in 0..2 {
            let cell_borders = table.rows[row_idx].cells[col_idx]
                .formatting
                .borders
                .as_ref();

            // Cell borders should either be None or have all-None edges
            if let Some(borders) = cell_borders {
                let has_any = borders.top.is_some()
                    || borders.bottom.is_some()
                    || borders.left.is_some()
                    || borders.right.is_some();
                assert!(
                    !has_any,
                    "cell ({row_idx},{col_idx}) should have no borders — \
                     empty tblBorders defines no borders to inherit. \
                     Got: top={:?}, bottom={:?}, left={:?}, right={:?}",
                    borders.top.as_ref().map(|b| &b.style),
                    borders.bottom.as_ref().map(|b| &b.style),
                    borders.left.as_ref().map(|b| &b.style),
                    borders.right.as_ref().map(|b| &b.style)
                );
            }
        }
    }
}
