//! Spec-compliance tests: Tracked Change Serialization Invariants
//!
//! These tests verify that the DOCX our redline engine PRODUCES meets Word's
//! structural requirements for tracked changes. The approach: create two DOCX
//! files (old/new), run `diff_and_redline`, export, then parse the resulting
//! DOCX XML and assert on structural properties.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/tracked-change-serialization/create_docs.py`.

use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::{Cursor, Read};

use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
use xmltree::{Element, XMLNode};
use zip::ZipArchive;

const FIXTURES: &str = "testdata/spec-compliance/tracked-change-serialization";

// ── helpers ──────────────────────────────────────────────────────────────

/// Run diff_and_redline on a before/after DOCX pair, export as Redline, return raw bytes.
fn redline_export(before_path: &str, after_path: &str) -> Vec<u8> {
    let before = fs::read(before_path).unwrap_or_else(|e| panic!("read {before_path}: {e}"));
    let after = fs::read(after_path).unwrap_or_else(|e| panic!("read {after_path}: {e}"));

    let runtime = SimpleRuntime::new();
    let ib = runtime.import_docx(&before).expect("import before");
    let ia = runtime.import_docx(&after).expect("import after");

    let meta = TransactionMeta {
        author: "spec_tracked_change_serialization".to_string(),
        reason: Some("tracked-change-serialization spec test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&ib.doc_handle, &ia.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");

    runtime
        .export_docx(&ib.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

/// Extract word/document.xml from a DOCX byte buffer.
fn extract_document_xml(docx_bytes: &[u8]) -> String {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("DOCX must contain word/document.xml");
    let mut out = String::new();
    file.read_to_string(&mut out)
        .expect("read word/document.xml");
    out
}

/// Try to extract word/comments.xml from a DOCX byte buffer.
/// Returns None if the part does not exist.
fn extract_comments_xml(docx_bytes: &[u8]) -> Option<String> {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = match zip.by_name("word/comments.xml") {
        Ok(f) => f,
        Err(_) => return None,
    };
    let mut out = String::new();
    file.read_to_string(&mut out)
        .expect("read word/comments.xml");
    Some(out)
}

fn parse_xml(xml: &str) -> Element {
    Element::parse(Cursor::new(xml.as_bytes())).expect("parse XML")
}

fn local_name(name: &str) -> &str {
    match name.rsplit_once(':') {
        Some((_, local)) => local,
        None => name,
    }
}

/// Check whether an element matches a w: tag by local name.
fn is_w_tag(element: &Element, local: &str) -> bool {
    let name = local_name(&element.name);
    if name != local {
        return false;
    }
    if element.prefix.as_deref() == Some("w") {
        return true;
    }
    if element
        .namespace
        .as_deref()
        .is_some_and(|ns| ns == "http://schemas.openxmlformats.org/wordprocessingml/2006/main")
    {
        return true;
    }
    element.name == local || element.name == format!("w:{local}")
}

/// Get an attribute value, trying both prefixed and unprefixed forms.
fn attr_value<'a>(element: &'a Element, qname: &str) -> Option<&'a str> {
    let (_prefix, local) = match qname.split_once(':') {
        Some((p, l)) if !p.is_empty() && !l.is_empty() => (Some(p), l),
        _ => (None, qname),
    };

    // Try matching by local name
    for (name, value) in &element.attributes {
        if name.local_name == local {
            return Some(value);
        }
    }

    // Try matching by full qname
    for (name, value) in &element.attributes {
        if name.local_name == qname {
            return Some(value);
        }
    }

    None
}

/// Find all elements with a given local tag name, recursively.
fn find_all_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if local_name(&root.name) == tag {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_elements(el, tag, out);
        }
    }
}

/// Find all elements matching a w: tag, recursively.
fn find_all_w_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if is_w_tag(root, tag) {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_w_elements(el, tag, out);
        }
    }
}

/// Check if any element with `child_tag` (by local name) appears as a
/// descendant of any element with `parent_tag` (by local name).
/// Returns the first offending path found, or None if the structure is clean.
fn find_nested_same_type(root: &Element, tag: &str) -> Option<String> {
    fn walk(el: &Element, tag: &str, inside_parent: bool, path: &str) -> Option<String> {
        let name = local_name(&el.name);
        let current_path = format!("{}/{}", path, el.name);

        if name == tag {
            if inside_parent {
                // We're inside a parent with the same tag -- illegal nesting.
                return Some(current_path);
            }
            // Start tracking: we're now inside a `tag` element.
            for child in &el.children {
                if let XMLNode::Element(child_el) = child
                    && let Some(found) = walk(child_el, tag, true, &current_path)
                {
                    return Some(found);
                }
            }
            return None;
        }

        // Not the target tag -- keep searching children.
        for child in &el.children {
            if let XMLNode::Element(child_el) = child
                && let Some(found) = walk(child_el, tag, inside_parent, &current_path)
            {
                return Some(found);
            }
        }
        None
    }

    walk(root, tag, false, "")
}

/// Check whether any `w:t` element appears inside a `w:del` container.
/// Returns the first offending path found, or None.
fn find_t_inside_del(root: &Element) -> Option<String> {
    fn search(el: &Element, inside_del: bool, path: &str) -> Option<String> {
        let name = local_name(&el.name);
        let current_path = format!("{}/{}", path, el.name);

        let now_inside_del = inside_del || name == "del";

        // Check for w:t (not w:delText) inside w:del
        if now_inside_del && name == "t" {
            // Verify this is actually a w:t text element (not some other namespace)
            let is_w_t = el.prefix.as_deref() == Some("w")
                || el.namespace.as_deref().is_some_and(|ns| {
                    ns == "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
                })
                || el.name == "t"
                || el.name == "w:t";

            if is_w_t {
                return Some(current_path);
            }
        }

        for child in &el.children {
            if let XMLNode::Element(child_el) = child
                && let Some(found) = search(child_el, now_inside_del, &current_path)
            {
                return Some(found);
            }
        }
        None
    }

    search(root, false, "")
}

/// Check whether `w:delText` exists inside `w:del` containers.
fn has_deltext_inside_del(root: &Element) -> bool {
    fn search(el: &Element, inside_del: bool) -> bool {
        let name = local_name(&el.name);
        let now_inside_del = inside_del || name == "del";

        if now_inside_del && name == "delText" {
            return true;
        }

        for child in &el.children {
            if let XMLNode::Element(child_el) = child
                && search(child_el, now_inside_del)
            {
                return true;
            }
        }
        false
    }

    search(root, false)
}

/// Collect all `w:id` attribute values from tracked change elements.
fn collect_annotation_ids(root: &Element, out: &mut Vec<(String, String)>) {
    let name = local_name(&root.name);

    // Tracked change elements that carry w:id
    let is_tracked_change = matches!(
        name,
        "ins"
            | "del"
            | "moveFrom"
            | "moveTo"
            | "rPrChange"
            | "pPrChange"
            | "sectPrChange"
            | "tblPrChange"
            | "trPrChange"
            | "tcPrChange"
            | "cellIns"
            | "cellDel"
            | "moveFromRangeStart"
            | "moveFromRangeEnd"
            | "moveToRangeStart"
            | "moveToRangeEnd"
            | "bookmarkStart"
            | "bookmarkEnd"
            | "commentRangeStart"
            | "commentRangeEnd"
    );

    if is_tracked_change && let Some(id) = attr_value(root, "w:id") {
        out.push((name.to_string(), id.to_string()));
    }

    for child in &root.children {
        if let XMLNode::Element(el) = child {
            collect_annotation_ids(el, out);
        }
    }
}

// =========================================================================
// Test 1: w:del must use w:delText, not w:t
// ECMA-376 §17.3.3.7
// =========================================================================

/// ECMA-376 §17.3.3.7: Inside `w:del`, text must use `w:delText`, not `w:t`.
///
/// Create old.docx with "Hello World", new.docx with "Hello" (delete " World").
/// The redline output must use w:delText for the deleted text, and must NOT
/// have any w:t elements inside w:del containers.
#[test]
fn spec_serialized_del_uses_deltext_not_t() {
    let before_path = format!("{FIXTURES}/del-uses-deltext/before.docx");
    let after_path = format!("{FIXTURES}/del-uses-deltext/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // First, verify there IS a w:del element (the diff produced a deletion)
    let mut del_elements = Vec::new();
    find_all_w_elements(&root, "del", &mut del_elements);
    assert!(
        !del_elements.is_empty(),
        "redline output should contain at least one w:del element for the deleted text"
    );

    // Assert: no w:t inside w:del
    if let Some(path) = find_t_inside_del(&root) {
        panic!(
            "ECMA-376 §17.3.3.7 violation: w:t found inside w:del. \
             Deleted text must use w:delText, not w:t.\nPath: {path}"
        );
    }

    // Assert: w:delText DOES exist inside w:del
    assert!(
        has_deltext_inside_del(&root),
        "w:del should contain w:delText elements for the deleted text, but none found"
    );
}

// =========================================================================
// Test 2: No nested w:ins inside w:ins or w:del inside w:del
// MS-OI29500 §2.1.330/§2.1.334
// =========================================================================

/// MS-OI29500 §2.1.330/§2.1.334: Word does not support nested `w:ins` inside
/// `w:ins` or `w:del` inside `w:del`.
///
/// Multiple text modifications across multiple paragraphs should produce
/// flat tracked change structures with no nesting of the same container type.
#[test]
fn spec_serialized_no_nested_ins_del() {
    let before_path = format!("{FIXTURES}/no-nested-ins-del/before.docx");
    let after_path = format!("{FIXTURES}/no-nested-ins-del/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Assert: no w:ins nested inside w:ins
    if let Some(path) = find_nested_same_type(&root, "ins") {
        panic!(
            "MS-OI29500 §2.1.330 violation: w:ins found nested inside w:ins. \
             Word does not support nested insertion containers.\nPath: {path}"
        );
    }

    // Assert: no w:del nested inside w:del
    if let Some(path) = find_nested_same_type(&root, "del") {
        panic!(
            "MS-OI29500 §2.1.334 violation: w:del found nested inside w:del. \
             Word does not support nested deletion containers.\nPath: {path}"
        );
    }

    // Verify the output actually contains tracked changes (the diff produced changes)
    let mut ins_elements = Vec::new();
    find_all_w_elements(&root, "ins", &mut ins_elements);
    let mut del_elements = Vec::new();
    find_all_w_elements(&root, "del", &mut del_elements);
    assert!(
        !ins_elements.is_empty() || !del_elements.is_empty(),
        "redline output should contain tracked changes (w:ins or w:del)"
    );
}

// =========================================================================
// Test 3: No revisions inside comments
// MS-OI29500 §2.1.313
// =========================================================================

/// MS-OI29500 §2.1.313: Word does not support revisions inside comments.
///
/// When text around a comment is changed, the redline engine must NOT wrap
/// comment content in w:del/w:ins elements.
#[test]
fn spec_serialized_no_revisions_in_comments() {
    let before_path = format!("{FIXTURES}/no-revisions-in-comments/before.docx");
    let after_path = format!("{FIXTURES}/no-revisions-in-comments/after.docx");
    let exported = redline_export(&before_path, &after_path);

    // Parse comments part if it exists
    let comments_xml = match extract_comments_xml(&exported) {
        Some(xml) => xml,
        None => {
            // If no comments.xml part, the constraint is trivially satisfied
            return;
        }
    };

    let comments_root = parse_xml(&comments_xml);

    // Find all w:comment elements
    let mut comment_elements = Vec::new();
    find_all_w_elements(&comments_root, "comment", &mut comment_elements);

    // Inside each comment, there should be no w:ins or w:del
    for comment in &comment_elements {
        let comment_id = attr_value(comment, "w:id").unwrap_or("?");

        let mut ins_inside = Vec::new();
        find_all_w_elements(comment, "ins", &mut ins_inside);
        assert!(
            ins_inside.is_empty(),
            "MS-OI29500 §2.1.313 violation: w:ins found inside w:comment (id={comment_id}). \
             Word does not support revisions inside comments."
        );

        let mut del_inside = Vec::new();
        find_all_w_elements(comment, "del", &mut del_inside);
        assert!(
            del_inside.is_empty(),
            "MS-OI29500 §2.1.313 violation: w:del found inside w:comment (id={comment_id}). \
             Word does not support revisions inside comments."
        );
    }
}

// =========================================================================
// Test 4: Flat tracked changes structure (cross-cutting rule)
// =========================================================================

/// Cross-cutting rule: All run-level tracked change containers must be flat
/// (no nesting of same type).
///
/// Complex multi-edit scenario across a document. Asserts flat structure for
/// all tracked change container types: ins, del, moveFrom, moveTo.
#[test]
fn spec_serialized_flat_tracked_changes_structure() {
    let before_path = format!("{FIXTURES}/flat-tracked-changes/before.docx");
    let after_path = format!("{FIXTURES}/flat-tracked-changes/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Check all tracked change container types for nesting
    for tag in ["ins", "del", "moveFrom", "moveTo"] {
        if let Some(path) = find_nested_same_type(&root, tag) {
            panic!(
                "Flat structure violation: w:{tag} found nested inside w:{tag}. \
                 All tracked change containers must be flat (no same-type nesting).\nPath: {path}"
            );
        }
    }

    // Verify the output actually has some tracked changes
    let mut ins_elements = Vec::new();
    find_all_w_elements(&root, "ins", &mut ins_elements);
    let mut del_elements = Vec::new();
    find_all_w_elements(&root, "del", &mut del_elements);
    assert!(
        !ins_elements.is_empty() || !del_elements.is_empty(),
        "redline output should contain tracked changes"
    );
}

// =========================================================================
// Test 5: Move ranges are properly paired
// ECMA-376 §17.13.5.23-28
// =========================================================================

/// ECMA-376 §17.13.5.23-28: Every moveFromRangeStart must have a matching
/// moveFromRangeEnd (same w:id), and every moveToRangeStart must have a
/// matching moveToRangeEnd (same w:id). Source and destination are linked
/// by matching w:name attributes.
///
/// Scenario: Move paragraph B after C — (A, B, C) -> (A, C, B).
#[test]
fn spec_serialized_move_ranges_paired() {
    let before_path = format!("{FIXTURES}/move-ranges-paired/before.docx");
    let after_path = format!("{FIXTURES}/move-ranges-paired/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Collect all move range elements
    let mut move_from_starts = Vec::new();
    find_all_elements(&root, "moveFromRangeStart", &mut move_from_starts);
    let mut move_from_ends = Vec::new();
    find_all_elements(&root, "moveFromRangeEnd", &mut move_from_ends);
    let mut move_to_starts = Vec::new();
    find_all_elements(&root, "moveToRangeStart", &mut move_to_starts);
    let mut move_to_ends = Vec::new();
    find_all_elements(&root, "moveToRangeEnd", &mut move_to_ends);

    // If the diff engine does not produce moves (uses del+ins instead),
    // this test is trivially satisfied — no unpaired ranges.
    let has_any_move = !move_from_starts.is_empty()
        || !move_from_ends.is_empty()
        || !move_to_starts.is_empty()
        || !move_to_ends.is_empty();

    if !has_any_move {
        // The diff engine chose del+ins instead of move. This is valid but
        // means we can't test move range pairing. Verify del+ins are present.
        let mut del_elements = Vec::new();
        find_all_w_elements(&root, "del", &mut del_elements);
        let mut ins_elements = Vec::new();
        find_all_w_elements(&root, "ins", &mut ins_elements);
        assert!(
            !del_elements.is_empty() || !ins_elements.is_empty(),
            "paragraph move should produce either move ranges or del+ins tracked changes"
        );
        return;
    }

    // Every moveFromRangeStart must have a matching moveFromRangeEnd by w:id
    let from_start_ids: HashMap<&str, &Element> = move_from_starts
        .iter()
        .filter_map(|el| attr_value(el, "w:id").map(|id| (id, *el)))
        .collect();
    let from_end_ids: HashSet<&str> = move_from_ends
        .iter()
        .filter_map(|el| attr_value(el, "w:id"))
        .collect();

    for id in from_start_ids.keys() {
        assert!(
            from_end_ids.contains(id),
            "ECMA-376 §17.13.5.23: moveFromRangeStart with w:id={id} has no matching \
             moveFromRangeEnd"
        );
    }

    // Every moveToRangeStart must have a matching moveToRangeEnd by w:id
    let to_start_ids: HashMap<&str, &Element> = move_to_starts
        .iter()
        .filter_map(|el| attr_value(el, "w:id").map(|id| (id, *el)))
        .collect();
    let to_end_ids: HashSet<&str> = move_to_ends
        .iter()
        .filter_map(|el| attr_value(el, "w:id"))
        .collect();

    for id in to_start_ids.keys() {
        assert!(
            to_end_ids.contains(id),
            "ECMA-376 §17.13.5.25: moveToRangeStart with w:id={id} has no matching \
             moveToRangeEnd"
        );
    }

    // Source and destination should be linked by w:name
    let from_names: HashSet<&str> = move_from_starts
        .iter()
        .filter_map(|el| attr_value(el, "w:name"))
        .collect();
    let to_names: HashSet<&str> = move_to_starts
        .iter()
        .filter_map(|el| attr_value(el, "w:name"))
        .collect();

    for name in &from_names {
        assert!(
            to_names.contains(name),
            "ECMA-376 §17.13.5.23/25: moveFromRangeStart with w:name={name} has no matching \
             moveToRangeStart with the same name"
        );
    }

    for name in &to_names {
        assert!(
            from_names.contains(name),
            "ECMA-376 §17.13.5.25/23: moveToRangeStart with w:name={name} has no matching \
             moveFromRangeStart with the same name"
        );
    }
}

// =========================================================================
// Test 6: Revision IDs are unique
// ECMA-376 §17.13.5
// =========================================================================

/// ECMA-376 §17.13.5: Every annotation id must be unique within the document.
///
/// Run diff_and_redline on a changed document with multiple edits. Collect all
/// w:id values from tracked change elements. Assert no duplicates.
#[test]
fn spec_serialized_revision_ids_unique() {
    let before_path = format!("{FIXTURES}/revision-ids-unique/before.docx");
    let after_path = format!("{FIXTURES}/revision-ids-unique/after.docx");
    let exported = redline_export(&before_path, &after_path);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut annotations = Vec::new();
    collect_annotation_ids(&root, &mut annotations);

    assert!(
        !annotations.is_empty(),
        "redline output should contain annotation elements with w:id attributes"
    );

    // Check for duplicates
    let mut seen: HashMap<String, String> = HashMap::new();
    for (element_type, id) in &annotations {
        if let Some(prev_type) = seen.get(id) {
            panic!(
                "ECMA-376 §17.13.5 violation: duplicate annotation w:id={id}. \
                 First seen on <w:{prev_type}>, duplicate on <w:{element_type}>. \
                 All annotation IDs must be unique within the document."
            );
        }
        seen.insert(id.clone(), element_type.clone());
    }
}
