//! Spec-compliance tests: Paragraph property cascade edge cases
//!
//! These tests verify correct paragraph property resolution through the
//! style chain:
//!
//! - pageBreakBefore resolved through style chain (§17.3.1.23)
//! - Paragraph shading resolved through style chain (§17.3.1.31)
//! - keepNext/keepLines w:val="0" correctly parsed as false (§17.3.1.15, §17.3.1.14)
//! - pageBreakBefore w:val="0" correctly parsed as false (§17.3.1.23)
//! - pageBreakBefore inherited through deep basedOn chain (§17.3.1.23 + §17.7.4.3)
//! - Tab stops through deep basedOn chain with clears (§17.3.1.38)
//! - Borders through basedOn chain — whole-element replacement (§17.3.1.24)
//! - contextualSpacing val="0" overrides style's true (§17.3.1.9)
//!
//! Fixture DOCX files generated by
//! `testdata/spec-compliance/style-cascade-ppr-edge/create_docs.py`.

use stemma::{TabAlignment, TabLeader};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade-ppr-edge";

// ── helpers ──────────────────────────────────────────────────────────────

fn find_para_by_text<'a>(
    paras: &[&'a stemma::ParagraphNode],
    needle: &str,
) -> &'a stemma::ParagraphNode {
    paras
        .iter()
        .find(|p| common::paragraph_text(p).contains(needle))
        .unwrap_or_else(|| panic!("should find paragraph containing {:?}", needle))
}

// ═══════════════════════════════════════════════════════════════════════════
// pageBreakBefore from style chain (§17.3.1.23)
//
// Verifies that page_break_before is correctly resolved through the style's
// basedOn chain, not just from direct pPr.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.23: Style "BreakBefore" defines pageBreakBefore.
/// A paragraph with no direct pPr but referencing that style should
/// inherit page_break_before=true.
#[test]
fn page_break_before_inherited_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-break-before-from-style");
    let paras = common::all_paragraphs(&doc);

    // Para 0: no style — should be false
    let p0 = find_para_by_text(&paras, "No style no break");
    assert!(
        !p0.page_break_before,
        "para 0 (no style) should have page_break_before=false"
    );

    // Para 1: BreakBefore style — should inherit page_break_before=true
    let p1 = find_para_by_text(&paras, "Break style applied");
    assert!(
        p1.page_break_before,
        "para 1 (BreakBefore style) should inherit page_break_before=true from style \
         per §17.3.1.23."
    );
}

/// §17.3.1.23: Style "BreakBefore" defines pageBreakBefore, but direct
/// formatting sets pageBreakBefore val="0". Direct should override style.
#[test]
fn page_break_before_direct_false_overrides_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-break-before-from-style");
    let paras = common::all_paragraphs(&doc);

    // Para 2: BreakBefore style + direct pageBreakBefore val="0"
    let p2 = find_para_by_text(&paras, "Break style with direct off");
    assert!(
        !p2.page_break_before,
        "para 2 (style on + direct val=0) should have page_break_before=false. \
         Direct val=0 correctly overrides style's true per §17.3.1.23."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Paragraph shading from style chain (§17.3.1.31)
//
// Verifies that paragraph shading is resolved through the style chain,
// including basedOn inheritance and direct override.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.31: Style "Shaded" defines pPr shading fill=FFFF00.
/// A paragraph using that style should inherit the shading.
#[test]
fn para_shading_inherited_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-shading-from-style");
    let paras = common::all_paragraphs(&doc);

    // Para 0: no style — no shading
    let p0 = find_para_by_text(&paras, "No style no shading");
    assert!(
        p0.shading.is_none(),
        "para 0 (no style) should have no shading"
    );

    // Para 1: Shaded style — should inherit shading fill=FFFF00
    let p1 = find_para_by_text(&paras, "Shaded style applied");
    let shading = p1.shading.as_ref().expect(
        "para 1 (Shaded style) should inherit paragraph shading from style \
         per §17.3.1.31.",
    );
    assert_eq!(
        shading.fill.as_deref(),
        Some("FFFF00"),
        "para 1 shading fill should be FFFF00 from Shaded style"
    );
}

/// §17.3.1.31: Style shading should be inherited through basedOn chain.
#[test]
fn para_shading_inherited_through_based_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-shading-from-style");
    let paras = common::all_paragraphs(&doc);

    // Para 2: ShadedChild (basedOn Shaded) — should inherit fill=FFFF00
    let p2 = find_para_by_text(&paras, "Shaded child style applied");
    let shading = p2.shading.as_ref().expect(
        "para 2 (ShadedChild style, basedOn Shaded) should inherit paragraph \
         shading through the basedOn chain.",
    );
    assert_eq!(
        shading.fill.as_deref(),
        Some("FFFF00"),
        "para 2 shading fill should be FFFF00 (inherited from Shaded via ShadedChild)"
    );
}

/// §17.3.1.31: Direct shading should override style shading.
#[test]
fn para_shading_direct_overrides_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-shading-from-style");
    let paras = common::all_paragraphs(&doc);

    // Para 3: Shaded style + direct shading fill=00FF00
    let p3 = find_para_by_text(&paras, "Shaded style with direct override");
    let shading = p3
        .shading
        .as_ref()
        .expect("para 3 should have shading from direct formatting");
    assert_eq!(
        shading.fill.as_deref(),
        Some("00FF00"),
        "para 3 shading fill should be 00FF00 from direct (overrides style's FFFF00)"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// keepNext w:val="0" parsing (§17.3.1.15)
//
// Verifies that <w:keepNext w:val="0"/> is correctly parsed as false,
// respecting the val attribute per §17.3.1.15.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.15: <w:keepNext w:val="0"/> should produce keep_next=false.
#[test]
fn keep_next_val_zero_is_false() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "keep-next-val-false");
    let paras = common::all_paragraphs(&doc);

    // Para 0: no keepNext — None (absent)
    let p0 = find_para_by_text(&paras, "No keep next");
    assert_eq!(
        p0.keep_next, None,
        "para 0 (no keepNext element) should have keep_next=None"
    );

    // Para 1: direct keepNext (no val) — Some(true)
    let p1 = find_para_by_text(&paras, "Direct keep next on");
    assert_eq!(
        p1.keep_next,
        Some(true),
        "para 1 (keepNext with no val) should have keep_next=Some(true)"
    );

    // Para 2: direct keepNext val="0" — Some(false)
    let p2 = find_para_by_text(&paras, "Direct keep next val zero");
    assert_eq!(
        p2.keep_next,
        Some(false),
        "para 2 (keepNext val=0) should have keep_next=Some(false) per §17.3.1.15."
    );
}

/// §17.3.1.15: Direct keepNext val="0" should override style's keepNext=true.
#[test]
fn keep_next_direct_false_overrides_style_true() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "keep-next-val-false");
    let paras = common::all_paragraphs(&doc);

    // Para 3: KeepStyle (keepNext=true) + direct keepNext val="0"
    let p3 = find_para_by_text(&paras, "Style on direct off");
    assert_eq!(
        p3.keep_next,
        Some(false),
        "para 3 (style keepNext=true + direct val=0) should have keep_next=Some(false). \
         The direct explicit false should override the style's true."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// keepLines w:val="0" parsing (§17.3.1.14)
//
// Verifies that <w:keepLines w:val="0"/> is correctly parsed as false per §17.3.1.14.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.14: <w:keepLines w:val="0"/> should produce keep_lines=false.
#[test]
fn keep_lines_val_zero_is_false() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "keep-lines-val-false");
    let paras = common::all_paragraphs(&doc);

    // Para 0: no keepLines — None (absent)
    let p0 = find_para_by_text(&paras, "No keep lines");
    assert_eq!(p0.keep_lines, None, "para 0 should have keep_lines=None");

    // Para 1: direct keepLines (no val) — Some(true)
    let p1 = find_para_by_text(&paras, "Direct keep lines on");
    assert_eq!(
        p1.keep_lines,
        Some(true),
        "para 1 should have keep_lines=Some(true)"
    );

    // Para 2: direct keepLines val="0" — Some(false)
    let p2 = find_para_by_text(&paras, "Direct keep lines val zero");
    assert_eq!(
        p2.keep_lines,
        Some(false),
        "para 2 (keepLines val=0) should have keep_lines=Some(false) per §17.3.1.14."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// pageBreakBefore w:val="0" parsing (§17.3.1.23)
//
// Verifies that <w:pageBreakBefore w:val="0"/> is correctly parsed as false per §17.3.1.23.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.23: <w:pageBreakBefore w:val="0"/> should produce
/// page_break_before=false.
#[test]
fn page_break_before_val_zero_is_false() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-break-before-val-false");
    let paras = common::all_paragraphs(&doc);

    // Para 0: no pageBreakBefore — false
    let p0 = find_para_by_text(&paras, "No page break before");
    assert!(
        !p0.page_break_before,
        "para 0 should have page_break_before=false"
    );

    // Para 1: direct pageBreakBefore (no val) — true
    let p1 = find_para_by_text(&paras, "Direct page break before on");
    assert!(
        p1.page_break_before,
        "para 1 should have page_break_before=true"
    );

    // Para 2: direct pageBreakBefore val="0" — should be false
    let p2 = find_para_by_text(&paras, "Direct page break before val zero");
    assert!(
        !p2.page_break_before,
        "para 2 (pageBreakBefore val=0) should have page_break_before=false \
         per §17.3.1.23."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// pageBreakBefore through deep basedOn chain (§17.3.1.23 + §17.7.4.3)
//
// Verifies that pageBreakBefore is correctly inherited through a deep
// basedOn chain, and that an explicit val="0" in a grandchild cancels it.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.23 + §17.7.4.3: Root style has pageBreakBefore=true.
/// Child (basedOn root) should inherit it.
#[test]
fn page_break_before_inherited_through_deep_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-break-deep-chain");
    let paras = common::all_paragraphs(&doc);

    // Para 0: BreakRoot — page_break_before=true (directly on style)
    let p0 = find_para_by_text(&paras, "Root break before");
    assert!(
        p0.page_break_before,
        "para 0 (BreakRoot style) should have page_break_before=true from style \
         per §17.3.1.23."
    );

    // Para 1: BreakChild (basedOn BreakRoot) — should inherit true
    let p1 = find_para_by_text(&paras, "Child inherits break");
    assert!(
        p1.page_break_before,
        "para 1 (BreakChild, basedOn BreakRoot) should inherit page_break_before=true \
         through the basedOn chain per §17.7.4.3."
    );

    // Para 2: BreakGrandchild (basedOn BreakChild, explicit val="0") — should be false
    let p2 = find_para_by_text(&paras, "Grandchild break off");
    assert!(
        !p2.page_break_before,
        "para 2 (BreakGrandchild, explicit val=0) should have page_break_before=false. \
         The grandchild style explicitly sets pageBreakBefore=false to cancel \
         the inherited true from the root."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Tab stops through deep basedOn chain with clears (§17.3.1.38)
//
// This tests the overlay_tab_stops logic through a three-level style chain.
// The cascade-resolved values live in the DERIVED view field
// `effective_tab_stops_rel` (never serialized, never compared);
// `ParagraphNode.tab_stops` is authored-only (direct pPr w:tabs verbatim),
// so paragraphs whose tabs come entirely from the style chain carry an
// empty `tab_stops` and a populated effective view.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.38: Grandparent defines 3 tabs, parent clears one and adds one,
/// child clears another and adds one. Verify the effective tab stops.
///
/// Reads `effective_tab_stops_rel` (the style-RESOLVED view value):
/// `tab_stops` now holds only the paragraph's own authored pPr stops
/// (authored/effective split), and these fixtures author none directly.
/// The fixtures carry no indent, so relative positions equal absolute.
#[test]
fn tab_stops_deep_chain_grandparent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "tab-stops-deep-chain");
    let paras = common::all_paragraphs(&doc);

    // Para 0: GrandparentTabs — 720(left), 1440(center), 2880(right/dot)
    let p0 = find_para_by_text(&paras, "Grandparent tabs para");
    assert_eq!(
        p0.effective_tab_stops_rel.len(),
        3,
        "grandparent should have 3 tab stops, got {}: {:?}",
        p0.effective_tab_stops_rel.len(),
        p0.effective_tab_stops_rel
            .iter()
            .map(|t| t.position)
            .collect::<Vec<_>>()
    );
    assert_eq!(p0.effective_tab_stops_rel[0].position, 720);
    assert_eq!(p0.effective_tab_stops_rel[0].alignment, TabAlignment::Left);
    assert_eq!(p0.effective_tab_stops_rel[1].position, 1440);
    assert_eq!(
        p0.effective_tab_stops_rel[1].alignment,
        TabAlignment::Center
    );
    assert_eq!(p0.effective_tab_stops_rel[2].position, 2880);
    assert_eq!(p0.effective_tab_stops_rel[2].alignment, TabAlignment::Right);
    assert_eq!(p0.effective_tab_stops_rel[2].leader, Some(TabLeader::Dot));
}

/// §17.3.1.38: Parent (basedOn grandparent) clears 1440, adds 4320.
/// Effective: 720(left), 2880(right/dot), 4320(left).
#[test]
fn tab_stops_deep_chain_parent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "tab-stops-deep-chain");
    let paras = common::all_paragraphs(&doc);

    let p1 = find_para_by_text(&paras, "Parent tabs para");
    let positions: Vec<i32> = p1
        .effective_tab_stops_rel
        .iter()
        .map(|t| t.position)
        .collect();
    assert_eq!(
        p1.effective_tab_stops_rel.len(),
        3,
        "parent should have 3 tab stops (720 left, 2880 right, 4320 left), got {}: {:?}",
        p1.effective_tab_stops_rel.len(),
        positions
    );
    assert_eq!(p1.effective_tab_stops_rel[0].position, 720);
    assert_eq!(p1.effective_tab_stops_rel[0].alignment, TabAlignment::Left);
    assert_eq!(p1.effective_tab_stops_rel[1].position, 2880);
    assert_eq!(p1.effective_tab_stops_rel[1].alignment, TabAlignment::Right);
    assert_eq!(p1.effective_tab_stops_rel[1].leader, Some(TabLeader::Dot));
    assert_eq!(p1.effective_tab_stops_rel[2].position, 4320);
    assert_eq!(p1.effective_tab_stops_rel[2].alignment, TabAlignment::Left);
}

/// §17.3.1.38: Child (basedOn parent) clears 720, adds 5760(decimal).
/// Effective: 2880(right/dot), 4320(left), 5760(decimal).
#[test]
fn tab_stops_deep_chain_child() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "tab-stops-deep-chain");
    let paras = common::all_paragraphs(&doc);

    let p2 = find_para_by_text(&paras, "Child tabs para");
    let positions: Vec<i32> = p2
        .effective_tab_stops_rel
        .iter()
        .map(|t| t.position)
        .collect();
    assert_eq!(
        p2.effective_tab_stops_rel.len(),
        3,
        "child should have 3 tab stops (2880 right, 4320 left, 5760 decimal), got {}: {:?}",
        p2.effective_tab_stops_rel.len(),
        positions
    );
    assert_eq!(p2.effective_tab_stops_rel[0].position, 2880);
    assert_eq!(p2.effective_tab_stops_rel[0].alignment, TabAlignment::Right);
    assert_eq!(p2.effective_tab_stops_rel[0].leader, Some(TabLeader::Dot));
    assert_eq!(p2.effective_tab_stops_rel[1].position, 4320);
    assert_eq!(p2.effective_tab_stops_rel[1].alignment, TabAlignment::Left);
    assert_eq!(p2.effective_tab_stops_rel[2].position, 5760);
    assert_eq!(
        p2.effective_tab_stops_rel[2].alignment,
        TabAlignment::Decimal
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Borders through basedOn chain (§17.3.1.24)
//
// Tests whole-element replacement: if a child style has its own pBdr,
// it replaces the parent's pBdr entirely. If a child has no pBdr,
// it inherits the parent's.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.24: Parent style has top+bottom borders. A paragraph using the
/// parent style should have both.
#[test]
fn borders_parent_has_top_and_bottom() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "borders-based-on-chain");
    let paras = common::all_paragraphs(&doc);

    let p0 = find_para_by_text(&paras, "Parent borders top bottom");
    let borders = p0
        .borders
        .as_ref()
        .expect("para 0 (BorderParent style) should have borders");
    assert!(borders.top.is_some(), "parent style should have top border");
    assert!(
        borders.bottom.is_some(),
        "parent style should have bottom border"
    );
    assert_eq!(
        borders.top.as_ref().unwrap().color.as_deref(),
        Some("FF0000"),
        "top border color should be FF0000"
    );
    assert_eq!(
        borders.bottom.as_ref().unwrap().color.as_deref(),
        Some("0000FF"),
        "bottom border color should be 0000FF"
    );
}

/// §17.3.1.24: Child style (basedOn parent) defines only left border.
/// Per OOXML, pBdr is whole-element replacement — child's pBdr replaces
/// parent's entirely. Child should have only left, NOT top+bottom.
#[test]
fn borders_child_replaces_parent_entirely() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "borders-based-on-chain");
    let paras = common::all_paragraphs(&doc);

    let p1 = find_para_by_text(&paras, "Child border left only");
    let borders = p1
        .borders
        .as_ref()
        .expect("para 1 (BorderChild style) should have borders");

    // Child defines only left border — parent's top and bottom should NOT leak through
    assert!(
        borders.left.is_some(),
        "child style should have left border"
    );
    assert_eq!(
        borders.left.as_ref().unwrap().color.as_deref(),
        Some("00FF00"),
        "left border color should be 00FF00"
    );
    assert!(
        borders.top.is_none(),
        "child style should NOT have top border (pBdr is whole-element replacement, \
         child's pBdr replaces parent's entirely per §17.3.1.24)"
    );
    assert!(
        borders.bottom.is_none(),
        "child style should NOT have bottom border (pBdr is whole-element replacement)"
    );
}

/// §17.3.1.24: Style with no pBdr (basedOn parent with pBdr) inherits
/// the parent's borders.
#[test]
fn borders_inherited_when_child_has_no_pbdr() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "borders-based-on-chain");
    let paras = common::all_paragraphs(&doc);

    let p2 = find_para_by_text(&paras, "Inherit borders from parent");
    let borders = p2
        .borders
        .as_ref()
        .expect("para 2 (BorderInherit style, basedOn BorderParent) should inherit borders");
    assert!(
        borders.top.is_some(),
        "inherited style should have top border from parent"
    );
    assert!(
        borders.bottom.is_some(),
        "inherited style should have bottom border from parent"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// contextualSpacing val="0" overrides style's true (§17.3.1.9)
//
// This verifies that the existing extraction and resolution handles
// the explicit false correctly. Should PASS if the code is correct.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.9: No style — contextual_spacing should be None.
#[test]
fn contextual_spacing_no_style_is_none() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "contextual-spacing-false");
    let paras = common::all_paragraphs(&doc);

    let p0 = find_para_by_text(&paras, "No style no ctx spacing");
    assert_eq!(
        p0.contextual_spacing, None,
        "para 0 (no style) should have contextual_spacing=None"
    );
}

/// §17.3.1.9: Style defines contextualSpacing=true. Paragraph should
/// inherit it.
#[test]
fn contextual_spacing_inherited_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "contextual-spacing-false");
    let paras = common::all_paragraphs(&doc);

    let p1 = find_para_by_text(&paras, "Ctx style true");
    assert_eq!(
        p1.contextual_spacing,
        Some(true),
        "para 1 (CtxStyle) should inherit contextual_spacing=Some(true)"
    );
}

/// §17.3.1.9: Style contextualSpacing=true + direct val="0" → Some(false).
#[test]
fn contextual_spacing_direct_false_overrides_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "contextual-spacing-false");
    let paras = common::all_paragraphs(&doc);

    let p2 = find_para_by_text(&paras, "Ctx style direct false");
    assert_eq!(
        p2.contextual_spacing,
        Some(false),
        "para 2 (style true + direct val=0) should have contextual_spacing=Some(false)"
    );
}
