//! Spec-compliance tests: insideH/insideV border cascade edge cases and
//! cell spacing interaction.
//!
//! Spec refs:
//!   - ISO 29500-1 §17.4.22-25 (insideH/insideV mapping to cell edges)
//!   - ISO 29500-1 §17.4.38 (tblBorders fallback)
//!   - ISO 29500-1 §17.4.66 (three-tier border cascade)
//!   - MS-OI29500 §2.1.136, §2.1.138, §2.1.150 (cell spacing interaction)
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-border-inside-cascade/create_docs.py`

use stemma::{BlockNode, BorderStyle, CanonDoc};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-border-inside-cascade";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

/// Extract the border color for a given cell edge, returning None if no border.
fn cell_border_color(
    table: &stemma::TableNode,
    row: usize,
    col: usize,
    edge: &str,
) -> Option<String> {
    let borders = table.rows[row].cells[col].formatting.borders.as_ref()?;
    let border = match edge {
        "top" => borders.top.as_ref(),
        "bottom" => borders.bottom.as_ref(),
        "left" => borders.left.as_ref(),
        "right" => borders.right.as_ref(),
        _ => panic!("unknown edge: {edge}"),
    }?;
    // Nil/None style means no visible border — treat as absent for color matching
    if matches!(border.style, BorderStyle::Nil | BorderStyle::None) {
        return None;
    }
    border.color.clone()
}

/// Assert that a cell edge has a specific border color.
fn assert_border_color(
    table: &stemma::TableNode,
    row: usize,
    col: usize,
    edge: &str,
    expected_color: &str,
    context: &str,
) {
    let actual = cell_border_color(table, row, col, edge);
    assert_eq!(
        actual.as_deref(),
        Some(expected_color),
        "cell ({row},{col}) {edge} border: expected color {expected_color}, got {actual:?} — {context}"
    );
}

/// Assert that a cell edge has NO border (None, or Nil/None style).
fn assert_no_border(table: &stemma::TableNode, row: usize, col: usize, edge: &str, context: &str) {
    let actual = cell_border_color(table, row, col, edge);
    assert_eq!(
        actual, None,
        "cell ({row},{col}) {edge} border: expected no border, got color {actual:?} — {context}"
    );
}

/// Extract the border style for a given cell edge.
fn cell_border_style(
    table: &stemma::TableNode,
    row: usize,
    col: usize,
    edge: &str,
) -> Option<BorderStyle> {
    let borders = table.rows[row].cells[col].formatting.borders.as_ref()?;
    let border = match edge {
        "top" => borders.top.as_ref(),
        "bottom" => borders.bottom.as_ref(),
        "left" => borders.left.as_ref(),
        "right" => borders.right.as_ref(),
        _ => panic!("unknown edge: {edge}"),
    }?;
    Some(border.style.clone())
}

// =============================================================================
// 1. insideH maps to interior horizontal cell edges
//    (ISO 29500-1 §17.4.22)
// =============================================================================

/// ISO 29500-1 §17.4.22: insideH applies to bottom of non-last-row cells
/// and top of non-first-row cells.
///
/// 3x3 grid with distinct colors:
///   top=red, bottom=blue, insideH=magenta
///
/// Cell (0,0): top=red (outer), bottom=magenta (insideH — not last row)
/// Cell (1,1): top=magenta (insideH — not first row), bottom=magenta (insideH — not last row)
/// Cell (2,2): top=magenta (insideH — not first row), bottom=blue (outer — last row)
#[test]
fn spec_inside_h_maps_to_interior_horizontal_edges() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-h-mapping-3x3");
    let table = first_table(&doc);

    // Cell (0,0): first row → top=outer red, bottom=insideH magenta
    assert_border_color(
        table,
        0,
        0,
        "top",
        "FF0000",
        "§17.4.22: first row cell gets outer top border (red)",
    );
    assert_border_color(
        table,
        0,
        0,
        "bottom",
        "FF00FF",
        "§17.4.22: non-last-row cell bottom gets insideH (magenta)",
    );

    // Cell (1,1): interior → top=insideH magenta, bottom=insideH magenta
    assert_border_color(
        table,
        1,
        1,
        "top",
        "FF00FF",
        "§17.4.22: non-first-row cell top gets insideH (magenta)",
    );
    assert_border_color(
        table,
        1,
        1,
        "bottom",
        "FF00FF",
        "§17.4.22: non-last-row cell bottom gets insideH (magenta)",
    );

    // Cell (2,2): last row → top=insideH magenta, bottom=outer blue
    assert_border_color(
        table,
        2,
        2,
        "top",
        "FF00FF",
        "§17.4.22: non-first-row cell top gets insideH (magenta)",
    );
    assert_border_color(
        table,
        2,
        2,
        "bottom",
        "0000FF",
        "§17.4.22: last row cell gets outer bottom border (blue)",
    );
}

/// ISO 29500-1 §17.4.24: insideV applies to right of non-last-column cells
/// and left of non-first-column cells.
///
/// 3x3 grid with distinct colors:
///   left=green, right=yellow, insideV=cyan
///
/// Cell (0,0): left=green (outer), right=cyan (insideV — not last col)
/// Cell (1,1): left=cyan (insideV — not first col), right=cyan (insideV — not last col)
/// Cell (0,2): left=cyan (insideV — not first col), right=yellow (outer — last col)
#[test]
fn spec_inside_v_maps_to_interior_vertical_edges() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-h-mapping-3x3");
    let table = first_table(&doc);

    // Cell (0,0): first column → left=outer green, right=insideV cyan
    assert_border_color(
        table,
        0,
        0,
        "left",
        "00FF00",
        "§17.4.24: first column cell gets outer left border (green)",
    );
    assert_border_color(
        table,
        0,
        0,
        "right",
        "00FFFF",
        "§17.4.24: non-last-column cell right gets insideV (cyan)",
    );

    // Cell (1,1): interior column → left=insideV cyan, right=insideV cyan
    assert_border_color(
        table,
        1,
        1,
        "left",
        "00FFFF",
        "§17.4.24: non-first-column cell left gets insideV (cyan)",
    );
    assert_border_color(
        table,
        1,
        1,
        "right",
        "00FFFF",
        "§17.4.24: non-last-column cell right gets insideV (cyan)",
    );

    // Cell (0,2): last column → left=insideV cyan, right=outer yellow
    assert_border_color(
        table,
        0,
        2,
        "left",
        "00FFFF",
        "§17.4.24: non-first-column cell left gets insideV (cyan)",
    );
    assert_border_color(
        table,
        0,
        2,
        "right",
        "FFFF00",
        "§17.4.24: last column cell gets outer right border (yellow)",
    );
}

/// ISO 29500-1 §17.4.22, §17.4.24: Fully interior cell (1,1) in a 3x3 grid
/// gets insideH on both top and bottom, insideV on both left and right.
/// No outer table borders should leak to interior edges.
#[test]
fn spec_fully_interior_cell_all_inside_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-h-mapping-3x3");
    let table = first_table(&doc);

    // Cell (1,1) is fully interior: not in first/last row or first/last column.
    // All 4 edges should use interior borders:
    //   top=magenta (insideH), bottom=magenta (insideH)
    //   left=cyan (insideV), right=cyan (insideV)
    assert_border_color(
        table,
        1,
        1,
        "top",
        "FF00FF",
        "§17.4.22: fully interior cell top = insideH (magenta)",
    );
    assert_border_color(
        table,
        1,
        1,
        "bottom",
        "FF00FF",
        "§17.4.22: fully interior cell bottom = insideH (magenta)",
    );
    assert_border_color(
        table,
        1,
        1,
        "left",
        "00FFFF",
        "§17.4.24: fully interior cell left = insideV (cyan)",
    );
    assert_border_color(
        table,
        1,
        1,
        "right",
        "00FFFF",
        "§17.4.24: fully interior cell right = insideV (cyan)",
    );
}

// =============================================================================
// 2. Missing insideV: interior vertical edges get NO border
//    (ISO 29500-1 §17.4.38)
// =============================================================================

/// ISO 29500-1 §17.4.38: When insideV is omitted from tblBorders,
/// interior vertical edges should have NO border. The table's outer
/// left/right borders only apply to the outermost cells.
#[test]
fn spec_missing_inside_v_no_interior_vertical_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-h-only-no-inside-v");
    let table = first_table(&doc);

    // 2x2 table. insideH defined but no insideV.
    // Cell (0,0) right is an interior vertical edge → no insideV → no border
    assert_no_border(
        table,
        0,
        0,
        "right",
        "§17.4.38: no insideV defined, interior vertical edge should have no border",
    );

    // Cell (0,1) left is an interior vertical edge → no insideV → no border
    assert_no_border(
        table,
        0,
        1,
        "left",
        "§17.4.38: no insideV defined, interior vertical edge should have no border",
    );
}

/// ISO 29500-1 §17.4.38: When insideV is omitted, insideH should still apply
/// to interior horizontal edges. The two border types are independent.
#[test]
fn spec_missing_inside_v_inside_h_still_applies() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-h-only-no-inside-v");
    let table = first_table(&doc);

    // Cell (0,0) bottom is an interior horizontal edge → insideH = green dashed
    assert_border_color(
        table,
        0,
        0,
        "bottom",
        "00FF00",
        "§17.4.38: insideH still applies even when insideV is omitted",
    );

    // Verify it's dashed style (not single from the outer borders)
    let style = cell_border_style(table, 0, 0, "bottom");
    assert_eq!(
        style,
        Some(BorderStyle::Dashed),
        "§17.4.38: insideH border should be dashed (matching table insideH definition)"
    );

    // Cell (1,0) top is also an interior horizontal edge
    assert_border_color(
        table,
        1,
        0,
        "top",
        "00FF00",
        "§17.4.38: insideH applies to top of non-first-row cells",
    );
}

// =============================================================================
// 3. Cell spacing non-zero: borders present
//    (MS-OI29500 §2.1.150)
// =============================================================================

/// MS-OI29500 §2.1.150: When cell spacing is non-zero, borders should still
/// be present on cells. Cell (0,0) has an explicit right border (thick red),
/// which should be preserved regardless of cell spacing.
///
/// Per the ECMA spec, non-zero cell spacing means no conflict resolution
/// (borders display independently on each cell edge). Per MS-OI29500, Word
/// still applies conflict resolution for insideH/insideV even with spacing.
///
/// This test documents that cell-level borders are at least preserved.
#[test]
fn spec_cell_spacing_nonzero_borders_present() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-spacing-nonzero-borders");
    let table = first_table(&doc);

    // Verify cell spacing is parsed
    assert!(
        table.formatting.cell_spacing.is_some(),
        "table should have cell_spacing parsed from tblCellSpacing"
    );
    let spacing = table.formatting.cell_spacing.unwrap();
    assert_eq!(spacing, 20, "cell spacing should be 20 twips");

    // Cell (0,0) has explicit tcBorders right = thick sz=12 red.
    // This cell-level border should be preserved.
    let cell_00_borders = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders — it has explicit tcBorders");
    let right = cell_00_borders
        .right
        .as_ref()
        .expect("cell (0,0) should have a right border from tcBorders");
    assert_eq!(
        right.style,
        BorderStyle::Thick,
        "cell (0,0) right border style should be Thick (from explicit tcBorders)"
    );
    assert_eq!(
        right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border color should be FF0000 (red, from explicit tcBorders)"
    );
    assert_eq!(
        right.size,
        Some(12),
        "cell (0,0) right border size should be 12 (from explicit tcBorders)"
    );

    // Other cells should still have table-fallback borders on their edges.
    // Cell (1,1) is fully interior: should have borders from table-level fallback.
    let cell_11_borders = table.rows[1].cells[1].formatting.borders.as_ref();
    assert!(
        cell_11_borders.is_some(),
        "cell (1,1) should have borders from table-level fallback even with cell spacing"
    );
}
