//! Spec-compliance tests: Fields (ISO 29500-1 §17.16)
//!
//! These tests verify our implementation against specific OOXML field
//! constructs — both simple fields (fldSimple) and complex fields
//! (fldChar begin/separate/end with instrText).
//! Tests marked `#[ignore]` document known gaps.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{
    FieldData, FieldKind, FieldSemantic, InlineNode, OpaqueKind, TocFieldSpec, TocLevelsSpec,
};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/fields";

// -- helpers ----------------------------------------------------------------
/// Collect all FieldData from OpaqueInline nodes in a paragraph's segments.
fn collect_field_opaques(para: &stemma::ParagraphNode) -> Vec<&FieldData> {
    let mut fields = Vec::new();
    for inline in para.all_inlines() {
        if let InlineNode::OpaqueInline(opaque) = inline
            && let OpaqueKind::Field(ref fd) = opaque.kind
        {
            fields.push(fd);
        }
    }
    fields
}

// -- simple field tests -----------------------------------------------------

/// ISO 29500-1 §17.16.19: fldSimple produces an OpaqueInline with OpaqueKind::Field(FieldData).
///
/// Verifies that a simple field (w:fldSimple) is parsed into an OpaqueInline
/// with field_kind = FieldKind::Simple.
#[test]
fn spec_simple_field_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "simple-field");

    let paras = common::all_paragraphs(&doc);
    assert!(
        !paras.is_empty(),
        "should have at least one paragraph in simple-field fixture"
    );

    let fields = collect_field_opaques(paras.last().unwrap());
    assert!(
        !fields.is_empty(),
        "simple-field paragraph should contain at least one Field opaque. \
         The fixture has a w:fldSimple element."
    );

    let fd = fields[0];
    assert_eq!(
        fd.field_kind,
        FieldKind::Simple,
        "fldSimple should produce FieldKind::Simple, got {:?}",
        fd.field_kind
    );
}

/// ISO 29500-1 §17.16.19: fldSimple instruction text is captured from w:instr attribute.
///
/// The instruction text should be " PAGE ".
#[test]
fn spec_simple_field_instruction_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "simple-field");

    let paras = common::all_paragraphs(&doc);
    let fields = collect_field_opaques(paras.last().unwrap());
    assert!(!fields.is_empty(), "should have at least one field opaque");

    let fd = fields[0];
    let instr = fd
        .instruction_text
        .as_deref()
        .expect("fldSimple should have instruction_text populated from w:instr attribute");
    assert!(
        instr.contains("PAGE"),
        "instruction text should contain 'PAGE', got: {instr:?}"
    );
}

/// ISO 29500-1 §17.16.19: fldSimple display/result text is captured from nested runs.
///
/// The result text should be "1" (the PAGE field's cached value).
#[test]
fn spec_simple_field_display_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "simple-field");

    let paras = common::all_paragraphs(&doc);
    let fields = collect_field_opaques(paras.last().unwrap());
    assert!(!fields.is_empty(), "should have at least one field opaque");

    let fd = fields[0];
    let result = fd
        .result_text
        .as_deref()
        .expect("fldSimple should have result_text populated from nested w:r/w:t content");
    assert_eq!(
        result, "1",
        "result text should be '1' (the cached PAGE value)"
    );
}

// -- complex field tests ----------------------------------------------------

/// ISO 29500-1 §17.16.18: Complex field produces OpaqueInlines for Begin and End.
///
/// A complex field uses fldChar elements with begin/separate/end. At minimum,
/// the parser should produce OpaqueInlines with FieldKind::Begin and FieldKind::End.
#[test]
fn spec_complex_field_begin_end() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "complex-field");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    let has_begin = fields.iter().any(|fd| fd.field_kind == FieldKind::Begin);
    let has_end = fields.iter().any(|fd| fd.field_kind == FieldKind::End);

    assert!(
        has_begin,
        "complex field should have a FieldKind::Begin opaque. Found field kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
    assert!(
        has_end,
        "complex field should have a FieldKind::End opaque. Found field kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
}

/// ISO 29500-1 §17.16.18: Complex field instrText content is captured.
///
/// The instrText run between begin and separate should produce an OpaqueInline
/// with FieldKind::Instruction and the instruction text captured.
#[test]
fn spec_complex_field_instruction_captured() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "complex-field");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    let instr_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| fd.field_kind == FieldKind::Instruction)
        .collect();

    assert!(
        !instr_fields.is_empty(),
        "complex field should have at least one FieldKind::Instruction opaque. \
         Found field kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );

    let instr_text = instr_fields[0]
        .instruction_text
        .as_deref()
        .expect("instrText field should have instruction_text populated");
    assert!(
        instr_text.contains("DATE"),
        "instruction text should contain 'DATE', got: {instr_text:?}"
    );
}

// -- TOC field tests --------------------------------------------------------

/// ISO 29500-1 §17.16.5.68: TOC fldSimple instruction text is captured.
///
/// The instruction should contain "TOC" and the heading level switch.
#[test]
fn spec_toc_field_instruction() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "toc-field");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    assert!(
        !fields.is_empty(),
        "toc-field paragraph should contain at least one Field opaque"
    );

    let fd = fields[0];
    assert_eq!(
        fd.field_kind,
        FieldKind::Simple,
        "TOC fldSimple should be FieldKind::Simple"
    );

    let instr = fd
        .instruction_text
        .as_deref()
        .expect("TOC fldSimple should have instruction_text from w:instr attribute");
    assert!(
        instr.contains("TOC"),
        "instruction text should contain 'TOC', got: {instr:?}"
    );
    assert_eq!(
        fd.semantic,
        Some(FieldSemantic::Toc(TocFieldSpec {
            levels: TocLevelsSpec { from: 1, to: 3 },
            include_hyperlinks: false,
            hide_page_numbers_in_web: false,
            use_outline_levels: false,
        })),
        "TOC fldSimple should be classified semantically"
    );
}

// -- REF field tests --------------------------------------------------------

/// ISO 29500-1 §17.16.5.51: REF fldSimple instruction contains bookmark name.
///
/// The instruction text should contain "REF" and the target bookmark name.
#[test]
fn spec_ref_field_instruction() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "ref-field");

    let paras = common::all_paragraphs(&doc);

    // The REF field is in the second paragraph
    let ref_para = paras
        .iter()
        .find(|p| {
            collect_field_opaques(p)
                .iter()
                .any(|fd| fd.field_kind == FieldKind::Simple)
        })
        .expect("should find a paragraph with a Simple field (REF fldSimple)");

    let fields = collect_field_opaques(ref_para);
    let fd = fields[0];

    let instr = fd
        .instruction_text
        .as_deref()
        .expect("REF fldSimple should have instruction_text from w:instr attribute");
    assert!(
        instr.contains("REF"),
        "instruction text should contain 'REF', got: {instr:?}"
    );
    assert!(
        instr.contains("my_bookmark"),
        "instruction text should contain bookmark name 'my_bookmark', got: {instr:?}"
    );
}

// -- multiple fields tests --------------------------------------------------

/// ISO 29500-1 §17.16.19: Two fldSimple fields in one paragraph are independent.
///
/// Both PAGE and NUMPAGES fields should produce separate OpaqueInline nodes.
#[test]
fn spec_multiple_fields_independent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "multiple-fields");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    assert!(
        fields.len() >= 2,
        "paragraph with two fldSimple fields should produce at least 2 Field opaques, got {}",
        fields.len()
    );

    // Both should be Simple
    assert_eq!(
        fields[0].field_kind,
        FieldKind::Simple,
        "first field should be FieldKind::Simple"
    );
    assert_eq!(
        fields[1].field_kind,
        FieldKind::Simple,
        "second field should be FieldKind::Simple"
    );

    // They should have different instruction texts
    let instr0 = fields[0].instruction_text.as_deref().unwrap_or("");
    let instr1 = fields[1].instruction_text.as_deref().unwrap_or("");
    assert_ne!(
        instr0, instr1,
        "the two fields should have different instruction texts, but both are: {instr0:?}"
    );
}

/// Word tolerates whitespace around the `\o` level bounds — `TOC \o "1 - 9"`
/// occurs in real documents (corpus: docxcorpus/55/55364cc2…) and must parse
/// to the same spec as the tight form.
#[test]
fn spec_toc_levels_tolerate_whitespace() {
    let semantic = stemma::domain::parse_field_instruction(r#" TOC \o "1 - 9" \h \z \u "#)
        .expect("whitespace-padded TOC levels parse");
    assert_eq!(
        semantic,
        FieldSemantic::Toc(TocFieldSpec {
            levels: TocLevelsSpec { from: 1, to: 9 },
            include_hyperlinks: true,
            hide_page_numbers_in_web: true,
            use_outline_levels: true,
        })
    );
}
