//! Spec-compliance tests: Toggle Property Resolution Edge Cases
//!
//! These tests probe edge cases in toggle property resolution that are NOT
//! covered by the existing spec_style_toggle_audit or spec_style_cascade_bugs
//! test suites. Each test asserts **correct** behavior per the OOXML spec;
//! tests that fail expose real bugs in the current implementation.
//!
//! Key spec references:
//! - §17.7.3: Toggle property semantics across hierarchy levels
//! - §17.7.4.6: Linked style pairs (paragraph + character)
//! - §17.7.4.17: Implicit default styles
//! - §17.3.2.1 / §17.3.2.38: bCs/iCs replacement when cs/rtl active
//! - MS-OI29500 §2.1.230a: docDefaults toggle interaction
//! - MS-OI29500 §2.1.258: Word RESET semantics (not XOR)
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/style-cascade-toggle-edge/create_docs.py`.

use stemma::{InlineNode, Mark, MarkValue};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade-toggle-edge";

// -- helpers ---------------------------------------------------------------

fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}

fn find_para<'a>(paras: &[&'a stemma::ParagraphNode], needle: &str) -> &'a stemma::ParagraphNode {
    paras
        .iter()
        .find(|p| common::paragraph_text(p).contains(needle))
        .unwrap_or_else(|| panic!("should find paragraph containing {:?}", needle))
}

// =========================================================================
// 1. Linked char style basedOn chain property loss (§17.7.4.6)
//
// When a paragraph style is linked to a char style that has a basedOn chain,
// the Bug 2 fix uses linked_raw.marks (not the resolved chain). This prevents
// inherited properties from leaking, but also loses properties the char style
// inherits from its basedOn chain that the para style doesn't set.
//
// Setup:
// - BaseChar: italic=on, color=FF0000
// - AccentChar: basedOn BaseChar, bold=on (no italic, no color)
// - AccentPara: linked to AccentChar, rPr has sz=32 only
//
// Expected: runs get bold=ON (AccentChar), italic=ON (inherited from BaseChar),
// sz=32 (AccentPara), color=FF0000 (inherited from BaseChar).
//
// Bug: overlay uses AccentChar's raw marks (bold=On, italic=Inherit), so
// italic=On from BaseChar is lost.
// =========================================================================

/// §17.7.4.6: Linked char style's basedOn-inherited italic should apply
/// when the para style doesn't set italic. The Bug 2 fix over-corrects
/// by using raw marks instead of resolved marks.
#[test]
fn linked_based_on_italic_from_base_char() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-basedOn-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Linked basedOn test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Bold should be ON from AccentChar (explicitly set).
    assert!(
        run.marks.contains(&Mark::Bold),
        "AccentChar explicitly sets bold=on -> bold should be ON."
    );

    // Bug: italic=on is inherited by AccentChar from BaseChar. The linked
    // overlay uses AccentChar's raw marks (italic=Inherit), so italic is lost.
    // The para style AccentPara doesn't set italic either, so no level provides it.
    assert!(
        run.marks.contains(&Mark::Italic),
        "AccentChar inherits italic=on from BaseChar. Per §17.7.4.6, the \
         linked char style's resolved properties should apply. italic=ON \
         should come from BaseChar through AccentChar's basedOn chain."
    );

    // sz=32 from AccentPara's own rPr.
    assert_eq!(
        run.style_props.font_size,
        Some(32),
        "AccentPara sets sz=32 in its rPr. This should be preserved."
    );
}

/// §17.7.4.6: Linked char style's basedOn-inherited color should apply
/// when the para style doesn't set color.
#[test]
fn linked_based_on_color_from_base_char() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-basedOn-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Linked basedOn test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // color=FF0000 is inherited by AccentChar from BaseChar.
    // The para style AccentPara doesn't set color.
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "AccentChar inherits color=FF0000 from BaseChar. Per §17.7.4.6, \
         the linked char style's resolved properties should apply. \
         Bug: linked overlay uses raw marks, losing inherited color."
    );
}

/// §17.7.4.6: When AccentChar is applied explicitly as a char style (not via
/// link), its fully resolved basedOn chain should apply.
#[test]
fn linked_based_on_explicit_char_gets_full_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-basedOn-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Explicit char style test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(run.marks.contains(&Mark::Bold), "AccentChar sets bold=on.");
    assert!(
        run.marks.contains(&Mark::Italic),
        "AccentChar inherits italic=on from BaseChar. When applied explicitly \
         as a char style, the full basedOn chain should resolve."
    );
}

// =========================================================================
// 2. 4-level basedOn chain with toggle gap (§17.7.3)
//
// Root(bold=on,caps=on) → A(bold=off) → B(no rPr) → Leaf(bold=on)
//
// The key test is level B which has no rPr at all — it should inherit
// bold=off from A, not bold=on from Root.
// =========================================================================

/// §17.7.3: Leaf in 4-level chain overrides to bold=on, caps inherited from root.
#[test]
fn four_level_leaf_bold_on_caps_inherited() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "4level-toggle-gap");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Leaf 4-level bold on");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "Leaf4 sets bold=on, overriding the inherited bold=off from chain."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps=on from Root4 should inherit through all levels to Leaf4."
    );
}

/// §17.7.3: Level B has no rPr — should inherit bold=off from A.
#[test]
fn four_level_gap_inherits_off_from_parent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "4level-toggle-gap");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "B 4-level bold inherit gap");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "LevelB4 has no rPr. It inherits bold=off from LevelA4. \
         Per §17.7.3, first-value-encountered in the chain is A's off."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps=on from Root4 should inherit through all levels."
    );
}

/// §17.7.3: Level A explicitly sets bold=off.
#[test]
fn four_level_a_bold_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "4level-toggle-gap");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "A 4-level bold off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "LevelA4 sets bold=off explicitly."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps=on from Root4 should inherit to LevelA4."
    );
}

// =========================================================================
// 3. docDefaults toggle ON + deep basedOn chain (§17.7.3 + §2.1.230a)
//
// docDefaults: caps=on, strike=on.
// ParaBase: no overrides.
// ParaMid: basedOn ParaBase, caps=off.
// ParaLeaf: basedOn ParaMid, strike=off.
//
// Tests that toggle overrides from intermediate basedOn levels propagate
// correctly through to descendant styles, even when the descendant doesn't
// re-set the property.
// =========================================================================

/// §17.7.3: ParaLeaf inherits caps=off from ParaMid, strike=off from itself.
/// Both docDefaults toggles should be overridden.
#[test]
fn doc_defaults_deep_chain_leaf_both_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-deep-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Deep chain overrides docDefaults");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.caps != MarkValue::On,
        "ParaLeaf inherits caps=off from ParaMid. Even though docDefaults has \
         caps=on, the style chain's off should override per MS-OI29500 §2.1.230a."
    );
    assert!(
        run.style_props.strike != MarkValue::On,
        "ParaLeaf sets strike=off. Even though docDefaults has strike=on, \
         the style's off should override per MS-OI29500 §2.1.230a."
    );
}

/// §17.7.3: ParaMid has caps=off but doesn't touch strike. Strike should
/// come from docDefaults.
#[test]
fn doc_defaults_deep_chain_mid_caps_off_strike_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-deep-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Mid chain caps off strike on");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.caps != MarkValue::On,
        "ParaMid sets caps=off, overriding docDefaults caps=on."
    );
    assert!(
        run.style_props.strike == MarkValue::On,
        "ParaMid doesn't touch strike -> docDefaults strike=on should apply."
    );
}

/// §17.7.3: ParaBase doesn't override anything — both from docDefaults.
#[test]
fn doc_defaults_deep_chain_base_both_from_defaults() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-deep-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Base chain both from docDefaults");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.caps == MarkValue::On,
        "ParaBase doesn't override caps -> docDefaults caps=on should apply."
    );
    assert!(
        run.style_props.strike == MarkValue::On,
        "ParaBase doesn't override strike -> docDefaults strike=on should apply."
    );
}

/// §17.7.5: Unstyled paragraph gets both from docDefaults.
#[test]
fn doc_defaults_deep_chain_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-deep-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Unstyled caps and strike from docDefaults");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.caps == MarkValue::On,
        "unstyled paragraph -> docDefaults caps=on."
    );
    assert!(
        run.style_props.strike == MarkValue::On,
        "unstyled paragraph -> docDefaults strike=on."
    );
}

// =========================================================================
// 4. bold_cs toggle with cs/rtl active (§17.3.2.1 + §17.3.2.38)
//
// When cs=on or rtl=on, bold is REPLACED by bCs (§17.3.2.1).
// If bCs is absent (Inherit), bold should become effectively OFF for CS text.
// =========================================================================

/// §17.3.2.1: cs=on with bold=on but bCs absent. bCs=Inherit means not bold.
#[test]
fn bold_cs_absent_when_cs_active() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bold-cs-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "CS active bold but no bCs");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Per §17.3.2.1: when cs=on, b is IGNORED and only bCs applies.
    // bCs is absent (Inherit) -> effectively not bold for complex script text.
    assert!(
        !run.marks.contains(&Mark::Bold),
        "cs=on with bCs absent: bold should be OFF for complex script text. \
         Per §17.3.2.1, when cs is active, b is ignored and bCs determines boldness. \
         bCs=Inherit means not bold."
    );
}

/// §17.3.2.1: cs=on with bold=off but bCs=on. bCs wins -> bold.
#[test]
fn bold_cs_on_when_cs_active() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bold-cs-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "CS active bCs on overrides bold off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Per §17.3.2.1: when cs=on, bCs=on should make the text bold,
    // regardless of b being off.
    assert!(
        run.marks.contains(&Mark::Bold),
        "cs=on with bCs=on: bold should be ON for complex script text. \
         Per §17.3.2.1, bCs=on determines boldness when cs is active."
    );
}

/// §17.3.2.38: rtl=on with both bold=on and bCs=on. bCs wins -> bold.
#[test]
fn bold_cs_rtl_active_both_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bold-cs-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "RTL bold with bCs");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "rtl=on with bCs=on: bold should be ON. Per §17.3.2.38, \
         when rtl is active, bCs determines boldness."
    );
}

// =========================================================================
// 5. Default char style with toggle + explicit char style (§17.7.4.17)
//
// A custom default char style (w:default="1", non-DefaultParagraphFont ID)
// has italic=on, smallCaps=on. An explicit char style has bold=on only.
// The merge should give: bold=on (explicit), italic=on (default), smallCaps=on (default).
// =========================================================================

/// §17.7.4.17: Explicit char style + default char style merge. Both toggles
/// from the default should apply alongside the explicit style's bold.
#[test]
fn default_char_merge_with_explicit() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-style-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Explicit plus default char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "ExplicitChar sets bold=on."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "CustomDefaultChar (default char style) sets italic=on. Per §17.7.2, \
         when explicit char style doesn't set italic, default char style's \
         italic should fill in. The merge at line ~920 should produce this."
    );
    assert!(
        run.style_props.small_caps == MarkValue::On,
        "CustomDefaultChar sets smallCaps=on. Per §17.7.2, when explicit \
         char style doesn't set smallCaps, default char style's value should fill in."
    );
}

/// §17.7.4.17: No explicit char style -> default char style applies alone.
#[test]
fn default_char_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-style-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Default char style only");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "no explicit char style, default char doesn't set bold."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "CustomDefaultChar sets italic=on. With no explicit char style, \
         the default char style should apply."
    );
    assert!(
        run.style_props.small_caps == MarkValue::On,
        "CustomDefaultChar sets smallCaps=on."
    );
}

/// §17.7.2: Explicit char style italic=off should override default char italic=on.
#[test]
fn explicit_char_overrides_default_char_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-style-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Explicit italic off overrides default");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "NoItalicChar sets bold=on."
    );
    assert!(
        !run.marks.contains(&Mark::Italic),
        "NoItalicChar sets italic=off. This should override the default \
         char style's italic=on. Per §17.7.2, explicit char wins."
    );
    // smallCaps=on from default char style should still fill in
    // (NoItalicChar doesn't set smallCaps).
    assert!(
        run.style_props.small_caps == MarkValue::On,
        "NoItalicChar doesn't set smallCaps. Default char style's \
         smallCaps=on should fill in per merge logic."
    );
}

// =========================================================================
// 6. dstrike (double-strike) resolution
//
// dstrike is NOT a toggle property per ECMA-376 §17.7.3. The exhaustive
// toggle list is: b, bCs, caps, emboss, i, iCs, imprint, outline, shadow,
// smallCaps, strike, vanish. dstrike (§17.3.2.9) is absent from that list.
// Using non-toggle (resolve_mark / override) semantics is correct here.
// =========================================================================

/// §17.7.3: Para style dstrike=on + char style dstrike=on -> dstrike=on.
#[test]
fn dstrike_both_para_and_char() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "dstrike-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Both para and char dstrike");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.double_strike == MarkValue::On,
        "both para and char style set dstrike=on -> should be ON."
    );
}

/// §17.7.3: Para style dstrike=on, no char style -> dstrike=on.
#[test]
fn dstrike_para_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "dstrike-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Para dstrike only");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.double_strike == MarkValue::On,
        "para style dstrike=on -> should be ON."
    );
}

/// §17.7.3: Direct dstrike=off overrides para style dstrike=on.
#[test]
fn dstrike_direct_off_overrides() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "dstrike-toggle");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Direct dstrike off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.double_strike != MarkValue::On,
        "direct dstrike=off should override para style dstrike=on."
    );
}

// =========================================================================
// 7. Rare toggle properties cascade (§17.7.3)
//
// Tests vanish, emboss, shadow, outline — less commonly tested toggle
// properties — through the full hierarchy including docDefaults.
// =========================================================================

/// §17.7.3: VanishStyle + ShadowChar: vanish=on, emboss=off (overrides
/// docDefaults), shadow=on, outline=on.
#[test]
fn rare_toggle_vanish_shadow_outline() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "rare-toggle-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Vanish shadow outline test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.vanish == MarkValue::On,
        "VanishStyle sets vanish=on."
    );
    assert!(
        run.style_props.emboss != MarkValue::On,
        "VanishStyle sets emboss=off, overriding docDefaults emboss=on. \
         Per MS-OI29500 §2.1.230a, styles can override docDefaults toggles."
    );
    assert!(
        run.style_props.shadow == MarkValue::On,
        "ShadowChar sets shadow=on."
    );
    assert!(
        run.style_props.outline == MarkValue::On,
        "ShadowChar sets outline=on."
    );
}

/// §17.7.3: VanishStyle only: vanish=on, emboss=off.
#[test]
fn rare_toggle_vanish_emboss_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "rare-toggle-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Vanish emboss off test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.vanish == MarkValue::On,
        "VanishStyle sets vanish=on."
    );
    assert!(
        run.style_props.emboss != MarkValue::On,
        "VanishStyle sets emboss=off, overriding docDefaults emboss=on."
    );
}

/// §17.7.5: Unstyled paragraph gets emboss=on from docDefaults.
#[test]
fn rare_toggle_unstyled_emboss_from_defaults() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "rare-toggle-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Unstyled emboss from docDefaults");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.style_props.emboss == MarkValue::On,
        "unstyled paragraph -> docDefaults emboss=on should apply."
    );
}

// =========================================================================
// 8. Toggle val variants: true/1/absent=on, false/off/0=off (§22.9.2.7)
//
// Tests that val="true", val="1", and bare element all produce On,
// and val="false" and val="off" produce Off.
// =========================================================================

/// §22.9.2.7: Root uses val="true" and val="1" — both should be On.
#[test]
fn val_true_and_1_are_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "val-false-propagation");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Root val true and 1");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "bold with val=\"true\" should be ON per §22.9.2.7."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "italic with val=\"1\" should be ON per §22.9.2.7."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps with no val attribute (bare element) should be ON per §22.9.2.7."
    );
}

/// §22.9.2.7: Mid uses val="false" and val="off" — both should be Off.
#[test]
fn val_false_and_off_are_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "val-false-propagation");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Mid val false and off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "bold with val=\"false\" should be OFF per §22.9.2.7."
    );
    assert!(
        !run.marks.contains(&Mark::Italic),
        "italic with val=\"off\" should be OFF per §22.9.2.7."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps inherited from Root (not overridden by Mid)."
    );
}

/// §17.7.3: Leaf inherits Off values from Mid.
#[test]
fn val_leaf_inherits_off_from_mid() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "val-false-propagation");
    let paras = common::all_paragraphs(&doc);

    let p = find_para(&paras, "Leaf inherits false and off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "Leaf inherits bold=off from Mid (val=\"false\")."
    );
    assert!(
        !run.marks.contains(&Mark::Italic),
        "Leaf inherits italic=off from Mid (val=\"off\")."
    );
    assert!(
        run.style_props.caps == MarkValue::On,
        "caps=on inherited from Root through Mid (Mid doesn't override caps)."
    );
}
