//! Spec-compliance tests: docDefaults pPr, Normal basedOn, and style resolution edge cases
//!
//! These tests verify correct behavior for edge cases in:

//!   - docDefaults pPr (alignment, indent, spacing, contextualSpacing)
//!   - Normal style with basedOn chain
//!   - Multiple default paragraph styles
//!   - basedOn edge cases (non-existent, circular, cross-type)
//!
//! Key spec references:
//!   - ISO 29500-1 §17.7.5: docDefaults (rPrDefault, pPrDefault)
//!   - ISO 29500-1 §17.7.4.17: Default styles (w:default="1")
//!   - ISO 29500-1 §17.7.4.3: basedOn chain and type validation
//!   - ISO 29500-1 §17.7.2: Style hierarchy precedence
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/style-cascade-defaults-edge/create_docs.py`.

use stemma::{Alignment, InlineNode, Mark};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade-defaults-edge";

// -- helpers -----------------------------------------------------------------

fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}

fn find_para_by_text<'a>(
    paras: &[&'a stemma::ParagraphNode],
    needle: &str,
) -> &'a stemma::ParagraphNode {
    paras
        .iter()
        .find(|p| common::paragraph_text(p).contains(needle))
        .unwrap_or_else(|| panic!("should find paragraph containing {:?}", needle))
}

// ============================================================================
// 1. docDefaults pPr alignment (§17.7.5)
//
// Verifies that docDefaults/pPrDefault/pPr jc=center is resolved correctly:
// unstyled paragraphs inherit it, styles and direct formatting override it.
// ============================================================================

/// §17.7.5: Unstyled paragraph should get alignment=center from docDefaults pPr.
#[test]
fn docdefaults_ppr_alignment_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-alignment");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled center from docDefaults");

    // Verifies that resolve_effective_alignment consults ppr_defaults.
    assert_eq!(
        p.align,
        Some(Alignment::Center),
        "unstyled paragraph should get alignment=Center from docDefaults pPr. \
         Per §17.7.5, docDefaults provides base paragraph properties."
    );
}

/// §17.7.5: Style with jc=left should override docDefaults jc=center.
#[test]
fn docdefaults_ppr_alignment_style_overrides() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-alignment");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Left from style");

    assert_eq!(
        p.align,
        Some(Alignment::Left),
        "LeftAlignStyle sets jc=left, should override docDefaults jc=center."
    );
}

/// §17.7.5: Direct jc=right should override docDefaults jc=center.
#[test]
fn docdefaults_ppr_alignment_direct_overrides() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-alignment");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct right overrides docDefaults");

    assert_eq!(
        p.align,
        Some(Alignment::Right),
        "direct jc=right should override docDefaults jc=center."
    );
}

// ============================================================================
// 2. docDefaults pPr indentation (§17.7.5)
//
// Verifies that docDefaults/pPrDefault/pPr ind left=720 right=360 is
// resolved correctly for unstyled paragraphs and partial direct overrides.
// ============================================================================

/// §17.7.5: Unstyled paragraph should get indent from docDefaults pPr.
#[test]
fn docdefaults_ppr_indent_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-indent");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled indent from docDefaults");

    // Verifies that resolve_effective_indent consults ppr_defaults.
    let indent = p.indent.as_ref();
    assert!(
        indent.is_some(),
        "unstyled paragraph should have indent from docDefaults pPr. \
         Per §17.7.5, docDefaults provides base paragraph properties."
    );
    let indent = indent.unwrap();
    assert_eq!(
        indent.left,
        Some(720),
        "unstyled paragraph should get indent left=720 from docDefaults pPr."
    );
    assert_eq!(
        indent.right,
        Some(360),
        "unstyled paragraph should get indent right=360 from docDefaults pPr."
    );
}

/// §17.7.5 + §17.3.1.12: Direct left=0 overrides docDefaults left=720,
/// but right should still come from docDefaults (per-attribute merge).
#[test]
fn docdefaults_ppr_indent_direct_partial_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-indent");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct left zero overrides docDefaults");

    let indent = p.indent.as_ref();
    assert!(
        indent.is_some(),
        "paragraph with direct left=0 should still have indent (at least from docDefaults right)."
    );
    let indent = indent.unwrap();
    assert_eq!(
        indent.left,
        Some(0),
        "direct left=0 should override docDefaults left=720."
    );
    // Per-attribute merge: right should come from docDefaults since direct
    // doesn't set it.
    assert_eq!(
        indent.right,
        Some(360),
        "direct left=0 does not set right — right should come from docDefaults (360). \
         Per §17.3.1.12, indentation merges per-attribute."
    );
}

// ============================================================================
// 3. docDefaults pPr spacing + style spacing merge (§17.7.5 + §17.7.2)
//
// docDefaults pPr sets before=240, line=276. A style that only sets
// after=120 should merge with docDefaults: before from docDefaults,
// after from style, line from docDefaults.
//
// This SHOULD work because resolve_effective_spacing already falls through
// to ppr_defaults. This test serves as a regression guard.
// ============================================================================

/// §17.7.5: Unstyled paragraph should get spacing from docDefaults pPr.
#[test]
fn docdefaults_ppr_spacing_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-spacing-merge");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled spacing from docDefaults");

    let spacing = p
        .spacing
        .as_ref()
        .expect("unstyled paragraph should have spacing from docDefaults pPr");
    assert_eq!(
        spacing.before,
        Some(240),
        "unstyled paragraph should get before=240 from docDefaults pPr."
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "unstyled paragraph should get line=276 from docDefaults pPr."
    );
}

/// §17.7.5 + §17.7.2: Style sets only after=120. Before and line should
/// come from docDefaults (per-field merge).
#[test]
fn docdefaults_ppr_spacing_style_merge() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-spacing-merge");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Style after only merges with docDefaults");

    let spacing = p
        .spacing
        .as_ref()
        .expect("AfterOnlyStyle paragraph should have spacing");
    assert_eq!(spacing.after, Some(120), "AfterOnlyStyle sets after=120.");
    assert_eq!(
        spacing.before,
        Some(240),
        "AfterOnlyStyle doesn't set before — should come from docDefaults (240). \
         Per §17.7.5, docDefaults provides base, style overrides per-field."
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "AfterOnlyStyle doesn't set line — should come from docDefaults (276)."
    );
}

// ============================================================================
// 4. Normal style with basedOn chain — rPr inheritance (§17.7.4.3)
//
// Normal (default paragraph style) has basedOn=CustomBase. CustomBase
// sets sz=24, color=FF0000. Normal overrides sz=28. An unstyled paragraph
// should get sz=28 from Normal and color=FF0000 from CustomBase.
// ============================================================================

/// §17.7.4.3 + §17.7.4.17: Normal basedOn CustomBase. Implicit Normal
/// paragraph should get font_size=28 from Normal (overrides CustomBase's 24).
#[test]
fn normal_based_on_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-with-based-on");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Implicit Normal with basedOn");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "implicit Normal (basedOn CustomBase) should resolve font_size=28 \
         from Normal's own rPr (overriding CustomBase's sz=24). \
         Per §17.7.4.3, child style values override parent per-property."
    );
}

/// §17.7.4.3 + §17.7.4.17: Normal basedOn CustomBase. Implicit Normal
/// paragraph should inherit color=FF0000 from CustomBase.
#[test]
fn normal_based_on_inherits_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-with-based-on");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Implicit Normal with basedOn");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "implicit Normal (basedOn CustomBase) should inherit color=FF0000 \
         from CustomBase. Normal does not set color, so it falls through \
         the basedOn chain."
    );
}

/// §17.7.4.17: Explicit pStyle=Normal should produce the same result as implicit.
#[test]
fn normal_based_on_explicit_matches_implicit() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-with-based-on");
    let paras = common::all_paragraphs(&doc);

    let p_implicit = find_para_by_text(&paras, "Implicit Normal with basedOn");
    let p_explicit = find_para_by_text(&paras, "Explicit Normal with basedOn");

    let implicit_run = &text_nodes(p_implicit)[0];
    let explicit_run = &text_nodes(p_explicit)[0];

    assert_eq!(
        implicit_run.style_props.font_size, explicit_run.style_props.font_size,
        "implicit and explicit Normal should produce the same font_size"
    );
    assert_eq!(
        implicit_run.style_props.color, explicit_run.style_props.color,
        "implicit and explicit Normal should produce the same color"
    );
}

// ============================================================================
// 5. Multiple paragraph styles with default="1" (§17.7.4.17)
//
// Per spec, only one style per type should have default="1". When two
// exist, the code should not crash. We test that it handles this gracefully.
// ============================================================================

/// §17.7.4.17: Two paragraph styles with default="1" — code should not crash.
/// The unstyled paragraph should get properties from one of them.
#[test]
fn multiple_defaults_does_not_crash() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "multiple-default-para-styles");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled with two defaults");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    // The code should pick one of the two defaults. We verify it doesn't crash
    // and that font_size is set to one of the two values (20 or 28).
    let font_size = run.style_props.font_size;
    assert!(
        font_size == Some(20) || font_size == Some(28),
        "with two default paragraph styles (sz=20 and sz=28), unstyled paragraph \
         should get font_size from one of them. Got: {:?}",
        font_size
    );

    // Similarly, color should be from one of the two defaults.
    let color = run.style_props.color.as_deref();
    assert!(
        color == Some("FF0000") || color == Some("0000FF"),
        "with two default paragraph styles, color should be from one of them. Got: {:?}",
        color
    );
}

// ============================================================================
// 6. basedOn pointing to non-existent styleId (§17.7.4.3)
//
// A style has basedOn pointing to "NonExistentParent". The code should
// handle this gracefully (not crash) and the style's own properties
// should still be available.
// ============================================================================

/// §17.7.4.3: basedOn pointing to non-existent styleId. Style's own
/// properties should still resolve correctly.
#[test]
fn based_on_nonexistent_does_not_crash() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "based-on-nonexistent");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Orphan style with broken basedOn");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "OrphanStyle sets sz=28 — should still resolve despite broken basedOn chain."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("00FF00"),
        "OrphanStyle sets color=00FF00 — should still resolve despite broken basedOn."
    );
}

// ============================================================================
// 7. Circular basedOn chain (§17.7.4.3)
//
// CycleA basedOn CycleB, CycleB basedOn CycleA. The code has cycle
// detection (resolve_chain uses visited set). Test that it doesn't
// infinite loop and that properties resolve reasonably.
// ============================================================================

/// §17.7.4.3: CycleA basedOn CycleB. Should resolve CycleA's own props
/// plus CycleB's props (before cycle detection stops the chain).
#[test]
fn circular_based_on_cycle_a() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "circular-based-on");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "CycleA style run");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    // CycleA sets sz=24 and bold. CycleB sets color=0000FF.
    // The chain is CycleA -> CycleB -> (CycleA again, cycle stops).
    // So CycleA should get its own sz=24, bold, plus CycleB's color.
    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "CycleA sets sz=24, should resolve despite circular basedOn."
    );
    assert!(
        run.marks.contains(&Mark::Bold),
        "CycleA sets bold=on, should resolve despite circular basedOn."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "CycleA basedOn CycleB — should inherit color=0000FF from CycleB \
         (resolved before cycle detection stops the chain)."
    );
}

/// §17.7.4.3: CycleB basedOn CycleA. Should resolve CycleB's own props
/// plus CycleA's props (before cycle detection stops the chain).
#[test]
fn circular_based_on_cycle_b() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "circular-based-on");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "CycleB style run");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    // CycleB sets color=0000FF. CycleA sets sz=24 and bold.
    // Chain is CycleB -> CycleA -> (CycleB again, cycle stops).
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "CycleB sets color=0000FF, should resolve despite circular basedOn."
    );
    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "CycleB basedOn CycleA — should inherit sz=24 from CycleA \
         (resolved before cycle detection stops)."
    );
    assert!(
        run.marks.contains(&Mark::Bold),
        "CycleB basedOn CycleA — should inherit bold from CycleA."
    );
}

// ============================================================================
// 8. Cross-type basedOn (§17.7.4.3)
//
// Paragraph style CrossTypePara has basedOn pointing to character style
// CharParent. Per §17.7.4.3, this cross-type reference should be ignored
// (the chain stops at the type mismatch).
// ============================================================================

/// §17.7.4.3: CrossTypePara basedOn CharParent (character style). The
/// cross-type reference should be ignored — CharParent's color and sz
/// should NOT leak into the paragraph style.
#[test]
fn cross_type_based_on_ignored() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "cross-type-based-on");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Cross type basedOn para");
    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    // CrossTypePara sets bold in its own rPr. CharParent (char style) sets
    // color=FF0000 and sz=32. The cross-type basedOn should be ignored.
    assert!(
        run.marks.contains(&Mark::Bold),
        "CrossTypePara sets bold=on in its own rPr — should still work."
    );

    // CharParent's color should NOT leak through the cross-type basedOn.
    assert_eq!(
        run.style_props.color.as_deref(),
        None,
        "CrossTypePara basedOn CharParent (character style) — per §17.7.4.3, \
         cross-type basedOn is ignored. CharParent's color=FF0000 should NOT \
         leak into the paragraph style."
    );

    // CharParent's font_size (32) should NOT leak through the cross-type basedOn.
    // The template's docDefaults rPr has sz=22, which is the expected fallback.
    assert_ne!(
        run.style_props.font_size,
        Some(32),
        "CrossTypePara basedOn CharParent — CharParent's sz=32 should NOT \
         leak into the paragraph style per §17.7.4.3."
    );
}

// ============================================================================
// 9. docDefaults pPr contextualSpacing (§17.7.5 + §17.3.1.9)
//
// Verifies that docDefaults pPr contextualSpacing=true is resolved for
// unstyled paragraphs, and that styles can override it to false.
// ============================================================================

/// §17.7.5: Unstyled paragraph should get contextualSpacing=true from
/// docDefaults pPr.
#[test]
fn docdefaults_ppr_contextual_spacing_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-contextual");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled contextual from docDefaults");

    // Verifies that resolve_effective_contextual_spacing consults ppr_defaults.
    assert_eq!(
        p.contextual_spacing,
        Some(true),
        "unstyled paragraph should get contextualSpacing=true from docDefaults pPr. \
         Per §17.7.5, docDefaults provides base paragraph properties."
    );
}

/// §17.3.1.9: Style with contextualSpacing=false should override docDefaults.
#[test]
fn docdefaults_ppr_contextual_spacing_style_overrides() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "docdefaults-ppr-contextual");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "NoCtxStyle overrides docDefaults");

    assert_eq!(
        p.contextual_spacing,
        Some(false),
        "NoCtxStyle sets contextualSpacing=false, should override docDefaults."
    );
}

// ============================================================================
// 10. Normal basedOn — paragraph property inheritance (§17.7.4.3 + §17.7.4.17)
//
// Normal basedOn SpacingBase. SpacingBase sets after=200, before=100,
// jc=center. Normal overrides before=0. An unstyled paragraph should get:
//   spacing_before=0 (Normal), spacing_after=200 (SpacingBase), jc=center (SpacingBase)
// ============================================================================

/// §17.7.4.3: Normal basedOn SpacingBase. Unstyled paragraph should get
/// spacing_after=200 inherited from SpacingBase through Normal's basedOn chain.
#[test]
fn normal_based_on_ppr_spacing_inherited() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-based-on-ppr");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Implicit Normal inherits from SpacingBase");

    let spacing = p
        .spacing
        .as_ref()
        .expect("implicit Normal paragraph should have spacing");

    // SpacingBase sets after=200. Normal doesn't override after.
    // Per §17.7.4.3, Normal inherits after from SpacingBase.
    assert_eq!(
        spacing.after,
        Some(200),
        "Normal basedOn SpacingBase — after=200 should be inherited from SpacingBase. \
         Per §17.7.4.3, basedOn chain provides parent properties."
    );
}

/// §17.7.4.3: Normal overrides before=0 (SpacingBase sets before=100).
#[test]
fn normal_based_on_ppr_spacing_overridden() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-based-on-ppr");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Implicit Normal inherits from SpacingBase");

    let spacing = p
        .spacing
        .as_ref()
        .expect("implicit Normal paragraph should have spacing");

    // Normal sets before=0, overriding SpacingBase's before=100.
    assert_eq!(
        spacing.before,
        Some(0),
        "Normal sets before=0, overriding SpacingBase's before=100. \
         Per §17.7.4.3, child style values override parent per-property."
    );
}

/// §17.7.4.3 + §17.7.4.17: Normal basedOn SpacingBase. SpacingBase sets
/// jc=center. Normal doesn't set jc. Unstyled paragraph should get center.
#[test]
fn normal_based_on_ppr_alignment_inherited() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-based-on-ppr");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Implicit Normal inherits from SpacingBase");

    // SpacingBase sets jc=center. Normal doesn't override it.
    // Alignment should be inherited through Normal's basedOn chain.
    assert_eq!(
        p.align,
        Some(Alignment::Center),
        "Normal basedOn SpacingBase — jc=center should be inherited from SpacingBase. \
         Per §17.7.4.3, unoverridden parent properties are inherited."
    );
}
