//! Spec-compliance tests: Footer Inheritance Chains (ECMA-376 section 17.10.2)
//!
//! Per ECMA-376 section 17.10.2: when a section omits a footerReference for a
//! given kind, it inherits that kind from the preceding section. Inheritance
//! is per-kind -- a section can declare "first" while inheriting "default".
//!
//! These tests verify footer inheritance across 3+ sections, mirroring
//! the header inheritance chain tests in spec_section_constraints.rs.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/section-footer-chains/create_fixtures.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-footer-chains";

// -- helpers ----------------------------------------------------------------

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&stemma::SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(
    blocks: &'a [BlockNode],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// Test 1: Three-section footer inheritance (partial per-kind)
// ==========================================================================

/// ECMA-376 section 17.10.2: Per-kind footer inheritance across 3 sections.
///
/// S1: default + first footers (titlePg=true).
/// S2: only first footer (titlePg=true) — inherits default from S1.
/// S3 (body): declares nothing (titlePg=true) — inherits both from S2.
#[test]
fn spec_three_section_footer_inheritance() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "three-section-footer-inheritance");

    // 3 footer parts in the document
    assert_eq!(doc.footers.len(), 3, "should have 3 footer parts");

    let mid_sections = section_paragraphs(&doc);
    assert_eq!(mid_sections.len(), 2, "should have 2 mid-document sections");

    let s1_sp = mid_sections[0];
    let s2_sp = mid_sections[1];
    let s3_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body section properties");

    // S1: 2 effective footer refs (default + first)
    assert_eq!(
        s1_sp.footer_refs.len(),
        2,
        "S1 should have 2 footer refs, got {:?}",
        s1_sp.footer_refs
    );

    // S2: 2 effective footer refs (inherited default from S1 + own first)
    assert_eq!(
        s2_sp.footer_refs.len(),
        2,
        "S2 should have 2 footer refs (own first + inherited default), got {:?}",
        s2_sp.footer_refs
    );

    // S3: 2 effective footer refs (inherited from S2)
    assert_eq!(
        s3_sp.footer_refs.len(),
        2,
        "S3 should have 2 footer refs (both inherited), got {:?}",
        s3_sp.footer_refs
    );

    // S2's default part_path == S1's default part_path (inherited)
    let s1_default = s1_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S1 should have a Default footer ref");
    let s2_default = s2_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have a Default footer ref (inherited from S1)");
    assert_eq!(
        s1_default.part_path, s2_default.part_path,
        "S2 should inherit S1's default footer"
    );

    // S2's first part_path != S1's first part_path (overridden)
    let s1_first = s1_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S1 should have a First footer ref");
    let s2_first = s2_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S2 should have a First footer ref");
    assert_ne!(
        s1_first.part_path, s2_first.part_path,
        "S2 should override S1's first footer"
    );

    // S3 inherits exactly what S2 has
    let s3_default = s3_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S3 should have a Default footer ref (inherited)");
    let s3_first = s3_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S3 should have a First footer ref (inherited)");
    assert_eq!(
        s3_default.part_path, s2_default.part_path,
        "S3 inherits default footer from S2"
    );
    assert_eq!(
        s3_first.part_path, s2_first.part_path,
        "S3 inherits first footer from S2"
    );

    // Verify the actual content of inherited footers via story lookup
    let s3_default_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s3_default.part_path)
        .expect("should find footer story for S3's inherited default footer");
    let text = blocks_text(&s3_default_story.blocks);
    assert!(
        text.contains("S1 Default Footer"),
        "S3's inherited default footer should contain 'S1 Default Footer', got: '{}'",
        text
    );

    let s3_first_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s3_first.part_path)
        .expect("should find footer story for S3's inherited first footer");
    let text = blocks_text(&s3_first_story.blocks);
    assert!(
        text.contains("S2 First Footer"),
        "S3's inherited first footer should contain 'S2 First Footer', got: '{}'",
        text
    );
}

// ==========================================================================
// Test 2: Three-section footer override chain
// ==========================================================================

/// ECMA-376 section 17.10.2: Override propagation across 3 sections.
///
/// S1: default footer ("S1 Default Footer").
/// S2: default footer ("S2 Default Footer") — overrides S1.
/// S3 (body): declares nothing — should inherit S2's default (NOT S1's).
#[test]
fn spec_three_section_footer_override_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "three-section-footer-override-chain");

    // 2 footer parts in the document
    assert_eq!(doc.footers.len(), 2, "should have 2 footer parts");

    let mid_sections = section_paragraphs(&doc);
    assert_eq!(mid_sections.len(), 2, "should have 2 mid-document sections");

    let s1_sp = mid_sections[0];
    let s2_sp = mid_sections[1];
    let s3_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body section properties");

    // S1: 1 footer ref (default)
    assert_eq!(
        s1_sp.footer_refs.len(),
        1,
        "S1 should have 1 footer ref, got {:?}",
        s1_sp.footer_refs
    );

    // S2: 1 footer ref (own default, overriding S1)
    assert_eq!(
        s2_sp.footer_refs.len(),
        1,
        "S2 should have 1 footer ref, got {:?}",
        s2_sp.footer_refs
    );

    let s1_default = s1_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S1 should have a Default footer ref");
    let s2_default = s2_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have a Default footer ref");

    // S2's default != S1's default (overridden, not inherited)
    assert_ne!(
        s1_default.part_path, s2_default.part_path,
        "S2 should override S1's default footer, not inherit it"
    );

    // S3: 1 footer ref (inherited from S2)
    assert_eq!(
        s3_sp.footer_refs.len(),
        1,
        "S3 should have 1 footer ref (inherited from S2), got {:?}",
        s3_sp.footer_refs
    );

    let s3_default = s3_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S3 should have a Default footer ref (inherited)");

    // S3's default == S2's default (inherited from S2, NOT S1)
    assert_eq!(
        s3_default.part_path, s2_default.part_path,
        "S3 should inherit S2's default footer (not S1's). S3 part_path={}, S2 part_path={}, S1 part_path={}",
        s3_default.part_path, s2_default.part_path, s1_default.part_path
    );

    // Verify the content: S3's footer should be "S2 Default Footer"
    let s3_default_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s3_default.part_path)
        .expect("should find footer story for S3's inherited default footer");
    let text = blocks_text(&s3_default_story.blocks);
    assert!(
        text.contains("S2 Default Footer"),
        "S3's inherited default footer should contain 'S2 Default Footer', got: '{}'",
        text
    );
}

// ==========================================================================
// Test 3: Mixed header/footer inheritance across 3 sections
// ==========================================================================

/// ECMA-376 section 17.10.2: Mixed header and footer inheritance.
///
/// S1: default header + default footer.
/// S2: declares default header only — inherits footer from S1.
/// S3 (body): declares default footer only — inherits header from S2.
///
/// This tests that header and footer inheritance are independent: a section
/// can override one while inheriting the other.
#[test]
fn spec_mixed_header_footer_three_sections() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-three-sections");

    let mid_sections = section_paragraphs(&doc);
    assert_eq!(mid_sections.len(), 2, "should have 2 mid-document sections");

    let s1_sp = mid_sections[0];
    let s2_sp = mid_sections[1];
    let s3_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body section properties");

    // -- S1: 1 header ref + 1 footer ref --
    assert_eq!(
        s1_sp.header_refs.len(),
        1,
        "S1 should have 1 header ref, got {:?}",
        s1_sp.header_refs
    );
    assert_eq!(
        s1_sp.footer_refs.len(),
        1,
        "S1 should have 1 footer ref, got {:?}",
        s1_sp.footer_refs
    );

    let s1_header = s1_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S1 should have a Default header ref");
    let s1_footer = s1_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S1 should have a Default footer ref");

    // -- S2: 1 header ref (own) + 1 footer ref (inherited from S1) --
    assert_eq!(
        s2_sp.header_refs.len(),
        1,
        "S2 should have 1 header ref, got {:?}",
        s2_sp.header_refs
    );
    assert_eq!(
        s2_sp.footer_refs.len(),
        1,
        "S2 should have 1 footer ref (inherited from S1), got {:?}",
        s2_sp.footer_refs
    );

    let s2_header = s2_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have a Default header ref");
    let s2_footer = s2_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have a Default footer ref (inherited from S1)");

    // S2's header is its own (different from S1)
    assert_ne!(
        s1_header.part_path, s2_header.part_path,
        "S2 should have its own header, not inherited from S1"
    );

    // S2's footer is inherited from S1
    assert_eq!(
        s1_footer.part_path, s2_footer.part_path,
        "S2 should inherit S1's default footer"
    );

    // -- S3: 1 header ref (inherited from S2) + 1 footer ref (own) --
    assert_eq!(
        s3_sp.header_refs.len(),
        1,
        "S3 should have 1 header ref (inherited from S2), got {:?}",
        s3_sp.header_refs
    );
    assert_eq!(
        s3_sp.footer_refs.len(),
        1,
        "S3 should have 1 footer ref (own), got {:?}",
        s3_sp.footer_refs
    );

    let s3_header = s3_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S3 should have a Default header ref (inherited from S2)");
    let s3_footer = s3_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S3 should have a Default footer ref (own)");

    // S3's header is inherited from S2
    assert_eq!(
        s3_header.part_path, s2_header.part_path,
        "S3 should inherit S2's default header"
    );

    // S3's footer is its own (different from S1/S2's)
    assert_ne!(
        s3_footer.part_path, s1_footer.part_path,
        "S3 should have its own footer, not inherited from S1"
    );

    // Verify content of inherited stories
    let s2_footer_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s2_footer.part_path)
        .expect("should find footer story for S2's inherited footer");
    let text = blocks_text(&s2_footer_story.blocks);
    assert!(
        text.contains("S1 Default Footer"),
        "S2's inherited footer should contain 'S1 Default Footer', got: '{}'",
        text
    );

    let s3_header_story = doc
        .headers
        .iter()
        .find(|h| h.part_name == s3_header.part_path)
        .expect("should find header story for S3's inherited header");
    let text = blocks_text(&s3_header_story.blocks);
    assert!(
        text.contains("S2 Default Header"),
        "S3's inherited header should contain 'S2 Default Header', got: '{}'",
        text
    );

    let s3_footer_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s3_footer.part_path)
        .expect("should find footer story for S3's own footer");
    let text = blocks_text(&s3_footer_story.blocks);
    assert!(
        text.contains("S3 Default Footer"),
        "S3's own footer should contain 'S3 Default Footer', got: '{}'",
        text
    );
}
