//! Spec-compliance tests: Violations found during Pandoc codebase audit
//!
//! These tests encode OOXML spec constraints that our implementation currently
//! violates, discovered by comparing our DOCX pipeline against Pandoc's
//! battle-tested reader/writer.
//!
//! Tests marked `#[ignore]` document known gaps — they encode the *correct*
//! spec behavior and are expected to fail against the current implementation.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_pandoc_audit.py`.

use std::io::{Cursor, Read as _};

use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
use xmltree::{Element, XMLNode};
use zip::ZipArchive;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/pandoc-audit";

// ── helpers ──────────────────────────────────────────────────────────────

fn extract_part(docx_bytes: &[u8], part: &str) -> Option<String> {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = match zip.by_name(part) {
        Ok(f) => f,
        Err(_) => return None,
    };
    let mut out = String::new();
    file.read_to_string(&mut out).expect("read part");
    Some(out)
}

fn parse_xml(xml: &str) -> Element {
    Element::parse(Cursor::new(xml.as_bytes())).expect("parse XML")
}

fn local_name(name: &str) -> &str {
    match name.rsplit_once(':') {
        Some((_, local)) => local,
        None => name,
    }
}

/// Run diff_and_redline on a before/after DOCX pair, export as Redline, return raw bytes.
fn redline_export(before_path: &str, after_path: &str) -> Vec<u8> {
    let before = std::fs::read(before_path).unwrap_or_else(|e| panic!("read {before_path}: {e}"));
    let after = std::fs::read(after_path).unwrap_or_else(|e| panic!("read {after_path}: {e}"));

    let runtime = SimpleRuntime::new();
    let ib = runtime.import_docx(&before).expect("import before");
    let ia = runtime.import_docx(&after).expect("import after");

    let meta = TransactionMeta {
        author: "spec_pandoc_audit".to_string(),
        reason: Some("pandoc-audit spec test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&ib.doc_handle, &ia.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");

    runtime
        .export_docx(&ib.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

/// Import a single DOCX fixture and immediately export it (roundtrip), returning raw bytes.
fn roundtrip_export(fixture_path: &str) -> Vec<u8> {
    let bytes = std::fs::read(fixture_path).unwrap_or_else(|e| panic!("read {fixture_path}: {e}"));

    let runtime = SimpleRuntime::new();
    let import = runtime.import_docx(&bytes).expect("import");

    runtime
        .export_docx(&import.doc_handle, ExportMode::Redline)
        .expect("export")
}

/// Recursively find all elements matching a local tag name.
fn find_all_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if local_name(&root.name) == tag {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_elements(el, tag, out);
        }
    }
}

// =========================================================================
// 1) CT_Numbering: abstractNum elements must precede num elements (Annex A)
// =========================================================================
//
// ECMA-376 Annex A, CT_Numbering:
//
//   <xsd:complexType name="CT_Numbering">
//     <xsd:sequence>
//       <xsd:element name="numPicBullet" ... minOccurs="0" maxOccurs="unbounded"/>
//       <xsd:element name="abstractNum"  ... minOccurs="0" maxOccurs="unbounded"/>
//       <xsd:element name="num"          ... minOccurs="0" maxOccurs="unbounded"/>
//     </xsd:sequence>
//   </xsd:complexType>
//
// The xsd:sequence constraint requires ALL abstractNum elements to appear
// before ALL num elements. When merge_target_numbering appends new
// (abstractNum, num) pairs to the end of an existing numbering.xml that
// already contains num elements, the interleaved result violates this
// sequence constraint.

/// ECMA-376 Annex A: After any export, numbering.xml must have all
/// abstractNum elements before all num elements (CT_Numbering sequence
/// constraint).
///
/// This test roundtrips a document with numbering and verifies the output
/// maintains correct ordering. Currently passes because roundtrip preserves
/// the original numbering.xml ordering.
///
/// Note: The latent bug in merge_target_numbering (which appends
/// (abstractNum, num) pairs after existing num elements) is currently
/// unreachable through diff_and_redline because the merge pipeline
/// materializes numbering as literal_prefix before merge_target_numbering
/// runs. If the pipeline is changed to preserve numbering on merged
/// paragraphs (as the code comment suggests was the intent), the
/// interleaving violation would surface. See runtime.rs:1287-1321.
#[test]
fn spec_ct_numbering_abstractnum_before_num_after_roundtrip() {
    let fixture_path = format!("{FIXTURES}/numbering-merge-base/input.docx");
    let output = roundtrip_export(&fixture_path);

    let numbering_xml = extract_part(&output, "word/numbering.xml")
        .expect("output DOCX should contain word/numbering.xml");
    let root = parse_xml(&numbering_xml);

    assert_numbering_ordering(&root);
}

/// ECMA-376 Annex A: After a merge, numbering.xml must maintain the
/// abstractNum-before-num ordering. This verifies the invariant holds
/// after diff_and_redline.
#[test]
fn spec_ct_numbering_abstractnum_before_num_after_merge() {
    let base_path = format!("{FIXTURES}/numbering-merge-base/input.docx");
    let target_path = format!("{FIXTURES}/numbering-merge-target/input.docx");

    let output = redline_export(&base_path, &target_path);

    let numbering_xml = extract_part(&output, "word/numbering.xml")
        .expect("output DOCX should contain word/numbering.xml");
    let root = parse_xml(&numbering_xml);

    assert_numbering_ordering(&root);
}

fn assert_numbering_ordering(root: &Element) {
    // Collect the sequence of top-level element tag names (local names only).
    let child_tags: Vec<&str> = root
        .children
        .iter()
        .filter_map(|c| {
            if let XMLNode::Element(el) = c {
                Some(local_name(&el.name))
            } else {
                None
            }
        })
        .collect();

    // Verify: once we see the first "num", no "abstractNum" should follow.
    let mut seen_num = false;
    for (i, tag) in child_tags.iter().enumerate() {
        match *tag {
            "num" => seen_num = true,
            "abstractNum" if seen_num => {
                panic!(
                    "CT_Numbering sequence violation (ECMA-376 Annex A): \
                     abstractNum at position {i} appears after a num element.\n\
                     Full sequence: {child_tags:?}\n\
                     Per the XSD, all abstractNum elements must precede all num elements."
                );
            }
            _ => {}
        }
    }
}

// =========================================================================
// 2) CT_Tc: last child of w:tc must be w:p, not w:tbl (§17.4.65)
// =========================================================================
//
// ECMA-376 §17.4.65 (tc — Table Cell):
//
//   "If a table cell does not include at least one block-level element,
//    then this document shall be considered corrupt."
//
// CT_Tc (Annex A):
//
//   <xsd:sequence>
//     <xsd:element name="tcPr" ... minOccurs="0" maxOccurs="1"/>
//     <xsd:group ref="EG_BlockLevelElts" minOccurs="1" maxOccurs="unbounded"/>
//   </xsd:sequence>
//
// While the XSD allows any block-level element (paragraph or table) as the
// last child, Word requires the last child of w:tc to be w:p. A nested
// w:tbl as the final element causes document corruption in Word 2007–2010
// and validation failures in later versions.
//
// Our serializer guards against empty cells (emitting a bare w:p), but does
// NOT append a trailing w:p when the last block is a nested table.

/// ECMA-376 §17.4.65: After serializing a document with a nested table
/// as the last element in a cell, the output should have a trailing w:p
/// after the nested w:tbl to satisfy Word's content model requirement.
///
/// Uses a self-diff (identical before/after) to force the document through
/// the serialization pipeline, which is where the fix applies.
#[test]
fn spec_ct_tc_trailing_paragraph_after_nested_table() {
    let fixture_path = format!("{FIXTURES}/nested-table-in-cell/input.docx");
    let output = redline_export(&fixture_path, &fixture_path);

    let doc_xml = extract_part(&output, "word/document.xml")
        .expect("output DOCX should contain word/document.xml");
    let root = parse_xml(&doc_xml);

    // Find all w:tc elements in the output.
    let mut tc_elements = Vec::new();
    find_all_elements(&root, "tc", &mut tc_elements);

    assert!(
        !tc_elements.is_empty(),
        "Output document should contain at least one table cell"
    );

    for (idx, tc) in tc_elements.iter().enumerate() {
        // Get the last element child of this tc (skipping text nodes).
        let element_children: Vec<&Element> = tc
            .children
            .iter()
            .filter_map(|c| {
                if let XMLNode::Element(el) = c {
                    Some(el)
                } else {
                    None
                }
            })
            .collect();

        // Check if this cell contains a nested table.
        let has_nested_table = element_children
            .iter()
            .any(|el| local_name(&el.name) == "tbl");

        if !has_nested_table {
            continue;
        }

        // For cells with nested tables, the last element child must be w:p.
        let last = element_children
            .last()
            .unwrap_or_else(|| panic!("tc[{idx}] has no element children"));

        let last_tag = local_name(&last.name);
        assert_eq!(
            last_tag,
            "p",
            "ECMA-376 §17.4.65 / Word compat: tc[{idx}] contains a nested table \
             but its last element child is <w:{last_tag}>, not <w:p>. \
             Word requires the last child of w:tc to be w:p. \
             The serializer should append an empty <w:p/> after nested tables.\n\
             Cell children: {:?}",
            element_children
                .iter()
                .map(|el| local_name(&el.name))
                .collect::<Vec<_>>()
        );
    }
}

/// Verify the fixture itself has the expected structure (nested table, no trailing p).
/// This test confirms the fixture is correctly constructed for the spec test above.
#[test]
fn spec_ct_tc_fixture_has_nested_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nested-table-in-cell");

    // The document should have an outer table.
    let outer_table = doc
        .blocks
        .iter()
        .find_map(|b| match &b.block {
            stemma::BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain an outer table");

    // The first cell should contain blocks, at least one of which is a table.
    let cell = &outer_table.rows[0].cells[0];
    let has_nested_table = cell
        .blocks
        .iter()
        .any(|b| matches!(b, stemma::BlockNode::Table(_)));

    assert!(
        has_nested_table,
        "First cell should contain a nested table. Cell blocks: {:?}",
        cell.blocks
            .iter()
            .map(|b| match b {
                stemma::BlockNode::Paragraph(_) => "Paragraph",
                stemma::BlockNode::Table(_) => "Table",
                stemma::BlockNode::OpaqueBlock(_) => "OpaqueBlock",
            })
            .collect::<Vec<_>>()
    );
}
