//! Auto-generated by the spec-word-compliance workflow.
//!
//! Area: "Footnote/endnote reference plumbing and content stories".
//!
//! Each `#[test]` encodes a behavioural constraint mined from ECMA-376 /
//! ISO 29500-1 / MS-OI29500 about how Word consumes and round-trips
//! footnote/endnote *reference* runs in the body story. A FAILING assertion
//! means stemma diverges from Word — i.e. it encodes a REAL Word-compliance
//! gap, not a thing to be "made to pass" by weakening the test. Fix the engine
//! at the source, or accept the failure as a confirmed finding.
//!
//! Methodology guardrails honoured here:
//!   * `xmlContains` / `xmlOmits` assertions run against `reserialize()`, which
//!     reflects stemma's verbatim-preservation contract (untouched opaque
//!     content is round-tripped byte-verbatim). They are used ONLY for "the
//!     reference run and its id/style survive serialization", which IS what the
//!     verbatim contract promises.
//!   * Consumption semantics ("the body text excludes the note story",
//!     "reject-all == baseline") are asserted on the READ side via
//!     `read_accepted()` / `read_rejected()` + `to_text()`.
//!   * Word's narrower note-id ceiling (<=32767) is an "opens-clean" validity
//!     question, asserted via `stemma::api::validate`.

use std::io::{Cursor, Read, Write};
use zip::write::FileOptions;

// ─── Prelude: minimal-docx plumbing (mirrors the shared spec-suite prelude) ───

/// Build a valid minimal `.docx`. `body_xml` is the inner content of
/// `<w:body>…</w:body>` (paragraphs etc.); `extra_parts` are additional
/// `(part_name, xml)` entries placed into the zip, with a matching content-type
/// Override emitted for the known WordprocessingML parts (styles, numbering).
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );

    // Build content-type overrides for extra parts we understand.
    let mut overrides = String::from(
        r#"<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>"#,
    );
    for (name, _) in extra_parts {
        let ct = match *name {
            "word/styles.xml" => {
                Some("application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml")
            }
            "word/numbering.xml" => {
                Some("application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml")
            }
            "word/footnotes.xml" => {
                Some("application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml")
            }
            "word/endnotes.xml" => {
                Some("application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml")
            }
            _ => None,
        };
        if let Some(ct) = ct {
            overrides.push_str(&format!(
                r#"<Override PartName="/{name}" ContentType="{ct}"/>"#
            ));
        }
    }

    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>{overrides}</Types>"#
    );
    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;
    let doc_rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>"#;

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (name, xml) in extra_parts {
            zip.start_file(*name, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip a `.docx` and return the contents of `word/document.xml`.
fn document_xml_of(docx: &[u8]) -> String {
    let mut zip = zip::ZipArchive::new(Cursor::new(docx)).expect("open docx zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("word/document.xml present");
    let mut s = String::new();
    file.read_to_string(&mut s).expect("read document.xml");
    s
}

/// Parse → serialize (no-op roundtrip) → return the re-emitted `word/document.xml`.
/// For UNTOUCHED content this reflects stemma's verbatim-preservation contract.
fn reserialize(bytes: &[u8]) -> String {
    let doc = stemma::api::Document::parse(bytes).expect("parse");
    let out = doc
        .serialize(&stemma::ExportOptions::default())
        .expect("serialize");
    document_xml_of(&out)
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn footnote_reference_run_preserves_rstyle_and_id_through_roundtrip() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"<w:footnoteReference w:id="1""#),
        "ECMA-376 §17.11.14 / ISO 29500-1 §17.11.14 — refs: the footnoteReference w:id linkage is load-bearing and stemma preserves untouched opaque content verbatim, so the id must survive the roundtrip; got XML:\n{xml}"
    );
    assert!(
        xml.contains(r#"w:val="FootnoteReference""#),
        "ECMA-376 §17.11.14 / ISO 29500-1 §17.11.14 — refs: canonical markup binds the reference run to the FootnoteReference character style; a verbatim roundtrip must retain it; got XML:\n{xml}"
    );
}

// check_footnote_endnote_id_range validates the in-body
// footnoteReference/endnoteReference ids (§17.11.14), not just the note
// definitions — an id past Word's 32767 ceiling is flagged.
#[test]
fn footnote_reference_id_above_word_max_not_clean() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Referenced text.</w:t></w:r><w:r><w:footnoteReference w:id="40000"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let report = stemma::api::validate(&b);
    assert!(
        !report.ok,
        "MS-OI29500 §2.1.300/§2.1.302, ISO 29500-1 §17.11.14/§17.18.10 — refs: Word only accepts note ids in [-2147483648, 32767]; id=40000 is outside Word's range so the document must NOT open clean (validate must report an error). Got ok={} issues={:?}",
        report.ok, report.issues
    );
}

// endnoteReference ids are range-checked too (same rule).
#[test]
fn endnote_reference_id_above_word_max_not_clean() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Referenced text.</w:t></w:r><w:r><w:endnoteReference w:id="40000"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let report = stemma::api::validate(&b);
    assert!(
        !report.ok,
        "MS-OI29500 §2.1.300/§2.1.302, ISO 29500-1 §17.11.7/§17.18.10 — refs: Word's endnote id ceiling is 32767 (same as footnotes); endnoteReference id=40000 is outside Word's range so the document must NOT open clean. Got ok={} issues={:?}",
        report.ok, report.issues
    );
}

#[test]
fn footnote_reference_custommarkfollows_false_preserved_verbatim() {
    let body = r#"<w:p><w:r><w:t>Text</w:t></w:r><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:customMarkFollows="0" w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:customMarkFollows="0""#),
        "ECMA-376 §17.11.14, Annex A CT_FtnEdnRef — refs: verbatim-preservation contract means an explicitly authored, default-equivalent customMarkFollows=\"0\" is opaque markup the engine must round-trip unchanged, not collapse to the omitted default; got XML:\n{xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "ECMA-376 §17.11.14, Annex A CT_FtnEdnRef — refs: ST_OnOff admits 0/false, so customMarkFollows=\"0\" on CT_FtnEdnRef is schema-valid and must open without repair. Got ok={} issues={:?}",
        report.ok, report.issues
    );
}

#[test]
fn footnote_reference_reserved_id_value_preserved() {
    let body = r#"<w:p><w:r><w:t>Text</w:t></w:r><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:id="7"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:footnoteReference w:id="7""#),
        "ECMA-376 §17.11.10/§17.11.14, Annex A ST_DecimalNumber — refs: the reference id is the stable match key into the notes part; the engine must round-trip the exact authored id (7), not renumber it; got XML:\n{xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "ECMA-376 §17.11.14, Annex A CT_FtnEdnRef — refs: id=7 is a valid ST_DecimalNumber for CT_FtnEdnRef, so the markup is schema-valid and opens without repair. Got ok={} issues={:?}",
        report.ok, report.issues
    );
}

#[test]
fn endnote_reference_custommarkfollows_preserved_verbatim() {
    let body = r#"<w:p><w:r><w:t>This text is followed by an endnote</w:t></w:r><w:r><w:rPr><w:rStyle w:val="EndnoteReference"/></w:rPr><w:endnoteReference w:customMarkFollows="true" w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:customMarkFollows="true""#),
        "ECMA-376 §17.11.7 / ISO 29500-1 §17.11.7, Annex A CT_FtnEdnRef — refs: customMarkFollows is an authored numbering-suppression flag on CT_FtnEdnRef; a verbatim-preserving engine must re-emit it on reserialize for endnotes just as for footnotes; got XML:\n{xml}"
    );
    assert!(
        xml.contains("w:endnoteReference"),
        "ECMA-376 §17.11.7 / ISO 29500-1 §17.11.7 — refs: the endnoteReference run must survive the roundtrip intact (the reference linkage is the body half of the endnote per §17.11); got XML:\n{xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "ECMA-376 §17.11.7, Annex A CT_FtnEdnRef — refs: endnoteReference is CT_FtnEdnRef and customMarkFollows is an optional ST_OnOff attribute of that type, so the document is schema-valid and opens without repair. Got ok={} issues={:?}",
        report.ok, report.issues
    );
}

#[test]
fn footnote_reference_in_body_contributes_one_object_char_not_note_text() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Referenced text</w:t></w:r><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let doc = stemma::api::Document::parse(&b).expect("parse");
    let text = doc.read_accepted().unwrap().to_text();
    assert_eq!(
        text.trim(),
        "Referenced text\u{FFFC}",
        "ECMA-376 §17.11/§17.11.14 / ISO 29500-1 §17.11.14 — refs: only a reference mark sits in the body; the note story prose is separate, so the accepted body text is the run text plus exactly one object-replacement char for the anchor, never the note body. Got {text:?}"
    );
}

// NOTE: a second spec named `footnote_reference_custommarkfollows_preserved_verbatim`
// (customMarkFollows="1") appears in the SpecSet; Rust forbids duplicate test fn
// names, so it is folded into the distinctly-named test below
// (`footnote_reference_custommarkfollows_value1_preserved_verbatim`) which exercises
// the identical rule. See also `custommarkfollows_on_footnote_reference_preserved_verbatim`.
#[test]
fn footnote_reference_custommarkfollows_value1_preserved_verbatim() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:customMarkFollows="1" w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:customMarkFollows="1""#),
        "ECMA-376 §17.11.14 / ISO 29500-1 §17.11.14, §22.9.2.7 — refs: customMarkFollows controls numbering increment and is load-bearing; stemma preserves untouched opaque markup verbatim, so it must survive the roundtrip rather than be silently dropped; got XML:\n{xml}"
    );
}

#[test]
fn endnote_reference_in_body_contributes_one_object_char_not_endnote_text() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">See note</w:t></w:r><w:r><w:rPr><w:rStyle w:val="EndnoteReference"/></w:rPr><w:endnoteReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let doc = stemma::api::Document::parse(&b).expect("parse");
    let text = doc.read_accepted().unwrap().to_text();
    assert_eq!(
        text.trim(),
        "See note\u{FFFC}",
        "ECMA-376 §17.11.7/§17.11.8 / ISO 29500-1 §17.11.7 — refs: the endnote prose lives in the separate endnotes story, so the body's accepted text is the run text plus one anchor char, never the endnote body. Got {text:?}"
    );
}

#[test]
fn footnote_reference_anchor_survives_reject_all_when_not_tracked() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Baseline text</w:t></w:r><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let doc = stemma::api::Document::parse(&b).expect("parse");
    let rejected = doc.read_rejected().unwrap().to_text();
    assert_eq!(
        rejected.trim(),
        "Baseline text\u{FFFC}",
        "ECMA-376 §17.11.14/§17.11 / ISO 29500-1 §17.11.14 — refs: reject-all == baseline; an untracked footnoteReference is baseline body content, so reject-all retains the run text plus the single anchor char rather than dropping the reference mark. Got {rejected:?}"
    );
    let accepted = doc.read_accepted().unwrap().to_text();
    assert_eq!(
        accepted.trim(),
        "Baseline text\u{FFFC}",
        "ECMA-376 §17.11.14 — refs: with no tracked-change wrapper, the reference mark is also present under accept-all as a single anchor. Got {accepted:?}"
    );
}

#[test]
fn footnote_and_endnote_references_coexist_as_distinct_anchors_in_one_paragraph() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">A</w:t></w:r><w:r><w:rPr><w:rStyle w:val="FootnoteReference"/></w:rPr><w:footnoteReference w:id="1"/></w:r><w:r><w:t xml:space="preserve">B</w:t></w:r><w:r><w:rPr><w:rStyle w:val="EndnoteReference"/></w:rPr><w:endnoteReference w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"<w:footnoteReference w:id="1""#),
        "ECMA-376 §17.11.14 / ISO 29500-1 §17.11 — refs: the footnoteReference and its id are preserved verbatim and must remain present after roundtrip; got XML:\n{xml}"
    );
    assert!(
        xml.contains(r#"<w:endnoteReference w:id="1""#),
        "ECMA-376 §17.11.7 / ISO 29500-1 §17.11 — refs: the endnoteReference (distinct from the footnote reference, targeting the endnotes part) and its id are preserved verbatim and must remain present after roundtrip; got XML:\n{xml}"
    );
}

#[test]
fn custommarkfollows_on_footnote_reference_preserved_verbatim() {
    let body = r#"<w:p><w:r><w:t xml:space="preserve">Custom-marked note.</w:t></w:r><w:r><w:footnoteReference w:customMarkFollows="1" w:id="1"/></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    // xmlRegex `<w:footnoteReference[^>]*w:customMarkFollows="1"[^>]*w:id="1"`
    // translated to substring checks (no regex crate available). The verbatim
    // contract round-trips the element unchanged, so the literal authored form
    // is present; we assert both attributes are inside a footnoteReference start tag.
    let has_ref_with_both = xml.match_indices("<w:footnoteReference").any(|(start, _)| {
        let tag_end = xml[start..]
            .find('>')
            .map(|e| start + e)
            .unwrap_or(xml.len());
        let tag = &xml[start..tag_end];
        tag.contains(r#"w:customMarkFollows="1""#) && tag.contains(r#"w:id="1""#)
    });
    assert!(
        has_ref_with_both,
        "ISO 29500-1 §17.11.14/§22.9.2.7 — refs [xmlRegex translated to substring]: customMarkFollows is information-bearing (numbering skip); a faithful serializer preserves it verbatim alongside the id inside the footnoteReference start tag rather than dropping it as a default; got XML:\n{xml}"
    );
    assert!(
        xml.contains(r#"w:id="1""#),
        "ISO 29500-1 §17.11.14 — refs: the reference id must remain intact through the roundtrip so the body still links to its story; got XML:\n{xml}"
    );
}
