//! Spec-compliance tests: Section Properties (ISO 29500-1 §17.6)
//!
//! These tests verify our implementation against specific OOXML section
//! property constructs (margins, section type, borders, numbering, etc.).
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, SectionProperties, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/sections";

// -- helpers ----------------------------------------------------------------
/// Collect all paragraphs that have structured section properties.
fn section_paragraphs(doc: &CanonDoc) -> Vec<&SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(blocks: &'a [BlockNode], out: &mut Vec<&'a SectionProperties>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// -- page margins (§17.6.11) ------------------------------------------------

/// ISO 29500-1 §17.6.11: pgMar attributes should be accessible in SectionProperties.
///
/// The fixture has pgMar with top=1440, bottom=1440, left=1800, right=1800,
/// header=720, footer=720, gutter=360.
#[test]
fn spec_page_margins_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "page-margins");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one paragraph with section properties"
    );

    let props = section_props[0];

    assert_eq!(props.margin_top, Some(1440));
    assert_eq!(props.margin_bottom, Some(1440));
    assert_eq!(props.margin_left, Some(1800));
    assert_eq!(props.margin_right, Some(1800));
    assert_eq!(props.header_distance, Some(720));
    assert_eq!(props.footer_distance, Some(720));
    assert_eq!(props.gutter, Some(360));
}

// -- section type (§17.6.22) ------------------------------------------------

/// ISO 29500-1 §17.6.22: Section type (continuous/nextPage/evenPage/oddPage)
/// should be captured in SectionProperties.
///
/// The fixture has three sections: nextPage, continuous, evenPage.
#[test]
fn spec_section_type_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "section-types");

    let section_props = section_paragraphs(&doc);
    assert!(
        section_props.len() >= 2,
        "should have at least 2 mid-document sections, got {}",
        section_props.len()
    );

    assert_eq!(
        section_props[0].section_type,
        Some(stemma::domain::SectionType::NextPage)
    );
    assert_eq!(
        section_props[1].section_type,
        Some(stemma::domain::SectionType::Continuous)
    );
}

// -- multi-section margins (§17.6.11) ---------------------------------------

/// ISO 29500-1 §17.6.11: Each section preserves its own margin values independently.
///
/// The fixture has two sections: section 1 with narrow margins (720 twips),
/// section 2 with wide margins (2880 twips).
#[test]
fn spec_multi_section_different_margins() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "multi-section-margins");

    let section_props = section_paragraphs(&doc);
    assert!(
        section_props.len() >= 2,
        "should have at least 2 mid-document sections, got {}",
        section_props.len()
    );

    assert_eq!(section_props[0].margin_top, Some(720));
    assert_eq!(section_props[0].margin_left, Some(720));
    assert_eq!(section_props[1].margin_top, Some(2880));
    assert_eq!(section_props[1].margin_left, Some(2880));
}

// -- page borders (§17.6.7) -------------------------------------------------

/// ISO 29500-1 §17.6.7: pgBorders should be accessible in SectionProperties.
///
/// The fixture has solid blue borders (val=single, sz=12, color=0000FF)
/// on all four edges.
#[test]
fn spec_page_borders_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "page-borders");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one paragraph with section properties"
    );

    let props = section_props[0];
    let borders = props
        .page_borders
        .as_ref()
        .expect("should have page borders");
    let top = borders.top.as_ref().expect("should have top border");
    assert_eq!(top.style, stemma::domain::BorderStyle::Single);
    assert_eq!(top.color.as_deref(), Some("0000FF"));
    assert_eq!(top.size, Some(12));
}

// -- line numbering (§17.6.8) -----------------------------------------------

/// ISO 29500-1 §17.6.8: lnNumType attributes (countBy, start, restart) should
/// be captured in SectionProperties.
///
/// The fixture has lnNumType with countBy=5, start=1, restart=newPage.
#[test]
fn spec_line_numbering_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "line-numbering");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one paragraph with section properties"
    );

    let props = section_props[0];
    let ln = props
        .line_numbering
        .as_ref()
        .expect("should have line numbering");
    assert_eq!(ln.count_by, Some(5));
    assert_eq!(ln.start, Some(1));
    assert_eq!(ln.restart.as_deref(), Some("newPage"));
}

// -- vertical alignment (§17.6.20) ------------------------------------------

/// ISO 29500-1 §17.6.20: vAlign attribute should be captured in SectionProperties.
///
/// The fixture has vAlign="center".
#[test]
fn spec_vertical_alignment_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vertical-alignment");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one paragraph with section properties"
    );

    let props = section_props[0];
    assert_eq!(props.v_align, Some(stemma::domain::SectionVAlign::Center));
}

// -- page number format (§17.6.12) ------------------------------------------

/// ISO 29500-1 §17.6.12: pgNumType attributes (fmt, start) should be captured
/// in SectionProperties.
///
/// The fixture has pgNumType with fmt=lowerRoman, start=3.
#[test]
fn spec_page_number_format_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "page-number-format");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one paragraph with section properties"
    );

    let props = section_props[0];
    let pg = props
        .page_number_type
        .as_ref()
        .expect("should have page number type");
    assert_eq!(pg.fmt.as_deref(), Some("lowerRoman"));
    assert_eq!(pg.start, Some(3));
}
