//! Spec-compliance tests: Redline output compatibility
//!
//! These tests verify that our redline DOCX output contains the correct
//! XML elements for compatibility with Word and Google Docs. Each test
//! imports a fixture, generates an identity redline, exports, and checks
//! the raw XML output for required elements.
//!
//! Covers: tblPr/tblGrid/tcPr serialization, bookmark preservation,
//! SDT content control preservation, w14:paraId/textId, w16du:dateUtc.
//!
//! Fixture DOCX files are in `testdata/spec-compliance/redline-compat/`
//! and generated by `testdata/spec-compliance/create_docs.py`.

use std::fs;
use std::io::{Cursor, Read};

use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
use xmltree::{Element, XMLNode};
use zip::ZipArchive;

const WORD_NS: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

// ── helpers ──────────────────────────────────────────────────────────────

fn redline_export_bytes(docx_bytes: &[u8]) -> Vec<u8> {
    let runtime = SimpleRuntime::new();
    let import1 = runtime.import_docx(docx_bytes).expect("import base");
    let import2 = runtime.import_docx(docx_bytes).expect("import target");
    let meta = TransactionMeta {
        author: "spec_redline_compat".to_string(),
        reason: Some("spec roundtrip test".to_string()),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&import1.doc_handle, &import2.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied, "redline should be applied");
    runtime
        .export_docx(&import1.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

fn extract_document_xml(docx_bytes: &[u8]) -> String {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("DOCX must contain word/document.xml");
    let mut out = String::new();
    file.read_to_string(&mut out)
        .expect("read word/document.xml");
    out
}

fn parse_xml(xml: &str) -> Element {
    Element::parse(Cursor::new(xml.as_bytes())).expect("parse XML")
}

fn is_w_tag(element: &Element, local: &str) -> bool {
    let name = local_name(&element.name);
    if name != local {
        return false;
    }
    if element.prefix.as_deref() == Some("w") {
        return true;
    }
    if element.namespace.as_deref() == Some(WORD_NS) {
        return true;
    }
    element.name == local || element.name == format!("w:{local}")
}

fn local_name(name: &str) -> &str {
    match name.rsplit_once(':') {
        Some((_, local)) => local,
        None => name,
    }
}

fn attr_value<'a>(element: &'a Element, qname: &str) -> Option<&'a str> {
    let (prefix, local) = split_qname(qname);

    if let Some(want_prefix) = prefix {
        for (name, value) in &element.attributes {
            if name.local_name == local && name.prefix.as_deref() == Some(want_prefix) {
                return Some(value);
            }
        }
    }

    for (name, value) in &element.attributes {
        if name.local_name == local {
            return Some(value);
        }
    }

    // Compatibility with legacy keys that were stored as plain strings.
    for (name, value) in &element.attributes {
        if name.local_name == qname {
            return Some(value);
        }
    }

    None
}

fn split_qname(qname: &str) -> (Option<&str>, &str) {
    match qname.split_once(':') {
        Some((prefix, local)) if !prefix.is_empty() && !local.is_empty() => (Some(prefix), local),
        _ => (None, qname),
    }
}

/// Find all elements with a given w: tag recursively.
fn find_all_w_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if is_w_tag(root, tag) {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_w_elements(el, tag, out);
        }
    }
}

/// Find a direct w: child element with a given tag.
fn find_w_child<'a>(parent: &'a Element, tag: &str) -> Option<&'a Element> {
    parent.children.iter().find_map(|child| match child {
        XMLNode::Element(el) if is_w_tag(el, tag) => Some(el),
        _ => None,
    })
}

// =========================================================================
// 1. TABLE PROPERTIES (tblPr, tblGrid, tcPr)
//    ISO 29500-1 §17.4
// =========================================================================

const TABLE_FIXTURE: &str =
    "testdata/spec-compliance/redline-compat/table-props-roundtrip/input.docx";

/// §17.4.59 tblPr: Table properties must survive redline roundtrip.
#[test]
fn spec_redline_preserves_tbl_pr() {
    let input = fs::read(TABLE_FIXTURE).unwrap_or_else(|e| panic!("read {TABLE_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut tbls = Vec::new();
    find_all_w_elements(&root, "tbl", &mut tbls);
    assert!(
        !tbls.is_empty(),
        "exported DOCX should contain at least one table"
    );

    let tbl = tbls[0];
    let tbl_pr = find_w_child(tbl, "tblPr").expect("table should have w:tblPr in redline output");

    // §17.4.61 tblW: table width
    let tbl_w = find_w_child(tbl_pr, "tblW").expect("tblPr should contain w:tblW");
    assert_eq!(
        attr_value(tbl_w, "w:w").or_else(|| attr_value(tbl_w, "w")),
        Some("5000"),
        "tblW width should be 5000"
    );

    // §17.4.28 jc: table alignment
    let jc = find_w_child(tbl_pr, "jc").expect("tblPr should contain w:jc");
    assert_eq!(
        attr_value(jc, "w:val").or_else(|| attr_value(jc, "val")),
        Some("center"),
        "table alignment should be center"
    );

    // §17.4.51 tblInd: table indent
    let tbl_ind = find_w_child(tbl_pr, "tblInd").expect("tblPr should contain w:tblInd");
    assert_eq!(
        attr_value(tbl_ind, "w:w").or_else(|| attr_value(tbl_ind, "w")),
        Some("360"),
        "table indent should be 360"
    );

    // §17.4.38 tblBorders
    let tbl_borders =
        find_w_child(tbl_pr, "tblBorders").expect("tblPr should contain w:tblBorders");
    for edge in ["top", "left", "bottom", "right", "insideH", "insideV"] {
        let border = find_w_child(tbl_borders, edge)
            .unwrap_or_else(|| panic!("tblBorders should have w:{edge} element"));
        assert_eq!(
            attr_value(border, "w:val").or_else(|| attr_value(border, "val")),
            Some("single"),
            "border {edge} style should be single"
        );
    }

    // §17.4.42 tblCellMar
    let tbl_cell_mar =
        find_w_child(tbl_pr, "tblCellMar").expect("tblPr should contain w:tblCellMar");
    let top = find_w_child(tbl_cell_mar, "top").expect("tblCellMar should have top margin");
    assert_eq!(
        attr_value(top, "w:w").or_else(|| attr_value(top, "w")),
        Some("72"),
        "default top cell margin should be 72"
    );
}

/// §17.4.15 tblGrid: Column widths must survive redline roundtrip.
#[test]
fn spec_redline_preserves_tbl_grid() {
    let input = fs::read(TABLE_FIXTURE).unwrap_or_else(|e| panic!("read {TABLE_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut tbls = Vec::new();
    find_all_w_elements(&root, "tbl", &mut tbls);
    let tbl = tbls[0];

    let tbl_grid =
        find_w_child(tbl, "tblGrid").expect("table should have w:tblGrid in redline output");

    let grid_cols: Vec<&Element> = tbl_grid
        .children
        .iter()
        .filter_map(|c| match c {
            XMLNode::Element(el) if is_w_tag(el, "gridCol") => Some(el),
            _ => None,
        })
        .collect();

    assert_eq!(
        grid_cols.len(),
        3,
        "tblGrid should have 3 gridCol children, got {}",
        grid_cols.len()
    );

    let widths: Vec<Option<&str>> = grid_cols
        .iter()
        .map(|gc| attr_value(gc, "w:w").or_else(|| attr_value(gc, "w")))
        .collect();
    assert_eq!(widths[0], Some("1500"), "gridCol 0 width");
    assert_eq!(widths[1], Some("2000"), "gridCol 1 width");
    assert_eq!(widths[2], Some("1500"), "gridCol 2 width");
}

/// §17.4.65 tcPr: Cell properties must survive redline roundtrip.
#[test]
fn spec_redline_preserves_tc_pr() {
    let input = fs::read(TABLE_FIXTURE).unwrap_or_else(|e| panic!("read {TABLE_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Find cell (0,0) which has explicit shading and vAlign
    let mut tbls = Vec::new();
    find_all_w_elements(&root, "tbl", &mut tbls);
    let tbl = tbls[0];

    let mut rows = Vec::new();
    find_all_w_elements(tbl, "tr", &mut rows);
    assert!(!rows.is_empty(), "table should have rows");

    let mut cells = Vec::new();
    find_all_w_elements(rows[0], "tc", &mut cells);
    assert!(!cells.is_empty(), "first row should have cells");

    let tc = cells[0];
    let tc_pr = find_w_child(tc, "tcPr").expect("cell (0,0) should have w:tcPr in redline output");

    // §17.3.5 shd: cell shading
    let shd = find_w_child(tc_pr, "shd").expect("tcPr should contain w:shd for cell (0,0)");
    assert_eq!(
        attr_value(shd, "w:fill").or_else(|| attr_value(shd, "fill")),
        Some("FFFF00"),
        "cell shading fill should be FFFF00 (yellow)"
    );

    // §17.4.84 vAlign: vertical alignment
    let v_align =
        find_w_child(tc_pr, "vAlign").expect("tcPr should contain w:vAlign for cell (0,0)");
    assert_eq!(
        attr_value(v_align, "w:val").or_else(|| attr_value(v_align, "val")),
        Some("center"),
        "cell vertical alignment should be center"
    );

    // §17.4.72 tcW: cell width
    let tc_w = find_w_child(tc_pr, "tcW").expect("tcPr should contain w:tcW for cell (0,0)");
    assert_eq!(
        attr_value(tc_w, "w:w").or_else(|| attr_value(tc_w, "w")),
        Some("1500"),
        "cell width should be 1500"
    );
}

// =========================================================================
// 2. BOOKMARKS (bookmarkStart/bookmarkEnd)
//    ISO 29500-1 §17.13.6
// =========================================================================

const BOOKMARK_FIXTURE: &str = "testdata/spec-compliance/bookmarks/bookmark-roundtrip/input.docx";

/// §17.13.6.2: bookmarkStart and bookmarkEnd must survive redline export
/// and be present in the output XML.
#[test]
fn spec_redline_preserves_bookmark_xml() {
    let input =
        fs::read(BOOKMARK_FIXTURE).unwrap_or_else(|e| panic!("read {BOOKMARK_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut bm_starts = Vec::new();
    find_all_w_elements(&root, "bookmarkStart", &mut bm_starts);

    let mut bm_ends = Vec::new();
    find_all_w_elements(&root, "bookmarkEnd", &mut bm_ends);

    // Filter out internal anchors (stemma_ prefix)
    let user_starts: Vec<_> = bm_starts
        .iter()
        .filter(|el| {
            let name = attr_value(el, "w:name")
                .or_else(|| attr_value(el, "name"))
                .unwrap_or("");
            !name.starts_with("stemma")
        })
        .collect();

    assert!(
        !user_starts.is_empty(),
        "exported DOCX should contain at least one user bookmarkStart. \
         Found {} total bookmarkStart (including internal anchors), \
         but none are user bookmarks.",
        bm_starts.len()
    );

    assert!(
        !bm_ends.is_empty(),
        "exported DOCX should contain at least one bookmarkEnd"
    );

    // Verify the bookmark has the expected name attribute
    let has_roundtrip_bm = user_starts.iter().any(|el| {
        let name = attr_value(el, "w:name")
            .or_else(|| attr_value(el, "name"))
            .unwrap_or("");
        name == "roundtrip_bookmark"
    });
    assert!(
        has_roundtrip_bm,
        "exported DOCX should contain bookmarkStart with name='roundtrip_bookmark'. \
         Found user bookmarks: {:?}",
        user_starts
            .iter()
            .map(|el| attr_value(el, "w:name")
                .or_else(|| attr_value(el, "name"))
                .unwrap_or("?"))
            .collect::<Vec<_>>()
    );
}

// =========================================================================
// 3. SDT CONTENT CONTROLS (w:sdt)
//    ISO 29500-1 §17.5.2
// =========================================================================

const BLOCK_SDT_FIXTURE: &str = "testdata/spec-compliance/content/block-sdt/input.docx";

/// §17.5.2.32: Block-level SDT must survive redline roundtrip.
/// The w:sdt element (or its content) should be present in the output.
#[test]
fn spec_redline_preserves_block_sdt() {
    let input =
        fs::read(BLOCK_SDT_FIXTURE).unwrap_or_else(|e| panic!("read {BLOCK_SDT_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);

    // The block SDT should either be preserved as w:sdt or its content
    // should be present in the output (body-level SDTs roundtrip as opaque).
    let has_sdt = xml.contains("sdt");
    let has_content = xml.contains("Content inside block SDT");

    assert!(
        has_sdt || has_content,
        "exported DOCX should preserve block SDT (either as w:sdt element \
         or with its inner text content). Neither found in output XML."
    );
}

// =========================================================================
// 4. w14:paraId / w14:textId
//    MS-DOCX §2.6.2.3/2.6.2.4
// =========================================================================

const PARA_ID_FIXTURE: &str =
    "testdata/spec-compliance/redline-compat/para-id-roundtrip/input.docx";

/// MS-DOCX §2.6.2.3: w14:paraId must survive redline roundtrip.
#[test]
fn spec_redline_preserves_para_id() {
    let input = fs::read(PARA_ID_FIXTURE).unwrap_or_else(|e| panic!("read {PARA_ID_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut paragraphs = Vec::new();
    find_all_w_elements(&root, "p", &mut paragraphs);

    let paras_with_id: Vec<_> = paragraphs
        .iter()
        .filter(|p| attr_value(p, "w14:paraId").is_some())
        .collect();

    assert!(
        paras_with_id.len() >= 2,
        "exported DOCX should have at least 2 paragraphs with w14:paraId \
         (input has 2 paragraphs with paraId). Found {}. \
         Total paragraphs: {}",
        paras_with_id.len(),
        paragraphs.len()
    );

    // Check specific IDs are preserved
    let ids: Vec<&str> = paras_with_id
        .iter()
        .filter_map(|p| attr_value(p, "w14:paraId"))
        .collect();
    assert!(
        ids.contains(&"3B2A1C4D"),
        "paraId '3B2A1C4D' should be preserved. Found: {:?}",
        ids
    );
    assert!(
        ids.contains(&"5F6E7D8C"),
        "paraId '5F6E7D8C' should be preserved. Found: {:?}",
        ids
    );
}

/// MS-DOCX §2.6.2.4: w14:textId must survive redline roundtrip.
#[test]
fn spec_redline_preserves_text_id() {
    let input = fs::read(PARA_ID_FIXTURE).unwrap_or_else(|e| panic!("read {PARA_ID_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    let mut paragraphs = Vec::new();
    find_all_w_elements(&root, "p", &mut paragraphs);

    let paras_with_text_id: Vec<_> = paragraphs
        .iter()
        .filter(|p| attr_value(p, "w14:textId").is_some())
        .collect();

    assert!(
        paras_with_text_id.len() >= 2,
        "exported DOCX should have at least 2 paragraphs with w14:textId. Found {}.",
        paras_with_text_id.len()
    );

    let ids: Vec<&str> = paras_with_text_id
        .iter()
        .filter_map(|p| attr_value(p, "w14:textId"))
        .collect();
    assert!(
        ids.contains(&"77A80E01"),
        "textId '77A80E01' should be preserved. Found: {:?}",
        ids
    );
}

/// w14 namespace must be declared on the document root.
#[test]
fn spec_redline_declares_w14_namespace() {
    let input = fs::read(PARA_ID_FIXTURE).unwrap_or_else(|e| panic!("read {PARA_ID_FIXTURE}: {e}"));
    let exported = redline_export_bytes(&input);
    let xml = extract_document_xml(&exported);

    assert!(
        xml.contains("schemas.microsoft.com/office/word/2010/wordml") || xml.contains("w14"),
        "exported DOCX should declare the w14 namespace"
    );
}

// =========================================================================
// 5. w16du:dateUtc
//    MS-DOCX §2.12
// =========================================================================

/// MS-DOCX §2.12: Tracked change elements should carry w16du:dateUtc.
///
/// Uses the simple-text sample pair which produces ins/del elements.
#[test]
fn spec_redline_has_date_utc_on_tracked_changes() {
    let before_path = std::path::PathBuf::from("testdata").join("simple-text/before.docx");
    let after_path = std::path::PathBuf::from("testdata").join("simple-text/after.docx");

    let before =
        fs::read(&before_path).unwrap_or_else(|e| panic!("read {}: {e}", before_path.display()));
    let after =
        fs::read(&after_path).unwrap_or_else(|e| panic!("read {}: {e}", after_path.display()));

    let runtime = SimpleRuntime::new();
    let import_before = runtime.import_docx(&before).expect("import before");
    let import_after = runtime.import_docx(&after).expect("import after");

    let meta = TransactionMeta {
        author: "spec_redline_compat".to_string(),
        reason: Some("dateUtc spec test".to_string()),
        timestamp_utc: Some("2025-06-01T12:00:00Z".to_string()),
    };
    let apply = runtime
        .diff_and_redline(&import_before.doc_handle, &import_after.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(apply.applied);

    let exported = runtime
        .export_docx(&import_before.doc_handle, ExportMode::Redline)
        .expect("export");
    let xml = extract_document_xml(&exported);
    let root = parse_xml(&xml);

    // Find all w:ins and w:del elements
    let mut ins_elements = Vec::new();
    find_all_w_elements(&root, "ins", &mut ins_elements);
    let mut del_elements = Vec::new();
    find_all_w_elements(&root, "del", &mut del_elements);

    assert!(
        !ins_elements.is_empty() || !del_elements.is_empty(),
        "redline should have at least one tracked change (ins or del)"
    );

    // All tracked change elements should have w16du:dateUtc
    for el in &ins_elements {
        let date_utc = attr_value(el, "w16du:dateUtc");
        assert!(
            date_utc.is_some(),
            "w:ins element should have w16du:dateUtc attribute. \
             w:date={:?}, attributes: {:?}",
            attr_value(el, "w:date"),
            el.attributes
                .keys()
                .map(|k| &k.local_name)
                .collect::<Vec<_>>()
        );
    }

    for el in &del_elements {
        let date_utc = attr_value(el, "w16du:dateUtc");
        assert!(
            date_utc.is_some(),
            "w:del element should have w16du:dateUtc attribute. \
             w:date={:?}, attributes: {:?}",
            attr_value(el, "w:date"),
            el.attributes
                .keys()
                .map(|k| &k.local_name)
                .collect::<Vec<_>>()
        );
    }

    // dateUtc value should match w:date value
    for el in ins_elements.iter().chain(del_elements.iter()) {
        let date = attr_value(el, "w:date").or_else(|| attr_value(el, "date"));
        let date_utc = attr_value(el, "w16du:dateUtc");
        if let (Some(d), Some(du)) = (date, date_utc) {
            assert_eq!(
                d, du,
                "w16du:dateUtc should match w:date on tracked change element"
            );
        }
    }
}

/// w16du namespace must be declared when tracked changes are present.
#[test]
fn spec_redline_declares_w16du_namespace() {
    let before_path = std::path::PathBuf::from("testdata").join("simple-text/before.docx");
    let after_path = std::path::PathBuf::from("testdata").join("simple-text/after.docx");

    let before =
        fs::read(&before_path).unwrap_or_else(|e| panic!("read {}: {e}", before_path.display()));
    let after =
        fs::read(&after_path).unwrap_or_else(|e| panic!("read {}: {e}", after_path.display()));

    let runtime = SimpleRuntime::new();
    let import_before = runtime.import_docx(&before).expect("import before");
    let import_after = runtime.import_docx(&after).expect("import after");

    let meta = TransactionMeta {
        author: "spec_redline_compat".to_string(),
        reason: Some("namespace test".to_string()),
        timestamp_utc: Some("2025-06-01T12:00:00Z".to_string()),
    };
    runtime
        .diff_and_redline(&import_before.doc_handle, &import_after.doc_handle, meta)
        .expect("diff_and_redline");

    let exported = runtime
        .export_docx(&import_before.doc_handle, ExportMode::Redline)
        .expect("export");
    let xml = extract_document_xml(&exported);

    assert!(
        xml.contains("schemas.microsoft.com/office/word/2023/wordml/word16du")
            || xml.contains("w16du"),
        "exported DOCX should declare the w16du namespace"
    );
}
