//! Spec-compliance tests: Indentation precedence and lineRule defaults.
//!
//! ECMA-376 §17.3.1.12 (indentation): "The firstLine and hanging attributes
//! are mutually exclusive, if both are specified, then the firstLine value is
//! ignored." — meaning hanging wins.
//!
//! ECMA-376 §17.3.1.33 (spacing): "If this attribute [lineRule] is omitted,
//! then it shall be assumed to be of a value auto if a line attribute value is
//! present."
//!
//! Fixtures generated by `testdata/spec-compliance/spacing-indentation/create_docs.py`.

use stemma::LineSpacingRule;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/spacing-indentation";

// ── firstLine/hanging precedence ────────────────────────────────────────

/// ECMA-376 §17.3.1.12: When a *paragraph style* defines ind with both
/// `hanging="360"` and `firstLine="720"`, hanging wins. Verifies that the
/// style parser correctly gives hanging precedence over firstLine.
#[test]

fn spec_hanging_wins_over_firstline_in_style() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "hanging-wins-style");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| p.style_id.as_deref() == Some("HangingWins"))
        .expect(
            "should find a paragraph with style_id='HangingWins'. \
             The fixture applies this style but it may not have survived import.",
        );

    let indent = p.indent.as_ref().expect(
        "paragraph with HangingWins style should have indentation resolved from style, \
         but indent is None",
    );

    // §17.3.1.12: hanging wins over firstLine when both are present.
    // hanging=360 → effective_first_line_twips = -360
    assert_eq!(
        indent.effective_first_line_twips,
        Some(-360),
        "ECMA-376 §17.3.1.12: hanging should win over firstLine in style. \
         Expected effective_first_line_twips = -360 (hanging=360), \
         got {:?}. The style parser likely checks firstLine before hanging.",
        indent.effective_first_line_twips
    );
}

/// ECMA-376 §17.3.1.12: When a *numbering level* defines ind with both
/// `hanging="360"` and `firstLine="720"`, hanging wins. Verifies that the
/// numbering parser correctly gives hanging precedence over firstLine.
#[test]

fn spec_hanging_wins_over_firstline_in_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "hanging-wins-numbering");
    let paras = common::all_paragraphs(&doc);

    // Find the numbered paragraph (it should have numbering info or at least
    // inherit indentation from the numbering level).
    let p = paras
        .iter()
        .find(|p| {
            p.indent
                .as_ref()
                .is_some_and(|i| i.effective_first_line_twips.is_some())
        })
        .expect(
            "should find a paragraph with indentation from numbering. \
             The fixture uses numId=100 ilvl=0 with both hanging and firstLine.",
        );

    let indent = p.indent.as_ref().unwrap();

    // §17.3.1.12: hanging wins over firstLine when both are present.
    assert_eq!(
        indent.effective_first_line_twips,
        Some(-360),
        "ECMA-376 §17.3.1.12: hanging should win over firstLine in numbering level. \
         Expected effective_first_line_twips = -360 (hanging=360), \
         got {:?}. The numbering parser likely checks firstLine before hanging.",
        indent.effective_first_line_twips
    );
}

/// ECMA-376 §17.3.1.12: Direct formatting with both `hanging="360"` and
/// `firstLine="720"` — hanging wins.
///
/// Control test: word_ir.rs already handles this correctly.
#[test]
fn spec_hanging_wins_over_firstline_direct() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "hanging-wins-direct");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| {
            p.indent
                .as_ref()
                .is_some_and(|i| i.effective_first_line_twips.is_some())
        })
        .expect(
            "should find a paragraph with direct indentation. \
             The fixture has direct w:ind with hanging and firstLine.",
        );

    let indent = p.indent.as_ref().unwrap();

    // §17.3.1.12: hanging wins over firstLine when both are present.
    assert_eq!(
        indent.effective_first_line_twips,
        Some(-360),
        "ECMA-376 §17.3.1.12: hanging should win over firstLine in direct formatting. \
         Expected effective_first_line_twips = -360 (hanging=360), \
         got {:?}",
        indent.effective_first_line_twips
    );
}

// ── lineRule defaults ───────────────────────────────────────────────────

/// ECMA-376 §17.3.1.33: When a *style* defines `spacing line="276"` but
/// omits lineRule, the resolved line_rule should default to Auto.
/// Verifies that the style-only path correctly applies the lineRule default.
#[test]

fn spec_linerule_defaults_to_auto_from_style() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "linerule-default-style");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| p.style_id.as_deref() == Some("LineNoRule"))
        .expect(
            "should find a paragraph with style_id='LineNoRule'. \
             The fixture applies this style but it may not have survived import.",
        );

    let spacing = p.spacing.as_ref().expect(
        "paragraph with LineNoRule style should have spacing resolved from style, \
         but spacing is None",
    );

    assert_eq!(
        spacing.line,
        Some(276),
        "spacing line should be 276 from style, got {:?}",
        spacing.line
    );

    // §17.3.1.33: lineRule defaults to Auto when line is present but lineRule is omitted.
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "ECMA-376 §17.3.1.33: lineRule should default to Auto when line is present \
         but lineRule is omitted in the style. Got {:?}. \
         The style-only path in resolve_effective_spacing does not apply this default.",
        spacing.line_rule
    );
}

/// ECMA-376 §17.3.1.33: Direct `spacing line="276"` with no lineRule
/// defaults to Auto.
///
/// Control test: word_ir.rs already handles this correctly.
#[test]
fn spec_linerule_defaults_to_auto_direct() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "linerule-default-direct");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| p.spacing.as_ref().is_some_and(|s| s.line.is_some()))
        .expect(
            "should find a paragraph with direct spacing line value. \
             The fixture has direct w:spacing with line=276.",
        );

    let spacing = p.spacing.as_ref().unwrap();

    assert_eq!(
        spacing.line,
        Some(276),
        "spacing line should be 276 from direct formatting, got {:?}",
        spacing.line
    );

    // §17.3.1.33: lineRule defaults to Auto when line is present but lineRule is omitted.
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "ECMA-376 §17.3.1.33: lineRule should default to Auto when line is present \
         but lineRule is omitted. Got {:?}",
        spacing.line_rule
    );
}

// ── basic indentation ───────────────────────────────────────────────────

/// ECMA-376 §17.3.1.12: Basic left/right indentation.
///
/// Paragraph with `ind left="720" right="360"` should have those values
/// on the domain Indentation.
#[test]
fn spec_indentation_left_right_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "indent-left-right");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| {
            p.indent
                .as_ref()
                .is_some_and(|i| i.left.is_some() || i.right.is_some())
        })
        .expect(
            "should find a paragraph with left/right indentation. \
             The fixture has direct w:ind with left=720 right=360.",
        );

    let indent = p.indent.as_ref().unwrap();

    assert_eq!(
        indent.left,
        Some(720),
        "left indent should be 720 twips, got {:?}",
        indent.left
    );
    assert_eq!(
        indent.right,
        Some(360),
        "right indent should be 360 twips, got {:?}",
        indent.right
    );
}

/// ECMA-376 §17.3.1.12: Negative start indent extends past margin.
///
/// Paragraph with `ind start="-720"` should produce left=-720.
#[test]
fn spec_indentation_negative_start_extends_past_margin() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "indent-negative-start");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| {
            p.indent
                .as_ref()
                .is_some_and(|i| i.left.is_some_and(|v| v < 0))
        })
        .expect(
            "should find a paragraph with negative left indentation. \
             The fixture has direct w:ind with start=-720.",
        );

    let indent = p.indent.as_ref().unwrap();

    assert_eq!(
        indent.left,
        Some(-720),
        "negative start indent should produce left=-720, got {:?}",
        indent.left
    );
}
