//! Spec-compliance tests: Numbering (ISO 29500-1 §17.9)
//!
//! These tests verify our implementation against specific OOXML numbering
//! constructs. Tests marked `#[ignore]` document known gaps — they encode
//! the *correct* spec behavior and are expected to fail against the current
//! implementation.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/numbering";

// ── helpers ──────────────────────────────────────────────────────────────
/// Extract the numbering prefix from each paragraph.
///
/// For structurally numbered paragraphs (numPr → numbering engine), the prefix
/// is extracted from rendered_text (format: "prefix\tbody text").
/// For manually typed enumerators, it comes from literal_prefix.
/// Non-numbered paragraphs produce None.
fn numbering_prefixes(doc: &CanonDoc) -> Vec<Option<String>> {
    let mut prefixes = Vec::new();
    collect_prefixes_tracked(&doc.blocks, &mut prefixes);
    prefixes
}

fn collect_prefixes_tracked(blocks: &[TrackedBlock], out: &mut Vec<Option<String>>) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_prefixes_bare(blocks: &[BlockNode], out: &mut Vec<Option<String>>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                out.push(extract_prefix(p));
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_prefixes_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

/// Extract the numbering prefix from a paragraph.
/// Prefers literal_prefix; falls back to splitting rendered_text on tab.
fn extract_prefix(p: &stemma::ParagraphNode) -> Option<String> {
    if let Some(ref lp) = p.literal_prefix {
        return Some(lp.clone());
    }
    // For synthesized numbering, rendered_text is "prefix\tbody text"
    if let Some(ref rt) = p.rendered_text
        && let Some(idx) = rt.find('\t')
    {
        let prefix = rt[..idx].to_string();
        if !prefix.is_empty() {
            return Some(prefix);
        }
    }
    None
}

// ── w:lvlOverride / w:startOverride ─────────────────────────────────────

/// ISO 29500-1 §17.9.8 (lvlOverride) / §17.9.26 (startOverride):
/// lvlOverride with startOverride restarts numbering.
///
/// Document has two lists sharing an abstract definition. The second list
/// uses numId=2 which has lvlOverride/startOverride to restart at 1.
///
/// Expected: First list (a),(b),(c). Second list restarts: (a),(b).
#[test]
fn spec_lvl_override_restarts_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "lvl-override");

    let prefixes = numbering_prefixes(&doc);
    // Filter to only numbered paragraphs (those with a prefix)
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    // Expected: (a), (b), (c), then restart: (a), (b)
    assert!(
        numbered.len() >= 5,
        "should have at least 5 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // First list
    assert!(
        numbered[0].contains('a'),
        "first item should be (a), got: '{}'",
        numbered[0]
    );
    assert!(
        numbered[1].contains('b'),
        "second item should be (b), got: '{}'",
        numbered[1]
    );
    assert!(
        numbered[2].contains('c'),
        "third item should be (c), got: '{}'",
        numbered[2]
    );

    // Second list — should restart at (a) due to lvlOverride
    assert!(
        numbered[3].contains('a'),
        "fourth item (second list, first) should be (a) due to startOverride, got: '{}'",
        numbered[3]
    );
    assert!(
        numbered[4].contains('b'),
        "fifth item (second list, second) should be (b), got: '{}'",
        numbered[4]
    );
}

// ── w:isLgl ─────────────────────────────────────────────────────────────

/// ISO 29500-1 §17.9.4: isLgl forces inherited level values to display as decimal.
/// (§17.9.5 is "lvl — Numbering Level Override Definition", not isLgl.)
///
/// The "current level forced to decimal" behavior is per MS-OI29500 §17.9.4
/// note (a), not the base ECMA-376 spec.
///
/// Level 0: upperRoman, Level 1: lowerLetter, Level 2: decimal with isLgl.
/// Expected level 2 prefix: "1.1.1" (all levels forced to decimal).
#[test]
fn spec_is_lgl_forces_decimal() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "is-lgl");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "should have at least 3 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Level 0: should be "I." (upperRoman)
    assert!(
        numbered[0].contains('I'),
        "level 0 should be 'I.', got: '{}'",
        numbered[0]
    );

    // Level 1: should be "I.a." (per the lvlText pattern)
    assert!(
        numbered[1].contains('a'),
        "level 1 should contain 'a', got: '{}'",
        numbered[1]
    );

    // Level 2 WITH isLgl: should be "1.1.1" (all inherited levels forced to decimal)
    // NOT "I.a.1"
    assert!(
        numbered[2].starts_with("1.1.1"),
        "level 2 with isLgl should be '1.1.1', got: '{}'. \
         isLgl forces all inherited level references to use decimal format.",
        numbered[2]
    );
}

// ── w:lvlRestart ────────────────────────────────────────────────────────

/// ISO 29500-1 §17.9.10: lvlRestart=0 means the level counter never resets.
///
/// Level 1 has lvlRestart=0. After level 0 reappears, level 1 should
/// continue its counter (c, d) instead of restarting (a, b).
#[test]
fn spec_lvl_restart_zero_never_resets() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "lvl-restart");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 6,
        "should have at least 6 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Structure: 1. / a) / b) / 2. / c) / d)
    // (level 1 does NOT restart because lvlRestart=0)

    // First group
    assert!(
        numbered[0].contains('1'),
        "first level-0 item should be '1.', got: '{}'",
        numbered[0]
    );
    assert!(
        numbered[1].contains('a'),
        "first level-1 item should be 'a)', got: '{}'",
        numbered[1]
    );
    assert!(
        numbered[2].contains('b'),
        "second level-1 item should be 'b)', got: '{}'",
        numbered[2]
    );

    // Second group — level 1 should CONTINUE (not restart)
    assert!(
        numbered[3].contains('2'),
        "second level-0 item should be '2.', got: '{}'",
        numbered[3]
    );
    assert!(
        numbered[4].contains('c'),
        "third level-1 item should be 'c)' (continued, not restarted), got: '{}'",
        numbered[4]
    );
    assert!(
        numbered[5].contains('d'),
        "fourth level-1 item should be 'd)' (continued, not restarted), got: '{}'",
        numbered[5]
    );
}

// ── Multi-level numbering ───────────────────────────────────────────────

/// Multi-level outline numbering with %N cross-references.
///
/// Tests that the basic multi-level expansion (I. / I.1 / I.1.a) works
/// correctly. This is a positive test (should pass).
#[test]
fn spec_multi_level_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "multi-level");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 8,
        "should have 8 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Expected sequence:
    // I.  / I.1 / I.1.a) / I.1.b) / I.2 / I.2.a) / II. / II.1

    // Level 0: "I."
    assert!(
        numbered[0].starts_with("I."),
        "first level-0 should be 'I.', got: '{}'",
        numbered[0]
    );

    // Level 1: "I.1"
    assert!(
        numbered[1].starts_with("I.1"),
        "first level-1 should be 'I.1', got: '{}'",
        numbered[1]
    );

    // Level 2: "I.1.a)"
    assert!(
        numbered[2].starts_with("I.1.a)"),
        "first level-2 should be 'I.1.a)', got: '{}'",
        numbered[2]
    );

    // Level 2: "I.1.b)"
    assert!(
        numbered[3].starts_with("I.1.b)"),
        "second level-2 should be 'I.1.b)', got: '{}'",
        numbered[3]
    );

    // Level 1: "I.2"
    assert!(
        numbered[4].starts_with("I.2"),
        "second level-1 should be 'I.2', got: '{}'",
        numbered[4]
    );

    // Level 2 resets: "I.2.a)"
    assert!(
        numbered[5].starts_with("I.2.a)"),
        "level-2 after new level-1 should reset to 'I.2.a)', got: '{}'",
        numbered[5]
    );

    // Level 0: "II."
    assert!(
        numbered[6].starts_with("II."),
        "second level-0 should be 'II.', got: '{}'",
        numbered[6]
    );

    // Level 1: "II.1"
    assert!(
        numbered[7].starts_with("II.1"),
        "level-1 under new level-0 should be 'II.1', got: '{}'",
        numbered[7]
    );
}

// ── All 9 numbering levels ───────────────────────────────────────────────

/// ISO 29500-1 §17.9.6: All 9 levels (0-8) with decimal numbering.
///
/// Each level synthesizes a progressively deeper prefix: 1. / 1.1. / 1.1.1. / ...
/// Verifies the numbering engine handles maximum depth correctly.
#[test]
fn spec_all_nine_levels() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "all-nine-levels");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert_eq!(
        numbered.len(),
        9,
        "should have exactly 9 numbered paragraphs (one per level), got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Level 0: "1."
    assert_eq!(
        numbered[0], "1.",
        "level 0 should be '1.', got: '{}'",
        numbered[0]
    );

    // Level 1: "1.1."
    assert_eq!(
        numbered[1], "1.1.",
        "level 1 should be '1.1.', got: '{}'",
        numbered[1]
    );

    // Level 2: "1.1.1."
    assert_eq!(
        numbered[2], "1.1.1.",
        "level 2 should be '1.1.1.', got: '{}'",
        numbered[2]
    );

    // Level 8 (deepest): "1.1.1.1.1.1.1.1.1."
    let expected_deep = "1.1.1.1.1.1.1.1.1.";
    assert_eq!(
        numbered[8], expected_deep,
        "level 8 (deepest) should be '{}', got: '{}'",
        expected_deep, numbered[8]
    );
}

// ── Number format types ──────────────────────────────────────────────────

/// ISO 29500-1 §17.9.17: Various number format types.
///
/// Tests bullet (•), lowerRoman (i, ii, iii), upperRoman (I, II),
/// and upperLetter (A, B) formats.
#[test]
fn spec_number_format_types() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "number-format-types");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    // We expect: 2 bullets + 3 lowerRoman + 2 upperRoman + 2 upperLetter = 9 numbered
    assert!(
        numbered.len() >= 9,
        "should have at least 9 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // Bullets: "•" (mapped from PUA char)
    assert_eq!(
        numbered[0], "•",
        "first bullet should be '•', got: '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "•",
        "second bullet should be '•', got: '{}'",
        numbered[1]
    );

    // Lower roman: i., ii., iii.
    assert_eq!(
        numbered[2], "i.",
        "first lowerRoman should be 'i.', got: '{}'",
        numbered[2]
    );
    assert_eq!(
        numbered[3], "ii.",
        "second lowerRoman should be 'ii.', got: '{}'",
        numbered[3]
    );
    assert_eq!(
        numbered[4], "iii.",
        "third lowerRoman should be 'iii.', got: '{}'",
        numbered[4]
    );

    // Upper roman: I., II.
    assert_eq!(
        numbered[5], "I.",
        "first upperRoman should be 'I.', got: '{}'",
        numbered[5]
    );
    assert_eq!(
        numbered[6], "II.",
        "second upperRoman should be 'II.', got: '{}'",
        numbered[6]
    );

    // Upper letter: A., B.
    assert_eq!(
        numbered[7], "A.",
        "first upperLetter should be 'A.', got: '{}'",
        numbered[7]
    );
    assert_eq!(
        numbered[8], "B.",
        "second upperLetter should be 'B.', got: '{}'",
        numbered[8]
    );
}

// ── Start-at override ────────────────────────────────────────────────────

/// ISO 29500-1 §17.9.15: w:start val="5" — list starts at 5, not 1.
#[test]
fn spec_start_at_five() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "start-at-override");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 3,
        "should have at least 3 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    assert_eq!(
        numbered[0], "5.",
        "first item should be '5.' (start=5), got: '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "6.",
        "second item should be '6.', got: '{}'",
        numbered[1]
    );
    assert_eq!(
        numbered[2], "7.",
        "third item should be '7.', got: '{}'",
        numbered[2]
    );
}

// ── Shared abstract numbering ────────────────────────────────────────────

/// ISO 29500-1 §17.9.8: Two lists sharing abstractNumId with different overrides.
///
/// numId=1 starts at 1 (default). numId=2 has startOverride=10.
/// First list: 1., 2. Second list: 10., 11.
#[test]
fn spec_shared_abstract_num_with_different_overrides() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "shared-abstract-num");

    let prefixes = numbering_prefixes(&doc);
    let numbered: Vec<&str> = prefixes.iter().filter_map(|p| p.as_deref()).collect();

    assert!(
        numbered.len() >= 4,
        "should have at least 4 numbered paragraphs, got {}: {:?}",
        numbered.len(),
        numbered
    );

    // First list (numId=1): 1., 2.
    assert_eq!(
        numbered[0], "1.",
        "first list item 1 should be '1.', got: '{}'",
        numbered[0]
    );
    assert_eq!(
        numbered[1], "2.",
        "first list item 2 should be '2.', got: '{}'",
        numbered[1]
    );

    // Second list (numId=2): 10., 11.
    assert_eq!(
        numbered[2], "10.",
        "second list item 1 should be '10.' (startOverride=10), got: '{}'",
        numbered[2]
    );
    assert_eq!(
        numbered[3], "11.",
        "second list item 2 should be '11.', got: '{}'",
        numbered[3]
    );
}
