//! Spec-compliance tests: Indent Interaction Audit
//!
//! Tests verify spec constraints for indent interactions:
//!   - Character-unit indent values survive prefix stripping and tab absorption.
//!   - Tab absorption only fires for hanging indent (negative firstLine),
//!     not positive firstLine.
//!   - Numbering w:ind replaces style w:ind as a whole element (element-level
//!     override), so style firstLine does not leak through.
//!     Note: ECMA-376 §17.3.1.12 uses per-attribute wording, but empirical
//!     Word behavior uses element-level override for numbering-over-style.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/indent-interaction-audit";

// ==========================================================================
// Character-unit indent survives prefix stripping
// ==========================================================================

/// ISO 29500-1 §17.3.1.12 + MS-OI29500 2.1.44: When a paragraph has
/// character-unit indent values (w:startChars, w:endChars) and the runtime
/// strips a literal prefix like "(a)\t", the char-unit values must be
/// propagated to the output Indentation — not hardcoded to None.
///
/// Fixture:
///   P0: w:left=720, w:startChars=200, w:endChars=100, tab at 1440,
///       text "(a)\tBody text..." — triggers prefix stripping.
///   P1: w:left=720, w:startChars=200, w:endChars=100, no prefix (control).
///
/// Expected: Both P0 and P1 should have start_chars=Some(200), end_chars=Some(100).
/// Prefix stripping branch previously hardcoded start_chars=None, end_chars=None.
#[test]
fn gap101_char_unit_indent_survives_prefix_stripping() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "char-unit-prefix-stripping");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P1: control — no prefix, char-unit values pass through
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 (control) should have indent");
    assert_eq!(
        indent1.start_chars,
        Some(200),
        "P1 (control) start_chars should be 200. Got {:?}",
        indent1.start_chars,
    );
    assert_eq!(
        indent1.end_chars,
        Some(100),
        "P1 (control) end_chars should be 100. Got {:?}",
        indent1.end_chars,
    );

    // P0: prefix stripped — char-unit values must survive
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent after prefix stripping");
    assert_eq!(
        indent0.start_chars,
        Some(200),
        "P0 start_chars should be 200 after prefix stripping. \
         Prefix stripping branch previously hardcoded start_chars=None. Got {:?}",
        indent0.start_chars,
    );
    assert_eq!(
        indent0.end_chars,
        Some(100),
        "P0 end_chars should be 100 after prefix stripping. \
         Prefix stripping branch previously hardcoded end_chars=None. Got {:?}",
        indent0.end_chars,
    );
}

// ==========================================================================
// Tab absorption preserves indent with positive firstLine
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: Tab absorption (collapsing firstLine into left
/// when body text contains tabs) is only correct for hanging indent (negative
/// firstLine). With positive firstLine and tabs, the code must NOT absorb
/// firstLine into left — that would incorrectly shift continuation lines.
///
/// Fixture:
///   P0: w:left=720, w:firstLine=360, text "A\tB" — has tabs + positive firstLine.
///   P1: w:left=720, w:firstLine=360, text "AB" — no tabs (control).
///
/// Expected: Both P0 and P1 should have left=720, first_line=360.
/// Condition `first_line_twips != 0` previously fired
/// incorrectly for positive firstLine, absorbing it into left (left=1080,
/// first_line=None).
#[test]
fn gap102_tab_absorption_preserves_continuation_with_positive_firstline() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "tab-absorption-positive-firstline");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P1: control — no tabs, indent passes through unchanged
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 (control) should have indent");
    assert_eq!(
        indent1.left,
        Some(720),
        "P1 (control) left should be 720. Got {:?}",
        indent1.left,
    );
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(360),
        "P1 (control) first_line should be 360. Got {:?}",
        indent1.effective_first_line_twips,
    );

    // P0: positive firstLine + tabs — tab absorption must NOT fire
    let indent0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 (tab absorption must NOT fire for positive firstLine). \
         Condition previously fired for all non-zero firstLine, absorbing it into left. Got {:?}",
        indent0.left,
    );
    assert_eq!(
        indent0.effective_first_line_twips,
        Some(360),
        "P0 first_line should be 360 (preserved, not absorbed). \
         Tab absorption previously set first_line=None. Got {:?}",
        indent0.effective_first_line_twips,
    );
}

// ==========================================================================
// Numbering indent blocks style firstLine
// ==========================================================================

/// ISO 29500-1 §17.9.22 + §17.3.1.12: When numbering provides w:ind
/// (e.g., left=720 but no firstLine), the numbering w:ind element replaces
/// the style's w:ind as a whole (element-level override). The style's
/// firstLine must NOT leak through via per-field merge.
///
/// Note: ECMA-376 §17.3.1.12 uses per-attribute inheritance wording, but
/// empirical Word behavior uses element-level override for numbering-over-style.
/// We follow Word's behavior.
///
/// Fixture:
///   Style "FirstLineStyle": w:ind left=360, firstLine=240.
///   Numbering level 0: w:ind left=720 (no firstLine, no hanging).
///   P0: Style + numbering — numbering w:ind replaces style w:ind entirely.
///   P1: Style only (control) — should have left=360, firstLine=240.
///
/// Expected P0: left=720, firstLine=None.
/// Expected P1: left=360, firstLine=240.
/// Per-field merge previously leaked style firstLine=240 into P0.
#[test]
fn gap103_numbering_indent_blocks_style_firstline() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "numbering-blocks-style-firstline");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P1: control — style only, should have both left and firstLine from style
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 (control) should have indent from style");
    assert_eq!(
        indent1.left,
        Some(360),
        "P1 (control) left should be 360 from style. Got {:?}",
        indent1.left,
    );
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(240),
        "P1 (control) first_line should be 240 from style. Got {:?}",
        indent1.effective_first_line_twips,
    );

    // P0: style + numbering — numbering w:ind replaces style w:ind entirely
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent from numbering");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 (from numbering level). Got {:?}",
        indent0.left,
    );
    assert_eq!(
        indent0.effective_first_line_twips, None,
        "P0 first_line should be None (numbering w:ind replaces style w:ind entirely). \
         Per-field merge previously leaked style firstLine=240. Got {:?}",
        indent0.effective_first_line_twips,
    );
}
