//! Spec-compliance tests: Table Content Model Constraints
//!
//! These tests verify our implementation against specific OOXML table content
//! model constraints — width coercion, vMerge grid alignment, gridSpan overflow,
//! and border conflict resolution. Tests marked `#[ignore]` document known gaps.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_table_content_model.py`.

use stemma::{BlockNode, CanonDoc, InlineNode, TableNode, VerticalMerge};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-content-model";

// ── helpers ──────────────────────────────────────────────────────────────

fn first_table(doc: &CanonDoc) -> &TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

fn cell_text(table: &TableNode, row: usize, col: usize) -> String {
    let cell = &table.rows[row].cells[col];
    let mut text = String::new();
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            let inlines = p.all_inlines_owned();
            for inline in &inlines {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

// =========================================================================
// Width type coercion when w=0 (MS-OI29500 §2.1.166)
// =========================================================================
//
// MS-OI29500 §2.1.166: If the w attribute value is 0, the type attribute
// is treated as "auto" regardless of the specified value. This applies to
// both tblW and tcW elements.
//
// Fixture: width-type-nil
//   - Table width: w=0 type=pct  (should coerce to auto)
//   - Cell 0: w=5000 type=pct   (normal, no coercion)
//   - Cell 1: w=0 type=dxa      (should coerce to auto)

/// MS-OI29500 §2.1.166: Table width w=0 should force type to auto,
/// regardless of the declared type attribute (pct in this case).
#[test]
fn spec_table_width_zero_coerced_to_auto() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "width-type-nil");
    let table = first_table(&doc);

    let width = table
        .formatting
        .width
        .as_ref()
        .expect("table should have a width element");
    assert_eq!(
        width.width_type,
        stemma::domain::WidthType::Auto,
        "MS-OI29500 §2.1.166: table width w=0 with type=pct should be coerced to auto. \
         Got type={:?}, w={}",
        width.width_type,
        width.w,
    );
}

/// MS-OI29500 §2.1.171: Cell width w=0 should force type to auto,
/// regardless of the declared type attribute (dxa in this case).
#[test]
fn spec_cell_width_zero_coerced_to_auto() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "width-type-nil");
    let table = first_table(&doc);

    // Cell 1 (index 1) has w=0, type=dxa — should be coerced to auto
    let cell_width = table.rows[0].cells[1]
        .formatting
        .width
        .as_ref()
        .expect("cell 1 should have a width element");
    assert_eq!(
        cell_width.width_type,
        stemma::domain::WidthType::Auto,
        "MS-OI29500 §2.1.171: cell width w=0 with type=dxa should be coerced to auto. \
         Got type={:?}, w={}",
        cell_width.width_type,
        cell_width.w,
    );
}

// =========================================================================
// vMerge grid alignment (ISO 29500-1 §17.4.84)
// =========================================================================
//
// §17.4.84: A vMerge continuation cell should have the same gridSpan as the
// restart cell above it. If the gridSpan differs, the vertical merge is
// non-conformant.
//
// Fixture: vmerge-grid (3x3 table)
//   Row 0: [gridSpan=2, vMerge=restart] [normal]
//   Row 1: [gridSpan=2, vMerge=continue] [normal]   ← matching, correct
//   Row 2: [gridSpan=1, vMerge=continue] [normal] [normal]  ← mismatched

/// ISO 29500-1 §17.4.84: Rows 0 and 1 have matching gridSpan=2 on the
/// vMerge restart/continue cells. This should be imported correctly.
#[test]
fn spec_vmerge_matching_grid_span_accepted() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-grid");
    let table = first_table(&doc);

    assert!(
        table.rows.len() >= 3,
        "table should have at least 3 rows, got {}",
        table.rows.len(),
    );

    // Row 0, cell 0: vMerge=restart, gridSpan=2
    let cell_00 = &table.rows[0].cells[0];
    assert_eq!(
        cell_00.v_merge,
        VerticalMerge::Restart,
        "row 0, cell 0 should be vMerge::Restart",
    );
    assert_eq!(cell_00.grid_span, 2, "row 0, cell 0 should have gridSpan=2",);

    // Row 1, cell 0: vMerge=continue, gridSpan=2
    let cell_10 = &table.rows[1].cells[0];
    assert_eq!(
        cell_10.v_merge,
        VerticalMerge::Continue,
        "row 1, cell 0 should be vMerge::Continue",
    );
    assert_eq!(
        cell_10.grid_span, 2,
        "row 1, cell 0 should have gridSpan=2 (matching restart cell above)",
    );

    // Row 0, cell 0 text should be identifiable
    let text_00 = cell_text(table, 0, 0);
    assert!(
        text_00.contains("R0C0"),
        "row 0, cell 0 text should contain 'R0C0', got: '{text_00}'",
    );
}

/// ISO 29500-1 §17.4.84: Row 2 has vMerge=continue with gridSpan=1 but the
/// restart cell (row 0) has gridSpan=2. This is a non-conformant document.
/// The parser normalizes this by breaking the invalid vMerge chain.
#[test]
fn spec_vmerge_mismatched_grid_span_detected() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-grid");
    let table = first_table(&doc);

    // Row 2, cell 0 has gridSpan=1 but is vMerge=continue from a gridSpan=2 restart.
    // A conformant implementation should detect and handle this mismatch.
    let cell_20 = &table.rows[2].cells[0];

    // The mismatch should be detected — either by:
    // (a) normalizing the gridSpan to match the restart (gridSpan=2), or
    // (b) breaking the vMerge chain (converting to VerticalMerge::None), or
    // (c) returning an error during import.
    //
    // Currently none of these happen — the mismatched merge is silently preserved.
    assert_ne!(
        cell_20.v_merge,
        VerticalMerge::Continue,
        "row 2, cell 0 has gridSpan=1 but continues from gridSpan=2 restart. \
         Per §17.4.84, this vMerge should not be treated as a valid continuation. \
         v_merge={:?}, grid_span={}",
        cell_20.v_merge,
        cell_20.grid_span,
    );
}

// =========================================================================
// gridSpan overflow (ISO 29500-1 §17.4.17)
// =========================================================================
//
// §17.4.17: gridSpan specifies how many grid columns a cell occupies.
// If gridSpan exceeds the number of columns declared in tblGrid, the
// document is non-conformant.
//
// Fixture: grid-span-overflow
//   tblGrid: 3 columns
//   Row 0: single cell with gridSpan=5 (exceeds grid width)
//   Row 1: 3 normal cells

/// ISO 29500-1 §17.4.17: gridSpan=5 exceeds the tblGrid width of 3 columns.
/// The parser clamps gridSpan to the tblGrid column count.
#[test]
fn spec_gridspan_exceeding_grid_width() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "grid-span-overflow");
    let table = first_table(&doc);

    // The table grid declares 3 columns
    assert_eq!(
        table.formatting.grid_cols.len(),
        3,
        "tblGrid should declare 3 columns",
    );

    // Row 0, cell 0 has gridSpan=5 — this exceeds the grid
    let cell_00 = &table.rows[0].cells[0];

    // A conformant implementation should either:
    // (a) extend grid_cols to 5 columns to accommodate the span, or
    // (b) clamp gridSpan to 3 (the grid width), or
    // (c) reject the document during import.
    //
    // Currently the gridSpan=5 is preserved as-is without validation.
    assert!(
        cell_00.grid_span <= table.formatting.grid_cols.len() as u32,
        "gridSpan ({}) should not exceed tblGrid column count ({}). \
         Per §17.4.17, gridSpan must reference valid grid columns.",
        cell_00.grid_span,
        table.formatting.grid_cols.len(),
    );
}

// =========================================================================
// Border conflict resolution (ISO 29500-1 §17.4.66)
// =========================================================================
//
// §17.4.66: When tblCellSpacing is 0 (collapsed borders), adjacent cells
// that specify different borders on their shared edge create a conflict.
// The spec defines a resolution algorithm based on border weight and style.
//
// Fixture: border-conflict
//   2x2 table, tblCellSpacing=0
//   Cell (0,0) right border: red single sz=12
//   Cell (0,1) left border:  blue double sz=4

/// ISO 29500-1 §17.4.66: Adjacent cell borders conflict when tblCellSpacing=0.
/// Cell (0,0) has right=red/single/12 (weight=12) and cell (0,1) has left=blue/double/4 (weight=12).
/// On weight ties, the style precedence list determines the winner (higher-ranked
/// style wins, e.g., double > single per MS-OI29500 §2.1.169). Both cells should
/// agree on the shared edge.
#[test]
fn spec_adjacent_cell_border_conflict_resolution() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-conflict");
    let table = first_table(&doc);

    assert_eq!(table.rows.len(), 2, "table should have 2 rows");
    assert_eq!(table.rows[0].cells.len(), 2, "row 0 should have 2 cells");

    // Cell (0,0) right border
    let borders_00 = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders");
    let right_00 = borders_00
        .right
        .as_ref()
        .expect("cell (0,0) should have a right border");

    // Cell (0,1) left border
    let borders_01 = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,1) should have borders");
    let left_01 = borders_01
        .left
        .as_ref()
        .expect("cell (0,1) should have a left border");

    // Per §17.4.66 conflict resolution:
    // The borders on the shared edge should be resolved to a single winner.
    // After resolution, both cells should agree on the shared edge border.
    assert_eq!(
        right_00.color, left_01.color,
        "after conflict resolution, cell (0,0) right border and cell (0,1) left border \
         should agree. Per §17.4.66, the winning border is determined by style weight. \
         Cell (0,0) right: {:?}/{:?}, Cell (0,1) left: {:?}/{:?}",
        right_00.style, right_00.color, left_01.style, left_01.color,
    );
}
