//! Spec-compliance tests: Formatting change fidelity (*PrChange elements)
//!
//! These tests verify that pPrChange, rPrChange, and other *PrChange elements
//! correctly capture and preserve the previous formatting state per ECMA-376.
//!
//! Approach: create old/new DOCX pairs with specific formatting differences
//! (including a small text edit so the diff engine detects BlockModified),
//! run `diff_and_redline`, export the redline, and parse the raw XML to verify
//! the *PrChange element content.
//!
//! IMPORTANT: The diff engine intentionally skips formatting-only changes on
//! identical-text blocks (not "semantic contract changes"). pPrChange is only
//! generated when the block text also changed, triggering BlockModified in the
//! diff and formatting comparison in the merge step.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/tracked-change-formatting/create_docs.py`.

use std::fs;
use std::io::{Cursor, Read};

use stemma::{DocxRuntime, ExportMode, SimpleRuntime, TransactionMeta};
use xmltree::{Element, XMLNode};
use zip::ZipArchive;

const FIXTURES: &str = "testdata/spec-compliance/tracked-change-formatting";
const WORD_NS: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

// ── helpers ──────────────────────────────────────────────────────────────

/// Run diff_and_redline on old/new fixture pair and return the redline DOCX bytes.
fn redline_from_pair(fixture_name: &str) -> Vec<u8> {
    let old_path = format!("{FIXTURES}/{fixture_name}/old.docx");
    let new_path = format!("{FIXTURES}/{fixture_name}/new.docx");

    let old_bytes = fs::read(&old_path).unwrap_or_else(|e| panic!("read {old_path}: {e}"));
    let new_bytes = fs::read(&new_path).unwrap_or_else(|e| panic!("read {new_path}: {e}"));

    let runtime = SimpleRuntime::new();
    let import_old = runtime.import_docx(&old_bytes).expect("import old");
    let import_new = runtime.import_docx(&new_bytes).expect("import new");

    let meta = TransactionMeta {
        author: "spec_tracked_change_formatting".to_string(),
        reason: Some(format!("spec test: {fixture_name}")),
        timestamp_utc: Some("2025-01-15T10:30:00Z".to_string()),
    };

    let apply = runtime
        .diff_and_redline(&import_old.doc_handle, &import_new.doc_handle, meta)
        .expect("diff_and_redline");
    assert!(
        apply.applied,
        "redline should be applied for fixture '{fixture_name}'"
    );

    runtime
        .export_docx(&import_old.doc_handle, ExportMode::Redline)
        .expect("export redline")
}

/// Extract word/document.xml from a DOCX zip.
fn extract_document_xml(docx_bytes: &[u8]) -> String {
    let cursor = Cursor::new(docx_bytes);
    let mut zip = ZipArchive::new(cursor).expect("open DOCX zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("DOCX must contain word/document.xml");
    let mut out = String::new();
    file.read_to_string(&mut out)
        .expect("read word/document.xml");
    out
}

fn parse_xml(xml: &str) -> Element {
    Element::parse(Cursor::new(xml.as_bytes())).expect("parse XML")
}

fn is_w_tag(element: &Element, local: &str) -> bool {
    let name = local_name(&element.name);
    if name != local {
        return false;
    }
    if element.prefix.as_deref() == Some("w") {
        return true;
    }
    if element.namespace.as_deref() == Some(WORD_NS) {
        return true;
    }
    element.name == local || element.name == format!("w:{local}")
}

fn local_name(name: &str) -> &str {
    match name.rsplit_once(':') {
        Some((_, local)) => local,
        None => name,
    }
}

fn attr_value<'a>(element: &'a Element, qname: &str) -> Option<&'a str> {
    let (prefix, local) = split_qname(qname);

    if let Some(want_prefix) = prefix {
        for (name, value) in &element.attributes {
            if name.local_name == local && name.prefix.as_deref() == Some(want_prefix) {
                return Some(value);
            }
        }
    }

    for (name, value) in &element.attributes {
        if name.local_name == local {
            return Some(value);
        }
    }

    // Compatibility with legacy keys stored as plain strings.
    for (name, value) in &element.attributes {
        if name.local_name == qname {
            return Some(value);
        }
    }

    None
}

fn split_qname(qname: &str) -> (Option<&str>, &str) {
    match qname.split_once(':') {
        Some((prefix, local)) if !prefix.is_empty() && !local.is_empty() => (Some(prefix), local),
        _ => (None, qname),
    }
}

/// Recursively find all elements matching a w: tag.
fn find_all_w_elements<'a>(root: &'a Element, tag: &str, out: &mut Vec<&'a Element>) {
    if is_w_tag(root, tag) {
        out.push(root);
    }
    for child in &root.children {
        if let XMLNode::Element(el) = child {
            find_all_w_elements(el, tag, out);
        }
    }
}

/// Find a direct w: child element with a given tag.
fn find_w_child<'a>(parent: &'a Element, tag: &str) -> Option<&'a Element> {
    parent.children.iter().find_map(|child| match child {
        XMLNode::Element(el) if is_w_tag(el, tag) => Some(el),
        _ => None,
    })
}

// =========================================================================
// 1. pPrChange preserves previous alignment
//    ECMA-376 §17.13.5.29
// =========================================================================

/// ECMA-376 §17.13.5.29: When paragraph alignment changes (left -> center)
/// alongside a text edit, the pPrChange should record the previous alignment.
///
/// Old: left-aligned, "Alignment test paragraph here."
/// New: center-aligned, "Alignment test paragraph."
///
/// The redline output should contain w:pPrChange with an inner pPr/jc@val="left".
#[test]
fn spec_pprchange_preserves_previous_alignment() {
    let redline_bytes = redline_from_pair("alignment-change");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut ppr_changes = Vec::new();
    find_all_w_elements(&root, "pPrChange", &mut ppr_changes);
    assert!(
        !ppr_changes.is_empty(),
        "redline XML should contain at least one w:pPrChange element. \
         The diff engine detected a text change (BlockModified) but did not \
         emit pPrChange for the alignment difference."
    );

    // pPrChange must have w:author and w:id attributes (§17.13.5.29).
    assert!(
        attr_value(ppr_changes[0], "w:author").is_some()
            || attr_value(ppr_changes[0], "author").is_some(),
        "pPrChange should have a w:author attribute"
    );
    assert!(
        attr_value(ppr_changes[0], "w:id").is_some() || attr_value(ppr_changes[0], "id").is_some(),
        "pPrChange should have a w:id attribute"
    );

    // The inner pPr of pPrChange should have jc with val="left".
    let inner_ppr = find_w_child(ppr_changes[0], "pPr")
        .expect("pPrChange should have a child w:pPr element per §17.13.5.29");
    let jc = find_w_child(inner_ppr, "jc");
    assert!(
        jc.is_some(),
        "inner pPr of pPrChange should have w:jc recording the previous alignment"
    );
    let jc_val = attr_value(jc.unwrap(), "w:val").or_else(|| attr_value(jc.unwrap(), "val"));
    assert_eq!(
        jc_val,
        Some("left"),
        "pPrChange inner jc@val should be 'left' (the previous alignment), got: {:?}",
        jc_val
    );

    // The outer pPr (on the paragraph itself) should have the NEW alignment.
    let mut paragraphs = Vec::new();
    find_all_w_elements(&root, "p", &mut paragraphs);
    let para_with_center = paragraphs.iter().find(|p| {
        find_w_child(p, "pPr")
            .and_then(|ppr| find_w_child(ppr, "jc"))
            .and_then(|jc| attr_value(jc, "w:val").or_else(|| attr_value(jc, "val")))
            == Some("center")
    });
    assert!(
        para_with_center.is_some(),
        "the paragraph should have w:jc val='center' as the current (new) alignment"
    );
}

// =========================================================================
// 2. pPrChange preserves previous spacing
//    ECMA-376 §17.13.5.29
// =========================================================================

/// ECMA-376 §17.13.5.29: When paragraph spacing changes (before=240 -> before=480)
/// alongside a text edit, pPrChange should record the previous spacing value.
///
/// Old: spacing before=240, "Spacing test paragraph here."
/// New: spacing before=480, "Spacing test paragraph."
#[test]
fn spec_pprchange_preserves_previous_spacing() {
    let redline_bytes = redline_from_pair("spacing-change");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut ppr_changes = Vec::new();
    find_all_w_elements(&root, "pPrChange", &mut ppr_changes);
    assert!(
        !ppr_changes.is_empty(),
        "redline XML should contain at least one w:pPrChange element. \
         The diff should detect BlockModified (text changed) and spacing \
         difference should produce pPrChange."
    );

    let inner_ppr =
        find_w_child(ppr_changes[0], "pPr").expect("pPrChange should have a child w:pPr element");
    let spacing = find_w_child(inner_ppr, "spacing");
    assert!(
        spacing.is_some(),
        "inner pPr of pPrChange should have w:spacing recording the previous spacing"
    );
    let before_val =
        attr_value(spacing.unwrap(), "w:before").or_else(|| attr_value(spacing.unwrap(), "before"));
    assert_eq!(
        before_val,
        Some("240"),
        "pPrChange inner spacing@before should be '240' (previous value), got: {:?}",
        before_val
    );

    // Verify the paragraph's current spacing is the new value (480).
    let mut paragraphs = Vec::new();
    find_all_w_elements(&root, "p", &mut paragraphs);
    let para_with_spacing = paragraphs.iter().find(|p| {
        find_w_child(p, "pPr")
            .and_then(|ppr| find_w_child(ppr, "spacing"))
            .and_then(|sp| attr_value(sp, "w:before").or_else(|| attr_value(sp, "before")))
            == Some("480")
    });
    assert!(
        para_with_spacing.is_some(),
        "the paragraph should have w:spacing before='480' as the current (new) spacing"
    );
}

// =========================================================================
// 3. pPrChange preserves previous indentation
//    ECMA-376 §17.13.5.29
// =========================================================================

/// ECMA-376 §17.13.5.29: When indentation changes (none -> left=720 hanging=360)
/// alongside a text edit, pPrChange should capture the previous state (no indent).
///
/// Old: no indentation, "Indentation test paragraph here."
/// New: left=720 hanging=360, "Indentation test paragraph."
#[test]
fn spec_pprchange_preserves_previous_indentation() {
    let redline_bytes = redline_from_pair("indentation-change");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut ppr_changes = Vec::new();
    find_all_w_elements(&root, "pPrChange", &mut ppr_changes);
    assert!(
        !ppr_changes.is_empty(),
        "redline XML should contain at least one w:pPrChange element. \
         The diff should detect BlockModified (text changed) and indentation \
         difference should produce pPrChange."
    );

    // The inner pPr should NOT have an ind element (no previous indentation).
    let inner_ppr =
        find_w_child(ppr_changes[0], "pPr").expect("pPrChange should have a child w:pPr element");
    let ind = find_w_child(inner_ppr, "ind");
    assert!(
        ind.is_none(),
        "inner pPr of pPrChange should NOT have w:ind since the old paragraph \
         had no indentation. The previous state had no indent."
    );

    // The outer pPr (on the paragraph itself) should have the new indentation.
    let mut paragraphs = Vec::new();
    find_all_w_elements(&root, "p", &mut paragraphs);
    let para_with_ind = paragraphs.iter().find(|p| {
        find_w_child(p, "pPr")
            .and_then(|ppr| find_w_child(ppr, "ind"))
            .is_some()
    });
    assert!(
        para_with_ind.is_some(),
        "the paragraph in the redline output should have w:ind with the new indentation"
    );
}

// =========================================================================
// 4. rPrChange preserves previous run formatting (adding bold)
//    ECMA-376 §17.13.5.31
// =========================================================================

/// ECMA-376 §17.13.5.31: When run formatting changes (normal -> bold)
/// alongside a text edit, rPrChange should record the previous state (no bold).
///
/// Old: normal text "Bold test text here."
/// New: bold text "Bold test text."
///
/// The unchanged portion "Bold test text" should get an rPrChange showing
/// the previous state without bold. The diff treats this as modified text
/// (due to the "here." deletion) and detects the formatting change on the
/// overlapping portion.
#[test]
fn spec_rprchange_preserves_previous_bold() {
    let redline_bytes = redline_from_pair("bold-change");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut rpr_changes = Vec::new();
    find_all_w_elements(&root, "rPrChange", &mut rpr_changes);
    assert!(
        !rpr_changes.is_empty(),
        "redline XML should contain at least one w:rPrChange element \
         when run formatting changes from normal to bold. The diff should \
         detect a formatting difference on the unchanged text portion."
    );

    // The inner rPr of rPrChange should NOT have w:b (text was not bold before).
    let inner_rpr = find_w_child(rpr_changes[0], "rPr")
        .expect("rPrChange should have a child w:rPr element per §17.13.5.31");
    let bold = find_w_child(inner_rpr, "b");
    assert!(
        bold.is_none(),
        "inner rPr of rPrChange should NOT have w:b since the text was not bold \
         before. The previous state had no bold formatting."
    );

    // The outer rPr (on the run itself) SHOULD have w:b (current state is bold).
    let mut runs = Vec::new();
    find_all_w_elements(&root, "r", &mut runs);
    let run_with_bold = runs.iter().find(|r| {
        find_w_child(r, "rPr")
            .and_then(|rpr| find_w_child(rpr, "b"))
            .is_some()
    });
    assert!(
        run_with_bold.is_some(),
        "at least one run in the redline output should have w:b (the current bold state)"
    );

    // rPrChange must have w:author and w:id attributes.
    assert!(
        attr_value(rpr_changes[0], "w:author").is_some()
            || attr_value(rpr_changes[0], "author").is_some(),
        "rPrChange should have a w:author attribute"
    );
}

// =========================================================================
// 5. pPrChange is a COMPLETE snapshot, not a delta
//    ECMA-376 §17.13.5.29
// =========================================================================

/// ECMA-376 §17.13.5.29: The child pPr of pPrChange is a COMPLETE snapshot
/// of the previous paragraph properties, not just the properties that changed.
///
/// Old: left-aligned, spacing before=240, keepNext=true, "Complete snapshot test here."
/// New: center-aligned, spacing before=240, keepNext=true, "Complete snapshot test."
/// (only alignment and text changed)
///
/// The pPrChange should record ALL previous properties:
/// - jc = left (alignment changed)
/// - spacing before = 240 (unchanged but should be in the snapshot)
/// - keepNext (unchanged but should be in the snapshot)
///
/// Previously a known gap -- pPrChange now emits a complete snapshot
/// including properties like keepNext.
#[test]
fn spec_pprchange_is_complete_snapshot_not_delta() {
    let redline_bytes = redline_from_pair("complete-snapshot");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut ppr_changes = Vec::new();
    find_all_w_elements(&root, "pPrChange", &mut ppr_changes);
    assert!(
        !ppr_changes.is_empty(),
        "redline XML should contain at least one w:pPrChange element"
    );

    let inner_ppr =
        find_w_child(ppr_changes[0], "pPr").expect("pPrChange should have a child w:pPr element");

    // Check 1: previous alignment should be recorded (this property changed).
    let jc = find_w_child(inner_ppr, "jc");
    assert!(
        jc.is_some(),
        "inner pPr should have w:jc recording previous alignment"
    );
    let jc_val = attr_value(jc.unwrap(), "w:val").or_else(|| attr_value(jc.unwrap(), "val"));
    assert_eq!(jc_val, Some("left"), "previous alignment should be 'left'");

    // Check 2: previous spacing should be recorded (did NOT change, but per
    // §17.13.5.29 the inner pPr is a complete snapshot of the previous state).
    let spacing = find_w_child(inner_ppr, "spacing");
    assert!(
        spacing.is_some(),
        "inner pPr should have w:spacing recording previous spacing (before=240), \
         even though spacing did not change. Per §17.13.5.29, pPrChange is a \
         complete snapshot of the previous state."
    );
    let before_val =
        attr_value(spacing.unwrap(), "w:before").or_else(|| attr_value(spacing.unwrap(), "before"));
    assert_eq!(
        before_val,
        Some("240"),
        "previous spacing before should be '240'"
    );

    // Check 3: keepNext should be recorded (did NOT change, but should be in snapshot).
    // This is the key gap: our model does not capture keepNext in ParagraphFormattingChange.
    let keep_next = find_w_child(inner_ppr, "keepNext");
    assert!(
        keep_next.is_some(),
        "inner pPr should have w:keepNext recording that the previous paragraph \
         had keepNext=true. Per §17.13.5.29, the child pPr of pPrChange must be \
         a COMPLETE snapshot of previous properties, not just the changed ones. \
         Our ParagraphFormattingChange does not model keepNext, so this is lost."
    );
}

// =========================================================================
// 6. Cell formatting change (tcPrChange) on cell shading
//    ECMA-376 §17.13.5.36
// =========================================================================

/// ECMA-376 §17.13.5.36: When cell properties change (shading added) alongside
/// a text edit, tcPrChange should capture the previous cell state.
///
/// Old: table with unshaded cell, "Cell content here."
/// New: cell gets yellow shading, "Cell content."
///
/// This test documents a known gap: our diff engine does not track cell-level
/// formatting changes during diff_and_redline. CellFormattingChange is only
/// populated during import of DOCX files that already contain w:tcPrChange.
#[test]
fn spec_formatting_change_on_table_cell_properties() {
    let redline_bytes = redline_from_pair("cell-shading-change");
    let xml = extract_document_xml(&redline_bytes);
    let root = parse_xml(&xml);

    let mut tc_pr_changes = Vec::new();
    find_all_w_elements(&root, "tcPrChange", &mut tc_pr_changes);
    assert!(
        !tc_pr_changes.is_empty(),
        "redline XML should contain at least one w:tcPrChange element \
         when cell formatting changes (shading added). Currently, our diff \
         engine does not track cell formatting changes."
    );

    // The inner tcPr of tcPrChange should NOT have w:shd (cell was unshaded before).
    let inner_tc_pr = find_w_child(tc_pr_changes[0], "tcPr")
        .expect("tcPrChange should have a child w:tcPr element");
    let shd = find_w_child(inner_tc_pr, "shd");
    assert!(
        shd.is_none(),
        "inner tcPr of tcPrChange should NOT have w:shd since the cell was \
         unshaded before"
    );
}
