//! Spec-compliance tests: nil vs none border semantics (MS-OI29500 SS2.1.169).
//!
//! Per MS-OI29500 SS2.1.169, there is a critical distinction between `nil` and
//! `none` border styles in conflict resolution:
//!
//! - **`none`** = "I have no border" -> the opposing border SHALL be displayed
//! - **`nil`**  = "Explicitly suppress this border" -> NO border shall be
//!   displayed (nil wins, suppresses the opposing border)
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-border-nil-none/create_docs.py`

use stemma::{BlockNode, BorderStyle, CanonDoc};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-border-nil-none";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

// =============================================================================
// 1. nil border suppresses opposing table border
//    MS-OI29500 SS2.1.169
// =============================================================================

/// MS-OI29500 SS2.1.169: nil border means "no border shall be displayed",
/// suppressing even the opposing side's border at the shared edge.
///
/// Setup: 1x2 table with table-level borders (single sz=8 black).
/// Cell (0,0) has tcBorders right=nil. Cell (0,1) has no tcBorders.
///
/// At the shared edge, cell (0,0) has explicit nil. The table-level insideV
/// that would be inherited by cell (0,1) should NOT display because nil means
/// "no border shall be displayed."
///
/// After conflict resolution, both cells should show no border at the shared
/// edge (nil suppresses the inherited insideV).
#[test]
fn spec_nil_border_suppresses_opposing_table_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nil-suppresses-opposing");
    let table = first_table(&doc);

    // Cell (0,0) explicitly set right=nil. After resolution, this should remain
    // nil/none (no border) because nil suppresses everything.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref());

    match cell_00_right {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::Nil | BorderStyle::None),
                "cell (0,0) right border should be Nil or None (suppressed), got {:?} — \
                 MS-OI29500 SS2.1.169: nil means 'no border shall be displayed'",
                border.style
            );
        }
        None => {
            // No border at all is also acceptable (suppressed = absent)
        }
    }

    // Cell (0,1) would inherit insideV from table borders, but the adjacent
    // cell (0,0) has nil which should suppress it. After conflict resolution,
    // cell (0,1) left border should also be nil/none/absent.
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref());

    match cell_01_left {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::Nil | BorderStyle::None),
                "cell (0,1) left border should be Nil or None — neighbor's nil suppresses \
                 the inherited insideV per MS-OI29500 SS2.1.169. Got {:?}",
                border.style
            );
        }
        None => {
            // No border at all is also acceptable (suppressed = absent)
        }
    }
}

// =============================================================================
// 2. none border allows opposing to display
//    MS-OI29500 SS2.1.169
// =============================================================================

/// MS-OI29500 SS2.1.169: none border means "I have no border",
/// so the opposing side's border wins.
///
/// Setup: 1x2 table with table-level borders (single sz=8 black).
/// Cell (0,0) has tcBorders right=none. Cell (0,1) has tcBorders left=single
/// sz=12 red.
///
/// At the shared edge, cell (0,0) says "I have no border" (none). Cell (0,1)
/// has a red border. Per spec, the red border should win and be displayed on
/// both sides of the shared edge.
#[test]
fn spec_none_border_allows_opposing_to_display() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "none-allows-opposing");
    let table = first_table(&doc);

    // Cell (0,1) explicitly set left=single sz=12 red. This should win because
    // the opposing side (cell (0,0) right) is none ("I have no border").
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border — it explicitly set single sz=12 red");

    assert_eq!(
        cell_01_left.style,
        BorderStyle::Single,
        "cell (0,1) left border should be Single (it declared single sz=12 red)"
    );
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (FF0000)"
    );
    assert_eq!(
        cell_01_left.size,
        Some(12),
        "cell (0,1) left border size should be 12"
    );

    // Cell (0,0) right was none. After conflict resolution, the opposing red
    // border should win at the shared edge. Cell (0,0) right should now show
    // the red border (since none means "I have no border, display the opposing").
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect(
            "cell (0,0) should have a right border after resolution — \
             the opposing red border should win over none",
        );

    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border should be red (FF0000) — the opposing border wins \
         because none means 'I have no border, display the opposing'. \
         MS-OI29500 SS2.1.169: none = opposing border SHALL be displayed"
    );
    assert_eq!(
        cell_00_right.size,
        Some(12),
        "cell (0,0) right border size should be 12 (from winning opposing border)"
    );
}

// =============================================================================
// 3. nil suppresses thick border
//    MS-OI29500 SS2.1.169
// =============================================================================

/// MS-OI29500 SS2.1.169: nil suppresses even a thick heavy border.
///
/// Setup: 1x2 table with no table-level borders.
/// Cell (0,0) has tcBorders right=nil.
/// Cell (0,1) has tcBorders left=thick sz=24 red.
///
/// Per spec, nil means "no border shall be displayed" — it suppresses even the
/// thick border on the opposing side. The shared edge should have NO visible
/// border (nil wins over thick).
#[test]
fn spec_nil_suppresses_thick_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "nil-beats-thick-border");
    let table = first_table(&doc);

    // Cell (0,0) explicitly set right=nil. After resolution, this should
    // remain nil/none — nil is an absolute suppressor.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref());

    match cell_00_right {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::Nil | BorderStyle::None),
                "cell (0,0) right border should be Nil or None (suppressed), got {:?} — \
                 MS-OI29500 SS2.1.169: nil means 'no border shall be displayed'",
                border.style
            );
        }
        None => {
            // No border at all is also acceptable
        }
    }

    // Cell (0,1) had thick sz=24 red, but the adjacent nil should suppress it.
    // After conflict resolution, cell (0,1) left border should be nil/none/absent.
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref());

    match cell_01_left {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::Nil | BorderStyle::None),
                "cell (0,1) left border should be Nil or None — neighbor's nil suppresses \
                 even a thick sz=24 border per MS-OI29500 SS2.1.169. Got {:?} (color={:?}, size={:?})",
                border.style,
                border.color,
                border.size
            );
        }
        None => {
            // No border at all is also acceptable (suppressed = absent)
        }
    }
}

// =============================================================================
// 4. none vs none — no border
//    MS-OI29500 SS2.1.169
// =============================================================================

/// Both sides none means no border at shared edge.
///
/// Setup: 1x2 table with no table-level borders.
/// Cell (0,0) has tcBorders right=none.
/// Cell (0,1) has tcBorders left=none.
///
/// Both sides say "I have no border" — no border displays.
#[test]
fn spec_none_vs_none_no_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "none-vs-none-no-border");
    let table = first_table(&doc);

    // Cell (0,0) right: should be none/nil/absent
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref());

    match cell_00_right {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::None | BorderStyle::Nil),
                "cell (0,0) right border should be None or Nil, got {:?}",
                border.style
            );
        }
        None => {
            // No border at all is also acceptable
        }
    }

    // Cell (0,1) left: should be none/nil/absent
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref());

    match cell_01_left {
        Some(border) => {
            assert!(
                matches!(border.style, BorderStyle::None | BorderStyle::Nil),
                "cell (0,1) left border should be None or Nil, got {:?}",
                border.style
            );
        }
        None => {
            // No border at all is also acceptable
        }
    }
}
