//! Auto-generated by the spec-word-compliance workflow.
//!
//! Area: Style application order (docDefaults -> table -> numbering -> para ->
//! char -> direct).
//!
//! Each `#[test]` encodes a Word-compliance constraint mined from ISO/IEC
//! 29500-1, the normative XSD, and the [MS-OI29500] implementer notes. A FAILING
//! assertion here is NOT a flaky test: it encodes a real divergence between
//! stemma and Microsoft Word's documented behaviour and must be triaged as a
//! Word-compliance gap (fix the engine or the model), never "made green" by
//! weakening the assertion.
//!
//! Methodology note (consumption vs. save): stemma round-trips UNTOUCHED content
//! byte-verbatim. So these tests assert on the READ side (read_accepted /
//! read_rejected text) and on opens-clean validity — never on re-serialized XML
//! of an unedited document, which would only re-confirm verbatim preservation.

use stemma::api::{Document, validate};

// ─── Prelude: minimal valid .docx plumbing ──────────────────────────────────

/// Content-type override for a known extra part. Mirrors the overrides Word
/// writes for styles.xml / numbering.xml.
fn content_type_override(part: &str) -> Option<&'static str> {
    match part {
        "word/styles.xml" => Some(
            r#"<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>"#,
        ),
        "word/numbering.xml" => Some(
            r#"<Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>"#,
        ),
        _ => None,
    }
}

/// Document-rels relationship entry for a known extra part.
fn doc_rel(part: &str, rid: &str) -> Option<String> {
    match part {
        "word/styles.xml" => Some(format!(
            r#"<Relationship Id="{rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>"#
        )),
        "word/numbering.xml" => Some(format!(
            r#"<Relationship Id="{rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>"#
        )),
        _ => None,
    }
}

/// Build a valid minimal `.docx`. `body_xml` is wrapped in
/// `<w:document …><w:body>…</w:body></w:document>`. Each `(part, xml)` in
/// `extra_parts` is added as its own zip entry, with a matching
/// `[Content_Types].xml` override and `word/_rels/document.xml.rels` entry.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );

    let mut overrides = String::new();
    for (part, _) in extra_parts {
        let ov = content_type_override(part)
            .unwrap_or_else(|| panic!("no content-type override known for extra part {part}"));
        overrides.push_str(ov);
    }
    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>{overrides}</Types>"#
    );

    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;

    let mut doc_rels_inner = String::new();
    for (i, (part, _)) in extra_parts.iter().enumerate() {
        let rid = format!("rIdX{}", i + 1);
        let r = doc_rel(part, &rid)
            .unwrap_or_else(|| panic!("no document rel known for extra part {part}"));
        doc_rels_inner.push_str(&r);
    }
    let doc_rels = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{doc_rels_inner}</Relationships>"#
    );

    use std::io::Write;
    use zip::write::FileOptions;
    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (part, xml) in extra_parts {
            zip.start_file(*part, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip `docx` and return `word/document.xml` as a String.
#[allow(dead_code)]
fn document_xml_of(docx: &[u8]) -> String {
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(docx)).expect("open zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("document.xml present");
    let mut s = String::new();
    use std::io::Read;
    file.read_to_string(&mut s).expect("read document.xml");
    s
}

/// Parse -> serialize(default) -> the resulting `word/document.xml` String.
#[allow(dead_code)]
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse for reserialize");
    let out = doc
        .serialize(&stemma::ExportOptions::default())
        .expect("serialize");
    document_xml_of(&out)
}

/// True when `validate()` reports no errors (Word opens without repair).
fn opens_clean(bytes: &[u8]) -> bool {
    validate(bytes).ok
}

/// Render the validation issues for an assertion message.
fn validation_detail(bytes: &[u8]) -> String {
    let report = validate(bytes);
    if report.issues.is_empty() {
        "<no issues>".to_string()
    } else {
        report
            .issues
            .iter()
            .map(|i| {
                format!(
                    "[{:?}] {}{}",
                    i.code,
                    i.message,
                    i.context
                        .as_deref()
                        .map(|c| format!(" ({c})"))
                        .unwrap_or_default()
                )
            })
            .collect::<Vec<_>>()
            .join("; ")
    }
}

fn accept_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse for accept")
        .read_accepted()
        .expect("read_accepted")
        .to_text()
        .trim()
        .to_string()
}

fn reject_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse for reject")
        .read_rejected()
        .expect("read_rejected")
        .to_text()
        .trim()
        .to_string()
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn docdefaults_pprdefault_only_no_rprdefault_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Centered default only</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:pPrDefault><w:pPr><w:jc w:val="center"/></w:pPr></w:pPrDefault></w:docDefaults></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.5.1/§17.7.5.3, ECMA-376 §A.1 CT_DocDefaults: rPrDefault is minOccurs=0, so a docDefaults carrying only pPrDefault is schema-valid and must open without repair. validate() issues: {}",
        validation_detail(&b)
    );
}

#[test]
fn docdefaults_rprdefault_empty_rpr_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Empty default run props</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr/></w:rPrDefault><w:pPrDefault><w:pPr/></w:pPrDefault></w:docDefaults></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.5.5, ECMA-376 §A.1 CT_RPrDefault: rPr (and pPr) inside the defaults are minOccurs=0, so an empty default block is schema-valid and must open without repair. validate() issues: {}",
        validation_detail(&b)
    );
}

#[test]
fn numbering_lvl_ppr_disallowed_child_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Numbered body text</w:t></w:r></w:p><w:sectPr/>"#;
    let numbering = (
        "word/numbering.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:keepNext/><w:ind w:left="720" w:hanging="360"/><w:jc w:val="left"/></w:pPr></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>"#,
    );
    let b = make_docx(body, &[numbering]);
    assert!(
        opens_clean(&b),
        "MS-OI29500 §2.1.289 / ISO 29500-1 §17.9.22: keepNext is not in Word's allowed {{jc,ind,tabs}} set for a numbering lvl pPr, but Word ignores the disallowed child rather than refusing the file, so the package must open without repair. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Numbered body text",
        "ISO 29500-1 §17.9.22/§17.7.2: numbering-level pPr (cascade level 3) contributes paragraph formatting only; an ignored extra child cannot inject content, so accepted visible text equals the literal run text."
    );
    assert_eq!(
        reject_text(&b),
        "Numbered body text",
        "ISO 29500-1 §17.9.22: no tracked change is present; reject-all yields the same authored run text regardless of the ignored lvl-pPr child."
    );
}

#[test]
fn numbering_lvl_rpr_disallowed_child_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Item body</w:t></w:r></w:p><w:sectPr/>"#;
    let numbering = (
        "word/numbering.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:lvlJc w:val="left"/><w:rPr><w:rStyle w:val="Strong"/><w:b/></w:rPr></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>"#,
    );
    let b = make_docx(body, &[numbering]);
    assert!(
        opens_clean(&b),
        "MS-OI29500 §2.1.291 / ISO 29500-1 §17.9.24: rStyle is a child Word disallows inside the numbering symbol rPr, but Word ignores it rather than refusing the file, so the package must open without repair. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Item body",
        "ISO 29500-1 §17.9.24: the lvl rPr (and any ignored child) decorates only the generated numbering symbol, never the paragraph's runs; accepted text equals the literal run content with no label injected."
    );
    assert_eq!(
        reject_text(&b),
        "Item body",
        "ISO 29500-1 §17.9.24: no tracked change present; reject-all yields the same run text, and the symbol rPr child cannot add content."
    );
}

#[test]
fn tablenormal_style_children_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Plain paragraph</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="table" w:default="1" w:styleId="TableNormal"><w:name w:val="Normal Table"/><w:rPr><w:b/></w:rPr></w:style></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "MS-OI29500 §2.1.242 / ISO 29500-1 §17.7.4.17: Word ignores the children of TableNormal rather than refusing the document, so a TableNormal carrying an rPr opens without repair. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Plain paragraph",
        "ISO 29500-1 §17.7.4.17/§17.7.2: a style's children (here on the ignored TableNormal) are formatting only and the table-style cascade level injects no text; accepted visible text equals the literal run content."
    );
    assert_eq!(
        reject_text(&b),
        "Plain paragraph",
        "ISO 29500-1 §17.7.4.17: no tracked change present; reject-all yields the same run text regardless of the ignored TableNormal children."
    );
}

#[test]
fn pprdefault_disallowed_child_sectpr_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Defaults section ignored</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:pPrDefault><w:pPr><w:jc w:val="center"/><w:sectPr><w:pgSz w:w="12240" w:h="15840"/></w:sectPr></w:pPr></w:pPrDefault></w:docDefaults></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "MS-OI29500 §2.1.244 / ISO 29500-1 §17.7.5.2: sectPr is a disallowed pPrDefault pPr child, but Word ignores it rather than refusing the file, so the package opens without repair. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Defaults section ignored",
        "ISO 29500-1 §17.7.5.2/§17.7.5: document defaults (cascade level 1) contribute formatting only; an ignored sectPr inside pPrDefault cannot inject content, so accepted text equals the literal run text."
    );
    assert_eq!(
        reject_text(&b),
        "Defaults section ignored",
        "ISO 29500-1 §17.7.5: no tracked change present; reject-all yields the same run text regardless of the ignored pPrDefault sectPr."
    );
}

#[test]
fn rprdefault_disallowed_child_rstyle_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Default rstyle ignored</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="character" w:styleId="Strong"><w:name w:val="Strong"/><w:rPr><w:b/></w:rPr></w:style><w:docDefaults><w:rPrDefault><w:rPr><w:rStyle w:val="Strong"/><w:sz w:val="24"/></w:rPr></w:rPrDefault></w:docDefaults></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "MS-OI29500 §2.1.245 / ISO 29500-1 §17.7.5.4: rStyle is a disallowed rPrDefault rPr child, but Word ignores it rather than refusing the file, so the package opens without repair. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Default rstyle ignored",
        "ISO 29500-1 §17.7.5.4/§17.7.5: document defaults (cascade level 1) contribute run formatting only; an ignored rStyle inside rPrDefault cannot inject content, so accepted text equals the literal run text."
    );
    assert_eq!(
        reject_text(&b),
        "Default rstyle ignored",
        "ISO 29500-1 §17.7.5.4: no tracked change present; reject-all yields the same run text regardless of the ignored rPrDefault rStyle."
    );
}

#[test]
fn direct_numid_zero_removes_style_numbering_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="ListNum"/><w:numPr><w:numId w:val="0"/></w:numPr></w:pPr><w:r><w:t>Body text, numbering removed.</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:styleId="ListNum"><w:name w:val="List Number"/><w:pPr><w:numPr><w:numId w:val="3"/></w:numPr></w:pPr></w:style></w:styles>"#,
    );
    let numbering = (
        "word/numbering.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:multiLevelType w:val="singleLevel"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:lvlJc w:val="left"/></w:lvl></w:abstractNum><w:num w:numId="3"><w:abstractNumId w:val="0"/></w:num></w:numbering>"#,
    );
    let b = make_docx(body, &[styles, numbering]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.9.18: numId=0 is the documented removal sentinel and is never resolved against numbering.xml, so the package must validate without a dangling-numbering-reference error even though the level-0 reference has no w:num definition. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Body text, numbering removed.",
        "ISO 29500-1 §17.7.2: the numbering label (whether applied or removed) is never run text, so removing numbering via direct numId=0 leaves the paragraph's run text exactly the original."
    );
}

#[test]
fn docdefaults_rprdefault_then_pprdefault_order_opens_clean() {
    let body = r#"<w:p><w:r><w:t>Hello, world</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:b/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:jc w:val="center"/></w:pPr></w:pPrDefault></w:docDefaults></w:styles>"#,
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.5.1 / CT_DocDefaults: a styles.xml whose docDefaults orders rPrDefault before pPrDefault is schema-valid and must validate without error. validate() issues: {}",
        validation_detail(&b)
    );
    assert_eq!(
        accept_text(&b),
        "Hello, world",
        "ISO 29500-1 §17.7.5: docDefaults (rPrDefault bold + pPrDefault centered) contributes only formatting; the unstyled paragraph's run text is unchanged, so accepted text equals the original."
    );
}

#[test]
fn toggle_xor_table_level_with_para_chain_cancels_bold() {
    // Render-side XOR resolution is an oracle (Word) question; the daily check
    // here is opens-clean validity of the schema-valid worked example.
    let body = r#"<w:tbl><w:tblPr><w:tblStyle w:val="TblBold"/></w:tblPr><w:tr><w:tc><w:p><w:pPr><w:pStyle w:val="ParaBold"/></w:pPr><w:r><w:t>cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:style w:type=\"table\" w:styleId=\"TblBold\"><w:name w:val=\"TblBold\"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type=\"paragraph\" w:styleId=\"ParaBold\"><w:name w:val=\"ParaBold\"/><w:rPr><w:b/></w:rPr></w:style></w:styles>",
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.3 worked example: a table whose table style and a contained paragraph's style both set the bold toggle is schema-valid; Word opens it without repair (the table-true XOR para-true = off resolution is a render concern). validate() issues: {}",
        validation_detail(&b)
    );
}

#[test]
fn toggle_docdefaults_true_shortcircuits_xor_to_true() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="ParaBold"/></w:pPr><w:r><w:rPr><w:rStyle w:val="CharBold"/></w:rPr><w:t>text</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:docDefaults><w:rPrDefault><w:rPr><w:b/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type=\"paragraph\" w:styleId=\"ParaBold\"><w:name w:val=\"ParaBold\"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type=\"character\" w:styleId=\"CharBold\"><w:name w:val=\"CharBold\"/><w:rPr><w:b/></w:rPr></w:style></w:styles>",
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.3/§17.7.5.4: docDefaults rPrDefault b, a paragraph style b, and a character style b are all schema-valid; Word opens without repair (the docDefaults-true short-circuit forcing effective bold is a render concern). validate() issues: {}",
        validation_detail(&b)
    );
}

#[test]
fn toggle_first_value_in_basedon_chain_wins_not_nearest() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="ChildOff"/></w:pPr><w:r><w:t>text</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = (
        "word/styles.xml",
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:style w:type=\"paragraph\" w:styleId=\"ParentOn\"><w:name w:val=\"ParentOn\"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type=\"paragraph\" w:styleId=\"ChildOff\"><w:name w:val=\"ChildOff\"/><w:basedOn w:val=\"ParentOn\"/><w:rPr><w:b w:val=\"0\"/></w:rPr></w:style></w:styles>",
    );
    let b = make_docx(body, &[styles]);
    assert!(
        opens_clean(&b),
        "ISO 29500-1 §17.7.3/§17.7.4.3: a paragraph style with explicit b val=0 basedOn a parent with b is schema-valid; Word opens without repair (the first-value-in-basedOn-walk-wins resolution is a render concern). validate() issues: {}",
        validation_detail(&b)
    );
}
