//! MS-OI29500 §17.3.1 + MS-DOCX §2.3: Microsoft implementation notes for
//! paragraph properties.
//!
//! These tests encode behaviors documented in Microsoft's implementation notes
//! (MS-OI29500) and Word extensions (MS-DOCX) where Word's actual behavior
//! diverges from or supplements the base ISO 29500 spec.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_ms_para_props.py`.

use stemma::Alignment;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/ms-paragraph-props";

// =========================================================================
// Default paragraph alignment is Left
// =========================================================================

/// MS-OI29500 2.1.45 §17.3.1.13: When no jc element is specified anywhere
/// in the style hierarchy, Word applies left alignment as the default.
///
/// The ISO spec says "no alignment is applied" but Word always defaults
/// to left. Our code currently returns `None` for alignment when no jc
/// is specified, which is technically per ISO but diverges from Word.
///
/// Fixture: jc-default-left
///   P0: no style, no direct jc
///   P1: CenterStyle with jc=center
///   P2: Normal style, no jc
#[test]
fn ms_p01_jc_default_left_when_unspecified() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "jc-default-left");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P0: no alignment specified — Word defaults to Left
    assert_eq!(
        paras[0].align,
        Some(Alignment::Left),
        "P0: Word defaults to Left alignment when jc is unspecified (MS-OI29500 2.1.45). \
         Our code returns None, but Word always applies Left."
    );

    // P1: CenterStyle has jc=center — should resolve center
    assert_eq!(
        paras[1].align,
        Some(Alignment::Center),
        "P1: CenterStyle defines jc=center, should resolve to Center"
    );

    // P2: Normal style, no jc — Word defaults to Left
    assert_eq!(
        paras[2].align,
        Some(Alignment::Left),
        "P2: Normal style with no jc — Word defaults to Left (MS-OI29500 2.1.45)"
    );
}

// =========================================================================
// keepLines ignored inside tables
// =========================================================================

/// MS-OI29500 2.1.46 §17.3.1.14: Word ignores the keepLines property when
/// rendering paragraphs inside a table cell.
///
/// The ISO spec says keepLines applies to all paragraphs, but Word
/// specifically ignores it in table context. This means a consumer that
/// respects keepLines for table paragraphs would diverge from Word behavior.
///
/// Fixture: keeplines-in-table
///   P0: keepLines outside table (should be honored)
///   P1: keepLines inside table cell (Word ignores)
///   P2: keepLines outside table (control)
#[test]
fn ms_p02_keeplines_ignored_in_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "keeplines-in-table");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs (2 body + 1 table cell), got {}",
        paras.len()
    );

    // P0: keepLines outside table — should be Some(true)
    assert_eq!(
        paras[0].keep_lines,
        Some(true),
        "P0: keepLines outside table should be Some(true)"
    );

    // P1: keepLines inside table — Word IGNORES it at render (MS-OI29500
    // 2.1.46), but that is a consumption rule, not a save rewrite: Word
    // preserves the authored markup verbatim on save, and so must we. The
    // model keeps the authored value; renderers apply the ignore-rule.
    assert_eq!(
        paras[1].keep_lines,
        Some(true),
        "P1: authored keepLines inside a table cell stays in the model \
         (render-time ignore-rule, not a save rewrite; MS-OI29500 2.1.46)"
    );

    // P2: keepLines outside table — should be Some(true)
    assert_eq!(
        paras[2].keep_lines,
        Some(true),
        "P2: keepLines outside table (control) should be Some(true)"
    );
}

// =========================================================================
// widowControl ignored inside tables
// =========================================================================

/// MS-OI29500 2.1.66 §17.3.1.44: Word ignores the widowControl property
/// when rendering paragraphs inside a table.
///
/// Same pattern as keepLines — the property is parsed but Word ignores
/// it in table context.
///
/// Fixture: widow-control-in-table
///   P0: widowControl=false outside table
///   P1: widowControl=false inside table cell (Word ignores)
#[test]
fn ms_p03_widow_control_ignored_in_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "widow-control-in-table");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: widowControl=false outside table — should be honored
    assert_eq!(
        paras[0].widow_control,
        Some(false),
        "P0: widowControl=false outside table should be preserved"
    );

    // P1: widowControl=false inside table — Word IGNORES it at render
    // (MS-OI29500 2.1.66), but that is a consumption rule, not a save rewrite:
    // the authored markup must round-trip verbatim. The model keeps the
    // authored value; renderers apply the ignore-rule.
    assert_eq!(
        paras[1].widow_control,
        Some(false),
        "P1: authored widowControl inside a table cell stays in the model \
         (render-time ignore-rule, not a save rewrite; MS-OI29500 2.1.66)"
    );
}

// =========================================================================
// beforeLines/afterLines override non-line-unit spacing
// =========================================================================

/// MS-OI29500 2.1.60 §17.3.1.33: During style hierarchy application, Word
/// overrides non-line-unit spacing (w:before/w:after in twips) with related
/// non-zero line-unit spacing (w:beforeLines/w:afterLines) from earlier in
/// the style hierarchy.
///
/// This is different from the ISO spec's normal precedence rules where
/// direct formatting wins over style. In Word, if a style defines
/// beforeLines=200 and the paragraph has direct before=480, Word uses
/// beforeLines=200 from the style.
///
/// Fixture: spacing-beforelines-override
///   P0: LineSpacedStyle (beforeLines=200, afterLines=100)
///   P1: LineSpacedStyle + direct before=480
///   P2: direct before=480 only (control)
#[test]
fn ms_p04_spacing_beforelines_overrides_direct_before() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "spacing-beforelines-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P0: style only — should have beforeLines=200, afterLines=100
    let sp0 = paras[0]
        .spacing
        .as_ref()
        .expect("P0 should have spacing from LineSpacedStyle");
    assert_eq!(
        sp0.before_lines,
        Some(200),
        "P0 before_lines should be 200 from LineSpacedStyle"
    );
    assert_eq!(
        sp0.after_lines,
        Some(100),
        "P0 after_lines should be 100 from LineSpacedStyle"
    );

    // P1: style + direct before=480.
    // Per MS Word, beforeLines=200 from style should override direct before=480.
    // Our current code does element-level override for direct spacing, so
    // the direct spacing replaces the style's spacing entirely —
    // losing the line-unit values.
    let sp1 = paras[1].spacing.as_ref().expect("P1 should have spacing");
    assert_eq!(
        sp1.before_lines,
        Some(200),
        "P1: Word uses beforeLines=200 from style, overriding direct before=480 \
         (MS-OI29500 2.1.60). Our element-level override drops line-unit values."
    );

    // P2: direct before=480 only (no style) — should be 480
    let sp2 = paras[2].spacing.as_ref().expect("P2 should have spacing");
    assert_eq!(
        sp2.before,
        Some(480),
        "P2 before should be 480 (direct formatting, no style conflict)"
    );
}

// =========================================================================
// Character-unit indents (startChars, etc.) not parsed
// =========================================================================

/// MS-OI29500 2.1.44 §17.3.1.12(a): Word ignores a character-unit indent whose
/// value is zero "along with related character-unit indents applied earlier in
/// the style hierarchy." Read precisely: a direct `startChars="0"` cancels BOTH
/// itself AND the same-named character indent inherited from the style — it is
/// an explicit override to zero, not a no-op. The effective character indent
/// becomes none (rendering falls back to the twip value), and — critically — the
/// direct zero must be preserved in the model so it survives a rebuild. Dropping
/// it would let the style's character indent re-apply and shift the paragraph.
///
/// Fixture: ind-char-unit-zero
///   P0: CharIndentStyle (startChars=100, firstLineChars=50)
///   P1: CharIndentStyle + direct startChars=0 (cancels the inherited startChars)
#[test]
fn ms_p05_char_unit_indent_zero_overrides_inherited() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "ind-char-unit-zero");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: style defines startChars=100, firstLineChars=50.
    let ind0 = paras[0]
        .indent
        .as_ref()
        .expect("P0: CharIndentStyle defines startChars=100, firstLineChars=50");
    assert_eq!(
        ind0.start_chars,
        Some(100),
        "P0: start_chars should be 100 from CharIndentStyle"
    );
    assert_eq!(
        ind0.first_line_chars,
        Some(50),
        "P0: first_line_chars should be 50 from CharIndentStyle"
    );

    // P1: style startChars=100 + direct startChars=0. The explicit direct zero
    // overrides (cancels) the inherited character indent per 2.1.44a, so the
    // resolved start_chars is Some(0), NOT the style's 100. It must be preserved
    // as an explicit zero so a rebuild re-emits it and Word does not re-apply the
    // style's character indent.
    let ind1 = paras[1]
        .indent
        .as_ref()
        .expect("P1: direct startChars=0 is a real override and must be present");
    assert_eq!(
        ind1.start_chars,
        Some(0),
        "P1: direct startChars=0 overrides the style's startChars=100 (MS-OI29500 2.1.44a); \
         the explicit zero is preserved, not dropped or replaced by the inherited value"
    );
    // firstLineChars is a different attribute — not cancelled by startChars=0 —
    // so it still inherits the style's value.
    assert_eq!(
        ind1.first_line_chars,
        Some(50),
        "P1: style's firstLineChars=50 persists (different attribute, not cancelled)"
    );
}

// =========================================================================
// Character-unit indent overrides non-char-unit indent
// =========================================================================

/// MS-OI29500 2.1.44 §17.3.1.12(b): During style hierarchy application,
/// Word overrides non-character-unit indents with related non-zero
/// character-unit indents that are applied earlier in the style hierarchy.
///
/// This means a style's startChars=200 will override a paragraph's direct
/// w:start="720" — the character-unit value takes precedence regardless
/// of position in the hierarchy.
///
/// Fixture: ind-char-unit-override
///   P0: CharOverrideStyle (startChars=200) + direct start=720
///   P1: direct start=720 only (control)
#[test]
fn ms_p06_char_unit_indent_overrides_non_char_unit() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "ind-char-unit-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: style has startChars=200, paragraph has direct start=720.
    // MS-OI29500 2.1.44(b): non-zero style char-unit overrides direct twip.
    // Our model stores both; start_chars=200 signals the consumer to use char-unit.
    let ind0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        ind0.left,
        Some(720),
        "P0: twip value 720 is preserved in the model"
    );
    assert_eq!(
        ind0.start_chars,
        Some(200),
        "P0: start_chars=200 from style should override twip left=720 \
         (MS-OI29500 2.1.44b). Consumer uses start_chars when present and non-zero."
    );

    // P1: direct start=720 only — should resolve to 720 with no char-unit
    let ind1 = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(
        ind1.left,
        Some(720),
        "P1: direct start=720, no char-unit interference"
    );
    assert_eq!(
        ind1.start_chars, None,
        "P1: no char-unit indent — start_chars should be None"
    );
}

// =========================================================================
// mirrorIndents + hanging indent interaction
// =========================================================================

/// MS-OI29500 2.1.49 §17.3.1.18(a): Word incorrectly aligns the hanging
/// indent to the left margin for odd-numbered pages when a hanging indent
/// is used with mirrorIndents.
///
/// We don't parse or handle mirrorIndents at all, so the interaction
/// between mirrorIndents and hanging indent is completely absent.
///
/// Fixture: mirror-indents-hanging
///   P0: mirrorIndents + start=1440, hanging=720
///   P1: mirrorIndents + start=1440, no hanging (control)
///   P2: start=1440, hanging=720, no mirrorIndents (control)
#[test]
fn ms_p07_mirror_indents_with_hanging() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "mirror-indents-hanging");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P2 (control): hanging indent without mirrorIndents — standard behavior
    let ind2 = paras[2].indent.as_ref().expect("P2 should have indent");
    assert_eq!(
        ind2.left,
        Some(1440),
        "P2 left should be 1440 (start=1440, no mirrorIndents)"
    );
    assert_eq!(
        ind2.effective_first_line_twips,
        Some(-720),
        "P2 first_line should be -720 (hanging=720)"
    );

    // P0: mirrorIndents + hanging — Word has a known bug here, but we should
    // at minimum parse the mirrorIndents element so the paragraph model
    // reflects its presence. Currently we ignore mirrorIndents entirely.
    //
    // When mirrorIndents is implemented, the paragraph model should include
    // a field indicating mirror_indents=true, and the consumer should know
    // to swap start/end on even pages.
    let ind0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        ind0.left,
        Some(1440),
        "P0 left should be 1440 (from start=1440)"
    );
    assert_eq!(
        ind0.effective_first_line_twips,
        Some(-720),
        "P0 first_line should be -720 (hanging=720)"
    );
    // mirrorIndents is now parsed
    assert_eq!(paras[0].mirror_indents, Some(true), "P0: mirrorIndents on");
    assert_eq!(
        paras[2].mirror_indents, None,
        "P2: no mirrorIndents — absent"
    );
}

// =========================================================================
// mirrorIndents ignored inside tables
// =========================================================================

/// MS-OI29500 2.1.49 §17.3.1.18(b): Word ignores mirrorIndents when
/// displaying paragraphs inside a table.
///
/// This is the same pattern as keepLines (§17.3.1.14) and widowControl
/// (§17.3.1.44) — certain paragraph properties are silently ignored in
/// table context.
///
/// Fixture: mirror-indents-in-table
///   P0: mirrorIndents + start=1440, end=720 outside table
///   P1: same mirrorIndents inside table cell (Word ignores)
#[test]
fn ms_p08_mirror_indents_ignored_in_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "mirror-indents-in-table");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: outside table — mirrorIndents should be reflected in the model
    let ind0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        ind0.left,
        Some(1440),
        "P0 left should be 1440 (start=1440 outside table)"
    );
    assert_eq!(
        ind0.right,
        Some(720),
        "P0 right should be 720 (end=720 outside table)"
    );
    assert_eq!(
        paras[0].mirror_indents,
        Some(true),
        "P0: mirrorIndents outside table on"
    );

    // P1: inside table — Word ignores mirrorIndents at render time.
    // We parse it faithfully; consumers must check table context.
    let ind1 = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(
        ind1.left,
        Some(1440),
        "P1 left should be 1440 (start=1440, even in table)"
    );
    // We parse mirrorIndents from XML. Table-context suppression is a rendering concern.
    assert_eq!(
        paras[1].mirror_indents,
        Some(true),
        "P1: mirrorIndents parsed from XML (table suppression is a rendering concern)"
    );
}

// =========================================================================
// overrideTableStyleFontSizeAndJustification
// =========================================================================

/// MS-DOCX 2.3.1: The overrideTableStyleFontSizeAndJustification compat
/// setting controls whether the default paragraph style's font size (11pt
/// or 12pt) and left justification override a table style's values.
///
/// When this setting is FALSE (the default!), the default paragraph style's
/// 11pt/12pt font and left justification do NOT override the table style.
/// This means a table style with center alignment and 14pt font will be
/// preserved even though Normal style has left/11pt.
///
/// We don't parse compat settings at all, so this behavioral switch is
/// completely absent from our style resolution.
///
/// Fixture: override-table-style-font-jc
///   FancyTableStyle has jc=center, sz=28 (14pt)
///   Normal style has default left/11pt
///   Table uses FancyTableStyle
/// NOTE: This test requires table style base pPr/rPr propagation to table
/// cell paragraphs, which is separate from the compat setting. The compat
/// setting behavior is verified in spec_ms_tables (override-table-style-font).
#[test]
fn ms_p09_override_table_style_font_size_and_jc() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "override-table-style-font-jc");
    let paras = common::all_paragraphs(&doc);

    // Find paragraphs inside the table (they follow the first body paragraph)
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs (1 body + table cells), got {}",
        paras.len()
    );

    // The table cell paragraphs should have center alignment from the table style.
    // With the default compat setting (false), Normal's left justification
    // should NOT override the table style's center.
    //
    // Find a table cell paragraph (any paragraph after P0 that's inside a table).
    let table_para = &paras[1]; // First table cell paragraph

    assert_eq!(
        table_para.align,
        Some(Alignment::Center),
        "Table cell paragraph should have Center alignment from FancyTableStyle. \
         The default compat setting (overrideTableStyleFontSizeAndJustification=false) \
         means Normal's left jc should NOT override the table style's center. \
         (MS-DOCX 2.3.1)"
    );
}

// =========================================================================
// Tab stop position range [-31680, 31680]
// =========================================================================

/// MS-OI29500 2.1.61 §17.3.1.37: Word restricts tab stop positions to
/// ±31680 twips (±22 inches) — at LOAD/render time. That is a consumption
/// rule, NOT a save rewrite: Word preserves an out-of-range w:pos verbatim in
/// the markup. Clamping at parse rewrote authored positions and collided them
/// with real stops at the boundary (see known_bug_tab_stop_reemit.rs bug 2).
/// The model therefore carries the authored value verbatim.
///
/// Fixture: tab-pos-range
///   Tab stops at: 1440 (normal), 31680 (max), 32000 (beyond max)
#[test]
fn ms_p10_tab_pos_range_preserved_verbatim() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tab-pos-range");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| !p.tab_stops.is_empty())
        .expect("should find a paragraph with tab stops");

    let positions: Vec<i32> = p.tab_stops.iter().map(|s| s.position).collect();
    assert_eq!(
        positions,
        vec![1440, 31680, 32000],
        "authored tab-stop positions round-trip verbatim, including the
         beyond-±31680 value (Word's range limit is a load-time consumption
         rule, not a save rewrite; MS-OI29500 2.1.61)"
    );
}
