//! Spec-compliance tests: Section Inheritance & Settings (ISO 29500-1 sections 17.6, 17.10, 17.11)
//!
//! These tests verify behavioral constraints around:
//! - Header/footer inheritance across sections (per-kind, per-story-type)
//! - evenAndOddHeaders interaction with even-page header filtering
//! - titlePg being section-specific (not inherited across sections)
//! - Section break type completeness (nextColumn)
//! - Continuous section property inheritance (only when unspecified)
//! - Per-section footnote/endnote properties
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/section-inheritance-audit/create_docs.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, SectionProperties, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-inheritance-audit";

// -- helpers ----------------------------------------------------------------

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(blocks: &'a [BlockNode], out: &mut Vec<&'a SectionProperties>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// 1. FOOTER INHERITANCE ACROSS SECTIONS (ISO 29500-1 sections 17.10.2)
// ==========================================================================

/// ISO 29500-1 sections 17.10.2: Footer inheritance across sections.
///
/// S1 defines a default footer "Section 1 Footer". S2 does not define
/// a footer reference. Per spec, S2 should inherit the footer from S1.
///
/// This mirrors the header inheritance test but for footers, which is
/// a separate code path in resolve_section_header_inheritance.
#[test]
fn spec_footer_inheritance_story_parsed() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footer-inheritance");

    // The document should have exactly one footer story
    assert_eq!(
        doc.footers.len(),
        1,
        "document should have exactly 1 footer story, got {}",
        doc.footers.len()
    );

    // Verify it's a Default-kind footer
    assert_eq!(
        doc.footers[0].kind,
        HeaderFooterKind::Default,
        "footer should be Default kind"
    );

    // Verify content
    let text = blocks_text(&doc.footers[0].blocks);
    assert!(
        text.contains("Section 1 Footer"),
        "footer text should contain 'Section 1 Footer', got: '{text}'"
    );
}

/// ISO 29500-1 sections 17.10.2: S2 inherits footer from S1.
///
/// S1's sectPr declares a default footer. S2 (body-level sectPr) has no
/// footer reference. resolve_section_header_inheritance should propagate
/// the default footer ref to S2.
#[test]
fn spec_footer_inherited_to_section_2() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footer-inheritance");

    let footer_part = &doc.footers[0].part_name;

    // S1: mid-document section should have footer_refs with the default footer
    let all_paras = common::all_paragraphs(&doc);
    let sect1_para = all_paras
        .iter()
        .find(|p| p.section_properties.is_some())
        .expect("should find a paragraph with section_properties");
    let s1_sp = sect1_para.section_properties.as_ref().unwrap();
    assert_eq!(s1_sp.footer_refs.len(), 1, "S1 should have 1 footer ref");
    assert_eq!(s1_sp.footer_refs[0].kind, HeaderFooterKind::Default);
    assert_eq!(&s1_sp.footer_refs[0].part_path, footer_part);

    // S2 (body-level section): should inherit footer from S1
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");
    assert_eq!(
        body_sp.footer_refs.len(),
        1,
        "S2 should inherit 1 footer ref from S1, got {}",
        body_sp.footer_refs.len()
    );
    assert_eq!(body_sp.footer_refs[0].kind, HeaderFooterKind::Default);
    assert_eq!(
        &body_sp.footer_refs[0].part_path, footer_part,
        "S2 should inherit S1's default footer"
    );
}

// ==========================================================================
// 2. EVEN HEADERS PRESERVED AT IMPORT WHEN SETTING IS OFF (ISO 29500-1 sections 17.10.1)
// ==========================================================================

/// ISO 29500-1 sections 17.10.1: When evenAndOddHeaders is absent (false),
/// even-page headers shall not be used for layout.
///
/// The fixture has both a default and an even-page header, but NO
/// evenAndOddHeaders setting. We preserve both referenced stories at import
/// time so the model round-trips the package faithfully; page selection logic
/// decides whether the even story is active.
#[test]
fn spec_even_headers_preserved_when_setting_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "even-headers-setting-off");

    // Both referenced stories should remain in the model.
    assert_eq!(
        doc.headers.len(),
        2,
        "referenced header stories should be preserved even when evenAndOddHeaders is off, got {}",
        doc.headers.len()
    );
    let kinds: Vec<&HeaderFooterKind> = doc.headers.iter().map(|h| &h.kind).collect();
    assert!(
        kinds.contains(&&HeaderFooterKind::Default),
        "should preserve Default header, got: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::Even),
        "should preserve Even header story, got: {kinds:?}"
    );
}

/// ISO 29500-1 sections 17.10.1: Even-page header refs remain part of the
/// section model even when evenAndOddHeaders is off.
///
/// This preserves the underlying document structure for round-trip/export.
#[test]
fn spec_even_header_refs_preserved_in_section_props_when_setting_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "even-headers-setting-off");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    // The even reference is preserved in the canonical model.
    let even_refs: Vec<_> = body_sp
        .header_refs
        .iter()
        .filter(|r| r.kind == HeaderFooterKind::Even)
        .collect();
    assert_eq!(
        even_refs.len(),
        1,
        "even-page header ref should be preserved in section properties, got {} even refs",
        even_refs.len()
    );

    assert_eq!(
        body_sp.header_refs.len(),
        2,
        "should preserve both default and even header refs, got {}",
        body_sp.header_refs.len()
    );
}

// ==========================================================================
// 3. EVEN HEADERS PRESERVED WHEN SETTING IS ON (ISO 29500-1 sections 17.10.1)
// ==========================================================================

/// ISO 29500-1 sections 17.10.1: When evenAndOddHeaders is true, both
/// default (odd) and even-page headers should be active.
#[test]
fn spec_even_headers_preserved_when_setting_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "even-headers-setting-on");

    // Both headers should be imported
    assert_eq!(
        doc.headers.len(),
        2,
        "with evenAndOddHeaders on, 2 headers (default + even) should be imported, got {}",
        doc.headers.len()
    );

    let kinds: Vec<&HeaderFooterKind> = doc.headers.iter().map(|h| &h.kind).collect();
    assert!(
        kinds.contains(&&HeaderFooterKind::Default),
        "should have Default header, got: {kinds:?}"
    );
    assert!(
        kinds.contains(&&HeaderFooterKind::Even),
        "should have Even header, got: {kinds:?}"
    );
}

/// Verify even header content is correct when evenAndOddHeaders is on.
#[test]
fn spec_even_header_content_when_setting_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "even-headers-setting-on");

    let even_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Even)
        .expect("should have Even header");
    let text = blocks_text(&even_hdr.blocks);
    assert!(
        text.contains("Even Page Header"),
        "Even header should contain 'Even Page Header', got: '{text}'"
    );
}

// ==========================================================================
// 4. TITLE PAGE IS PER-SECTION (ISO 29500-1 sections 17.10.6)
// ==========================================================================

/// ISO 29500-1 sections 17.10.6: titlePg is per-section, not inherited.
///
/// S1 has titlePg=true with both default and first-page headers.
/// S2 has no titlePg. S1.title_page should be Some(true),
/// S2.title_page should be None (titlePg is not inherited).
#[test]
fn spec_title_page_not_inherited_across_sections() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "title-page-inheritance");

    // S1 (mid-document section) should have title_page=true
    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section"
    );
    let s1 = section_props[0];
    assert_eq!(
        s1.title_page,
        Some(true),
        "S1 title_page should be Some(true), got {:?}",
        s1.title_page
    );

    // S2 (body-level section) should NOT have title_page set
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");
    assert_eq!(
        body_sp.title_page, None,
        "S2 title_page should be None (not inherited from S1), got {:?}",
        body_sp.title_page
    );
}

/// ISO 29500-1 §17.10.6 governs DISPLAY ("title page header SHALL NOT be
/// shown" when `titlePg` is absent), NOT file CONTENT. The parsed model carries
/// header/footer references verbatim, including inherited First-kind refs, and
/// lets the consumer (Word) apply the display rule from `title_page` at render
/// time. The model must NOT mutate stored refs based on `titlePg`.
///
/// S1 has titlePg=true and declares both default and first headers.
/// S2 has no titlePg and no header declarations. S2 inherits BOTH the default
/// AND the first-kind ref from S1 — inheritance does not depend on titlePg.
///
/// Both header stories remain in doc.headers.
#[test]
fn spec_header_refs_inherited_regardless_of_title_pg() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "title-page-inheritance");

    // Both headers should be imported (default + first).
    assert_eq!(
        doc.headers.len(),
        2,
        "should have 2 header stories (default + first), got {}",
        doc.headers.len()
    );

    // S2 inherits BOTH refs from S1 — titlePg gates display, not the model.
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");
    assert_eq!(
        body_sp.header_refs.len(),
        2,
        "S2 should inherit both header refs (default + first), got {}",
        body_sp.header_refs.len()
    );

    let has_default = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S2 should have inherited default header ref");
    assert!(
        has_first,
        "S2 should inherit the first header ref too (titlePg gates display, not the stored model)"
    );
}

// ==========================================================================
// 5. NEXT COLUMN SECTION TYPE (ISO 29500-1 sections 17.6.22)
// ==========================================================================

/// Verifies ISO 29500-1 §17.6.22: nextColumn is one of five valid section
/// break types. The spec defines: nextPage, continuous, evenPage, oddPage,
/// and nextColumn. A document with type="nextColumn" parses correctly.
#[test]
fn spec_next_column_section_type_parsed() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "next-column-section");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section"
    );

    // The section should have section_type=NextColumn.
    // Per ISO 29500-1 sections 17.6.22, nextColumn is a valid ST_SectionMark value.
    assert_eq!(
        section_props[0].section_type,
        Some(stemma::domain::SectionType::NextColumn),
        "section_type should be NextColumn, got {:?}",
        section_props[0].section_type
    );
}

// ==========================================================================
// 6. SECTION TYPE DEFAULT (ISO 29500-1 sections 17.6.22)
// ==========================================================================

/// ISO 29500-1 sections 17.6.22: When w:type is not specified, the default
/// is nextPage.
///
/// The fixture has a sectPr with no w:type element. The parser should
/// leave section_type as None (since the element is absent), and the
/// rendering layer should treat None as nextPage.
#[test]
fn spec_section_type_none_when_absent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "section-type-absent");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section"
    );

    // When w:type is absent, section_type should be None
    assert_eq!(
        section_props[0].section_type, None,
        "absent w:type should be parsed as None, got {:?}",
        section_props[0].section_type
    );
}

/// When w:type is absent, the section should still parse its margins.
#[test]
fn spec_section_type_absent_margins_parsed() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "section-type-absent");

    let section_props = section_paragraphs(&doc);
    assert!(!section_props.is_empty());

    let s1 = section_props[0];
    assert_eq!(
        s1.margin_top,
        Some(1440),
        "margin_top should be 1440, got {:?}",
        s1.margin_top
    );
    assert_eq!(
        s1.margin_left,
        Some(1800),
        "margin_left should be 1800, got {:?}",
        s1.margin_left
    );
}

// ==========================================================================
// 7. FOOTNOTE PROPERTIES PER SECTION (ISO 29500-1 sections 17.11.3)
// ==========================================================================

/// ISO 29500-1 sections 17.11.3: Section-level footnotePr parsed correctly.
///
/// S1 has footnotes at pageBottom with lowerRoman numbering.
/// S2 has footnotes beneathText starting at 10.
#[test]
fn spec_footnote_props_section_1() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-props-per-section");

    let section_props = section_paragraphs(&doc);
    assert!(
        !section_props.is_empty(),
        "should have at least one mid-document section"
    );

    let s1 = section_props[0];
    let fn_pr = s1.footnote_pr.as_ref().expect("S1 should have footnote_pr");

    assert_eq!(
        fn_pr.position,
        Some(stemma::domain::NotePosition::PageBottom),
        "S1 footnote position should be PageBottom, got {:?}",
        fn_pr.position
    );
    assert_eq!(
        fn_pr.num_fmt.as_ref().map(|f| f.to_xml_str()),
        Some("lowerRoman"),
        "S1 footnote numFmt should be lowerRoman, got {:?}",
        fn_pr.num_fmt
    );
}

/// ISO 29500-1 sections 17.11.3: S2 has different footnote properties than S1.
#[test]
fn spec_footnote_props_section_2() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "footnote-props-per-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    let fn_pr = body_sp
        .footnote_pr
        .as_ref()
        .expect("S2 should have footnote_pr");

    assert_eq!(
        fn_pr.position,
        Some(stemma::domain::NotePosition::BeneathText),
        "S2 footnote position should be BeneathText, got {:?}",
        fn_pr.position
    );
    assert_eq!(
        fn_pr.num_start,
        Some(10),
        "S2 footnote numStart should be 10, got {:?}",
        fn_pr.num_start
    );
}

// ==========================================================================
// 8. CONTINUOUS SECTION WITH OWN MARGINS (ISO 29500-1 sections 17.6.22)
// ==========================================================================

/// ISO 29500-1 sections 17.6.22: Continuous section with its own margins
/// should keep those margins, not inherit from the previous section.
///
/// inherit_page_properties only fills in None fields. If S2 specifies
/// margins, they should be preserved.
#[test]
fn spec_continuous_section_keeps_own_margins() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "continuous-own-margins");

    // S1 has wide margins (2880)
    let section_props = section_paragraphs(&doc);
    assert!(!section_props.is_empty());
    let s1 = section_props[0];
    assert_eq!(s1.margin_top, Some(2880), "S1 margin_top should be 2880");
    assert_eq!(s1.margin_left, Some(2880), "S1 margin_left should be 2880");

    // S2 (continuous) has its own narrow margins (720)
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    assert_eq!(
        body_sp.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous"
    );

    // S2 should keep its own margins, NOT inherit S1's
    assert_eq!(
        body_sp.margin_top,
        Some(720),
        "S2 margin_top should be 720 (own), not 2880 (inherited), got {:?}",
        body_sp.margin_top
    );
    assert_eq!(
        body_sp.margin_left,
        Some(720),
        "S2 margin_left should be 720 (own), not 2880 (inherited), got {:?}",
        body_sp.margin_left
    );
    assert_eq!(
        body_sp.margin_bottom,
        Some(720),
        "S2 margin_bottom should be 720, got {:?}",
        body_sp.margin_bottom
    );
    assert_eq!(
        body_sp.margin_right,
        Some(720),
        "S2 margin_right should be 720, got {:?}",
        body_sp.margin_right
    );
}

// ==========================================================================
// 9. MIXED HEADER + FOOTER INHERITANCE (ISO 29500-1 sections 17.10.2, 17.10.5)
// ==========================================================================

/// ISO 29500-1 sections 17.10.2 / 17.10.5: Mixed header and footer inheritance.
///
/// S1 declares default header + default footer.
/// S2 declares only a first-page header (no default header, no footer).
/// S2 should inherit default header from S1 AND default footer from S1.
#[test]
fn spec_mixed_stories_parsed() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-inheritance");

    // 2 headers (default from S1 + first from S2)
    assert_eq!(
        doc.headers.len(),
        2,
        "should have 2 header stories, got {}",
        doc.headers.len()
    );

    // 1 footer (default from S1)
    assert_eq!(
        doc.footers.len(),
        1,
        "should have 1 footer story, got {}",
        doc.footers.len()
    );
}

/// S2 should have 2 header refs: own first + inherited default.
#[test]
fn spec_mixed_s2_header_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-inheritance");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    // S2 should have 2 header refs: first (own) + default (inherited from S1)
    assert_eq!(
        body_sp.header_refs.len(),
        2,
        "S2 should have 2 header refs (own first + inherited default), got {:?}",
        body_sp.header_refs
    );

    let has_default = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S2 should have inherited default header ref");
    assert!(has_first, "S2 should have own first header ref");
}

/// S2 should inherit the default footer from S1.
#[test]
fn spec_mixed_s2_footer_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-inheritance");

    let footer_part = &doc.footers[0].part_name;

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    // S2 should have 1 footer ref: default (inherited from S1)
    assert_eq!(
        body_sp.footer_refs.len(),
        1,
        "S2 should have 1 footer ref (inherited default), got {:?}",
        body_sp.footer_refs
    );

    assert_eq!(body_sp.footer_refs[0].kind, HeaderFooterKind::Default);
    assert_eq!(
        &body_sp.footer_refs[0].part_path, footer_part,
        "S2's footer ref should point to S1's footer"
    );
}

/// S1 header content should be "Section 1 Default Header".
#[test]
fn spec_mixed_header_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-inheritance");

    let default_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::Default)
        .expect("should have Default header");
    let text = blocks_text(&default_hdr.blocks);
    assert!(
        text.contains("Section 1 Default Header"),
        "Default header should contain 'Section 1 Default Header', got: '{text}'"
    );

    let first_hdr = doc
        .headers
        .iter()
        .find(|h| h.kind == HeaderFooterKind::First)
        .expect("should have First header");
    let text = blocks_text(&first_hdr.blocks);
    assert!(
        text.contains("Section 2 First Header"),
        "First header should contain 'Section 2 First Header', got: '{text}'"
    );
}

/// Footer content should be "Section 1 Default Footer".
#[test]
fn spec_mixed_footer_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-header-footer-inheritance");

    let text = blocks_text(&doc.footers[0].blocks);
    assert!(
        text.contains("Section 1 Default Footer"),
        "Default footer should contain 'Section 1 Default Footer', got: '{text}'"
    );
}

// ==========================================================================
// 10. ENDNOTE PROPERTIES PER SECTION (ISO 29500-1 sections 17.11.2)
// ==========================================================================

/// ISO 29500-1 sections 17.11.2: Section-level endnotePr parsed correctly.
///
/// S1 has endnotes at sectEnd with upperRoman numbering.
/// S2 has endnotes at docEnd.
#[test]
fn spec_endnote_props_section_1() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "endnote-props-per-section");

    let section_props = section_paragraphs(&doc);
    assert!(!section_props.is_empty());

    let s1 = section_props[0];
    let en_pr = s1.endnote_pr.as_ref().expect("S1 should have endnote_pr");

    assert_eq!(
        en_pr.position,
        Some(stemma::domain::NotePosition::SectEnd),
        "S1 endnote position should be SectEnd, got {:?}",
        en_pr.position
    );
    assert_eq!(
        en_pr.num_fmt.as_ref().map(|f| f.to_xml_str()),
        Some("upperRoman"),
        "S1 endnote numFmt should be upperRoman, got {:?}",
        en_pr.num_fmt
    );
}

/// ISO 29500-1 sections 17.11.2: S2 has endnote position at docEnd.
#[test]
fn spec_endnote_props_section_2() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "endnote-props-per-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist");

    let en_pr = body_sp
        .endnote_pr
        .as_ref()
        .expect("S2 should have endnote_pr");

    assert_eq!(
        en_pr.position,
        Some(stemma::domain::NotePosition::DocEnd),
        "S2 endnote position should be DocEnd, got {:?}",
        en_pr.position
    );
}
