//! Deep probing tests: Table Conditional Formatting (ISO 29500-1 §17.7.6)
//!
//! These tests probe the exact boundaries of what works and what doesn't
//! in the conditional formatting system, complementing the broader tests
//! in spec_table_cascade.rs and spec_table_style_resolution.rs.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, InlineNode, TableNode};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-conditional-deep";

// ── helpers ──────────────────────────────────────────────────────────────
fn first_table(doc: &CanonDoc) -> &TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

// ── A) tblLook flags controlling which conditionals apply (§17.7.6) ─────

/// ISO 29500-1 §17.7.6: When w:tblLook w:firstRow="0", the firstRow
/// conditional formatting should NOT apply even though the style defines it.
///
/// Table style has firstRow (blue 4472C4) and band1Horz (gray D9D9D9).
/// tblLook disables firstRow. Row 0 would get band1Horz IF band size > 0.
///
/// NOTE: Per MS-OI29500 §17.7.6.5, band size defaults to 0 when
/// absent, meaning no banding. This fixture doesn't specify tblStyleRowBandSize,
/// so no banding is applied and row 0 gets no conditional shading at all.
#[test]
fn spec_tbllook_disables_firstrow_row0_gets_banding() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-disables-firstrow");
    let table = first_table(&doc);

    // Band size defaults to 0 = no banding.
    // firstRow is disabled, and without banding, row 0 gets no conditional shading.
    assert!(
        table.rows[0].cells[0].formatting.shading.is_none(),
        "cell (0,0): no shading — firstRow disabled and band size defaults to 0"
    );
}

/// With firstRow disabled and band size defaulting to 0, no rows get banding.
///
/// tblStyleRowBandSize defaults to 0 when absent = no banding.
#[test]
fn spec_tbllook_disables_firstrow_banding_continues() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-disables-firstrow");
    let table = first_table(&doc);

    // Band size defaults to 0 = no banding for any row.
    assert!(
        table.rows[2].cells[0].formatting.shading.is_none(),
        "cell (2,0): no shading — band size defaults to 0"
    );

    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): no shading — band size defaults to 0"
    );
}

// ── B) Conditional cell margins from firstRow (§17.7.6) ─────────────────

/// ISO 29500-1 §17.7.6: firstRow conditional with tblCellMar in tcPr.
/// Cell margins (150tw) should be applied to first-row cells.
#[test]
fn spec_conditional_cell_margins_firstrow() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-cell-margins");
    let table = first_table(&doc);

    // First row cell (0,0): should have shading AND margins from conditional
    let shading = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading from firstRow conditional");
    assert_eq!(
        shading.fill.as_deref(),
        Some("4472C4"),
        "cell (0,0): shading should be blue (4472C4) from firstRow conditional"
    );

    let margins = table.rows[0].cells[0]
        .formatting
        .margins
        .as_ref()
        .expect("cell (0,0) should have margins from firstRow conditional");
    assert_eq!(
        margins.top,
        Some(150),
        "cell (0,0) margin top should be 150tw from firstRow conditional"
    );
    assert_eq!(
        margins.left,
        Some(150),
        "cell (0,0) margin left should be 150tw from firstRow conditional"
    );
}

/// ISO 29500-1 §17.7.6: Data row cells should NOT get conditional margins.
#[test]
fn spec_conditional_cell_margins_data_row_unaffected() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-cell-margins");
    let table = first_table(&doc);

    // Data row (1,0): no conditional applies → no margins
    assert!(
        table.rows[1].cells[0].formatting.margins.is_none(),
        "cell (1,0): data row should have no conditional margins"
    );
    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): data row should have no conditional shading"
    );
}

// ── C) Direct cell formatting overrides conditional (§17.7.6) ────────────

/// ISO 29500-1 §17.7.6: Direct cell shading should override conditional shading.
/// Cell (0,0) has direct green shading; firstRow conditional has blue.
/// Direct wins: green (00B050).
#[test]
fn spec_direct_shading_overrides_conditional() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-shading-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,0): direct green should win over conditional blue
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("00B050"),
        "cell (0,0): direct green (00B050) should override conditional blue (4472C4)"
    );

    // Cell (0,1): no direct shading → conditional blue applies
    let shading_01 = table.rows[0].cells[1]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,1) should have shading from firstRow conditional");
    assert_eq!(
        shading_01.fill.as_deref(),
        Some("4472C4"),
        "cell (0,1): should get conditional blue (4472C4)"
    );
}

/// ISO 29500-1 §17.7.6: Data row cells should have no shading.
#[test]
fn spec_direct_shading_data_rows_clean() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-shading-overrides-conditional");
    let table = first_table(&doc);

    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): data row should have no shading"
    );
    assert!(
        table.rows[1].cells[1].formatting.shading.is_none(),
        "cell (1,1): data row should have no shading"
    );
}

// ── D) Conditional firstRow borders (§17.7.6) ───────────────────────────

/// ISO 29500-1 §17.7.6: firstRow conditional with tcBorders should apply
/// cell-level borders to first-row cells.
///
/// The table style has root tblBorders (black sz=4) and firstRow conditional
/// borders (red sz=12). After cascade:
/// - First row cells get red/12 from conditional (cell border wins at table edge)
/// - Data row cells get black/4 from table cascade (no conditional applies)
/// - Adjacent resolution may overwrite data row shared edges with heavier conditional borders
#[test]
fn spec_conditional_firstrow_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-firstrow-borders");
    let table = first_table(&doc);

    // First row cells should have thick red borders from conditional
    let borders_00 = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders from firstRow conditional");

    let top = borders_00
        .top
        .as_ref()
        .expect("cell (0,0) should have top border");
    assert_eq!(
        top.size,
        Some(12),
        "cell (0,0) top border size should be 12 (1.5pt) from firstRow conditional"
    );
    assert_eq!(
        top.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) top border color should be red (FF0000) from firstRow conditional"
    );

    // Data row cells get table-cascaded borders (black/4), NOT conditional borders.
    // The conditional (red/12) should not directly apply to data rows.
    // However, shared edges may show heavier borders from adjacent resolution.
    let borders_10 = table.rows[1].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (1,0) should have borders from table cascade");

    // Non-shared edges should be from table cascade (black/4), NOT from conditional.
    // Cell (1,0) is at left edge and (in a 3-row table) not at bottom edge.
    let left_10 = borders_10
        .left
        .as_ref()
        .expect("cell (1,0) left border should exist from table cascade");
    assert_eq!(
        left_10.size,
        Some(4),
        "cell (1,0) left border should be sz=4 from table cascade, not sz=12 from conditional"
    );
    assert_eq!(
        left_10.color.as_deref(),
        Some("000000"),
        "cell (1,0) left border should be black from table cascade, not red from conditional"
    );
}

// ── E) wholeTable conditional type — discarded per MS-OI29500 §17.18.89 ──

/// MS-OI29500 §2.1.557 (§17.18.89): Word discards properties from tblStylePr
/// with type="wholeTable". Data rows should NOT get shading from wholeTable.
///
/// The fixture's style has shading F2F2F2 only in the wholeTable tblStylePr
/// (no root-level tcPr), so data rows have no shading.
#[test]
fn spec_whole_table_conditional_data_rows() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "whole-table-conditional");
    let table = first_table(&doc);

    // Data rows (1, 2): wholeTable is discarded, no root-level tcPr/shd → no shading
    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): wholeTable discarded per MS-OI29500 §17.18.89, no shading expected"
    );
    assert!(
        table.rows[2].cells[0].formatting.shading.is_none(),
        "cell (2,0): wholeTable discarded per MS-OI29500 §17.18.89, no shading expected"
    );
}

/// MS-OI29500 §17.18.89: firstRow conditional still applies normally.
/// Only wholeTable is discarded; higher-precedence conditionals work as before.
#[test]
fn spec_whole_table_conditional_firstrow_overrides() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "whole-table-conditional");
    let table = first_table(&doc);

    // Row 0: firstRow conditional should still apply blue shading
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading from firstRow conditional");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("4472C4"),
        "cell (0,0): firstRow blue (4472C4) still applies (only wholeTable is discarded)"
    );
}

// ── F) Multiple conditionals merging different property types (§17.7.6) ──

/// ISO 29500-1 §17.7.6: When firstRow provides only borders and firstCol
/// provides only shading, cell (0,0) should get BOTH — the non-overlapping
/// properties merge across conditional layers.
#[test]
fn spec_conditional_merge_corner_gets_both_properties() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-merge-properties");
    let table = first_table(&doc);

    // Cell (0,0): firstRow borders + firstCol shading
    let borders_00 = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders from firstRow conditional");
    let top = borders_00
        .top
        .as_ref()
        .expect("cell (0,0) should have top border");
    assert_eq!(
        top.size,
        Some(12),
        "cell (0,0) top border size should be 12 from firstRow conditional"
    );
    assert_eq!(
        top.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) top border color should be FF0000 from firstRow conditional"
    );

    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading from firstCol conditional");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("70AD47"),
        "cell (0,0): shading should be green (70AD47) from firstCol conditional"
    );
}

/// ISO 29500-1 §17.7.6: Cell (0,1) matches only firstRow (borders only, no shading).
/// Cell (1,0) matches only firstCol (shading only, no borders from conditional).
///
/// The table style has root tblBorders (black sz=4) and:
///   firstRow conditional: red sz=12 borders (no shading)
///   firstCol conditional: green shading (no borders)
///
/// After cascade, cells without conditional borders get table-cascaded borders
/// (black/4) per MS-OI29500 §2.1.169 fallback chain.
#[test]
fn spec_conditional_merge_single_conditional_cells() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-merge-properties");
    let table = first_table(&doc);

    // Cell (0,1): firstRow only → borders (red/12), no shading
    let borders_01 = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,1) should have borders from firstRow conditional");
    assert!(
        borders_01.top.is_some(),
        "cell (0,1) should have top border from firstRow"
    );
    assert!(
        table.rows[0].cells[1].formatting.shading.is_none(),
        "cell (0,1): firstRow has no shading, should be None"
    );

    // Cell (1,0): firstCol only → shading (green), no CONDITIONAL borders.
    // But per MS-OI29500 cascade, gets table-level borders (black/4) as fallback.
    let shading_10 = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (1,0) should have shading from firstCol conditional");
    assert_eq!(
        shading_10.fill.as_deref(),
        Some("70AD47"),
        "cell (1,0): should get green (70AD47) from firstCol"
    );
    // Cell (1,0) has no conditional borders, but gets table-cascaded borders (black/4).
    let borders_10 = table.rows[1].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (1,0) should have borders from table cascade");
    let left_10 = borders_10
        .left
        .as_ref()
        .expect("cell (1,0) left should have table-cascaded border");
    assert_eq!(
        left_10.color.as_deref(),
        Some("000000"),
        "cell (1,0) left: table cascade black, not conditional red"
    );
    assert_eq!(
        left_10.size,
        Some(4),
        "cell (1,0) left: table cascade sz=4, not conditional sz=12"
    );

    // Cell (1,1): no conditional → no shading, but gets table-cascaded borders.
    assert!(
        table.rows[1].cells[1].formatting.shading.is_none(),
        "cell (1,1): interior cell should have no conditional shading"
    );
    // Cell (1,1) has no conditional borders but gets table-cascaded borders (black/4).
    let borders_11 = table.rows[1].cells[1]
        .formatting
        .borders
        .as_ref()
        .expect("cell (1,1) should have borders from table cascade");
    let _top_11 = borders_11
        .top
        .as_ref()
        .expect("cell (1,1) top should have border");
    // The top border may be from adjacent resolution with firstRow cell above.
    // Non-shared edges should be from table cascade.
    let right_11 = borders_11
        .right
        .as_ref()
        .expect("cell (1,1) right should have table-cascaded border");
    assert_eq!(
        right_11.color.as_deref(),
        Some("000000"),
        "cell (1,1) right: table cascade black"
    );
}

// ── G) Band column (vertical) shading (§17.7.6) ─────────────────────────

/// ISO 29500-1 §17.7.6: band1Vert applies to odd columns (0, 2),
/// band2Vert applies to even columns (1, 3). noVBand must be "0".
/// Per MS-OI29500 §17.7.6.5/§17.7.6.7: Band size defaults to 0 when
/// absent, meaning no banding. This fixture doesn't specify tblStyleColBandSize,
/// so no column banding is applied.
#[test]
fn spec_band_column_shading_alternates() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-column-shading");
    let table = first_table(&doc);
    assert_eq!(table.rows.len(), 3, "table should have 3 rows");
    assert!(
        table.rows[0].cells.len() >= 4,
        "table should have 4 columns"
    );

    // Band size defaults to 0 = no banding.
    // No cells should have band shading when band sizes are absent.
    for row_idx in 0..3 {
        for col_idx in 0..4 {
            assert!(
                table.rows[row_idx].cells[col_idx]
                    .formatting
                    .shading
                    .is_none(),
                "cell ({row_idx},{col_idx}): no band shading when band size defaults to 0"
            );
        }
    }
}

// ── H) Direct para alignment overrides conditional (§17.7.6) ──

/// Get the first paragraph in a table cell.
fn cell_first_paragraph(table: &TableNode, row: usize, col: usize) -> &stemma::ParagraphNode {
    let cell = &table.rows[row].cells[col];
    cell.blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Paragraph(p) => Some(p),
            _ => None,
        })
        .expect("cell should contain at least one paragraph")
}

/// Get the first text node in a table cell.
fn cell_first_text_node(table: &TableNode, row: usize, col: usize) -> &stemma::TextNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    return t;
                }
            }
        }
    }
    panic!("cell ({row},{col}) should contain at least one text node")
}

/// ISO 29500-1 §17.7.6: Direct paragraph alignment
/// overrides conditional formatting alignment.
///
/// Table style's firstRow conditional sets jc=center in pPr.
/// Cell (0,0) has direct jc=right on its paragraph.
/// Direct wins: right alignment (not center from conditional).
/// Cell (0,1) has no direct alignment -> gets center from conditional.
#[test]
fn spec_direct_para_alignment_overrides_conditional() {
    let (_runtime, doc) =
        common::import_fixture(FIXTURES, "direct-para-alignment-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,0): direct right should win over conditional center
    let para_00 = cell_first_paragraph(table, 0, 0);
    assert_eq!(
        para_00.align,
        Some(stemma::Alignment::Right),
        "cell (0,0): direct right alignment should override conditional center"
    );

    // Cell (0,1): no direct alignment -> conditional center applies
    let para_01 = cell_first_paragraph(table, 0, 1);
    assert_eq!(
        para_01.align,
        Some(stemma::Alignment::Center),
        "cell (0,1): should get center alignment from conditional (no direct override)"
    );
}

// ── I) Direct font size overrides conditional (§17.7.6) ──

/// ISO 29500-1 §17.7.6: Direct run font size overrides
/// conditional formatting font size.
///
/// Table style's firstRow conditional sets sz=56 (28pt) in rPr.
/// Cell (0,0) run has direct sz=32 (16pt).
/// Direct wins: 32 half-points (not 56 from conditional).
/// Cell (0,1) has no direct font size -> gets 56 from conditional.
#[test]
fn spec_direct_font_size_overrides_conditional() {
    let (_runtime, doc) =
        common::import_fixture(FIXTURES, "direct-font-size-overrides-conditional");
    let table = first_table(&doc);

    // Cell (0,0): direct 32hp should win over conditional 56hp
    let text_00 = cell_first_text_node(table, 0, 0);
    assert_eq!(
        text_00.style_props.font_size,
        Some(32),
        "cell (0,0): direct font size 32hp should override conditional 56hp"
    );

    // Cell (0,1): no direct font size -> conditional 56hp applies
    let text_01 = cell_first_text_node(table, 0, 1);
    assert_eq!(
        text_01.style_props.font_size,
        Some(56),
        "cell (0,1): should get font size 56hp from conditional (no direct override)"
    );
}
