//! AUTO-GENERATED by the spec-word-compliance workflow.
//!
//! Area: "Hyperlink run wrapper (w:hyperlink: r:id, anchor, tgtFrame, tooltip,
//! history, docLocation)".
//!
//! Each `#[test]` encodes a Word-compliance constraint for the `w:hyperlink`
//! element (ISO 29500-1 §17.16.22 / MS-OI29500 §2.1.521 / ECMA-376 Part 1 §A.1
//! CT_Hyperlink). A FAILING assertion here is a REAL Word-compliance gap in the
//! stemma engine, NOT a test to be weakened until it passes. The assertion
//! messages carry the rule text + §refs so a failure is self-explanatory.
//!
//! Methodology note (consumption vs. save): stemma round-trips UNTOUCHED content
//! byte-verbatim. The `w:hyperlink` element is one of the few elements stemma's
//! serializer ACTIVELY REBUILDS on export (`build_hyperlink_element` in
//! `src/serialize/mod.rs`), so `reserialize()` of an unedited hyperlink reflects
//! serializer-generated markup — the correct surface for the "must re-emit
//! attribute X / nested marker Y" assertions below.

use std::io::{Read, Write};

use stemma::api::Document;

// ─── Prelude: minimal-DOCX plumbing (mirrors the shared spec-suite prelude) ──

/// Build a valid minimal `.docx`.
///
/// `body_xml` is wrapped in
/// `<w:document xmlns:w=… xmlns:r=…><w:body>{body_xml}</w:body></w:document>`.
/// The `xmlns:r` declaration is required because every hyperlink body uses
/// `r:id`. Any hyperlink `r:id` referenced in the body gets a matching external
/// hyperlink relationship in `word/_rels/document.xml.rels` so the package opens
/// clean (no dangling reference). `extra_parts` are added under `word/<name>`
/// with a content-type override.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>{body_xml}</w:body></w:document>"#
    );

    // Discover every distinct r:id="rIdN" referenced in the body and emit a
    // hyperlink relationship for each so the package has no dangling reference.
    let mut rids: Vec<String> = Vec::new();
    let needle = "r:id=\"";
    let mut search = body_xml;
    while let Some(pos) = search.find(needle) {
        let rest = &search[pos + needle.len()..];
        if let Some(end) = rest.find('"') {
            let rid = rest[..end].to_string();
            if !rids.contains(&rid) {
                rids.push(rid);
            }
            search = &rest[end + 1..];
        } else {
            break;
        }
    }
    let mut doc_rels = String::from(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">"#,
    );
    for rid in &rids {
        doc_rels.push_str(&format!(
            r#"<Relationship Id="{rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="http://example.com/" TargetMode="External"/>"#
        ));
    }
    doc_rels.push_str("</Relationships>");

    // Content-type overrides for extra parts (styles.xml/numbering.xml/etc).
    let mut overrides = String::new();
    for (name, _) in extra_parts {
        let ct = match *name {
            "styles.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
            }
            "numbering.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
            }
            other => panic!("make_docx: no content-type known for extra part {other}"),
        };
        overrides.push_str(&format!(
            r#"<Override PartName="/word/{name}" ContentType="{ct}"/>"#
        ));
    }

    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>{overrides}</Types>"#
    );
    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;

    use zip::write::FileOptions;
    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (name, content) in extra_parts {
            zip.start_file(format!("word/{name}"), opts).unwrap();
            zip.write_all(content.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip `docx` and return `word/document.xml` as a String.
fn document_xml_of(docx: &[u8]) -> String {
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(docx)).expect("open docx zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("word/document.xml present");
    let mut out = String::new();
    file.read_to_string(&mut out).expect("read document.xml");
    out
}

/// Parse → serialize(default) → return the re-serialized `word/document.xml`.
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse");
    let out = doc
        .serialize(&stemma::ExportOptions::default())
        .expect("serialize");
    document_xml_of(&out)
}

// ─── Specs ────────────────────────────────────────────────────────────────────

#[test]
fn hyperlink_nested_bookmark_preserved_on_serialize() {
    let body = r#"<w:p><w:hyperlink r:id="rId10"><w:bookmarkStart w:id="7" w:name="target"/><w:r><w:t>Click here</w:t></w:r><w:bookmarkEnd w:id="7"/></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("bookmarkStart"),
        "EG_PContent permits bookmarkStart inside a hyperlink (ISO 29500-1 §17.16.22; ECMA-376 §A.1 CT_Hyperlink = r_id?, w_EG_PContent*). A serializer that rebuilds the hyperlink must re-emit the nested w:bookmarkStart it consumed; dropping it severs the bookmark range. — got: {xml}"
    );
    assert!(
        xml.contains("bookmarkEnd"),
        "The matching w:bookmarkEnd is part of the same nested range and must survive serialization for the bookmark to remain well-formed (ISO 29500-1 §17.16.22; ECMA-376 §A.1). — got: {xml}"
    );
    assert!(
        xml.contains("Click here"),
        "The hyperlink display run text must still be present (control: the run is preserved even if the bookmark markers are dropped) (ISO 29500-1 §17.16.22). — got: {xml}"
    );
}

#[test]
fn hyperlink_tooltip_attr_preserved_on_serialize() {
    let body = r#"<w:p><w:hyperlink r:id="rId9" w:tooltip="Click here!"><w:r><w:t>http://example.com</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("w:tooltip=\"Click here!\""),
        "build_hyperlink_element rebuilds the hyperlink and must re-emit the w:tooltip it captured; Word persists tooltip as a saved attribute (MS-OI29500 §2.1.521 caps it at 260 chars), so the value must survive round-trip (ISO 29500-1 §17.16.22). — got: {xml}"
    );
}

#[test]
fn hyperlink_tgtframe_value_preserved_on_serialize() {
    let body = r#"<w:p><w:hyperlink r:id="rId9" w:tgtFrame="_blank"><w:r><w:t>open</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("w:tgtFrame=\"_blank\""),
        "The serializer rebuilds the hyperlink and must re-emit the captured w:tgtFrame attribute and its enumerated value unchanged (ISO 29500-1 §17.16.22; _blank = open target in new browser window). — got: {xml}"
    );
}

#[test]
fn hyperlink_doclocation_attr_preserved_on_serialize() {
    let body = r#"<w:p><w:hyperlink r:id="rId9" w:docLocation="table"><w:r><w:t>Click Here</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("w:docLocation=\"table\""),
        "build_hyperlink_element rebuilds the hyperlink and must re-emit the captured w:docLocation; Word persists it (length-capped at 255 chars per MS-OI29500 §2.1.521), so it must survive round-trip (ISO 29500-1 §17.16.22). — got: {xml}"
    );
}

#[test]
fn hyperlink_inner_run_formatting_restored_after_text_edit() {
    let body = r#"<w:p><w:hyperlink r:id="rId9"><w:r><w:rPr><w:b/></w:rPr><w:t>bold link</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("<w:b"),
        "The bold run inside the hyperlink carries rPr with w:b; the serializer rebuilds the run and must re-emit w:b so the linked text stays bold (ISO 29500-1 §17.16.22 run content). — got: {xml}"
    );
    assert!(
        xml.contains("bold link"),
        "The run display text must be preserved alongside its formatting (ISO 29500-1 §17.16.22). — got: {xml}"
    );
}

#[test]
fn hyperlink_both_rid_and_anchor_roundtrips_both_attrs() {
    let body = r#"<w:p><w:hyperlink r:id="rId7" w:anchor="section2"><w:r><w:t>See section 2 online</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    // xmlRegex translated to contains checks (the regex anchors a single
    // <w:hyperlink …> element; both attributes must appear on it). We assert the
    // attribute substrings AND that there is exactly one hyperlink open tag,
    // which together entail both attrs live on the same element.
    let hyperlink_open_tags = xml.matches("<w:hyperlink").count();
    assert_eq!(
        hyperlink_open_tags, 1,
        "Exactly one <w:hyperlink> element expected (regex <w:hyperlink[^>]*…> targets a single element) (ISO 29500-1 §17.16.22). — got: {xml}"
    );
    assert!(
        xml.contains("w:anchor=\"section2\""),
        "Per MS-OI29500 §2.1.521 Word retains the anchor (it appends '#section2' to the relationship Target), so the serializer must not drop w:anchor when r:id is also present (ISO 29500-1 §17.16.22). [xmlRegex <w:hyperlink[^>]*w:anchor=\"section2\"[^>]*> translated to contains] — got: {xml}"
    );
    assert!(
        xml.contains("r:id=\"rId7\""),
        "The external relationship reference must round-trip so the Target URL the anchor is appended to still resolves (ISO 29500-1 §17.16.22 id attribute). [xmlRegex <w:hyperlink[^>]*r:id=\"rId7\"[^>]*> translated to contains] — got: {xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "A hyperlink with both r:id and anchor is valid CT_Hyperlink; Word opens it without repair (ISO 29500-1 §17.16.22; MS-OI29500 §2.1.521). — validation issues: {:?}",
        report.issues
    );
}

#[test]
fn hyperlink_history_default_false_when_omitted() {
    let body = r#"<w:p><w:hyperlink r:id="rId7"><w:r><w:t>Link</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        !xml.contains("w:history"),
        "ISO 29500-1 §17.16.22: an omitted w:history defaults to false, so the serializer must not synthesize a w:history attribute that was never present in the source. — got: {xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "A history-less external hyperlink is valid CT_Hyperlink; Word opens it without repair (ISO 29500-1 §17.16.22). — validation issues: {:?}",
        report.issues
    );
}

#[test]
fn hyperlink_extra_attrs_history_tgtframe_tooltip_roundtrip() {
    let body = r#"<w:p><w:hyperlink r:id="rId7" w:tooltip="Open report" w:tgtFrame="_blank" w:history="1"><w:r><w:t>Report</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("w:tooltip=\"Open report\""),
        "ISO 29500-1 §17.16.22: tooltip is a meaningful UI string Word preserves; the serializer must round-trip it verbatim. — got: {xml}"
    );
    assert!(
        xml.contains("w:tgtFrame=\"_blank\""),
        "ISO 29500-1 §17.16.22: tgtFrame controls the frameset target; Word preserves it, so the serializer must round-trip it. — got: {xml}"
    );
    assert!(
        xml.contains("w:history=\"1\""),
        "An explicitly-present w:history must be preserved (its absence would flip the semantic to the false default per ISO 29500-1 §17.16.22). — got: {xml}"
    );
    let report = stemma::api::validate(&b);
    assert!(
        report.ok,
        "A hyperlink carrying tooltip/tgtFrame/history is valid CT_Hyperlink; Word opens it without repair (ISO 29500-1 §17.16.22). — validation issues: {:?}",
        report.issues
    );
}

#[test]
fn hyperlink_nested_run_formatting_preserved_on_serialize() {
    let body = r#"<w:p><w:hyperlink r:id="rId10"><w:r><w:rPr><w:rStyle w:val="Hyperlink"/><w:b/></w:rPr><w:t>Click here</w:t></w:r></w:hyperlink></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = reserialize(&b);
    assert!(
        xml.contains("<w:b/>"),
        "ISO 29500-1 §17.16.22: nested runs are ordinary run content; their rPr (bold) is rendered and saved by Word, so the serializer must preserve it. — got: {xml}"
    );
    assert!(
        xml.contains("w:val=\"Hyperlink\""),
        "ISO 29500-1 §17.16.22: the Hyperlink rStyle on the nested run is meaningful formatting that must round-trip. — got: {xml}"
    );
}
