//! Spec-compliance tests: Table Border Conflict Resolution & Conditional Formatting
//! (ISO 29500-1 SS17.4.66, SS17.7.6)
//!
//! These tests audit behavioral compliance of our table border conflict resolution
//! algorithm, conditional formatting application, cell margin cascade, width type
//! handling, vMerge edge cases, and gridSpan overflow.
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-borders-audit/create_docs.py`

use stemma::{BlockNode, BorderStyle, CanonDoc, VerticalMerge, WidthType};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-borders-audit";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

// =============================================================================
// 1. Table border fallback: cells without tcBorders inherit tblBorders
//    (ISO 29500-1 SS17.4.66)
// =============================================================================

/// Verifies ISO 29500-1 SS17.4.66: when a cell has no tcBorders element, the
/// table-level tblBorders serve as the effective borders. Edge cells use the
/// corresponding outer border (top/bottom/left/right), and interior edges use
/// insideH/insideV.
#[test]
fn spec_table_border_fallback_cells_inherit_table_borders() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-fallback-no-cell-borders");
    let table = first_table(&doc);

    // The table has tblBorders (red single sz=12) on all 6 edges.
    // NO cells have tcBorders.
    // Per SS17.4.66, cells should inherit table borders.

    // Verify table-level borders exist
    let tbl_borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have tblBorders");
    assert!(tbl_borders.top.is_some(), "table should have top border");
    assert!(
        tbl_borders.inside_h.is_some(),
        "table should have insideH border"
    );
    assert!(
        tbl_borders.inside_v.is_some(),
        "table should have insideV border"
    );

    // Cell (0,0) is top-left corner.
    // Per spec: top=table.top, bottom=table.insideH, left=table.left, right=table.insideV
    let cell_00_borders = table.rows[0].cells[0].formatting.borders.as_ref();
    assert!(
        cell_00_borders.is_some(),
        "cell (0,0) should have inherited borders from tblBorders — \
         SS17.4.66 says table borders serve as defaults when tcBorders is absent"
    );

    if let Some(borders) = cell_00_borders {
        assert!(
            borders.top.is_some(),
            "cell (0,0) top border should come from tblBorders.top"
        );
        assert!(
            borders.left.is_some(),
            "cell (0,0) left border should come from tblBorders.left"
        );
    }
}

/// SS17.4.66: Interior cell should get insideH for top/bottom borders.
/// Cell (1,0) is bottom-left: top should come from insideH.
#[test]
fn spec_table_border_fallback_bottom_row_gets_inside_h_on_top() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "border-fallback-no-cell-borders");
    let table = first_table(&doc);

    // Cell (1,0): not top row, so top border should come from insideH
    let cell_10_borders = table.rows[1].cells[0].formatting.borders.as_ref();
    assert!(
        cell_10_borders.is_some(),
        "cell (1,0) should have inherited borders from tblBorders — \
         SS17.4.66 fallback not applied to cells without explicit tcBorders"
    );
}

// =============================================================================
// 2. insideV for interior vertical edges
//    (ISO 29500-1 SS17.4.66 + SS17.4.38)
// =============================================================================

/// Verifies SS17.4.66: interior cells' left/right borders come from insideV,
/// not from the table's outer left/right borders.
#[test]
fn spec_inside_v_used_for_interior_vertical_edges() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-v-interior-cells");
    let table = first_table(&doc);

    // Table has: left/right = blue sz=12, insideV = green sz=4
    let tbl_borders = table
        .formatting
        .borders
        .as_ref()
        .expect("table should have borders");

    let outer_left_color = tbl_borders.left.as_ref().unwrap().color.as_deref().unwrap();
    let inside_v_color = tbl_borders
        .inside_v
        .as_ref()
        .unwrap()
        .color
        .as_deref()
        .unwrap();
    assert_eq!(outer_left_color, "0000FF", "outer left should be blue");
    assert_eq!(inside_v_color, "00FF00", "insideV should be green");

    // Cell (0,1) is the middle column (col 1 of 3).
    // Its LEFT border should come from insideV (green), not from table's left (blue).
    let cell_01 = &table.rows[0].cells[1];
    let cell_01_borders = cell_01.formatting.borders.as_ref();
    assert!(
        cell_01_borders.is_some(),
        "cell (0,1) should have borders (inherited from table if not direct) — \
         prerequisite for testing insideV vs left resolution"
    );
    if let Some(borders) = cell_01_borders {
        let left_border = borders
            .left
            .as_ref()
            .expect("cell (0,1) should have a left border");
        let left_color = left_border.color.as_deref().unwrap_or("");
        assert_eq!(
            left_color, "00FF00",
            "cell (0,1) left border should be green (from insideV), got {left_color} — \
             SS17.4.66: interior vertical edges use insideV, not table's left border"
        );
    }
}

/// SS17.4.66: Edge cell (0,0) right border in a 3-column table should use
/// insideV (not table's right border, since it's not the rightmost cell).
#[test]
fn spec_inside_v_first_cell_right_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "inside-v-interior-cells");
    let table = first_table(&doc);

    let tbl_borders = table.formatting.borders.as_ref().unwrap();
    let inside_v_color = tbl_borders
        .inside_v
        .as_ref()
        .unwrap()
        .color
        .as_deref()
        .unwrap();

    // Cell (0,0) right border should be insideV (green), not table right (blue)
    let cell_00 = &table.rows[0].cells[0];
    let cell_00_borders = cell_00.formatting.borders.as_ref();
    assert!(
        cell_00_borders.is_some(),
        "cell (0,0) should have borders (inherited from table if not direct) — \
         prerequisite for testing insideV resolution"
    );
    if let Some(borders) = cell_00_borders {
        let right_border = borders
            .right
            .as_ref()
            .expect("cell (0,0) should have a right border");
        let right_color = right_border.color.as_deref().unwrap_or("");
        assert_eq!(
            right_color, inside_v_color,
            "cell (0,0) right border should be insideV ({inside_v_color}), got {right_color} — \
             SS17.4.66: non-rightmost cell uses insideV for right border"
        );
    }
}

// =============================================================================
// 3. Cell border nil override
//    (ISO 29500-1 SS17.4.66 rules 1-2)
// =============================================================================

/// SS17.4.66 rule 2: Cell borders always win over table borders.
/// When a cell explicitly sets a border to `nil`, the nil should suppress
/// the table border, even though the table has a visible border there.
#[test]
fn spec_cell_nil_border_overrides_table_border() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-border-nil-override");
    let table = first_table(&doc);

    // Table has red single sz=12 borders. Cell (0,0) has nil top border.
    // Per rule 2, cell border wins: top should be nil (no border).
    let cell_00_borders = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("cell (0,0) should have borders");

    let top_border = cell_00_borders
        .top
        .as_ref()
        .expect("cell (0,0) should have a top border entry (even if nil)");
    assert!(
        matches!(top_border.style, BorderStyle::Nil | BorderStyle::None),
        "cell (0,0) top border style should be Nil — cell explicitly set nil, \
         which per SS17.4.66 rule 2 wins over table-level border. Got {:?}",
        top_border.style
    );
}

// =============================================================================
// 4. Cell margin per-side cascade
//    (ISO 29500-1 SS17.4.68)
// =============================================================================

/// SS17.4.68: tcMar overrides tblCellMar. The spec says "This setting, if
/// present, shall override the table cell margins from the table-level cell
/// margins (SS17.4.42)."
///
/// When tcMar specifies only left=400, the full tcMar element replaces
/// tblCellMar (per spec: "override" means replacement, not merge).
/// The other sides are unspecified in tcMar, so they have no value (default).
#[test]
fn spec_cell_margin_per_side_override() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-margin-per-side-cascade");
    let table = first_table(&doc);

    // Table-level: top=100, left=200, bottom=100, right=200
    let table_margins = table
        .formatting
        .default_cell_margins
        .as_ref()
        .expect("table should have default_cell_margins");
    assert_eq!(table_margins.top, Some(100));
    assert_eq!(table_margins.left, Some(200));

    // Cell (0,0) has tcMar with ONLY left=400.
    // Per SS17.4.68, "shall override" means replacement.
    let cell_margins = table.rows[0].cells[0]
        .formatting
        .margins
        .as_ref()
        .expect("cell (0,0) should have per-cell margins from tcMar");
    assert_eq!(
        cell_margins.left,
        Some(400),
        "cell (0,0) left margin should be 400 (from tcMar override)"
    );

    // The other sides should NOT inherit from tblCellMar per spec — tcMar replaces.
    // But the question is whether our code properly handles this.
    // Check that left is correctly overridden (the primary test).
    // The other sides being None vs table-default is an interpretation question.
}

/// Verify table-level cell margins are correctly parsed.
#[test]
fn spec_cell_margin_table_level_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-margin-per-side-cascade");
    let table = first_table(&doc);

    let margins = table
        .formatting
        .default_cell_margins
        .as_ref()
        .expect("table should have default_cell_margins");
    assert_eq!(margins.top, Some(100), "table default top margin");
    assert_eq!(margins.left, Some(200), "table default left margin");
    assert_eq!(margins.bottom, Some(100), "table default bottom margin");
    assert_eq!(margins.right, Some(200), "table default right margin");
}

// =============================================================================
// 5. Width type nil
//    (ISO 29500-1 SS17.18.90, MS-OI29500 SS17.4.2)
// =============================================================================

/// MS-OI29500 SS17.4.2(a): Width type "nil" means "no width specified".
/// Word ignores the element when type is nil. We should preserve the Nil type
/// in our domain model so it's distinguishable from Auto or a zero Dxa width.
#[test]
fn spec_width_type_nil_preserved_in_model() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "width-type-nil");
    let table = first_table(&doc);

    // Cell (0,0) has tcW type=nil
    let cell_00_width = table.rows[0].cells[0]
        .formatting
        .width
        .as_ref()
        .expect("cell (0,0) should have width");
    assert_eq!(
        cell_00_width.width_type,
        WidthType::Nil,
        "cell (0,0) width type should be Nil, not Auto or Dxa — \
         SS17.18.90: nil is distinct from zero-width"
    );

    // Cell (0,1) has tcW type=dxa w=3000
    let cell_01_width = table.rows[0].cells[1]
        .formatting
        .width
        .as_ref()
        .expect("cell (0,1) should have width");
    assert_eq!(
        cell_01_width.width_type,
        WidthType::Dxa,
        "cell (0,1) width type should be Dxa"
    );
    assert_eq!(cell_01_width.w, 3000, "cell (0,1) width should be 3000");
}

/// Nil width type should NOT be normalized to Auto.
/// Our parse_table_measurement has logic: "if w=0 and type is not Nil/Auto,
/// normalize to Auto". Nil should be exempt from this normalization.
#[test]
fn spec_width_type_nil_not_normalized_to_auto() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "width-type-nil");
    let table = first_table(&doc);

    let cell_00_width = table.rows[0].cells[0]
        .formatting
        .width
        .as_ref()
        .expect("cell (0,0) should have width");

    // Nil must not be converted to Auto
    assert_ne!(
        cell_00_width.width_type,
        WidthType::Auto,
        "nil width type must not be normalized to auto — \
         SS17.18.90: nil means 'no width specified', which is semantically \
         different from auto"
    );
}

// =============================================================================
// 6. vMerge continue without restart
//    (ISO 29500-1 SS17.4.84)
// =============================================================================

/// SS17.4.84: A vMerge=continue cell without a preceding restart is
/// non-conformant. Word treats it as a standalone cell.
///
/// Our implementation normalizes this to VerticalMerge::None, which matches
/// Word's behavior but differs from returning an error.
#[test]
fn spec_vmerge_orphan_continue_normalized_to_none() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-continue-no-restart");
    let table = first_table(&doc);

    // Row 0, Cell 0: no vMerge → None
    assert_eq!(
        table.rows[0].cells[0].v_merge,
        VerticalMerge::None,
        "row 0 cell 0 should have no vMerge"
    );

    // Row 1, Cell 0: vMerge=continue with no restart above → should be normalized to None
    assert_eq!(
        table.rows[1].cells[0].v_merge,
        VerticalMerge::None,
        "row 1 cell 0: orphan vMerge=continue should be normalized to None — \
         SS17.4.84: Word treats orphan continue as standalone cell"
    );

    // Row 2, Cell 0: no vMerge → None
    assert_eq!(
        table.rows[2].cells[0].v_merge,
        VerticalMerge::None,
        "row 2 cell 0 should have no vMerge"
    );
}

/// The orphan continue cell should still have its content preserved.
#[test]
fn spec_vmerge_orphan_content_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "vmerge-continue-no-restart");
    let table = first_table(&doc);

    // Row 1, Cell 0 had text "OrphanContinue". Even after normalization,
    // the cell content should be preserved.
    let cell_text = cell_text_content(&table.rows[1].cells[0]);
    assert!(
        !cell_text.is_empty(),
        "orphan continue cell should preserve its content after normalization"
    );
}

fn cell_text_content(cell: &stemma::TableCellNode) -> String {
    let mut text = String::new();
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            let inlines = p.all_inlines_owned();
            for inline in &inlines {
                if let stemma::InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

// =============================================================================
// 7. gridSpan overflow
//    (ISO 29500-1 SS17.4.17, MS-OI29500 SS17.4.17)
// =============================================================================

/// SS17.4.17: gridSpan should not exceed the grid column count.
/// MS-OI29500: gridSpan of 0 is treated as 1.
///
/// Our implementation clamps gridSpan to the total grid_col count.
/// This test verifies the clamping occurs.
#[test]
fn spec_gridspan_overflow_clamped() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-overflow");
    let table = first_table(&doc);

    let grid_cols = table.formatting.grid_cols.len() as u32;
    assert_eq!(grid_cols, 3, "grid should have 3 columns");

    // Row 1, Cell 1 originally had gridSpan=5, which exceeds the 3-column grid.
    // Our code should clamp it.
    let cell_11_span = table.rows[1].cells[1].grid_span;
    assert!(
        cell_11_span <= grid_cols,
        "row 1 cell 1 gridSpan ({cell_11_span}) should be clamped to grid width ({grid_cols}) — \
         SS17.4.17: gridSpan must not exceed grid column count"
    );
}

/// Verify row 0 cells are normal (gridSpan=1 each).
#[test]
fn spec_gridspan_overflow_row0_normal() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "gridspan-overflow");
    let table = first_table(&doc);

    assert_eq!(table.rows[0].cells.len(), 3, "row 0 should have 3 cells");
    for (i, cell) in table.rows[0].cells.iter().enumerate() {
        assert_eq!(cell.grid_span, 1, "row 0 cell {i} gridSpan should be 1");
    }
}

// =============================================================================
// 8. Conditional banding with lastRow exclusion
//    (ISO 29500-1 SS17.7.6)
// =============================================================================

/// SS17.7.6: When firstRow+lastRow are both enabled in tblLook, the banding
/// calculation should exclude both the first and last rows.
///
/// 4-row table: Row 0=firstRow, Row 3=lastRow, Rows 1-2=data rows.
/// Data rows should alternate: row 1=band1 (gray D9D9D9), row 2=band2 (light yellow FFFFCC).
#[test]
fn spec_banding_firstrow_gets_firstrow_formatting() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "banding-last-row-exclusion");
    let table = first_table(&doc);

    // Row 0 should have firstRow conditional shading (red FF0000)
    let shading_0 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("row 0 should have firstRow conditional shading");
    assert_eq!(
        shading_0.fill.as_deref(),
        Some("FF0000"),
        "row 0 (firstRow) should have red shading from firstRow conditional"
    );
}

#[test]
fn spec_banding_lastrow_gets_lastrow_formatting() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "banding-last-row-exclusion");
    let table = first_table(&doc);

    // Row 3 should have lastRow conditional shading (blue 0000FF)
    let shading_3 = table.rows[3].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("row 3 should have lastRow conditional shading");
    assert_eq!(
        shading_3.fill.as_deref(),
        Some("0000FF"),
        "row 3 (lastRow) should have blue shading from lastRow conditional"
    );
}

#[test]
fn spec_banding_data_rows_alternate() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "banding-last-row-exclusion");
    let table = first_table(&doc);

    // Row 1 (data_row_idx=0) should have band1Horz (gray D9D9D9)
    let shading_1 = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("row 1 should have band1 shading");
    assert_eq!(
        shading_1.fill.as_deref(),
        Some("D9D9D9"),
        "row 1 (data row 0) should have band1Horz gray shading (D9D9D9)"
    );

    // Row 2 (data_row_idx=1) should have band2Horz (light yellow FFFFCC)
    let shading_2 = table.rows[2].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("row 2 should have band2 shading");
    assert_eq!(
        shading_2.fill.as_deref(),
        Some("FFFFCC"),
        "row 2 (data row 1) should have band2Horz light yellow shading (FFFFCC)"
    );
}

// =============================================================================
// 9. Adjacent cell border conflict
//    (ISO 29500-1 SS17.4.66 rule 3)
// =============================================================================

/// SS17.4.66 rule 3: When two adjacent cells have conflicting borders, the
/// border with higher weight (size * style_rank) wins.
///
/// Cell (0,0) right border: single sz=24 red (weight = 24*1 = 24)
/// Cell (0,1) left border:  single sz=4  blue (weight = 4*1 = 4)
/// The heavier border (red, sz=24) wins and is applied to both cells.
#[test]
fn spec_adjacent_cell_border_weight_resolution() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "adjacent-cell-border-conflict");
    let table = first_table(&doc);

    let cell_00 = &table.rows[0].cells[0];
    let cell_01 = &table.rows[0].cells[1];

    let right_00 = cell_00
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border after resolution");
    let left_01 = cell_01
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border after resolution");

    // After conflict resolution, both cells should agree on the winning border.
    assert_eq!(
        right_00.size.unwrap_or(0),
        24,
        "cell (0,0) right border should keep the heavier sz=24"
    );
    assert_eq!(
        left_01.size.unwrap_or(0),
        24,
        "cell (0,1) left border should be resolved to the heavier sz=24"
    );
    assert_eq!(
        right_00.color, left_01.color,
        "both cells should agree on the winning border color at the shared edge"
    );
}

// =============================================================================
// 10. tblLook legacy val bitmask
//     (MS-OI29500 SS17.4.55(c))
// =============================================================================

/// MS-OI29500 SS17.4.55(c): When no individual attributes are present on
/// tblLook, Word falls back to the w:val hex bitmask.
///
/// val="04A0" → firstRow=true, firstCol=true, noHBand=true, noVBand=true.
#[test]
fn spec_tbllook_legacy_bitmask_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-legacy-bitmask");
    let table = first_table(&doc);

    let tbl_look = table
        .formatting
        .tbl_look
        .as_ref()
        .expect("table should have tblLook");

    // 0x04A0 = 0b_0100_1010_0000
    // Bit fields: 0x0020=firstRow, 0x0040=lastRow, 0x0080=firstCol,
    //             0x0100=lastCol, 0x0200=noHBand, 0x0400=noVBand
    // 0x04A0 & 0x0020 = 0x0020 -> firstRow = true
    // 0x04A0 & 0x0040 = 0      -> lastRow = false
    // 0x04A0 & 0x0080 = 0x0080 -> firstCol = true
    // 0x04A0 & 0x0100 = 0      -> lastCol = false
    // 0x04A0 & 0x0200 = 0      -> noHBand = false
    // 0x04A0 & 0x0400 = 0x0400 -> noVBand = true
    assert!(
        tbl_look.first_row,
        "0x04A0 bit 0x0020: firstRow should be true"
    );
    assert!(
        !tbl_look.last_row,
        "0x04A0 bit 0x0040: lastRow should be false"
    );
    assert!(
        tbl_look.first_column,
        "0x04A0 bit 0x0080: firstCol should be true"
    );
    assert!(
        !tbl_look.last_column,
        "0x04A0 bit 0x0100: lastCol should be false"
    );
    assert!(
        !tbl_look.no_h_band,
        "0x04A0 bit 0x0200: noHBand should be false"
    );
    assert!(
        tbl_look.no_v_band,
        "0x04A0 bit 0x0400: noVBand should be true"
    );
}

/// The raw val string should be preserved for roundtrip fidelity.
#[test]
fn spec_tbllook_legacy_bitmask_val_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-legacy-bitmask");
    let table = first_table(&doc);

    let tbl_look = table.formatting.tbl_look.as_ref().unwrap();
    assert_eq!(
        tbl_look.val.as_deref(),
        Some("04A0"),
        "raw w:val should be preserved as '04A0' for roundtrip"
    );
}

/// When the legacy bitmask enables firstRow, conditional formatting from the
/// table style should apply to the first row.
#[test]
fn spec_tbllook_legacy_bitmask_firstrow_conditional_applied() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-legacy-bitmask");
    let table = first_table(&doc);

    // The table style has firstRow conditional with red shading (FF0000).
    // tblLook 0x04A0 has firstRow=true.
    let shading = table.rows[0].cells[0].formatting.shading.as_ref();
    assert!(
        shading.is_some(),
        "row 0 should have conditional shading from firstRow — \
         tblLook legacy bitmask 0x04A0 enables firstRow"
    );
    if let Some(s) = shading {
        assert_eq!(
            s.fill.as_deref(),
            Some("FF0000"),
            "row 0 should have red shading from firstRow conditional"
        );
    }
}

/// When the legacy bitmask does NOT enable lastRow, the last row should not
/// get lastRow conditional formatting.
#[test]
fn spec_tbllook_legacy_bitmask_lastrow_not_applied() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "tbllook-legacy-bitmask");
    let table = first_table(&doc);

    // The table style has lastRow conditional with blue shading (0000FF).
    // tblLook 0x04A0 has lastRow=false. Last row should NOT get blue shading.
    let last_row = table.rows.len() - 1;
    let shading = table.rows[last_row].cells[0].formatting.shading.as_ref();
    if let Some(s) = shading {
        assert_ne!(
            s.fill.as_deref(),
            Some("0000FF"),
            "last row should NOT have blue shading — \
             tblLook 0x04A0 has lastRow=false, so lastRow conditional should not apply"
        );
    }
}

/// Verifies MS-OI29500 SS17.4.55(a): when tblLook is omitted, the default
/// matches bitmask 0x04A0 (firstRow=true, firstCol=true, noVBand=true,
/// noHBand=false, all others false).
#[test]
fn spec_tbllook_default_matches_ms_0x04a0() {
    let default = stemma::TblLook::default();

    // According to MS-OI29500 SS17.4.55(a), the default bitmask is 0x04A0:
    // 0x0020 = firstRow = true
    // 0x0080 = firstCol = true
    // 0x0400 = noVBand = true
    // All other bits = false (including 0x0200 noHBand)
    assert!(
        default.first_row,
        "MS default 0x04A0: firstRow should be true"
    );
    assert!(
        default.first_column,
        "MS default 0x04A0: firstColumn should be true (bit 0x0080)"
    );
    assert!(
        !default.no_h_band,
        "MS default 0x04A0: noHBand should be false (bit 0x0200 not set)"
    );
    assert!(
        default.no_v_band,
        "MS default 0x04A0: noVBand should be true"
    );
    assert!(
        !default.last_row,
        "MS default 0x04A0: lastRow should be false"
    );
    assert!(
        !default.last_column,
        "MS default 0x04A0: lastCol should be false"
    );
}

// =============================================================================
// 11. Conditional formatting border override
//     (ISO 29500-1 SS17.7.6)
// =============================================================================

/// SS17.7.6: Conditional formatting borders from tblStylePr should override
/// the table-level borders for matching cells.
///
/// Table style has thin black borders (sz=4, color=000000).
/// firstRow conditional has thick red borders (sz=12, color=FF0000).
/// First row cells should display thick red, not thin black.
#[test]
fn spec_conditional_border_override_firstrow() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-border-override");
    let table = first_table(&doc);

    // Row 0 should have conditional borders from firstRow (red sz=12)
    let cell_00_borders = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .expect("row 0 cell 0 should have borders from firstRow conditional");

    // The top border should be the firstRow conditional's red border
    let top_border = cell_00_borders
        .top
        .as_ref()
        .expect("cell (0,0) should have top border");
    assert_eq!(
        top_border.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) top border should be red from firstRow conditional, \
         not black from base table style — SS17.7.6 precedence: \
         conditional formatting overrides base style"
    );
    assert_eq!(
        top_border.size,
        Some(12),
        "cell (0,0) top border size should be 12 (from firstRow conditional)"
    );
}

/// Row 1 (non-firstRow) should retain the base table style borders,
/// not the conditional firstRow borders.
///
/// Note: the top border of row 1 shares an edge with row 0's bottom border.
/// Per §17.4.66 rule 3, the heavier border (red/sz=12 from firstRow conditional)
/// wins at that shared edge. We check the bottom border instead, which is not
/// shared with a conditional row and should come from the base style.
#[test]
fn spec_conditional_border_base_style_on_non_matching_row() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-border-override");
    let table = first_table(&doc);

    // Row 1 should have the base table style borders (black sz=4)
    // unless conditional formatting replaced them.
    // Since row 1 doesn't match any conditional (noHBand=true), it should
    // have the table-level borders on non-shared edges.
    let cell_10_borders = table.rows[1].cells[0].formatting.borders.as_ref();

    // Check a non-shared edge: bottom border of the last row is the table's
    // outer bottom border, not shared with any conditional row.
    if let Some(borders) = cell_10_borders
        && let Some(bottom) = &borders.bottom
    {
        // Should be black (000000), not red (FF0000) — conditional firstRow
        // should not affect non-shared edges of non-matching rows.
        assert_ne!(
            bottom.color.as_deref(),
            Some("FF0000"),
            "row 1 cell (1,0) bottom border should NOT have firstRow conditional \
                 red border — firstRow only applies to row 0"
        );
    }
}
