//! Spec-compliance tests: Style Cascade Regression Tests
//!
//! These tests assert correct behavioral outcomes per the OOXML spec,
//! serving as regression tests for previously fixed issues:
//!
//! - Toggle-docDefaults interaction (§17.7.3 + MS-OI29500 §2.1.230a)
//! - Linked style property preservation via basedOn (§17.7.4.6)
//! - Table conditional formatting precedence (MS-OI29500 §17.4.54a)
//! - lineRule default when direct spacing omits it (§17.3.1.33)
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/style-cascade-bugs/create_fixtures.py`.

use stemma::{BlockNode, CanonDoc, InlineNode, LineSpacingRule, Mark};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade-bugs";

// ── helpers ──────────────────────────────────────────────────────────────

fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}

fn find_para_by_text<'a>(
    paras: &[&'a stemma::ParagraphNode],
    needle: &str,
) -> &'a stemma::ParagraphNode {
    paras
        .iter()
        .find(|p| common::paragraph_text(p).contains(needle))
        .unwrap_or_else(|| panic!("should find paragraph containing {:?}", needle))
}

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

fn cell_first_text_node(table: &stemma::TableNode, row: usize, col: usize) -> stemma::TextNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            for inline in p.all_inlines_owned() {
                if let InlineNode::Text(t) = inline {
                    return *t;
                }
            }
        }
    }
    panic!("cell ({row},{col}) should contain at least one text node")
}

// ═══════════════════════════════════════════════════════════════════════════
// Bug 1: Toggle-docDefaults interaction (§17.7.3 + MS-OI29500 §2.1.230a)
//
// When docDefaults sets a toggle property to ON, styles at lower levels
// (paragraph style, character style) should be able to turn it OFF.
//
// MS-OI29500 §2.1.230a: "If a toggle property is specified in document
// defaults, it shall be applied to all runs." But §17.7.3 says styles
// should be able to override document defaults.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3: docDefaults bold=on, italic=on. Para style sets bold=off.
/// The para style's explicit bold=off should override docDefaults bold=on.
/// Italic should remain ON from docDefaults (para style doesn't touch it).
#[test]
fn bug1_para_style_overrides_doc_defaults_bold() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug1-toggle-doc-defaults");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Para style bold off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Verifies that the para style's explicit Off overrides docDefaults On.
    assert!(
        !run.marks.contains(&Mark::Bold),
        "docDefaults bold=on + para style bold=off should produce bold=OFF. \
         The paragraph style explicitly disables bold. Per MS-OI29500 §2.1.230a \
         and §17.7.3, a style should be able to override document defaults."
    );

    // Italic should be ON from docDefaults (not overridden by this style).
    assert!(
        run.marks.contains(&Mark::Italic),
        "docDefaults italic=on should apply since StyleNoBold does not touch italic."
    );
}

/// §17.7.3: docDefaults italic=on. Char style sets italic=off.
/// The char style's explicit italic=off should override docDefaults.
#[test]
fn bug1_char_style_overrides_doc_defaults_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug1-toggle-doc-defaults");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Char style italic off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Verifies that the char style's explicit Off overrides docDefaults On.
    assert!(
        !run.marks.contains(&Mark::Italic),
        "docDefaults italic=on + char style italic=off should produce italic=OFF. \
         The character style explicitly disables italic."
    );

    // Bold should be ON from docDefaults (not overridden).
    assert!(
        run.marks.contains(&Mark::Bold),
        "docDefaults bold=on should apply since CharNoItalic does not touch bold."
    );
}

/// §17.7.3: docDefaults bold=on. Para style bold=off + char style bold=on.
/// Character style overrides paragraph style → bold should be ON.
#[test]
fn bug1_char_overrides_para_override_of_doc_defaults() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug1-toggle-doc-defaults");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Para off char on");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Char style bold=on should override para style's bold=off.
    assert!(
        run.marks.contains(&Mark::Bold),
        "para style bold=off + char style bold=on: char should win → bold=ON. \
         Per §17.7.2, character style overrides paragraph style."
    );

    // Italic from docDefaults should persist (neither style overrides it).
    assert!(
        run.marks.contains(&Mark::Italic),
        "docDefaults italic=on should persist — no style overrides italic."
    );
}

/// §17.7.5: No styles at all — docDefaults should apply directly.
#[test]
fn bug1_no_styles_doc_defaults_apply() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug1-toggle-doc-defaults");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "No styles at all");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "no styles → docDefaults bold=on should apply."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "no styles → docDefaults italic=on should apply."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Bug 2: Linked style property loss via basedOn (§17.7.4.6)
//
// When a paragraph style (HeadingPara, sz=32) is linked to a character
// style (HeadingChar, basedOn BaseChar sz=24, bold=on), the linked char
// style's resolved chain includes sz=24 from BaseChar. overlay_marks
// then overwrites HeadingPara's sz=32 with the linked char style's
// inherited sz=24.
//
// Per §17.7.4.6, properties explicitly set by the linked char style
// should override the para style. But properties inherited by the char
// style from its basedOn chain (that the char style itself doesn't
// explicitly set) should NOT override the para style's explicit values.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.6: HeadingPara (sz=32) linked to HeadingChar (basedOn BaseChar
/// sz=24, bold=on). Run in HeadingPara should get sz=32 from para rPr.
/// Verifies that the linked char overlay distinguishes between properties
/// the char style explicitly sets vs those it merely inherits from basedOn.
#[test]
fn bug2_linked_style_preserves_para_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug2-linked-style-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Heading linked no char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Bold should come from linked char style (explicitly set).
    assert!(
        run.marks.contains(&Mark::Bold),
        "HeadingChar explicitly sets bold=on → bold should be ON."
    );

    // Verifies that HeadingPara's explicit sz=32 is preserved — the linked
    // char's inherited sz=24 (from BaseChar) does not overwrite it.
    assert_eq!(
        run.style_props.font_size,
        Some(32),
        "HeadingPara sets sz=32 in its rPr. HeadingChar (linked) does not \
         explicitly set sz — it only inherits sz=24 from BaseChar. Per \
         §17.7.4.6, the linked char style should only override properties \
         it explicitly sets. The para style's sz=32 should be preserved."
    );

    // Color should come from HeadingPara (linked char doesn't set it).
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "HeadingChar does not set color → HeadingPara's color=FF0000 \
         should persist through the linked overlay."
    );
}

/// §17.7.4.6: When HeadingChar is applied explicitly as a character style
/// (not via linked para style), its resolved properties should apply fully.
/// The char style's basedOn chain gives it sz=24.
#[test]
fn bug2_explicit_char_style_gets_inherited_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug2-linked-style-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Heading linked explicit char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "HeadingChar sets bold=on → bold should be ON."
    );

    // When HeadingChar is applied explicitly as a char style on a run
    // within HeadingPara, the char style wins for font_size.
    // HeadingChar resolves to sz=24 (from BaseChar via basedOn).
    // Per §17.7.2: char style > para style for explicit char style application.
    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "explicit HeadingChar char style resolves to sz=24 (from BaseChar). \
         Per §17.7.2, character style overrides paragraph style per-property."
    );
}

/// §17.7.4.6: Run with HeadingChar only (no para style).
/// Should get bold from HeadingChar and font_size from BaseChar (basedOn).
#[test]
fn bug2_char_style_only_gets_based_on_props() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug2-linked-style-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Char style only");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "HeadingChar sets bold=on → bold should be ON."
    );

    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "HeadingChar basedOn BaseChar (sz=24) → font_size should be 24."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Bug 3: Table conditional formatting precedence (MS-OI29500 §17.4.54a)
//
// Precedence order (low to high):
//   wholeTable < bands < firstCol/lastCol < firstRow/lastRow < corners
//
// The application code constructs a matching vector in precedence order
// and fills properties first-wins. This is correct for per-property merge.
// The test verifies that corner cells (nwCell) get their shading from
// the corner conditional, and that lower-precedence conditionals fill
// in properties the corner conditional doesn't set.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.6(c): NW corner cell (0,0) should get nwCell shading (amber FFC000),
/// not firstRow shading (blue 4472C4) or firstCol shading (green 70AD47).
/// Verifies correct conditional formatting precedence per MS-OI29500 §17.4.54a.
#[test]
fn bug3_nw_corner_gets_corner_shading() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    // Cell (0,0) matches nwCell, firstRow, AND firstCol.
    // nwCell has highest precedence → shading should be FFC000 (amber).
    let shading = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("NW corner cell should have shading from nwCell conditional");

    assert_eq!(
        shading.fill.as_deref(),
        Some("FFC000"),
        "NW corner cell (0,0) should get shading from nwCell conditional (FFC000 amber), \
         not firstRow (4472C4 blue) or firstCol (70AD47 green). \
         Per MS-OI29500 §17.4.54a, corner cells have highest precedence."
    );
}

/// §17.7.6(c): NW corner cell should get bold and font_size from firstRow
/// (since nwCell doesn't set them — per-property fill from lower precedence).
#[test]
fn bug3_nw_corner_fills_bold_from_first_row() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    let text = cell_first_text_node(table, 0, 0);

    // nwCell doesn't set bold or font_size.
    // firstRow sets bold=true and font_size=28.
    // Per-property fill: firstRow fills in what nwCell doesn't set.
    assert!(
        text.marks.contains(&Mark::Bold),
        "NW corner cell should get bold=true from firstRow conditional \
         (nwCell doesn't set bold, firstRow does)."
    );

    assert_eq!(
        text.style_props.font_size,
        Some(28),
        "NW corner cell should get font_size=28 from firstRow conditional \
         (nwCell doesn't set font_size, firstRow does)."
    );
}

/// §17.7.6(c): Top-right cell (0,2) is firstRow only → should get blue shading.
#[test]
fn bug3_first_row_only_cell_gets_blue() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    let shading = table.rows[0].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("first row cell should have shading");

    assert_eq!(
        shading.fill.as_deref(),
        Some("4472C4"),
        "cell (0,2) is firstRow only → shading should be 4472C4 (blue)."
    );

    let text = cell_first_text_node(table, 0, 2);
    assert!(
        text.marks.contains(&Mark::Bold),
        "first row cell should get bold=true from firstRow conditional."
    );
}

/// §17.7.6(c): SE corner cell (2,2) should get seCell shading (red FF0000),
/// not lastRow shading (orange ED7D31).
#[test]
fn bug3_se_corner_gets_corner_shading() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    // Cell (2,2) matches seCell, lastRow, and lastCol.
    // seCell has highest precedence → shading should be FF0000 (red).
    let shading = table.rows[2].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("SE corner cell should have shading from seCell or lastRow");

    assert_eq!(
        shading.fill.as_deref(),
        Some("FF0000"),
        "SE corner cell (2,2) should get shading from seCell conditional (FF0000 red), \
         not lastRow (ED7D31 orange). Corner > firstRow/lastRow."
    );
}

/// §17.7.6(c): firstCol cell (1,0) should get green shading.
#[test]
fn bug3_first_col_cell_gets_green() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    let shading = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("first col cell should have shading");

    assert_eq!(
        shading.fill.as_deref(),
        Some("70AD47"),
        "cell (1,0) is firstCol only → shading should be 70AD47 (green)."
    );
}

/// §17.7.6(c): Center cell (1,1) has no matching conditional → no shading
/// (unless default cell shading applies).
#[test]
fn bug3_center_cell_no_conditional_shading() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug3-table-conditional-precedence");
    let table = first_table(&doc);

    // Cell (1,1): no firstRow, no firstCol, no lastRow, no corners, no bands.
    // Should have no conditional shading.
    let shading = &table.rows[1].cells[1].formatting.shading;

    assert!(
        shading.is_none() || shading.as_ref().unwrap().fill.is_none(),
        "center cell (1,1) has no matching conditional → shading should be None. \
         Got: {:?}",
        shading
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// Bug 4: lineRule default when direct spacing omits it (§17.3.1.33)
//
// §17.3.1.33: "If [lineRule] is omitted, then it shall be assumed to be
// of a value auto if a line attribute value is present."
//
// When direct w:spacing sets w:line but omits w:lineRule, the effective
// lineRule should be Auto, not inherited from the style.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.3.1.33: Style has lineRule=exact. Direct spacing sets line=480 but
/// omits lineRule. The effective lineRule should be Auto (not Exact from style).
/// Verifies that the lineRule default applies when direct spacing is present
/// but omits lineRule, rather than inheriting from the style.
#[test]
fn bug4_direct_line_without_rule_defaults_to_auto_exact_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug4-line-rule-default");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Exact style direct line only");

    let spacing = p
        .spacing
        .as_ref()
        .expect("paragraph should have spacing resolved");

    assert_eq!(spacing.line, Some(480), "direct spacing sets line=480.");

    // Verifies lineRule defaults to Auto per §17.3.1.33, not Exact from style.
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "direct spacing sets line=480 but omits lineRule. Per §17.3.1.33: \
         'If [lineRule] is omitted, then it shall be assumed to be of a value \
         auto if a line attribute value is present.' The lineRule should be \
         Auto, NOT Exact inherited from the style."
    );
}

/// §17.3.1.33: Same test with style lineRule=atLeast.
#[test]
fn bug4_direct_line_without_rule_defaults_to_auto_atleast_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug4-line-rule-default");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "AtLeast style direct line only");

    let spacing = p
        .spacing
        .as_ref()
        .expect("paragraph should have spacing resolved");

    assert_eq!(spacing.line, Some(480), "direct spacing sets line=480.");

    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "direct spacing sets line=480 but omits lineRule. Per §17.3.1.33, \
         lineRule should default to Auto, NOT atLeast from the style."
    );
}

/// §17.3.1.33: Style lineRule=exact, no direct spacing → lineRule from style.
#[test]
fn bug4_no_direct_spacing_inherits_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug4-line-rule-default");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Exact style no direct");

    let spacing = p
        .spacing
        .as_ref()
        .expect("paragraph should have spacing from style");

    assert_eq!(spacing.line, Some(360), "style sets line=360.");

    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Exact),
        "no direct spacing → lineRule should come from style (Exact)."
    );
}

/// §17.3.1.33: No style, direct line=480 without lineRule → Auto.
#[test]
fn bug4_no_style_direct_line_defaults_auto() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug4-line-rule-default");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "No style direct line only");

    let spacing = p
        .spacing
        .as_ref()
        .expect("paragraph should have spacing from direct");

    assert_eq!(spacing.line, Some(480), "direct spacing sets line=480.");

    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "no style, direct line without lineRule → Auto per §17.3.1.33."
    );
}

/// §17.3.1.33: No style, direct line=480 WITH lineRule=exact → Exact.
#[test]
fn bug4_explicit_direct_line_rule_honored() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "bug4-line-rule-default");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "No style direct exact");

    let spacing = p
        .spacing
        .as_ref()
        .expect("paragraph should have spacing from direct");

    assert_eq!(spacing.line, Some(480), "direct spacing sets line=480.");

    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Exact),
        "direct spacing explicitly sets lineRule=exact → should be Exact."
    );
}
