//! Spec-compliance tests: Paragraph property resolution through style chain
//!
//! These tests verify that paragraph properties (widowControl, keepNext,
//! keepLines, outlineLvl) are correctly resolved from the style's basedOn
//! chain when not directly set on the paragraph.
//!
//! Covers:
//!   - widowControl (§17.3.1.44)
//!   - keepNext (§17.3.1.15) / keepLines (§17.3.1.14)
//!   - outlineLvl (§17.3.1.20)
//!
//! Fixture DOCX files generated by `testdata/spec-compliance/create_style_para_audit.py`.

use stemma::HeadingLevel;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-para-audit";

// ==========================================================================
// widowControl resolved through style chain (§17.3.1.44)
// ==========================================================================

/// Style "NoWidow" defines widowControl=false. A paragraph referencing that
/// style (without direct widowControl) should inherit widow_control=Some(false).
/// A paragraph with direct widowControl=true should override the style.
#[test]
fn spec_audit_widow_control_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "widow-control-from-style");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // Para 0: no style override — widow_control should be None (spec default = true)
    assert_eq!(
        paras[0].widow_control, None,
        "para 0 (default) should have widow_control=None"
    );

    // Para 1: NoWidow style — should inherit widow_control=Some(false) from style
    assert_eq!(
        paras[1].widow_control,
        Some(false),
        "para 1 (NoWidow style) should inherit widow_control=false from style"
    );

    // Para 2: NoWidow style + direct widowControl (true) — direct wins
    assert_eq!(
        paras[2].widow_control,
        Some(true),
        "para 2 (direct override) should have widow_control=true from direct"
    );
}

// ==========================================================================
// keepNext/keepLines resolved through style chain (§17.3.1.14/15)
// ==========================================================================

/// Style "KeepTogether" defines keepNext + keepLines. Paragraphs referencing
/// that style should inherit both properties.
#[test]
fn spec_audit_keep_next_lines_from_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "keep-next-lines-from-style");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // Para 0: no style override — keep_next=None, keep_lines=None
    assert_eq!(
        paras[0].keep_next, None,
        "para 0 (default) should have keep_next=None"
    );
    assert_eq!(
        paras[0].keep_lines, None,
        "para 0 (default) should have keep_lines=None"
    );

    // Para 1: KeepTogether style — should inherit keepNext=true, keepLines=true
    assert_eq!(
        paras[1].keep_next,
        Some(true),
        "para 1 (KeepTogether style) should inherit keep_next=Some(true) from style"
    );
    assert_eq!(
        paras[1].keep_lines,
        Some(true),
        "para 1 (KeepTogether style) should inherit keep_lines=Some(true) from style"
    );
}

// ==========================================================================
// outlineLvl resolved from style chain (§17.3.1.20)
// ==========================================================================

/// Style "CustomHeading" defines outlineLvl=2 (heading level 3). A paragraph
/// referencing that style should be detected as H3.
#[test]
fn spec_audit_outline_lvl_from_custom_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "outline-lvl-from-style");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // Para 0: no style with outlineLvl — no heading level
    assert_eq!(
        paras[0].heading_level, None,
        "para 0 (default) should have no heading level"
    );

    // Para 1: CustomHeading style with outlineLvl=2 — heading level 3
    assert_eq!(
        paras[1].heading_level,
        Some(HeadingLevel::H3),
        "para 1 (CustomHeading style) should be H3 from outlineLvl=2"
    );
}
