//! Spec-compliance tests: Linked Style Resolution Edge Cases
//!
//! These tests target edge cases in linked style resolution (ISO 29500-1
//! §17.7.4.6) and default character style application (§17.7.4.17).
//!
//! Coverage:
//!   - Linked char basedOn chain properties cascade correctly (underline,
//!     color, highlight, italic) without overwriting the para style's
//!     explicit properties
//!   - Para style explicit properties preserved through linked overlay
//!   - Explicit char style on a linked para gets full resolved chain
//!   - Default character style applied to unstyled runs (§17.7.4.17)
//!   - Default char style + explicit char style merge correctly
//!   - Direct formatting overrides linked char style properties
//!   - Linked overlay does NOT leak into child styles via basedOn chain
//!   - Para basedOn chain with linked parent isolates link correctly
//!   - Linked char matching para values causes no information loss
//!
//! Fixture DOCX files generated by
//! `testdata/spec-compliance/style-cascade-linked-edge/create_docs.py`.

use stemma::{HighlightColor, InlineNode, Mark, MarkValue};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade-linked-edge";

// ── helpers ──────────────────────────────────────────────────────────────

fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}

fn find_para_by_text<'a>(
    paras: &[&'a stemma::ParagraphNode],
    needle: &str,
) -> &'a stemma::ParagraphNode {
    paras
        .iter()
        .find(|p| common::paragraph_text(p).contains(needle))
        .unwrap_or_else(|| panic!("should find paragraph containing {:?}", needle))
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. Linked char basedOn chain property loss — overcorrection of Bug 2
//
// The fix for Bug 2 (use raw marks instead of resolved chain) prevents
// the linked char style's basedOn chain from overwriting the para style's
// explicit properties. But it also prevents the char style's basedOn chain
// from CONTRIBUTING properties that the para style doesn't set at all.
//
// Per §17.7.4.6, the linked char style provides the run-level rPr for
// the paragraph style. This should include the char style's full resolved
// basedOn chain — but only override properties that the para style hasn't
// explicitly set.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.6: LinkedPara (sz=32, Arial) linked to LinkedChar (bold=on,
/// basedOn BaseChar(underline, color=0000FF, highlight=yellow)).
/// The para style should preserve sz=32 and font=Arial (its own properties).
/// Bold should come from LinkedChar's raw marks.
/// Underline, color, highlight should come from LinkedChar's basedOn chain.
#[test]
fn linked_based_on_loss_preserves_para_sz() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Para style explicitly sets sz=32 — should be preserved
    assert_eq!(
        run.style_props.font_size,
        Some(32),
        "LinkedPara sets sz=32 in rPr. The linked char overlay should NOT \
         overwrite this (LinkedChar doesn't explicitly set sz). Got {:?}",
        run.style_props.font_size
    );
}

#[test]
fn linked_based_on_loss_preserves_para_font() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Para style explicitly sets font=Arial — should be preserved
    assert_eq!(
        run.style_props.font_family.as_deref(),
        Some("Arial"),
        "LinkedPara sets font=Arial in rPr. The linked char overlay should \
         NOT overwrite this. Got {:?}",
        run.style_props.font_family
    );
}

#[test]
fn linked_based_on_loss_gets_char_bold() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // LinkedChar explicitly sets bold=on — should apply via linked overlay
    assert!(
        run.marks.contains(&Mark::Bold),
        "LinkedChar explicitly sets bold=on. This should apply via the \
         linked overlay."
    );
}

#[test]
fn linked_based_on_loss_gets_char_chain_underline() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseChar sets underline=on. LinkedChar inherits this via basedOn.
    // Per §17.7.4.6, the linked char style provides run-level rPr
    // which should include its basedOn chain. The para style (LinkedPara)
    // doesn't set underline, so the char chain's underline should apply.
    assert!(
        run.marks.contains(&Mark::Underline),
        "LinkedChar inherits underline=on from BaseChar via basedOn. \
         Per §17.7.4.6, the linked char style's resolved properties \
         should provide underline for runs. The para style doesn't set \
         underline, so BaseChar's underline should not conflict."
    );
}

#[test]
fn linked_based_on_loss_gets_char_chain_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseChar sets color=0000FF. LinkedChar inherits via basedOn.
    // LinkedPara doesn't set color — the char chain's color should apply.
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "LinkedChar inherits color=0000FF from BaseChar. The para style \
         doesn't set color, so the linked char chain's color should apply. \
         Got {:?}",
        run.style_props.color
    );
}

#[test]
fn linked_based_on_loss_gets_char_chain_highlight() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked basedOn loss test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseChar sets highlight=yellow. LinkedChar inherits via basedOn.
    // LinkedPara doesn't set highlight — the char chain's highlight should apply.
    assert_eq!(
        run.style_props.highlight,
        Some(HighlightColor::Yellow),
        "LinkedChar inherits highlight=yellow from BaseChar. The para \
         style doesn't set highlight, so the char chain's highlight \
         should apply. Got {:?}",
        run.style_props.highlight
    );
}

/// When LinkedChar is applied explicitly as a char style on a run,
/// the char style's full resolved chain should apply. This path uses
/// char_styles (fully resolved), not the linked overlay.
#[test]
fn linked_based_on_explicit_char_gets_full_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-loss");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Explicit linked char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Explicit char style → char_styles map → fully resolved chain
    assert!(
        run.marks.contains(&Mark::Bold),
        "explicit LinkedChar should provide bold=on"
    );
    assert!(
        run.marks.contains(&Mark::Underline),
        "explicit LinkedChar should inherit underline from BaseChar"
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "explicit LinkedChar should inherit color=0000FF from BaseChar"
    );
    assert_eq!(
        run.style_props.highlight,
        Some(HighlightColor::Yellow),
        "explicit LinkedChar should inherit highlight=yellow from BaseChar"
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Default character style (§17.7.4.17) — unstyled runs
//
// Per §17.7.4.17, when a run has no explicit rStyle, the default character
// style (w:type="character" w:default="1") should apply. The current
// resolve() function skips the default char style when char_style_id is
// None.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.17: Unstyled run should inherit italic from default char style.
#[test]
fn default_char_style_unstyled_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-unstyled");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled default char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Italic),
        "Unstyled run should inherit italic=on from the default character \
         style (CustomDefaultChar). Per §17.7.4.17, when a run has no \
         rStyle, the default character style applies."
    );
}

/// §17.7.4.17: Unstyled run should inherit font_size from default char style.
#[test]
fn default_char_style_unstyled_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-unstyled");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled default char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "Unstyled run should inherit font_size=28 from default char style. \
         Per §17.7.4.17, the default char style is the fallback for runs \
         without rStyle. Got {:?}",
        run.style_props.font_size
    );
}

/// §17.7.4.17: Unstyled run should inherit color from default char style.
#[test]
fn default_char_style_unstyled_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-unstyled");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Unstyled default char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "Unstyled run should inherit color=FF0000 from default char style. \
         Got {:?}",
        run.style_props.color
    );
}

/// §17.7.4.17 + §17.7.2: Explicit char style overrides default char style
/// for properties it sets, but inherits from default char style for
/// properties it doesn't set.
///
/// OverrideChar sets bold=on only. Default char style has italic=on,
/// sz=28, color=FF0000. The explicit char style should provide bold=on,
/// and the default char style should provide italic=on, sz=28, color=FF0000.
#[test]
fn default_char_style_explicit_override_inherits() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "default-char-unstyled");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Explicit override char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Bold from explicit char style
    assert!(
        run.marks.contains(&Mark::Bold),
        "OverrideChar sets bold=on — should apply."
    );

    // Italic from default char style (OverrideChar doesn't set it)
    assert!(
        run.marks.contains(&Mark::Italic),
        "OverrideChar doesn't set italic. Default char style has italic=on. \
         Per §17.7.2, properties unset by the explicit char style should \
         fall through to the default char style."
    );

    // font_size from default char style
    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "OverrideChar doesn't set font_size. Default char style has sz=28. \
         The font_size should fall through. Got {:?}",
        run.style_props.font_size
    );

    // color from default char style
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "OverrideChar doesn't set color. Default char style has color=FF0000. \
         Got {:?}",
        run.style_props.color
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Linked para style as basedOn target — link should NOT leak
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.6 + §17.7.4.3: LinkedParaT directly used — should get linked
/// char overlay. LinkedCharT raw marks = {italic=on}. Para rPr = {bold, sz=28}.
/// BaseCharT(underline=on) is in LinkedCharT's basedOn chain — this will
/// be lost due to raw marks overlay (same bug as fixture 1).
#[test]
fn linked_target_direct_gets_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked parent direct");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "LinkedParaT sets bold=on in rPr."
    );
    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "LinkedParaT sets sz=28."
    );
    // LinkedCharT raw marks = {italic=on}
    assert!(
        run.marks.contains(&Mark::Italic),
        "LinkedCharT explicitly sets italic=on — should apply via linked overlay."
    );
}

#[test]
fn linked_target_direct_gets_chain_underline() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked parent direct");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseCharT sets underline=on. LinkedCharT inherits via basedOn.
    // LinkedParaT doesn't set underline — should come from char chain.
    assert!(
        run.marks.contains(&Mark::Underline),
        "LinkedCharT inherits underline=on from BaseCharT. The para style \
         doesn't set underline, so the char chain's underline should apply."
    );
}

/// §17.7.4.6 + §17.7.4.3: ChildPara basedOn LinkedParaT (which is linked).
/// The linked char overlay from LinkedParaT should NOT leak into ChildPara.
/// ChildPara should only get LinkedParaT's basedOn chain rPr properties.
#[test]
fn linked_target_child_no_leak_bold() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked parent");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Bold from LinkedParaT's raw rPr (via basedOn chain)
    assert!(
        run.marks.contains(&Mark::Bold),
        "ChildPara should inherit bold=on from LinkedParaT via basedOn."
    );
}

#[test]
fn linked_target_child_no_leak_sz() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked parent");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "ChildPara should inherit sz=28 from LinkedParaT via basedOn."
    );
}

#[test]
fn linked_target_child_no_leak_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked parent");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("00FF00"),
        "ChildPara sets color=00FF00 in its own rPr."
    );
}

/// The linked char overlay (italic, underline) from LinkedParaT must NOT
/// leak into ChildPara's resolution. ChildPara does not have its own link.
#[test]
fn linked_target_child_no_italic_leak() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked parent");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // LinkedCharT sets italic=on, but ChildPara has no link — italic
    // from the linked overlay should NOT leak into ChildPara.
    assert!(
        !run.marks.contains(&Mark::Italic),
        "ChildPara basedOn LinkedParaT should NOT get italic from \
         LinkedCharT's linked overlay. The link only applies when \
         LinkedParaT is used directly."
    );
}

#[test]
fn linked_target_child_no_underline_leak() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-based-on-target");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked parent");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseCharT sets underline=on (inherited by LinkedCharT). This must
    // NOT leak into ChildPara.
    assert!(
        !run.marks.contains(&Mark::Underline),
        "ChildPara should NOT get underline from LinkedCharT's linked \
         overlay. The link only applies to LinkedParaT directly."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. Direct formatting overrides linked char style
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.2: Direct formatting overrides all style-level properties.
/// SimplePara linked to SimpleChar(bold=on, sz=24). Run has direct sz=40.
#[test]
fn direct_override_sz() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "direct-override-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct sz override");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(40),
        "Direct sz=40 should override linked char's sz=24 (and para's 28). \
         Per §17.7.2, direct formatting has highest priority."
    );
    assert!(
        run.marks.contains(&Mark::Bold),
        "Bold from linked char should still apply (direct doesn't touch it)."
    );
}

/// §17.7.2: Direct bold=off overrides linked char's bold=on.
#[test]
fn direct_override_bold() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "direct-override-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct bold off");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "Direct bold=off should override linked char's bold=on. \
         Per §17.7.2, direct formatting wins."
    );
}

/// §17.7.2: Direct color overrides para style's color.
#[test]
fn direct_override_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "direct-override-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct color override");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("00FF00"),
        "Direct color=00FF00 should override para style's color=FF0000."
    );
    assert!(
        run.marks.contains(&Mark::Bold),
        "Bold from linked char should still apply."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. Linked font family basedOn chain loss
//
// FontLinkedPara (font=Arial, sz=28) linked to FontLinkedChar (bold=on,
// basedOn BaseFontChar(font=Courier New, italic=on)). The italic from
// BaseFontChar should reach runs but is lost by raw marks overlay.
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn linked_font_family_loss_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-font-family-leak");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Font linked basedOn loss");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // BaseFontChar sets italic=on. FontLinkedChar inherits via basedOn.
    // FontLinkedPara doesn't set italic. The char chain's italic should apply.
    assert!(
        run.marks.contains(&Mark::Italic),
        "FontLinkedChar inherits italic=on from BaseFontChar via basedOn. \
         FontLinkedPara doesn't set italic. Per §17.7.4.6, the linked \
         char style's resolved properties should provide italic."
    );
}

#[test]
fn linked_font_family_preserves_para_font() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-font-family-leak");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Font linked basedOn loss");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Para style explicitly sets font=Arial — should be preserved
    assert_eq!(
        run.style_props.font_family.as_deref(),
        Some("Arial"),
        "FontLinkedPara sets font=Arial. This should be preserved. Got {:?}",
        run.style_props.font_family
    );
}

#[test]
fn linked_font_family_gets_bold() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-font-family-leak");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Font linked basedOn loss");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "FontLinkedChar explicitly sets bold=on — should apply."
    );
}

/// Explicit char style application gets full resolved chain.
#[test]
fn linked_font_family_explicit_char_gets_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-font-family-leak");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Explicit font linked char");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "explicit FontLinkedChar provides bold=on"
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "explicit FontLinkedChar inherits italic from BaseFontChar"
    );
    assert_eq!(
        run.style_props.font_family.as_deref(),
        Some("Courier New"),
        "explicit FontLinkedChar inherits font=Courier New from BaseFontChar. \
         Got {:?}",
        run.style_props.font_family
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. Para chain with linked parent — link does NOT leak
// ═══════════════════════════════════════════════════════════════════════════

/// LinkParaP directly — should get strike from linked char overlay.
#[test]
fn para_chain_linked_direct_strike() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-chain-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Direct linked para");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "LinkParaP sets bold=on in rPr."
    );
    assert!(
        run.style_props.strike == MarkValue::On,
        "LinkCharP sets strike=on — should apply via linked overlay."
    );
}

/// MidPara basedOn LinkParaP — link should NOT leak strike.
#[test]
fn para_chain_linked_mid_no_strike() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-chain-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Child of linked para");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "MidPara inherits bold=on from LinkParaP via basedOn."
    );
    assert!(run.marks.contains(&Mark::Italic), "MidPara sets italic=on.");
    assert!(
        run.style_props.strike != MarkValue::On,
        "MidPara should NOT get strike from LinkCharP's linked overlay. \
         The link only applies when LinkParaP is used directly."
    );
}

/// GrandPara basedOn MidPara basedOn LinkParaP — link should NOT leak.
#[test]
fn para_chain_linked_grand_no_strike() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "para-chain-linked");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Grandchild of linked para");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "GrandPara inherits bold from chain."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "GrandPara inherits italic from MidPara."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "GrandPara sets color=FF0000."
    );
    assert!(
        run.style_props.strike != MarkValue::On,
        "GrandPara should NOT get strike from linked overlay — two levels \
         removed from the linked style."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. Linked char explicitly matches para — no information loss
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.6: MatchPara (bold, sz=28, italic) linked to MatchChar
/// (bold, sz=28, color=0000FF). Both set bold and sz=28. The char also
/// sets color. The para's italic should be preserved since the char
/// doesn't set it.
#[test]
fn linked_explicit_match_preserves_italic() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-char-explicit-match");
    let paras = common::all_paragraphs(&doc);

    let p = find_para_by_text(&paras, "Linked match test");
    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "Both para and char set bold=on."
    );
    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "Both para and char set sz=28."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "MatchPara sets italic=on. MatchChar doesn't set italic. \
         Para's italic should be preserved."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "MatchChar sets color=0000FF. Para doesn't set color. \
         Char's color should apply via linked overlay."
    );
}
