//! Auto-generated by the spec-word-compliance workflow.
//!
//! Area: **Linked styles (paragraph+character link pairing)** — ECMA-376 / ISO
//! 29500-1 §17.7.4.6 `w:link`, with MS-OI29500 §2.1.235 implementation notes.
//!
//! Each `#[test]` encodes one declarative TestSpec mined from the OOXML / Word
//! specifications. A **FAIL here is a real Word-compliance gap in stemma** — the
//! engine diverges from how Microsoft Word consumes the markup. Do NOT weaken an
//! assertion to make it pass; a failing assertion is exactly the finding the
//! sweep is hunting for. Fix the engine (or, if the test encodes the wrong
//! expectation, fix the test against the spec), never the symptom.
//!
//! Methodology note: `w:link` pairing is a **consumption** rule (the link is
//! "ignored" on read, never rewritten on save). stemma round-trips untouched
//! content byte-verbatim, so these tests assert on the READ side
//! (`opens-clean` + `read_rejected()/read_accepted().to_text()`), never as
//! `xmlOmits` on the verbatim-preserved `w:link` markup.

use stemma::ExportOptions;
use stemma::api::{Document, validate};

// ─── Prelude / plumbing ──────────────────────────────────────────────────────

/// Build a minimal valid `.docx`. `body_xml` is the inner content of
/// `<w:body>…</w:body>`. `extra_parts` are additional package parts (e.g.
/// `word/styles.xml`) added with the right content-type override + relationship.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#
    );

    // Content types: base defaults + the document override, plus an override per
    // extra part (mapping the well-known part names to their content types).
    let mut overrides = String::from(
        r#"<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>"#,
    );
    for (part, _) in extra_parts {
        let ct = content_type_for(part);
        overrides.push_str(&format!(
            r#"<Override PartName="/{part}" ContentType="{ct}"/>"#
        ));
    }
    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>{overrides}</Types>"#
    );

    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;

    // document.xml.rels: one relationship per extra part (so styles.xml is
    // discoverable from the main document part).
    let mut doc_rel_entries = String::new();
    for (i, (part, _)) in extra_parts.iter().enumerate() {
        let rid = format!("rIdExtra{}", i + 1);
        let rel_type = rel_type_for(part);
        // Target is relative to word/ (the document part's folder).
        let target = part.strip_prefix("word/").unwrap_or(part);
        doc_rel_entries.push_str(&format!(
            r#"<Relationship Id="{rid}" Type="{rel_type}" Target="{target}"/>"#
        ));
    }
    let doc_rels = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{doc_rel_entries}</Relationships>"#
    );

    use std::io::Write;
    use zip::write::FileOptions;
    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (part, xml) in extra_parts {
            zip.start_file(*part, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

fn content_type_for(part: &str) -> &'static str {
    match part {
        "word/styles.xml" => {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
        }
        "word/numbering.xml" => {
            "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
        }
        other => panic!("unknown extra part content type for {other}"),
    }
}

fn rel_type_for(part: &str) -> &'static str {
    match part {
        "word/styles.xml" => {
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
        }
        "word/numbering.xml" => {
            "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering"
        }
        other => panic!("unknown extra part rel type for {other}"),
    }
}

/// Unzip and return `word/document.xml` of a `.docx` byte stream.
#[allow(dead_code)]
fn document_xml_of(docx: &[u8]) -> String {
    let archive = stemma::docx::DocxArchive::read(docx).expect("read archive");
    String::from_utf8(
        archive
            .get("word/document.xml")
            .expect("document.xml present")
            .to_vec(),
    )
    .expect("utf8")
}

/// Parse -> serialize -> return `word/document.xml`. Reflects stemma's
/// serializer output (verbatim-preserving for untouched content).
#[allow(dead_code)]
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse");
    let out = doc.serialize(&ExportOptions::default()).expect("serialize");
    document_xml_of(&out)
}

/// True when `validate` reports no errors (opens-clean in Word terms).
fn opens_clean(bytes: &[u8]) -> Result<(), String> {
    let report = validate(bytes);
    if report.ok && report.issues.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "validation issues: {:?}",
            report
                .issues
                .iter()
                .map(|i| format!("[{:?}] {}", i.code, i.message))
                .collect::<Vec<_>>()
        ))
    }
}

fn reject_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_rejected()
        .expect("read_rejected")
        .to_text()
}

fn accept_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text()
}

// ─── Style fixtures shared as &str ───────────────────────────────────────────

const STYLES_PARA_TO_PARA: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="BodyA"><w:name w:val="Body A"/><w:link w:val="BodyB"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="BodyB"><w:name w:val="Body B"/><w:rPr><w:i/></w:rPr></w:style></w:styles>"#;

const STYLES_DANGLING_PARA: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Quote"><w:name w:val="Quote"/><w:link w:val="DoesNotExist"/><w:rPr><w:i/></w:rPr></w:style></w:styles>"#;

const STYLES_CHAR_TO_CHAR: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="character" w:styleId="Emphasis"><w:name w:val="Emphasis"/><w:link w:val="Strong"/><w:rPr><w:i/></w:rPr></w:style><w:style w:type="character" w:styleId="Strong"><w:name w:val="Strong"/><w:rPr><w:b/></w:rPr></w:style></w:styles>"#;

const STYLES_CHAR_NO_LINK_HALF: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="HeadA"><w:name w:val="Head A"/><w:link w:val="Loner"/><w:rPr><w:b/><w:sz w:val="40"/></w:rPr></w:style><w:style w:type="character" w:styleId="Loner"><w:name w:val="Loner"/><w:rPr><w:i/></w:rPr></w:style></w:styles>"#;

const STYLES_PARA_DANGLING_CHAR: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="LinkedPara"><w:name w:val="Linked Para"/><w:link w:val="NoSuchCharStyle"/><w:rPr><w:b/></w:rPr></w:style></w:styles>"#;

const STYLES_PARA_TO_PARA_2: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="LinkedPara"><w:name w:val="Linked Para"/><w:link w:val="OtherPara"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="OtherPara"><w:name w:val="Other Para"/><w:rPr><w:i/></w:rPr></w:style></w:styles>"#;

const STYLES_CHAR_TO_NUMBERING: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="character" w:styleId="LinkedChar"><w:name w:val="Linked Char"/><w:link w:val="ListNum"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type="numbering" w:styleId="ListNum"><w:name w:val="List Num"/></w:style></w:styles>"#;

const STYLES_DUP_LINK: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="LinkedPara"><w:name w:val="Linked Para"/><w:link w:val="CharA"/><w:rPr><w:b/></w:rPr></w:style><w:style w:type="character" w:styleId="CharA"><w:name w:val="Char A"/><w:link w:val="LinkedPara"/><w:rPr><w:i/></w:rPr></w:style><w:style w:type="character" w:styleId="CharB"><w:name w:val="Char B"/><w:link w:val="LinkedPara"/><w:rPr><w:u w:val="single"/></w:rPr></w:style></w:styles>"#;

const STYLES_PLAIN_CHAR: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="character" w:styleId="PlainChar"><w:name w:val="Plain Char"/><w:rPr><w:b/></w:rPr></w:style></w:styles>"#;

const STYLES_PARA_TO_PARA_RICH: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:styleId="LinkedPara">
    <w:name w:val="Linked Para"/>
    <w:link w:val="OtherPara"/>
    <w:rPr><w:b/><w:sz w:val="32"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="OtherPara">
    <w:name w:val="Other Para"/>
    <w:rPr><w:i/><w:color w:val="FF0000"/></w:rPr>
  </w:style>
</w:styles>"#;

const STYLES_CHAR_TO_TABLE: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="character" w:styleId="CharLinksTbl">
    <w:name w:val="Char Links Tbl"/>
    <w:link w:val="GridTable"/>
    <w:rPr><w:b/></w:rPr>
  </w:style>
  <w:style w:type="table" w:styleId="GridTable">
    <w:name w:val="Grid Table"/>
    <w:tblPr/>
  </w:style>
</w:styles>"#;

// ─── Tests ───────────────────────────────────────────────────────────────────

#[test]
fn link_para_to_paragraph_style_cross_type_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="BodyA"/></w:pPr><w:r><w:t>cross type link</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_PARA_TO_PARA)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / ECMA-376 §17.7.4.6 — a paragraph-style w:link \
         pointing at another PARAGRAPH style 'shall be ignored'; an ignored \
         (not rejected) cross-type link is tolerated, so Word opens without \
         repair. Got {e}"
        )
    });

    assert_eq!(
        reject_text(&b).trim(),
        "cross type link",
        "ISO 29500-1 §17.7.4.6 — a link is purely a style-pairing hint; ignoring \
         it changes no document text, so reject-all (no tracked changes) yields \
         the original run text verbatim."
    );
}

#[test]
fn link_to_nonexistent_styleid_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="Quote"/></w:pPr><w:r><w:t>dangling link</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_DANGLING_PARA)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / ECMA-376 §17.7.4.6 — a w:link whose val names a \
         styleId no style defines 'shall be ignored'; a dangling link degrades \
         to a no-op, so Word opens without repair (parallel to the dangling \
         numStyleLink no-op). Got {e}"
        )
    });

    assert_eq!(
        reject_text(&b).trim(),
        "dangling link",
        "ISO 29500-1 §17.7.4.6 — ignoring the dead link leaves the run text \
         unchanged; with no tracked changes, reject-all returns the original text."
    );
}

#[test]
fn char_style_link_to_character_style_cross_type_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="Emphasis"/></w:rPr><w:t>char cross type</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_CHAR_TO_CHAR)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / ECMA-376 §17.7.4.6 — a character-style w:link \
         must refer to a paragraph style 'or this element shall be ignored'; a \
         char->char link is the mirror cross-type mismatch Word ignores rather \
         than refusing the file. Got {e}"
        )
    });

    assert_eq!(
        reject_text(&b).trim(),
        "char cross type",
        "ISO 29500-1 §17.7.4.6 / §17.7.9 — ignoring the cross-type link does not \
         alter run text; with no tracked changes, reject-all returns the original."
    );
}

#[test]
fn char_style_without_link_not_part_of_pairing_opens_clean() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="Loner"/></w:rPr><w:t>no link half</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_CHAR_NO_LINK_HALF)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / §17.7.9 — 'A style element without a child link \
         element is not part of a linked style pairing'; a standalone char style \
         applied via rStyle (even with another style linking TO it) is a normal, \
         valid construct that Word opens without repair. Got {e}"
        )
    });

    assert_eq!(
        reject_text(&b).trim(),
        "no link half",
        "ISO 29500-1 §17.7.4.6 / §17.7.9 — pairing membership affects only \
         formatting, not text; reject-all (no tracked changes) returns the \
         original run text."
    );
}

#[test]
fn para_link_to_nonexistent_styleid_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="LinkedPara"/></w:pPr><w:r><w:t>Linked paragraph with dangling link.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_PARA_DANGLING_CHAR)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / MS-OI29500 §2.1.235 — a w:link to a styleId no \
         style defines 'shall be ignored'; the I-XREF-001 check scopes only to \
         content references (pStyle/rStyle), NOT w:link targets in styles.xml, so \
         a dangling link MUST NOT be flagged as a missing-style error. Got {e}"
        )
    });
}

#[test]
fn para_link_to_paragraph_style_crosstype_ignored_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="LinkedPara"/></w:pPr><w:r><w:t>Para link points at another paragraph style.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_PARA_TO_PARA_2)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / MS-OI29500 §2.1.235 — a paragraph style's w:link \
         must refer to a character style 'or this element shall be ignored'; a \
         para->para link is silently dropped, not a repair-triggering error, so \
         stemma's validator must not reject it. Got {e}"
        )
    });
}

#[test]
fn char_link_to_numbering_style_crosstype_ignored_opens_clean() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="LinkedChar"/></w:rPr><w:t>Char style links to a numbering style.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_CHAR_TO_NUMBERING)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / MS-OI29500 §2.1.235 — a character style's w:link \
         must refer to a paragraph style 'or this element shall be ignored'; a \
         char->numbering link is silently dropped (target exists, only the type \
         is wrong), so the validator must report no errors. Got {e}"
        )
    });
}

#[test]
fn duplicate_link_to_same_style_last_wins_opens_clean() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="LinkedPara"/></w:pPr><w:r><w:t>Two char styles both link to this paragraph style.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_DUP_LINK)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "MS-OI29500 §2.1.235 / ISO 29500-1 §17.7.4.6 — 'Word ignores all but the \
         last link to a given style.' Two char styles linking to the same \
         paragraph style is not an error; the ambiguous-link package is tolerated \
         and opens without repair, so the validator must report no errors. Got {e}"
        )
    });
}

#[test]
fn char_style_without_link_not_a_pairing_opens_clean() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="PlainChar"/></w:rPr><w:t>Run using a character style that has no link.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_PLAIN_CHAR)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 — 'A style element without a child link element is \
         not part of a linked style pairing'; a plain character style referenced \
         via rStyle is a valid configuration that Word opens without repair. Got {e}"
        )
    });
}

#[test]
fn para_link_to_paragraph_style_is_cross_type_ignored() {
    let body = r#"<w:p><w:pPr><w:pStyle w:val="LinkedPara"/></w:pPr><w:r><w:t>linked para text</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_PARA_TO_PARA_RICH)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / ECMA-376 §17.7.4.6 — a para->para link is \
         ignored (not honored, not an error); Word opens such a file without \
         repair, so stemma's validator must report no errors. Got {e}"
        )
    });

    assert_eq!(
        accept_text(&b).trim(),
        "linked para text",
        "ISO 29500-1 §17.7.4.6 — the ignored cross-type link must not alter \
         document text; the paragraph still resolves to its own style, so \
         read-side (accept-all) text is unaffected."
    );
}

#[test]
fn char_link_to_table_style_parent_ignored() {
    let body = r#"<w:p><w:r><w:rPr><w:rStyle w:val="CharLinksTbl"/></w:rPr><w:t>char to table link</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[("word/styles.xml", STYLES_CHAR_TO_TABLE)]);

    opens_clean(&b).unwrap_or_else(|e| {
        panic!(
            "ISO 29500-1 §17.7.4.6 / ECMA-376 §17.7.4.6 — a character style's w:link \
         must refer to a paragraph style 'or this element shall be ignored'; a \
         char->table link is a type mismatch Word ignores, loading without \
         repair, so the validator must report no errors. Got {e}"
        )
    });

    assert_eq!(
        accept_text(&b).trim(),
        "char to table link",
        "ISO 29500-1 §17.7.4.6 — the ignored mismatched link must not change \
         content; read-side (accept-all) text is the run's text unchanged."
    );
}
