//! Spec-compliance tests: Style cascade & property override semantics
//!
//! These tests verify the per-field (attribute-level) merge behavior for
//! paragraph indentation and spacing properties as specified in:
//!   - ISO 29500-1 §17.3.1.12 (w:ind — per-attribute override)
//!   - ISO 29500-1 §17.3.1.33 (w:spacing — per-attribute override)
//!   - ISO 29500-1 §17.7.2 (style hierarchy)
//!   - ISO 29500-1 §17.7.4.3 (basedOn chain)
//!   - ISO 29500-1 §17.7.4.17 (docDefaults)
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::LineSpacingRule;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-cascade";

// ==========================================================================
// Scenario 1: Direct w:ind partial override — per-field merge (§17.3.1.12)
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: Style defines w:ind left=720 right=360 firstLine=240.
/// Paragraph with only style reference should get all three indent values.
#[test]
fn spec_cascade_indent_style_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "indent-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // Para 0: style only — full indent from style
    let indent = paras[0]
        .indent
        .as_ref()
        .expect("para 0 should have indent from style");
    assert_eq!(
        indent.left,
        Some(720),
        "para 0 left should be 720 from IndentedStyle"
    );
    assert_eq!(
        indent.right,
        Some(360),
        "para 0 right should be 360 from IndentedStyle"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(240),
        "para 0 firstLine should be 240 from IndentedStyle"
    );
}

/// ISO 29500-1 §17.3.1.12: "Indentation settings are overridden on an
/// individual basis" — direct w:ind with only left=1440 overrides left;
/// right and firstLine inherit from the style (per-attribute merge).
#[test]
fn spec_cascade_indent_partial_direct_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "indent-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 1: direct left=1440 — per-attribute merge (§17.3.1.12).
    // Direct overrides left; right and firstLine inherit from style.
    let indent = paras[1].indent.as_ref().expect("para 1 should have indent");
    assert_eq!(
        indent.left,
        Some(1440),
        "para 1 left should be 1440 from direct formatting"
    );
    assert_eq!(
        indent.right,
        Some(360),
        "para 1 right should be 360 (inherited from style per §17.3.1.12)"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(240),
        "para 1 firstLine should be 240 (inherited from style per §17.3.1.12)"
    );
}

/// ISO 29500-1 §17.3.1.12: Direct w:ind with all three fields set to 0
/// should override all style values.
#[test]
fn spec_cascade_indent_full_direct_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "indent-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 2: direct left=0, right=0, firstLine=0
    let indent = paras[2]
        .indent
        .as_ref()
        .expect("para 2 should have indent (all zeros)");
    assert_eq!(indent.left, Some(0), "para 2 left should be 0 from direct");
    assert_eq!(
        indent.right,
        Some(0),
        "para 2 right should be 0 from direct"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(0),
        "para 2 firstLine should be 0 from direct"
    );
}

// ==========================================================================
// Scenario 2: Direct w:spacing partial override — per-field merge (§17.3.1.33)
// ==========================================================================

/// ISO 29500-1 §17.3.1.33: Style defines before=240, after=120, line=276.
/// Paragraph with only style reference should get all spacing values.
#[test]
fn spec_cascade_spacing_style_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    let spacing = paras[0]
        .spacing
        .as_ref()
        .expect("para 0 should have spacing from style");
    assert_eq!(
        spacing.before,
        Some(240),
        "para 0 before should be 240 from SpacedStyle"
    );
    assert_eq!(
        spacing.after,
        Some(120),
        "para 0 after should be 120 from SpacedStyle"
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "para 0 line should be 276 from SpacedStyle"
    );
}

/// ISO 29500-1 §17.3.1.33: Per-attribute inheritance — when a direct
/// w:spacing element has only before="0", the absent after and line
/// attributes inherit from the style chain.
///
/// SpacedStyle: before=240, after=120, line=276, lineRule=auto.
/// Direct: before=0 only.
/// Expected: before=0 (direct), after=120 (style), line=276 (style).
#[test]
fn spec_cascade_spacing_partial_direct_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    let spacing = paras[1]
        .spacing
        .as_ref()
        .expect("para 1 should have spacing");
    assert_eq!(
        spacing.before,
        Some(0),
        "para 1 before should be 0 from direct formatting"
    );
    assert_eq!(
        spacing.after,
        Some(120),
        "para 1 after should inherit 120 from style (per-attribute, §17.3.1.33)"
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "para 1 line should inherit 276 from style (per-attribute, §17.3.1.33)"
    );
}

/// ISO 29500-1 §17.3.1.33: Direct w:spacing with line=480 but no lineRule.
/// Per spec, lineRule defaults to "auto" when line is present (special rule).
/// Per-attribute: before/after inherit from style.
///
/// SpacedStyle: before=240, after=120, line=276, lineRule=auto.
/// Direct: line=480 only.
/// Expected: before=240 (style), after=120 (style), line=480 (direct),
///           lineRule=auto (special default, not style inheritance).
#[test]
fn spec_cascade_spacing_line_rule_trivial_match() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 4,
        "expected at least 4 paragraphs, got {}",
        paras.len()
    );

    // Para 2: direct line=480, no lineRule, style has lineRule=auto
    let spacing = paras[2]
        .spacing
        .as_ref()
        .expect("para 2 should have spacing");
    assert_eq!(
        spacing.line,
        Some(480),
        "para 2 line should be 480 from direct"
    );
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "para 2 lineRule should be Auto (spec default when line is present)"
    );
    // Per-attribute: before/after inherit from style
    assert_eq!(
        spacing.before,
        Some(240),
        "para 2 before should inherit 240 from style (per-attribute, §17.3.1.33)"
    );
    assert_eq!(
        spacing.after,
        Some(120),
        "para 2 after should inherit 120 from style (per-attribute, §17.3.1.33)"
    );
}

/// ISO 29500-1 §17.3.1.33: "If [lineRule] is omitted, then it
/// shall be assumed to be of a value auto if a line attribute value is
/// present."
///
/// When direct w:spacing sets line=480 but omits lineRule, and the style
/// has lineRule=exact, the spec says lineRule should be "auto" (not
/// inherited from style). Current code does per-field merge for lineRule,
/// so it falls through to the style's "exact" — which is wrong.
#[test]
fn spec_cascade_spacing_line_rule_exact_style_gap016() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-partial-direct");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 4,
        "expected at least 4 paragraphs, got {}",
        paras.len()
    );

    // Para 3: ExactSpacedStyle (lineRule=exact) + direct line=480, no lineRule
    // Spec says: lineRule=auto (default when line present), NOT exact from style
    let spacing = paras[3]
        .spacing
        .as_ref()
        .expect("para 3 should have spacing");
    assert_eq!(
        spacing.line,
        Some(480),
        "para 3 line should be 480 from direct"
    );
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "para 3 lineRule should be Auto (spec default when line is present), \
         NOT Exact from style. Per §17.3.1.33: 'If [lineRule] is omitted, \
         then it shall be assumed to be of a value auto if a line attribute \
         value is present.'"
    );
}

// ==========================================================================
// Scenario 3: Deep basedOn chain (3+ levels) with per-field indent
// ==========================================================================

/// ISO 29500-1 §17.7.4.3 + §17.3.1.12: Three-level basedOn chain where
/// each level contributes a different indent field. The resolved style
/// should merge per-field across the chain.
///
/// IndentA: left=360
/// IndentB (basedOn A): right=360
/// IndentC (basedOn B): firstLine=240
/// Resolved for C: left=360 (from A), right=360 (from B), firstLine=240 (from C)
#[test]
fn spec_cascade_deep_based_on_style_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "deep-based-on-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // Para 0: StyleC — should accumulate indent from all ancestors
    let indent = paras[0]
        .indent
        .as_ref()
        .expect("para 0 (StyleC) should have indent from chain");
    assert_eq!(
        indent.left,
        Some(360),
        "para 0 left should be 360 from IndentA (root of chain)"
    );
    assert_eq!(
        indent.right,
        Some(360),
        "para 0 right should be 360 from IndentB (middle of chain)"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(240),
        "para 0 firstLine should be 240 from IndentC (leaf of chain)"
    );
}

/// ISO 29500-1 §17.3.1.12: Per-attribute merge — direct left=720 overrides
/// the chain's left; right and firstLine inherit from the style chain.
#[test]
fn spec_cascade_deep_based_on_with_direct() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "deep-based-on-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 1: StyleC + direct left=720 — per-attribute merge (§17.3.1.12).
    // Direct overrides left; right and firstLine inherit from style chain.
    let indent = paras[1].indent.as_ref().expect("para 1 should have indent");
    assert_eq!(
        indent.left,
        Some(720),
        "para 1 left should be 720 from direct (overrides chain's 360)"
    );
    assert_eq!(
        indent.right,
        Some(360),
        "para 1 right should be 360 (inherited from style chain per §17.3.1.12)"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(240),
        "para 1 firstLine should be 240 (inherited from IndentC per §17.3.1.12)"
    );
}

/// ISO 29500-1 §17.7.4.3: StyleB only inherits from IndentA, not IndentC.
/// Should have left=360 (from A), right=360 (from B), no firstLine.
#[test]
fn spec_cascade_deep_based_on_mid_chain() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "deep-based-on-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 2: StyleB — only left from A and right from B
    let indent = paras[2]
        .indent
        .as_ref()
        .expect("para 2 (StyleB) should have indent");
    assert_eq!(
        indent.left,
        Some(360),
        "para 2 left should be 360 from IndentA"
    );
    assert_eq!(
        indent.right,
        Some(360),
        "para 2 right should be 360 from IndentB"
    );
    assert_eq!(
        indent.effective_first_line_twips, None,
        "para 2 firstLine should be None (IndentB/A don't set it)"
    );
}

// ==========================================================================
// Scenario 4: docDefaults spacing interaction
// ==========================================================================

/// ISO 29500-1 §17.7.4.17: docDefaults provides fallback spacing.
/// Paragraph with no style should get docDefaults spacing.
#[test]
fn spec_cascade_doc_defaults_no_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-spacing");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // Para 0: no style — should get docDefaults spacing
    let spacing = paras[0]
        .spacing
        .as_ref()
        .expect("para 0 should have spacing from docDefaults");
    assert_eq!(
        spacing.after,
        Some(200),
        "para 0 after should be 200 from docDefaults"
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "para 0 line should be 276 from docDefaults"
    );
}

/// ISO 29500-1 §17.7.4.17 + §17.3.1.33: Style sets before=120.
/// After and line should fall through to docDefaults (per-field).
#[test]
fn spec_cascade_doc_defaults_style_partial_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-spacing");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 1: BeforeOnlyStyle — before from style, rest from docDefaults
    let spacing = paras[1]
        .spacing
        .as_ref()
        .expect("para 1 should have spacing");
    assert_eq!(
        spacing.before,
        Some(120),
        "para 1 before should be 120 from BeforeOnlyStyle"
    );
    assert_eq!(
        spacing.after,
        Some(200),
        "para 1 after should be 200 from docDefaults (style doesn't set it)"
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "para 1 line should be 276 from docDefaults (style doesn't set it)"
    );
}

/// ISO 29500-1 §17.3.1.33: Per-attribute inheritance — direct before=0
/// overrides style's before=120, but after and line inherit from the
/// chain (BeforeOnlyStyle doesn't set them → docDefaults).
#[test]
fn spec_cascade_doc_defaults_direct_overrides_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-spacing");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 2: BeforeOnlyStyle + direct before=0 — per-attribute
    let spacing = paras[2]
        .spacing
        .as_ref()
        .expect("para 2 should have spacing");
    assert_eq!(
        spacing.before,
        Some(0),
        "para 2 before should be 0 from direct (overrides style's 120)"
    );
    assert_eq!(
        spacing.after,
        Some(200),
        "para 2 after should inherit 200 from docDefaults (per-attribute, §17.3.1.33)"
    );
    assert_eq!(
        spacing.line,
        Some(276),
        "para 2 line should inherit 276 from docDefaults (per-attribute, §17.3.1.33)"
    );
}

// ==========================================================================
// Scenario 5: Normal (default) style edge case
// ==========================================================================

/// ISO 29500-1 §17.7.4.17: When no explicit pStyle is set, Normal style
/// applies. Normal defines left=720, firstLine=360.
#[test]
fn spec_cascade_normal_style_implicit() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-style-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // Para 0: no pStyle — should get Normal's indent
    let indent = paras[0]
        .indent
        .as_ref()
        .expect("para 0 should have indent from Normal style");
    assert_eq!(
        indent.left,
        Some(720),
        "para 0 left should be 720 from Normal"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(360),
        "para 0 firstLine should be 360 from Normal"
    );
}

/// ISO 29500-1 §17.3.1.12: Per-attribute merge — direct left=0 overrides
/// Normal's left; firstLine inherits from Normal.
#[test]
fn spec_cascade_normal_style_direct_partial_override() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-style-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 1: no explicit pStyle, direct left=0 — per-attribute merge (§17.3.1.12).
    // Direct overrides left; firstLine inherits from Normal.
    let indent = paras[1].indent.as_ref().expect("para 1 should have indent");
    assert_eq!(
        indent.left,
        Some(0),
        "para 1 left should be 0 from direct (overrides Normal's 720)"
    );
    assert_eq!(
        indent.effective_first_line_twips,
        Some(360),
        "para 1 firstLine should be 360 (inherited from Normal per §17.3.1.12)"
    );
}

/// ISO 29500-1 §17.3.1.12: Same as above but with explicit pStyle=Normal.
/// Per-attribute merge: direct left=0 wins, firstLine inherits from Normal.
#[test]
fn spec_cascade_normal_style_explicit_with_direct() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "normal-style-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(paras.len() >= 3, "expected at least 3 paragraphs");

    // Para 2: explicit pStyle=Normal, direct left=0 — per-attribute merge (§17.3.1.12).
    // Direct overrides left; firstLine inherits from Normal.
    let indent = paras[2].indent.as_ref().expect("para 2 should have indent");
    assert_eq!(indent.left, Some(0), "para 2 left should be 0 from direct");
    assert_eq!(
        indent.effective_first_line_twips,
        Some(360),
        "para 2 firstLine should be 360 (inherited from Normal per §17.3.1.12)"
    );
}
