//! Spec-compliance tests: Document Structure (ISO 29500-1 §17.3, §17.6)
//!
//! These tests verify our implementation against specific OOXML document
//! structure constructs (flow control, section properties, indentation).
//! Tests marked `#[ignore]` document known gaps.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::PageOrientation;

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/structure";

// -- flow control properties ------------------------------------------------

/// ISO 29500-1 §17.3.1.14: w:keepNext keeps paragraph with next paragraph.
#[test]
fn spec_keep_next_is_exposed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "flow-control-keep-next");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "should have at least 2 paragraphs, got {}",
        paras.len()
    );

    assert_eq!(
        paras[0].keep_next,
        Some(true),
        "first paragraph should have keep_next = Some(true)"
    );
}

/// ISO 29500-1 §17.3.1.15: w:keepLines keeps all lines on same page.
#[test]
fn spec_keep_lines_is_exposed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "flow-control-keep-next");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "should have at least 2 paragraphs, got {}",
        paras.len()
    );

    assert_eq!(
        paras[0].keep_lines,
        Some(true),
        "first paragraph should have keep_lines = Some(true)"
    );
}

/// ISO 29500-1 §17.3.1.23: w:pageBreakBefore forces page break before paragraph.
#[test]
fn spec_page_break_before_is_exposed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "flow-control-page-break-before");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "should have at least 2 paragraphs, got {}",
        paras.len()
    );

    // The second paragraph has w:pageBreakBefore in its pPr.
    assert!(
        paras[1].page_break_before,
        "second paragraph should have page_break_before = true"
    );
}

/// ISO 29500-1 §17.3.1.44: w:widowControl set to val="0" disables widow/orphan control.
#[test]
fn spec_widow_control_is_exposed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "widow-control");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "should have at least 2 paragraphs, got {}",
        paras.len()
    );

    // The first paragraph has w:widowControl val="0" — explicitly disabled.
    assert_eq!(
        paras[0].widow_control,
        Some(false),
        "first paragraph should have widow_control = Some(false)"
    );
}

// -- section properties -----------------------------------------------------

/// ISO 29500-1 §17.6.18: sectPr in pPr — typed parsing populates page size.
///
/// When a paragraph has a sectPr child in its pPr, the typed
/// `section_properties` field must be populated with the parsed page size
/// (no raw blob fallback).
#[test]
fn spec_section_properties_populated_from_sect_pr() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "section-page-size-orientation");

    let paras = common::all_paragraphs(&doc);

    let sect_para = paras
        .iter()
        .find(|p| p.section_properties.is_some())
        .expect(
            "At least one paragraph should have section_properties parsed. \
             The fixture has a sectPr with pgSz in the last paragraph's pPr.",
        );

    let sp = sect_para.section_properties.as_ref().unwrap();
    assert!(
        sp.page_width.is_some(),
        "section_properties.page_width should be parsed from pgSz"
    );
    assert!(
        sp.page_height.is_some(),
        "section_properties.page_height should be parsed from pgSz"
    );
}

/// ISO 29500-1 §17.6.14: Page size and orientation as structured data.
///
/// Section properties are parsed into structured fields (page_width,
/// page_height, orientation).
#[test]
fn spec_section_page_size_structured() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "section-page-size-orientation");

    let paras = common::all_paragraphs(&doc);

    let sect_para = paras
        .iter()
        .find(|p| p.section_properties.is_some())
        .expect("should have a paragraph with structured section properties");

    let props = sect_para.section_properties.as_ref().unwrap();

    // A4 page size in twips
    assert_eq!(
        props.page_width,
        Some(11906),
        "page width should be A4 width in twips"
    );
    assert_eq!(
        props.page_height,
        Some(16838),
        "page height should be A4 height in twips"
    );
    assert_eq!(
        props.orientation,
        Some(PageOrientation::Landscape),
        "orientation should be landscape"
    );
}

/// ISO 29500-1 §17.6.4: Column layout as structured data.
///
/// Section properties include column layout parsed from w:cols.
#[test]
fn spec_section_columns_structured() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "section-columns");

    let paras = common::all_paragraphs(&doc);

    let sect_para = paras
        .iter()
        .find(|p| p.section_properties.is_some())
        .expect("should have a paragraph with structured section properties");

    let props = sect_para.section_properties.as_ref().unwrap();

    assert_eq!(props.columns, Some(2), "should have 2 columns");
}

// -- indentation ------------------------------------------------------------

/// ISO 29500-1 §17.3.1.12: Left and right paragraph indentation.
///
/// Indentation IS fully parsed into the domain model.
#[test]
fn spec_indentation_left_right_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "indentation-types");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 5,
        "should have at least 5 paragraphs, got {}",
        paras.len()
    );

    // Paragraph 0: left=720
    let p0 = &paras[0];
    let indent0 = p0
        .indent
        .as_ref()
        .expect("paragraph 0 should have indentation. w:ind left=720 is present in XML.");
    assert_eq!(
        indent0.left,
        Some(720),
        "paragraph 0 left indent should be 720 twips"
    );

    // Paragraph 1: right=720
    let p1 = &paras[1];
    let indent1 = p1
        .indent
        .as_ref()
        .expect("paragraph 1 should have indentation. w:ind right=720 is present in XML.");
    assert_eq!(
        indent1.right,
        Some(720),
        "paragraph 1 right indent should be 720 twips"
    );
}

/// ISO 29500-1 §17.3.1.12: First-line paragraph indentation.
///
/// Indentation IS fully parsed.
#[test]
fn spec_indentation_first_line_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "indentation-types");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 5,
        "should have at least 5 paragraphs, got {}",
        paras.len()
    );

    // Paragraph 2: firstLine=360
    let p2 = &paras[2];
    let indent2 = p2
        .indent
        .as_ref()
        .expect("paragraph 2 should have indentation. w:ind firstLine=360 is present in XML.");
    assert_eq!(
        indent2.effective_first_line_twips,
        Some(360),
        "paragraph 2 first_line indent should be 360 twips"
    );

    // Paragraph 4: left=720, right=360, firstLine=360
    let p4 = &paras[4];
    let indent4 = p4
        .indent
        .as_ref()
        .expect("paragraph 4 should have indentation. w:ind left=720 right=360 firstLine=360.");
    assert_eq!(indent4.left, Some(720), "paragraph 4 left should be 720");
    assert_eq!(indent4.right, Some(360), "paragraph 4 right should be 360");
    assert_eq!(
        indent4.effective_first_line_twips,
        Some(360),
        "paragraph 4 first_line should be 360"
    );
}

/// ISO 29500-1 §17.3.1.12: Hanging indent (w:hanging → negative first_line).
///
/// The parser converts w:hanging to a negative first_line value.
#[test]
fn spec_indentation_hanging_parsed() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "indentation-types");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 5,
        "should have at least 5 paragraphs, got {}",
        paras.len()
    );

    // Paragraph 3: left=720, hanging=360 → first_line=-360
    let p3 = &paras[3];
    let indent3 = p3.indent.as_ref().expect(
        "paragraph 3 should have indentation. w:ind left=720 hanging=360 is present in XML.",
    );
    assert_eq!(
        indent3.left,
        Some(720),
        "paragraph 3 left indent should be 720 twips"
    );
    assert_eq!(
        indent3.effective_first_line_twips,
        Some(-360),
        "paragraph 3 first_line should be -360 (hanging indent of 360 twips stored as negative)"
    );
}
