//! Spec-compliance tests: Table Style Cascade & Conditional Formatting (ISO 29500-1 §17.7.6)
//!
//! These tests verify table style resolution edge cases against the OOXML spec:
//! - Conditional formatting precedence (§17.7.6)
//! - Table style paragraph properties (§17.7.6.1)
//! - Table style run properties (§17.7.6.2)
//! - Cell margin inheritance chain (§17.4.43)
//! - Band row/column interaction
//! - Table-level style properties (alignment, indent)
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{BlockNode, CanonDoc, InlineNode};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-cascade";

// ── helpers ──────────────────────────────────────────────────────────────
fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

/// Get the first paragraph in a table cell.
fn cell_first_paragraph(
    table: &stemma::TableNode,
    row: usize,
    col: usize,
) -> &stemma::ParagraphNode {
    let cell = &table.rows[row].cells[col];
    cell.blocks
        .iter()
        .find_map(|b| match b {
            BlockNode::Paragraph(p) => Some(p),
            _ => None,
        })
        .expect("cell should contain at least one paragraph")
}

/// Get the first text node in a table cell.
fn cell_first_text_node(table: &stemma::TableNode, row: usize, col: usize) -> &stemma::TextNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    return t;
                }
            }
        }
    }
    panic!("cell ({row},{col}) should contain at least one text node")
}

// ── Conditional formatting precedence (§17.7.6) ────────────────

/// MS-OI29500 §17.7.6(c): Conditional format precedence at corner cell (0,0).
///
/// Per MS spec, the precedence order is (higher overrides lower):
///   wholeTable < bands < firstCol/lastCol < firstRow/lastRow < corners
///
/// Cell (0,0) matches both firstRow (blue 4472C4) and firstCol (green 70AD47).
/// Per MS behavior, firstRow has HIGHER precedence than firstCol: blue (4472C4).
///
/// Note: The base ISO spec says firstCol > firstRow, but MS Word does the opposite.
/// Precedence corrected to match MS behavior.
#[test]
fn spec_conditional_precedence_corner_top_left() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-precedence");
    let table = first_table(&doc);

    // Cell (0,0): firstRow AND firstCol both match.
    // Per MS-OI29500 §17.7.6: firstRow > firstCol → blue (4472C4).
    let shading = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("corner cell (0,0) should have shading");
    assert_eq!(
        shading.fill.as_deref(),
        Some("4472C4"),
        "cell (0,0): firstRow (blue) should override firstCol (green) per MS-OI29500 §17.7.6"
    );
}

/// MS-OI29500 §17.7.6(c): Top-right corner: firstRow > lastCol.
///
/// Cell (0,2): firstRow (blue 4472C4) AND lastCol (red FF0000).
/// Per MS behavior, firstRow has HIGHER precedence: blue (4472C4).
#[test]
fn spec_conditional_precedence_corner_top_right() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-precedence");
    let table = first_table(&doc);

    let shading = table.rows[0].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("corner cell (0,2) should have shading");
    assert_eq!(
        shading.fill.as_deref(),
        Some("4472C4"),
        "cell (0,2): firstRow (blue) should override lastCol (red) per MS-OI29500 §17.7.6"
    );
}

/// MS-OI29500 §17.7.6(c): Bottom-left corner: lastRow > firstCol.
///
/// Cell (3,0): lastRow (yellow FFC000) AND firstCol (green 70AD47).
/// Per MS behavior, lastRow has HIGHER precedence: yellow (FFC000).
#[test]
fn spec_conditional_precedence_corner_bottom_left() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-precedence");
    let table = first_table(&doc);

    let shading = table.rows[3].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("corner cell (3,0) should have shading");
    assert_eq!(
        shading.fill.as_deref(),
        Some("FFC000"),
        "cell (3,0): lastRow (yellow) should override firstCol (green) per MS-OI29500 §17.7.6"
    );
}

/// MS-OI29500 §17.7.6(c): Bottom-right corner: lastRow > lastCol.
///
/// Cell (3,2): lastRow (yellow FFC000) AND lastCol (red FF0000).
/// Per MS behavior, lastRow has HIGHER precedence: yellow (FFC000).
#[test]
fn spec_conditional_precedence_corner_bottom_right() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-precedence");
    let table = first_table(&doc);

    let shading = table.rows[3].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("corner cell (3,2) should have shading");
    assert_eq!(
        shading.fill.as_deref(),
        Some("FFC000"),
        "cell (3,2): lastRow (yellow) should override lastCol (red) per MS-OI29500 §17.7.6"
    );
}

/// ISO 29500-1 §17.7.6: Non-corner cells get their single conditional.
///
/// Cell (0,1): only firstRow applies → blue (4472C4).
/// Cell (1,0): only firstCol applies → green (70AD47).
#[test]
fn spec_conditional_precedence_non_corner_cells() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "conditional-precedence");
    let table = first_table(&doc);

    // Cell (0,1): firstRow only → blue
    let shading_01 = table.rows[0].cells[1]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,1) should have shading from firstRow");
    assert_eq!(
        shading_01.fill.as_deref(),
        Some("4472C4"),
        "cell (0,1): firstRow only → blue (4472C4)"
    );

    // Cell (3,1): lastRow only → yellow
    let shading_31 = table.rows[3].cells[1]
        .formatting
        .shading
        .as_ref()
        .expect("cell (3,1) should have shading from lastRow");
    assert_eq!(
        shading_31.fill.as_deref(),
        Some("FFC000"),
        "cell (3,1): lastRow only → yellow (FFC000)"
    );

    // Cell (1,0): firstCol only → green
    let shading_10 = table.rows[1].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (1,0) should have shading from firstCol");
    assert_eq!(
        shading_10.fill.as_deref(),
        Some("70AD47"),
        "cell (1,0): firstCol only → green (70AD47)"
    );

    // Cell (1,2): lastCol only → red
    let shading_12 = table.rows[1].cells[2]
        .formatting
        .shading
        .as_ref()
        .expect("cell (1,2) should have shading from lastCol");
    assert_eq!(
        shading_12.fill.as_deref(),
        Some("FF0000"),
        "cell (1,2): lastCol only → red (FF0000)"
    );
}

// ── Conditional formatting pPr and rPr (§17.7.6.1, §17.7.6.2) ─

/// ISO 29500-1 §17.7.6.1: Conditional formatting paragraph properties.
///
/// Table style's firstRow tblStylePr sets jc=center in pPr.
/// Paragraphs in header row cells (with no direct alignment) should
/// inherit center alignment from the conditional formatting.
#[test]
fn spec_conditional_para_props_alignment() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "style-para-props");
    let table = first_table(&doc);

    // First row: paragraphs should be center-aligned from conditional pPr
    let para_00 = cell_first_paragraph(table, 0, 0);
    assert_eq!(
        para_00.align,
        Some(stemma::Alignment::Center),
        "paragraph in first row cell (0,0) should be center-aligned from conditional pPr"
    );

    let para_01 = cell_first_paragraph(table, 0, 1);
    assert_eq!(
        para_01.align,
        Some(stemma::Alignment::Center),
        "paragraph in first row cell (0,1) should be center-aligned from conditional pPr"
    );

    // Data rows: default Left alignment per MS-OI29500 §17.3.1.13(a)
    let para_10 = cell_first_paragraph(table, 1, 0);
    assert_eq!(
        para_10.align,
        Some(stemma::Alignment::Left),
        "paragraph in data row cell (1,0) should default to Left per MS-OI29500 §17.3.1.13(a)"
    );
}

/// ISO 29500-1 §17.7.6.2: Conditional formatting run properties.
///
/// Table style's firstRow tblStylePr sets bold in rPr.
/// Runs in header row cells (with no direct bold) should inherit bold
/// from the conditional formatting.
#[test]
fn spec_conditional_run_props_bold() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "style-run-props");
    let table = first_table(&doc);

    // First row: text should be bold from conditional rPr
    let text_00 = cell_first_text_node(table, 0, 0);
    assert!(
        text_00.marks.contains(&stemma::Mark::Bold),
        "text in first row cell (0,0) should be bold from conditional rPr"
    );

    // Data rows: text should not be bold
    let text_10 = cell_first_text_node(table, 1, 0);
    assert!(
        !text_10.marks.contains(&stemma::Mark::Bold),
        "text in data row cell (1,0) should not be bold"
    );
}

// ── Band row/column interaction ────────────────────────

/// MS-OI29500 §17.7.6.5/§17.7.6.7: Band size defaults to 0 when absent.
///
/// When tblStyleRowBandSize/tblStyleColBandSize are absent, MS Word defaults them
/// to 0 (no banding), not 1 as the base ISO spec says. Since this fixture doesn't
/// specify band sizes, no banding is applied and cells get no band shading.
#[test]
fn spec_band_interaction_row_wins_at_intersection() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-interaction");
    let table = first_table(&doc);

    // Band size defaults to 0 = no banding.
    // Cells should NOT have band shading when band sizes are absent.
    assert!(
        table.rows[0].cells[0].formatting.shading.is_none(),
        "cell (0,0): no band shading when band size defaults to 0"
    );
}

/// MS-OI29500 §17.7.6.5/§17.7.6.7: No banding when band size is 0.
///
/// Even rows also get no band shading when band size defaults to 0.
#[test]
fn spec_band_interaction_even_row_wins() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "band-interaction");
    let table = first_table(&doc);

    // Band size defaults to 0 = no banding.
    assert!(
        table.rows[1].cells[0].formatting.shading.is_none(),
        "cell (1,0): no band shading when band size defaults to 0"
    );
}

// ── Cell margin inheritance chain (§17.4.43) ────────────────────────────

/// ISO 29500-1 §17.4.43: Table direct cell margins override table style margins.
///
/// Table style defines default cell margins of 50tw.
/// Table direct tblCellMar overrides to 100tw.
/// All cells without direct tcMar should get 100tw (from table, not style).
#[test]
fn spec_cell_margin_table_overrides_style() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-margin-chain");
    let table = first_table(&doc);

    // Table-level default margins should be 100 (from direct tblCellMar, not style's 50)
    let default_margins = table
        .formatting
        .default_cell_margins
        .as_ref()
        .expect("table should have default_cell_margins");
    assert_eq!(
        default_margins.top,
        Some(100),
        "table default cell margin top should be 100 from direct tblCellMar"
    );
    assert_eq!(
        default_margins.left,
        Some(100),
        "table default cell margin left should be 100 from direct tblCellMar"
    );
}

/// ISO 29500-1 §17.4.43: Direct cell margins override table default margins.
///
/// Cell (2,0) has direct tcMar with 200tw on all sides.
/// This should override the table default of 100tw.
#[test]
fn spec_cell_margin_direct_overrides_table() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "cell-margin-chain");
    let table = first_table(&doc);

    let cell_margins = table.rows[2].cells[0]
        .formatting
        .margins
        .as_ref()
        .expect("cell (2,0) should have direct margins");
    assert_eq!(
        cell_margins.top,
        Some(200),
        "cell (2,0) direct margin top should be 200"
    );
    assert_eq!(
        cell_margins.bottom,
        Some(200),
        "cell (2,0) direct margin bottom should be 200"
    );
    assert_eq!(
        cell_margins.left,
        Some(200),
        "cell (2,0) direct margin left should be 200"
    );
    assert_eq!(
        cell_margins.right,
        Some(200),
        "cell (2,0) direct margin right should be 200"
    );
}

// ── Table-level style properties (§17.4.63) ────────────────────
// Note: These tests are placeholders for when TableStyleProps gains
// alignment and indent fields. Currently, the struct only has borders,
// default_cell_margins, default_cell_shading, and conditional.

// Table alignment and indent from style are not yet modeled in
// TableStyleProps or TableFormatting. When implemented, these tests
// should verify that style-level jc and tblInd propagate to the table.
// For now, we only test that the fixture imports without error.

/// ISO 29500-1 §17.4.63: Table style with alignment and indent should import.
#[test]
fn spec_style_table_props_imports() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "style-table-props");
    let table = first_table(&doc);
    assert_eq!(table.rows.len(), 2, "should have 2 rows");

    assert_eq!(
        table.formatting.alignment,
        Some(stemma::Alignment::Center),
        "table alignment should be center from style tblPr/jc"
    );
    assert_eq!(
        table.formatting.indent,
        Some(720),
        "table indent should be 720 twips from style tblPr/tblInd"
    );
}
