//! Spec-compliance tests: Style constraints and merge behavioral rules
//!
//! These tests verify specific OOXML style constraints:
//!   - ISO 29500-1 §17.7.4.6 (w:link — linked paragraph/character styles)
//!   - ISO 29500-1 §17.7.4.3 (w:basedOn — cross-type validation)
//!   - ISO 29500-1 §17.7.6.6 (tblStylePr nwCell — corner conditional precedence)
//!   - ISO 29500-1 §17.3.1.33 (w:spacing lineRule default)
//!
//! Tests marked `#[ignore]` document spec-correct behavior that the code
//! does NOT yet implement. Unmarked tests verify behavior we believe is
//! already correct.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_style_constraints.py`.

use stemma::{BlockNode, CanonDoc, InlineNode, LineSpacingRule, Mark};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-constraints";

// ── helpers ──────────────────────────────────────────────────────────────

/// Get the first text node of a paragraph.
fn first_text_node(p: &stemma::ParagraphNode) -> Option<&stemma::TextNode> {
    p.all_inlines().find_map(|inline| match inline {
        InlineNode::Text(t) => Some(t.as_ref()),
        _ => None,
    })
}

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

/// Get the first text node in a table cell.
fn cell_first_text_node(table: &stemma::TableNode, row: usize, col: usize) -> &stemma::TextNode {
    let cell = &table.rows[row].cells[col];
    for block in &cell.blocks {
        if let BlockNode::Paragraph(p) = block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    return t;
                }
            }
        }
    }
    panic!("cell ({row},{col}) should contain at least one text node")
}

// ==========================================================================
// Linked styles (§17.7.4.6)
// ==========================================================================

/// ISO 29500-1 §17.7.4.6: A paragraph using a linked paragraph style
/// ("HeadingLinked") should have its runs inherit the linked character
/// style's rPr merged with the paragraph style's own rPr.
///
/// Fixture: HeadingLinked (paragraph) = bold only;
///          HeadingLinkedChar (character) = italic + color=FF0000 + sz=28.
/// The linked char style's properties overlay the para style's resolved rPr.
/// Properties set by the linked char style win; properties only in the para
/// style (bold) fall through.
#[test]
fn spec_linked_paragraph_style_inherits_char_formatting() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-styles");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // Para 0: uses "HeadingLinked" paragraph style → linked char style overlays para rPr
    let tn = first_text_node(paras[0]).expect("para 0 should have text");

    assert!(
        tn.marks.contains(&Mark::Italic),
        "para 0 should be italic from linked character style"
    );
    assert_eq!(
        tn.style_props.color.as_deref(),
        Some("FF0000"),
        "para 0 color should be FF0000 from linked character style"
    );
    assert_eq!(
        tn.style_props.font_size,
        Some(28),
        "para 0 size should be 28 (14pt) from linked character style"
    );
    // Para style's own rPr (bold) falls through since linked char style doesn't set it
    assert!(
        tn.marks.contains(&Mark::Bold),
        "para 0 should be bold — para style's rPr property falls through when \
         linked char style doesn't override it (§17.7.4.6 merge semantics)"
    );

    // Para 1: normal paragraph — should NOT have the linked style's formatting
    let tn1 = first_text_node(paras[1]).expect("para 1 should have text");
    assert!(
        !tn1.marks.contains(&Mark::Bold),
        "para 1 (normal) should not be bold"
    );
}

// ==========================================================================
// basedOn type mismatch (§17.7.4.3)
// ==========================================================================

/// ISO 29500-1 §17.7.4.3: A character style's basedOn reference to a
/// paragraph style is a cross-type mismatch. Per spec, this basedOn
/// should be ignored — only CharStyleB's own properties should apply.
///
/// CharStyleB defines: italic + color=00FF00
/// ParaStyleA defines: bold + color=0000FF + size=32
///
/// If basedOn is correctly ignored, the run should be italic+green
/// without bold, blue, or size=32 from ParaStyleA.
///
/// Current gap: basedOn type checking is not implemented; the style
/// resolver may follow the basedOn chain regardless of type, leaking
/// ParaStyleA's properties into CharStyleB.
#[test]
fn spec_based_on_cross_type_is_ignored() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "based-on-type-mismatch");
    let paras = common::all_paragraphs(&doc);
    assert!(!paras.is_empty(), "expected at least 1 paragraph");

    let tn = first_text_node(paras[0]).expect("para 0 should have text");

    // CharStyleB's own properties should apply
    assert!(
        tn.marks.contains(&Mark::Italic),
        "run should be italic from CharStyleB's own rPr"
    );
    assert_eq!(
        tn.style_props.color.as_deref(),
        Some("00FF00"),
        "run color should be 00FF00 from CharStyleB (not 0000FF from ParaStyleA)"
    );

    // ParaStyleA's properties should NOT apply (basedOn cross-type ignored)
    assert!(
        !tn.marks.contains(&Mark::Bold),
        "run should NOT be bold — basedOn cross-type (char->para) must be ignored per §17.7.4.3"
    );
    assert_ne!(
        tn.style_props.font_size,
        Some(32),
        "run size should NOT be 32 from ParaStyleA — basedOn cross-type must be ignored"
    );
}

// ==========================================================================
// Table conditional precedence — nwCell (§17.7.6.6)
// ==========================================================================

/// ISO 29500-1 §17.7.6.6 + MS-OI29500 §17.4.54(a): Cell (0,0) matches
/// firstRow, firstCol, AND nwCell. The nwCell conditional has highest
/// precedence and should override both firstRow and firstCol formatting.
///
/// Expected: cell (0,0) text color = FF0000 (red from nwCell),
/// NOT 0000FF (blue from firstRow) or 00FF00 (green from firstCol).
/// Bold should be OFF (nwCell explicitly sets w:b w:val="0").
///
/// Current gap: conditional formatting merge order uses HashMap iteration,
/// so nwCell may not reliably override firstRow/firstCol. The precedence
/// order per MS-OI29500 is:
///   wholeTable < bands < firstCol/lastCol < firstRow/lastRow < corners
#[test]
fn spec_table_conditional_nw_cell_overrides_first_row_and_col() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "table-conditional-precedence");
    let table = first_table(&doc);

    // Cell (0,0): nwCell should win over firstRow and firstCol
    let text_00 = cell_first_text_node(table, 0, 0);
    assert_eq!(
        text_00.style_props.color.as_deref(),
        Some("FF0000"),
        "cell (0,0): nwCell (red) should override firstRow (blue) and firstCol (green)"
    );
    assert!(
        !text_00.marks.contains(&Mark::Bold),
        "cell (0,0): nwCell sets bold=off, overriding firstRow's bold=on"
    );

    // Cell (0,0) shading should come from nwCell
    let shading_00 = table.rows[0].cells[0]
        .formatting
        .shading
        .as_ref()
        .expect("cell (0,0) should have shading");
    assert_eq!(
        shading_00.fill.as_deref(),
        Some("FFDDDD"),
        "cell (0,0): nwCell shading fill should be FFDDDD"
    );

    // Cell (0,1): firstRow only — blue, bold
    let text_01 = cell_first_text_node(table, 0, 1);
    assert_eq!(
        text_01.style_props.color.as_deref(),
        Some("0000FF"),
        "cell (0,1): firstRow only — color should be blue (0000FF)"
    );
    assert!(
        text_01.marks.contains(&Mark::Bold),
        "cell (0,1): firstRow only — should be bold"
    );

    // Cell (1,0): firstCol only — green
    let text_10 = cell_first_text_node(table, 1, 0);
    assert_eq!(
        text_10.style_props.color.as_deref(),
        Some("00FF00"),
        "cell (1,0): firstCol only — color should be green (00FF00)"
    );

    // Cell (1,1): no conditional applies — MS-OI29500 §17.18.89 discards wholeTable.
    // Without wholeTable, and no root-level rPr color on the style, color is None.
    let text_11 = cell_first_text_node(table, 1, 1);
    assert_eq!(
        text_11.style_props.color.as_deref(),
        None,
        "cell (1,1): no conditional applies (wholeTable discarded per MS-OI29500 §17.18.89)"
    );
}

// ==========================================================================
// Spacing lineRule default (§17.3.1.33)
// ==========================================================================

/// ISO 29500-1 §17.3.1.33: Paragraph 1 uses "ExactSpacing" style with no
/// direct spacing. It should correctly inherit lineRule=exact from the style.
#[test]
fn spec_style_spacing_line_rule_inherited_normally() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-line-rule-default");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // Para 0: style only — should get line=480 and lineRule=exact from style
    let spacing = paras[0]
        .spacing
        .as_ref()
        .expect("para 0 should have spacing from style");
    assert_eq!(
        spacing.line,
        Some(480),
        "para 0 line should be 480 from ExactSpacing style"
    );
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Exact),
        "para 0 lineRule should be Exact from ExactSpacing style"
    );
}

/// ISO 29500-1 §17.3.1.33: "If [lineRule] is omitted, then it
/// shall be assumed to be of a value auto if a line attribute value is
/// present."
///
/// Paragraph 2 uses "ExactSpacing" style (lineRule=exact) but has direct
/// w:spacing with line=360 and NO lineRule attribute. Per spec, the
/// lineRule should default to "auto" (not inherit "exact" from style).
///
/// Current gap: the per-field merge for spacing lets lineRule
/// fall through to the style's "exact" value instead of applying the
/// spec default of "auto" when line is present but lineRule is omitted.
#[test]
fn spec_direct_spacing_without_line_rule_defaults_to_auto() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-line-rule-default");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // Para 1: ExactSpacing style + direct line=360 with NO lineRule
    let spacing = paras[1]
        .spacing
        .as_ref()
        .expect("para 1 should have spacing");
    assert_eq!(
        spacing.line,
        Some(360),
        "para 1 line should be 360 from direct formatting"
    );
    assert_eq!(
        spacing.line_rule,
        Some(LineSpacingRule::Auto),
        "para 1 lineRule should be Auto (spec default when line is present), \
         NOT Exact from style. Per §17.3.1.33: 'If [lineRule] is omitted, \
         then it shall be assumed to be of a value auto if a line attribute \
         value is present.'"
    );
}
