//! Spec-compliance tests: Continuous Section Break Edge Cases
//! (ECMA-376 §17.6.22, §17.6.11, §17.6.14, §17.11.2, §17.11.3)
//!
//! These tests cover edge cases in the rendering behavior of continuous
//! section breaks. They probe:
//!
//! 1. Forced break on orientation/page-size mismatch (§17.6.22 + §17.6.14)
//! 2. Top/bottom vs left/right margin distinction on shared page (§17.6.11)
//! 3. Chained continuous sections and page spill layout (§17.6.22)
//! 4. Mixed footnote/endnote settings on shared page (§17.11.2 / §17.11.3)
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/section-continuous-layout-edge/create_fixtures.py`.

use stemma::{BlockNode, CanonDoc, SectionProperties, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-continuous-layout-edge";

// -- helpers ----------------------------------------------------------------

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(blocks: &'a [BlockNode], out: &mut Vec<&'a SectionProperties>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// 1. FORCED BREAK ON ORIENTATION / PAGE-SIZE MISMATCH
// ==========================================================================
//
// ECMA-376 §17.6.22 defines section types including "continuous". However,
// Word (and other implementations per MS-OI29500) silently promote a
// continuous section break to a nextPage break when the orientation or page
// size differs from the preceding section. This is undocumented in the base
// spec but is consistent observed behavior.
//
// At the model level, the section_type remains "continuous" as declared in
// the XML. The promotion is a rendering-layer concern. These tests verify
// that the model preserves the declared properties correctly so that
// higher-level code can detect the mismatch and handle it.

/// ECMA-376 §17.6.22 / §17.6.14: Continuous section with different
/// orientation from the preceding section.
///
/// S1(nextPage, portrait 12240x15840) -> S2(continuous, landscape 15840x12240)
///
/// Word promotes this to a nextPage break at rendering time. At the model
/// level, S2 should retain its own declared page dimensions (landscape)
/// because pgSz is explicitly present in S2's sectPr. The `inherit_page_
/// properties` function only fills in None fields, so S2's explicit pgSz
/// is preserved.
#[test]
fn spec_orientation_mismatch_s2_retains_own_dimensions() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "orientation-mismatch");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        1,
        "should have 1 mid-document section (S1), got {}",
        section_props.len()
    );

    // S1: nextPage, portrait
    let s1 = section_props[0];
    assert_eq!(
        s1.section_type,
        Some(stemma::domain::SectionType::NextPage),
        "S1 should be nextPage"
    );
    assert_eq!(s1.page_width, Some(12240), "S1 page_width (portrait)");
    assert_eq!(s1.page_height, Some(15840), "S1 page_height (portrait)");

    // S2 (body-level): continuous, landscape
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 section_type should still be Continuous in the model (promotion is rendering-layer)"
    );

    // S2 has explicit pgSz with landscape dimensions — these must NOT be
    // overwritten by inheritance from S1.
    assert_eq!(
        s2.page_width,
        Some(15840),
        "S2 page_width should be 15840 (landscape, own value), got {:?}",
        s2.page_width
    );
    assert_eq!(
        s2.page_height,
        Some(12240),
        "S2 page_height should be 12240 (landscape, own value), got {:?}",
        s2.page_height
    );
    assert_eq!(
        s2.orientation,
        Some(stemma::domain::PageOrientation::Landscape),
        "S2 orientation should be Landscape, got {:?}",
        s2.orientation
    );
}

/// ECMA-376 §17.6.22 / §17.6.14: Detectable orientation mismatch between
/// continuous section and its predecessor.
///
/// Higher-level code can compare S1 and S2 page dimensions to detect
/// that Word would promote this to a nextPage break. This test verifies
/// the dimensions differ (the precondition for promotion).
#[test]
fn spec_orientation_mismatch_detectable_from_model() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "orientation-mismatch");

    let section_props = section_paragraphs(&doc);
    let s1 = section_props[0];
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    // The mismatch is detectable: S1 portrait vs S2 landscape
    let s1_portrait = s1.page_width < s1.page_height;
    let s2_portrait = s2.page_width < s2.page_height;

    assert!(
        s1_portrait,
        "S1 should be portrait (width < height): w={:?} h={:?}",
        s1.page_width, s1.page_height
    );
    assert!(
        !s2_portrait,
        "S2 should be landscape (width >= height): w={:?} h={:?}",
        s2.page_width, s2.page_height
    );
}

/// ECMA-376 §17.6.22 / §17.6.14: Continuous section with different page
/// size (same orientation) from the preceding section.
///
/// S1(nextPage, Letter 12240x15840) -> S2(continuous, Legal 12240x20160)
///
/// Word promotes S2 to nextPage because the page height differs.
/// At the model level, S2 retains its own declared page size.
#[test]
fn spec_page_size_mismatch_s2_retains_own_dimensions() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-size-mismatch");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        1,
        "should have 1 mid-document section (S1), got {}",
        section_props.len()
    );

    let s1 = section_props[0];
    assert_eq!(s1.page_width, Some(12240), "S1 page_width (Letter)");
    assert_eq!(s1.page_height, Some(15840), "S1 page_height (Letter)");

    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous in the model"
    );

    // S2 has explicit Legal-size pgSz — must not be overwritten
    assert_eq!(
        s2.page_width,
        Some(12240),
        "S2 page_width should be 12240 (Legal, same width as Letter), got {:?}",
        s2.page_width
    );
    assert_eq!(
        s2.page_height,
        Some(20160),
        "S2 page_height should be 20160 (Legal), got {:?}",
        s2.page_height
    );
}

/// ECMA-376 §17.6.22 / §17.6.14: Detectable page-size mismatch between
/// continuous section and its predecessor.
#[test]
fn spec_page_size_mismatch_detectable_from_model() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "page-size-mismatch");

    let section_props = section_paragraphs(&doc);
    let s1 = section_props[0];
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    // The mismatch is detectable: S1 Letter (15840) vs S2 Legal (20160)
    assert_ne!(
        s1.page_height, s2.page_height,
        "page heights should differ (Letter vs Legal): S1={:?}, S2={:?}",
        s1.page_height, s2.page_height
    );
}

/// ECMA-376 §17.6.22: Control test — continuous section with SAME
/// orientation and page size remains a genuine continuous break.
///
/// S1(nextPage, portrait 12240x15840) -> S2(continuous, portrait 12240x15840)
///
/// Same page size and orientation, so no promotion occurs. S2 keeps its
/// own margins (720 vs S1's 1440).
#[test]
fn spec_same_orientation_control_remains_continuous() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "same-orientation-control");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        1,
        "should have 1 mid-document section (S1)"
    );

    let s1 = section_props[0];
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous"
    );

    // Same page dimensions — no mismatch
    assert_eq!(
        s1.page_width, s2.page_width,
        "page widths should match: S1={:?}, S2={:?}",
        s1.page_width, s2.page_width
    );
    assert_eq!(
        s1.page_height, s2.page_height,
        "page heights should match: S1={:?}, S2={:?}",
        s1.page_height, s2.page_height
    );

    // S2 keeps its own margins (720), not inherited from S1 (1440)
    assert_eq!(
        s2.margin_top,
        Some(720),
        "S2 margin_top should be 720 (own), got {:?}",
        s2.margin_top
    );
    assert_eq!(
        s2.margin_left,
        Some(720),
        "S2 margin_left should be 720 (own), got {:?}",
        s2.margin_left
    );
    assert_eq!(
        s2.margin_right,
        Some(720),
        "S2 margin_right should be 720 (own), got {:?}",
        s2.margin_right
    );
    assert_eq!(
        s2.margin_bottom,
        Some(720),
        "S2 margin_bottom should be 720 (own), got {:?}",
        s2.margin_bottom
    );
}

// ==========================================================================
// 2. TOP/BOTTOM VS LEFT/RIGHT MARGIN DISTINCTION
// ==========================================================================
//
// ECMA-376 §17.6.11 (pgMar): On a shared physical page with a continuous
// break, top/bottom margins are locked by the preceding section (they are
// page-level and cannot change mid-page). Left/right margins CAN change
// mid-page because they define the text area width, not the page geometry.
//
// At the model level, when S2 explicitly declares all four margins, no
// inheritance occurs (the model fills in only None fields). These tests
// verify that S2's distinct left/right margins are preserved.

/// ECMA-376 §17.6.22 / §17.6.11: Continuous section with different
/// left/right margins from the preceding section.
///
/// S1(nextPage, left=1800 right=1800) -> S2(continuous, left=720 right=720)
///
/// Both sections share the same page size. S2 explicitly declares its
/// own margins, so all are preserved. The key assertion: S2's left/right
/// margins differ from S1's — this is valid for a continuous break.
#[test]
fn spec_left_right_margins_preserved_on_continuous() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "left-right-margins-differ");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        1,
        "should have 1 mid-document section (S1)"
    );

    let s1 = section_props[0];
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous"
    );

    // S1: wide margins
    assert_eq!(s1.margin_left, Some(1800), "S1 margin_left");
    assert_eq!(s1.margin_right, Some(1800), "S1 margin_right");

    // S2: narrow left/right margins (own values, not inherited)
    assert_eq!(
        s2.margin_left,
        Some(720),
        "S2 margin_left should be 720 (own), got {:?}",
        s2.margin_left
    );
    assert_eq!(
        s2.margin_right,
        Some(720),
        "S2 margin_right should be 720 (own), got {:?}",
        s2.margin_right
    );

    // Verify left/right actually differ from S1 (the point of this test)
    assert_ne!(
        s1.margin_left, s2.margin_left,
        "S2 left margin should differ from S1 (allowed on continuous break)"
    );
    assert_ne!(
        s1.margin_right, s2.margin_right,
        "S2 right margin should differ from S1 (allowed on continuous break)"
    );
}

/// ECMA-376 §17.6.11: Top/bottom margins are page-level — on a shared page
/// with a continuous break, they are logically locked by the preceding section.
///
/// At the model level, both sections explicitly declare top/bottom margins
/// with the same value (1440). This test documents the constraint: changing
/// top/bottom in a continuous section has no rendering effect on a shared
/// page, but the model faithfully preserves whatever the XML declares.
#[test]
fn spec_top_bottom_margins_same_on_shared_page() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "left-right-margins-differ");

    let section_props = section_paragraphs(&doc);
    let s1 = section_props[0];
    let s2 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    // Both sections declare the same top/bottom margins (1440).
    // In rendering, S2's top/bottom would be ignored on a shared page,
    // but the model preserves what the XML says.
    assert_eq!(
        s1.margin_top, s2.margin_top,
        "S1 and S2 top margins should match (page-level, locked by S1): S1={:?}, S2={:?}",
        s1.margin_top, s2.margin_top
    );
    assert_eq!(
        s1.margin_bottom, s2.margin_bottom,
        "S1 and S2 bottom margins should match (page-level, locked by S1): S1={:?}, S2={:?}",
        s1.margin_bottom, s2.margin_bottom
    );
}

// ==========================================================================
// 3. CHAINED CONTINUOUS SECTIONS — PAGE SPILL DETERMINES LAYOUT
// ==========================================================================
//
// ECMA-376 §17.6.22: When chained continuous sections spill to a new page,
// the new page's layout comes from the first section that begins on it, NOT
// the section that started the chain. This is a pagination-layer concern.
//
// At the model level, we verify:
// a) Each section carries distinct left margins through chained inheritance.
// b) The enriched state flows correctly through the chain (same mechanism
//    tested in spec_section_continuous_edge.rs but with more sections).

/// ECMA-376 §17.6.22: Chained continuous sections preserve distinct left
/// margins through inheritance chain.
///
/// S1(nextPage, left=1440) -> S2(continuous, left=720)
/// -> S3(continuous, left=360) -> S4(continuous, left=180)
///
/// Each section declares only a left margin; all other margins are inherited
/// from the preceding section.
#[test]
fn spec_chained_page_spill_distinct_left_margins() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "chained-continuous-page-spill");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        3,
        "should have 3 mid-document sections (S1, S2, S3), got {}",
        section_props.len()
    );

    // S1: nextPage, full margins
    let s1 = section_props[0];
    assert_eq!(
        s1.section_type,
        Some(stemma::domain::SectionType::NextPage),
        "S1 should be nextPage"
    );
    assert_eq!(s1.margin_left, Some(1440), "S1 margin_left");

    // S2: continuous, own left=720
    let s2 = section_props[1];
    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous"
    );
    assert_eq!(
        s2.margin_left,
        Some(720),
        "S2 margin_left should be 720 (own), got {:?}",
        s2.margin_left
    );

    // S3: continuous, own left=360
    let s3 = section_props[2];
    assert_eq!(
        s3.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S3 should be continuous"
    );
    assert_eq!(
        s3.margin_left,
        Some(360),
        "S3 margin_left should be 360 (own), got {:?}",
        s3.margin_left
    );

    // S4 (body-level): continuous, own left=180
    let s4 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S4)");
    assert_eq!(
        s4.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S4 should be continuous"
    );
    assert_eq!(
        s4.margin_left,
        Some(180),
        "S4 margin_left should be 180 (own), got {:?}",
        s4.margin_left
    );
}

/// ECMA-376 §17.6.22: Chained continuous sections inherit top/bottom/right
/// margins from the chain starter (S1) when they only declare left.
///
/// S2, S3, S4 each declare only left margin. The other margins should be
/// inherited from S1 (via the enrichment chain).
#[test]
fn spec_chained_page_spill_inherited_margins_flow_through() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "chained-continuous-page-spill");

    let section_props = section_paragraphs(&doc);
    let s1 = section_props[0];

    // All sections should inherit top/bottom/right from S1 (1440)
    for (label, sp) in [("S2", section_props[1]), ("S3", section_props[2])] {
        assert_eq!(
            sp.margin_top, s1.margin_top,
            "{label} margin_top should inherit {:?} from S1, got {:?}",
            s1.margin_top, sp.margin_top
        );
        assert_eq!(
            sp.margin_bottom, s1.margin_bottom,
            "{label} margin_bottom should inherit {:?} from S1, got {:?}",
            s1.margin_bottom, sp.margin_bottom
        );
        assert_eq!(
            sp.margin_right, s1.margin_right,
            "{label} margin_right should inherit {:?} from S1, got {:?}",
            s1.margin_right, sp.margin_right
        );
    }

    // S4 (body-level) should also inherit top/bottom/right from the chain
    let s4 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S4)");
    assert_eq!(
        s4.margin_top, s1.margin_top,
        "S4 margin_top should inherit {:?} from chain, got {:?}",
        s1.margin_top, s4.margin_top
    );
    assert_eq!(
        s4.margin_bottom, s1.margin_bottom,
        "S4 margin_bottom should inherit {:?} from chain, got {:?}",
        s1.margin_bottom, s4.margin_bottom
    );
    assert_eq!(
        s4.margin_right, s1.margin_right,
        "S4 margin_right should inherit {:?} from chain, got {:?}",
        s1.margin_right, s4.margin_right
    );
}

/// ECMA-376 §17.6.22: Page spill layout determination is a rendering-layer
/// concern. When chained continuous sections span multiple pages, the new
/// page's layout comes from the first section starting on that page.
///
/// The model preserves distinct section properties so that a renderer can
/// detect the page boundary. This test documents the requirement but does
/// not test rendering.
#[test]
#[ignore = "rendering-layer concern: page spill layout depends on pagination, not the import model"]
fn spec_chained_page_spill_new_page_uses_first_section_on_page() {
    // When continuous sections spill to a new page, the physical layout
    // (page size, top/bottom margins) of that new page comes from the
    // first section that starts on it, NOT from the section that started
    // the chain on the previous page.
    //
    // This requires a pagination engine to determine which section begins
    // on which page. The model preserves all per-section properties so
    // that a renderer can make this determination.
    //
    // Fixture: chained-continuous-page-spill has S1..S4 with decreasing
    // left margins. If S3 happens to start on a new page, that page's
    // layout (top/bottom margins, page size) would come from S3's
    // inherited values, not from S2.
}

// ==========================================================================
// 4. MIXED FOOTNOTE/ENDNOTE SETTINGS ON SHARED PAGE
// ==========================================================================
//
// ECMA-376 §17.11.3 (footnotePr) / §17.11.2 (endnotePr): Section-level
// footnote and endnote properties are per-section, even for continuous
// sections sharing a physical page. They control numbering format,
// restart behavior, and positioning independently per section.
//
// The import pipeline does NOT collapse footnote_pr / endnote_pr during
// continuous section inheritance — these are section-specific settings,
// not page-level properties.

/// ECMA-376 §17.11.3: Section-level footnote properties are preserved
/// independently across continuous sections.
///
/// S1(nextPage, footnote decimal/continuous) ->
/// S2(continuous, footnote lowerRoman/eachSect) ->
/// S3(continuous, body-level, footnote upperLetter/eachPage)
///
/// Each section has distinct footnote numFmt and numRestart.
#[test]
fn spec_mixed_footnote_settings_s1_properties() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-footnote-settings");

    let section_props = section_paragraphs(&doc);
    assert_eq!(
        section_props.len(),
        2,
        "should have 2 mid-document sections (S1, S2), got {}",
        section_props.len()
    );

    // S1: footnote decimal/continuous
    let s1 = section_props[0];
    let s1_fp = s1.footnote_pr.as_ref().expect("S1 should have footnote_pr");
    assert_eq!(
        s1_fp.num_fmt,
        Some(stemma::domain::NumberFormat::Decimal),
        "S1 footnote numFmt should be Decimal, got {:?}",
        s1_fp.num_fmt
    );
    assert_eq!(
        s1_fp.num_restart,
        Some(stemma::domain::RestartRule::Continuous),
        "S1 footnote numRestart should be Continuous, got {:?}",
        s1_fp.num_restart
    );

    // S1: endnote lowerRoman
    let s1_ep = s1.endnote_pr.as_ref().expect("S1 should have endnote_pr");
    assert_eq!(
        s1_ep.num_fmt,
        Some(stemma::domain::NumberFormat::LowerRoman),
        "S1 endnote numFmt should be LowerRoman, got {:?}",
        s1_ep.num_fmt
    );
}

/// ECMA-376 §17.11.3: S2 (continuous) has different footnote settings
/// from S1 — these are per-section, not collapsed during inheritance.
#[test]
fn spec_mixed_footnote_settings_s2_independent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-footnote-settings");

    let section_props = section_paragraphs(&doc);
    let s1 = section_props[0];
    let s2 = section_props[1];

    assert_eq!(
        s2.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S2 should be continuous"
    );

    // S2: footnote lowerRoman/eachSect (different from S1)
    let s2_fp = s2.footnote_pr.as_ref().expect("S2 should have footnote_pr");
    assert_eq!(
        s2_fp.num_fmt,
        Some(stemma::domain::NumberFormat::LowerRoman),
        "S2 footnote numFmt should be LowerRoman, got {:?}",
        s2_fp.num_fmt
    );
    assert_eq!(
        s2_fp.num_restart,
        Some(stemma::domain::RestartRule::EachSect),
        "S2 footnote numRestart should be EachSect, got {:?}",
        s2_fp.num_restart
    );

    // S2: endnote upperRoman (different from S1's lowerRoman)
    let s2_ep = s2.endnote_pr.as_ref().expect("S2 should have endnote_pr");
    assert_eq!(
        s2_ep.num_fmt,
        Some(stemma::domain::NumberFormat::UpperRoman),
        "S2 endnote numFmt should be UpperRoman, got {:?}",
        s2_ep.num_fmt
    );

    // Verify S1 and S2 have different footnote settings (the whole point)
    let s1_fp = s1.footnote_pr.as_ref().unwrap();
    assert_ne!(
        s1_fp.num_fmt, s2_fp.num_fmt,
        "S1 and S2 should have different footnote numFmt (per-section independence)"
    );
    assert_ne!(
        s1_fp.num_restart, s2_fp.num_restart,
        "S1 and S2 should have different footnote numRestart (per-section independence)"
    );
}

/// ECMA-376 §17.11.3: S3 (continuous, body-level) has yet another set of
/// footnote settings — all three sections are independent.
#[test]
fn spec_mixed_footnote_settings_s3_independent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-footnote-settings");

    let section_props = section_paragraphs(&doc);
    let s2 = section_props[1];

    let s3 = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S3)");

    assert_eq!(
        s3.section_type,
        Some(stemma::domain::SectionType::Continuous),
        "S3 should be continuous"
    );

    // S3: footnote upperLetter/eachPage (different from both S1 and S2)
    let s3_fp = s3.footnote_pr.as_ref().expect("S3 should have footnote_pr");
    assert_eq!(
        s3_fp.num_fmt,
        Some(stemma::domain::NumberFormat::UpperLetter),
        "S3 footnote numFmt should be UpperLetter, got {:?}",
        s3_fp.num_fmt
    );
    assert_eq!(
        s3_fp.num_restart,
        Some(stemma::domain::RestartRule::EachPage),
        "S3 footnote numRestart should be EachPage, got {:?}",
        s3_fp.num_restart
    );

    // S3: endnote decimal (different from S1's lowerRoman and S2's upperRoman)
    let s3_ep = s3.endnote_pr.as_ref().expect("S3 should have endnote_pr");
    assert_eq!(
        s3_ep.num_fmt,
        Some(stemma::domain::NumberFormat::Decimal),
        "S3 endnote numFmt should be Decimal, got {:?}",
        s3_ep.num_fmt
    );

    // Verify all three sections have different footnote numFmt
    let s2_fp = s2.footnote_pr.as_ref().unwrap();
    assert_ne!(
        s2_fp.num_fmt, s3_fp.num_fmt,
        "S2 and S3 should have different footnote numFmt"
    );
}

/// ECMA-376 §17.11.3: Continuous section inheritance does NOT collapse
/// footnote/endnote properties. These are section-specific settings,
/// not page-level properties that get inherited via
/// `propagate_continuous_section_properties`.
///
/// Even though S2 and S3 are continuous, they each retain their own
/// footnote_pr and endnote_pr — the inheritance mechanism only applies
/// to page-level properties (margins, page size, orientation).
#[test]
fn spec_footnote_properties_not_collapsed_by_inheritance() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mixed-footnote-settings");

    let section_props = section_paragraphs(&doc);

    // Collect all footnote numFmt values across sections
    let s1_fmt = section_props[0]
        .footnote_pr
        .as_ref()
        .and_then(|fp| fp.num_fmt.clone());
    let s2_fmt = section_props[1]
        .footnote_pr
        .as_ref()
        .and_then(|fp| fp.num_fmt.clone());
    let s3_fmt = doc
        .body_section_properties
        .as_ref()
        .and_then(|sp| sp.footnote_pr.as_ref())
        .and_then(|fp| fp.num_fmt.clone());

    // All three should be distinct
    assert_eq!(
        s1_fmt,
        Some(stemma::domain::NumberFormat::Decimal),
        "S1 footnote numFmt"
    );
    assert_eq!(
        s2_fmt,
        Some(stemma::domain::NumberFormat::LowerRoman),
        "S2 footnote numFmt"
    );
    assert_eq!(
        s3_fmt,
        Some(stemma::domain::NumberFormat::UpperLetter),
        "S3 footnote numFmt"
    );

    // Similarly for endnote numFmt
    let s1_end_fmt = section_props[0]
        .endnote_pr
        .as_ref()
        .and_then(|ep| ep.num_fmt.clone());
    let s2_end_fmt = section_props[1]
        .endnote_pr
        .as_ref()
        .and_then(|ep| ep.num_fmt.clone());
    let s3_end_fmt = doc
        .body_section_properties
        .as_ref()
        .and_then(|sp| sp.endnote_pr.as_ref())
        .and_then(|ep| ep.num_fmt.clone());

    assert_eq!(
        s1_end_fmt,
        Some(stemma::domain::NumberFormat::LowerRoman),
        "S1 endnote numFmt"
    );
    assert_eq!(
        s2_end_fmt,
        Some(stemma::domain::NumberFormat::UpperRoman),
        "S2 endnote numFmt"
    );
    assert_eq!(
        s3_end_fmt,
        Some(stemma::domain::NumberFormat::Decimal),
        "S3 endnote numFmt"
    );
}
