//! Spec-compliance tests: Annotation and tracked change behavioral constraints
//! (ISO 29500-1 §17.11.2, §17.16.2, §17.13.4)
//!
//! These tests verify cross-validation and balancing constraints:
//!   - Footnote reference integrity: footnoteReference must have matching FootnoteStory
//!   - Field code balance: complex fields must be properly balanced (begin/separate/end)
//!   - Comment referential integrity: comment range/reference must have matching CommentStory
//!
//! Tests marked `#[ignore]` document known gaps — they encode the *correct* spec
//! behavior and are expected to fail against the current implementation.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/create_annotation_constraints.py`.

use stemma::{BlockNode, FieldData, FieldKind, InlineNode, NoteType, OpaqueKind};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/annotation-constraints";

// ── helpers ──────────────────────────────────────────────────────────────

/// Collect all FieldData from OpaqueInline nodes in a paragraph.
fn collect_field_opaques(para: &stemma::ParagraphNode) -> Vec<&FieldData> {
    let mut fields = Vec::new();
    for inline in para.all_inlines() {
        if let InlineNode::OpaqueInline(opaque) = inline
            && let OpaqueKind::Field(ref fd) = opaque.kind
        {
            fields.push(fd);
        }
    }
    fields
}

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[stemma::TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

// =========================================================================
// FOOTNOTE REFERENCE INTEGRITY (§17.11.2, §17.3.3.9)
// =========================================================================

/// ISO 29500-1 §17.11.2: A footnoteReference in the body must link to a
/// FootnoteStory with the same ID.
///
/// Happy path: the fixture has footnoteReference(id=1) in the body and a
/// matching footnote(id=1) in footnotes.xml. Both should be present in
/// the parsed CanonDoc.
#[test]
fn spec_footnote_reference_has_matching_story() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "footnote-ref-integrity");

    // (a) Body should contain a FootnoteReference with reference_id="1"
    let paras = common::all_paragraphs(&doc);
    assert!(!paras.is_empty(), "should have at least one paragraph");

    let footnote_ref_id = paras.iter().find_map(|p| {
        p.all_inlines().find_map(|inline| {
            if let InlineNode::OpaqueInline(oi) = inline
                && let OpaqueKind::FootnoteReference(ref_data) = &oi.kind
            {
                return Some(ref_data.reference_id.clone());
            }
            None
        })
    });

    assert_eq!(
        footnote_ref_id.as_deref(),
        Some("1"),
        "body should contain a FootnoteReference opaque with reference_id=\"1\""
    );

    // (b) CanonDoc.footnotes should contain a FootnoteStory with id="1"
    let fn1 = doc.footnotes.iter().find(|fn_| fn_.id == "1");
    assert!(
        fn1.is_some(),
        "CanonDoc.footnotes should contain FootnoteStory with id=\"1\", \
         got ids: {:?}",
        doc.footnotes.iter().map(|n| &n.id).collect::<Vec<_>>()
    );

    let fn1 = fn1.unwrap();
    assert_eq!(
        fn1.note_type,
        NoteType::Normal,
        "footnote id=1 should be NoteType::Normal"
    );

    let text = blocks_text(&fn1.blocks);
    assert!(
        text.contains("This is the footnote"),
        "footnote content should contain 'This is the footnote', got: '{}'",
        text
    );
}

/// ISO 29500-1 §17.11.2: A footnoteReference with id="999" that has no
/// matching footnote in footnotes.xml should be detected as an error.
///
/// This cross-validation is not currently implemented — the system silently
/// imports orphaned references. Once implemented, this test should verify
/// that import fails or flags the orphaned reference.
#[test]
fn spec_footnote_orphaned_reference_detected() {
    // Conceptual: if a footnoteReference had id="999" with no matching
    // footnote story, the system should fail-fast during import.
    //
    // This test is ignored because cross-validation of footnote reference
    // integrity is not yet implemented. When it is, construct a fixture
    // with an orphaned reference and assert that import returns an error.
    // TODO: construct fixture with orphaned reference and assert import error
}

// =========================================================================
// FIELD CODE BALANCE (§17.16.2)
// =========================================================================

/// ISO 29500-1 §17.16.2: A properly balanced complex field produces
/// fldChar opaques in order: Begin, Instruction, Separate, End.
///
/// The fixture has: fldChar(begin) -> instrText("DATE") -> fldChar(separate)
/// -> result text -> fldChar(end). All four field-related opaques should
/// appear in the correct order.
#[test]
fn spec_field_begin_separate_end_balanced() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "field-balance");

    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "should have at least 2 paragraphs (field paragraph + normal text), got {}",
        paras.len()
    );

    // The first paragraph contains the complex field
    let fields = collect_field_opaques(paras[0]);

    assert!(
        !fields.is_empty(),
        "first paragraph should contain Field opaques for the complex field. \
         Inlines: {:?}",
        paras[0]
            .all_inlines()
            .map(|i| format!("{:?}", std::mem::discriminant(i)))
            .collect::<Vec<_>>()
    );

    let has_begin = fields.iter().any(|fd| fd.field_kind == FieldKind::Begin);
    let has_separate = fields.iter().any(|fd| fd.field_kind == FieldKind::Separate);
    let has_end = fields.iter().any(|fd| fd.field_kind == FieldKind::End);

    assert!(
        has_begin,
        "complex field should have FieldKind::Begin. Found kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
    assert!(
        has_separate,
        "complex field should have FieldKind::Separate. Found kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
    assert!(
        has_end,
        "complex field should have FieldKind::End. Found kinds: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );

    // Verify ordering: Begin must come before Separate, Separate before End
    let kind_sequence: Vec<&FieldKind> = fields.iter().map(|fd| &fd.field_kind).collect();
    let begin_pos = kind_sequence
        .iter()
        .position(|k| **k == FieldKind::Begin)
        .expect("Begin should exist");
    let separate_pos = kind_sequence
        .iter()
        .position(|k| **k == FieldKind::Separate)
        .expect("Separate should exist");
    let end_pos = kind_sequence
        .iter()
        .position(|k| **k == FieldKind::End)
        .expect("End should exist");

    assert!(
        begin_pos < separate_pos,
        "Begin (pos {}) should come before Separate (pos {})",
        begin_pos,
        separate_pos
    );
    assert!(
        separate_pos < end_pos,
        "Separate (pos {}) should come before End (pos {})",
        separate_pos,
        end_pos
    );
}

/// ISO 29500-1 §17.16.18: An unbalanced field (Begin with no matching End)
/// should be handled by graceful degradation — treating the runs as literal
/// text — not by rejecting the import.
///
/// Per §17.16.18, when a complex field is not properly balanced, a conforming
/// consumer treats the content as literal run content rather than field
/// instructions. This is not an import error; it is specified fallback behavior.
///
/// This graceful degradation is not currently implemented — unbalanced fields
/// are silently accepted as-is. Once implemented, this test should verify that
/// runs within unbalanced field markers are treated as literal text.
#[test]
fn spec_field_balance_validated_on_import() {
    // Conceptual: a complex field with fldChar(begin) but no fldChar(end)
    // should degrade gracefully — the runs should be treated as literal text
    // content, not as field instructions.
    //
    // This test is ignored because field balance graceful degradation is not
    // yet implemented. When it is, construct a fixture with an unbalanced
    // field and assert that the runs are preserved as literal text.
    // TODO: construct fixture with unbalanced field and assert literal text degradation
}

// =========================================================================
// COMMENT REFERENTIAL INTEGRITY (§17.13.4)
// =========================================================================

/// ISO 29500-1 §17.13.4.2/3: commentRangeStart and commentRangeEnd markers
/// with id="1" should be present in the body, along with a commentReference
/// with id="1".
///
/// Happy path: the fixture has all three inline markers for comment id=1.
#[test]
fn spec_comment_range_has_matching_reference() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "comment-ref-integrity");

    let paras = common::all_paragraphs(&doc);
    assert!(!paras.is_empty(), "should have at least one paragraph");

    let all_inlines: Vec<&InlineNode> = paras.iter().flat_map(|p| p.all_inlines()).collect();

    let has_range_start = all_inlines
        .iter()
        .any(|i| matches!(i, InlineNode::CommentRangeStart { id } if id == "1"));
    let has_range_end = all_inlines
        .iter()
        .any(|i| matches!(i, InlineNode::CommentRangeEnd { id } if id == "1"));
    let has_reference = all_inlines
        .iter()
        .any(|i| matches!(i, InlineNode::CommentReference { id } if id == "1"));

    // CommentReference may also be stored as an OpaqueInline with
    // OpaqueKind::CommentReference — check that form too.
    let has_opaque_reference = all_inlines.iter().any(|i| match i {
        InlineNode::OpaqueInline(o) => matches!(
            &o.kind,
            OpaqueKind::CommentReference(ref_data) if ref_data.reference_id == "1"
        ),
        _ => false,
    });

    // Also check for Decoration-based representation (alternative encoding)
    let has_decoration_range = all_inlines.iter().any(
        |i| matches!(i, InlineNode::Decoration(d) if d.kind == stemma::DecorationType::CommentRange),
    );

    assert!(
        has_range_start || has_decoration_range,
        "body should contain CommentRangeStart{{id: \"1\"}} or CommentRange decoration. \
         Found inline discriminants: {:?}",
        all_inlines
            .iter()
            .map(|i| format!("{:?}", std::mem::discriminant(*i)))
            .collect::<Vec<_>>()
    );

    assert!(
        has_range_end || has_decoration_range,
        "body should contain CommentRangeEnd{{id: \"1\"}} or CommentRange decoration. \
         Found inline discriminants: {:?}",
        all_inlines
            .iter()
            .map(|i| format!("{:?}", std::mem::discriminant(*i)))
            .collect::<Vec<_>>()
    );

    assert!(
        has_reference || has_opaque_reference,
        "body should contain CommentReference{{id: \"1\"}} (either as InlineNode::CommentReference \
         or OpaqueInline with OpaqueKind::CommentReference). \
         Found inlines: {:?}",
        all_inlines
    );
}

/// ISO 29500-1 §17.13.4.2: The comment story for id="1" should exist in
/// CanonDoc.comments with the correct author and content.
///
/// Happy path: the fixture has a matching comment in comments.xml.
#[test]
fn spec_comment_reference_has_matching_story() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "comment-ref-integrity");

    assert!(
        !doc.comments.is_empty(),
        "CanonDoc.comments should not be empty — fixture has one comment"
    );

    let comment = doc
        .comments
        .iter()
        .find(|c| c.id == "1")
        .expect("should find CommentStory with id=\"1\"");

    assert_eq!(
        comment.author.as_deref(),
        Some("Test"),
        "comment author should be 'Test'"
    );

    // Verify the comment has content
    assert!(
        !comment.blocks.is_empty(),
        "comment should have at least one block of content"
    );

    let text = blocks_text(&comment.blocks);
    assert!(
        text.contains("My comment"),
        "comment text should contain 'My comment', got: '{}'",
        text
    );
}

/// ISO 29500-1 §17.13.4.5: A commentReference with NO range markers
/// (no commentRangeStart/End) is actually valid — per §17.13.4.5, the
/// comment anchors at the commentReference location itself.
///
/// The case that IS non-conformant is when exactly ONE of
/// commentRangeStart/End is present without the other — that is an
/// unpaired range marker and should be flagged as a structural error.
///
/// This cross-validation is not currently implemented — unpaired range
/// markers are silently accepted. Once implemented, this test should
/// verify that a lone commentRangeStart (without a matching
/// commentRangeEnd) is detected as non-conformant.
#[test]
fn spec_comment_reference_without_range_detected() {
    // Conceptual: a commentReference(id="1") with NO commentRangeStart/End
    // is valid per §17.13.4.5 — the comment anchors at the reference point.
    //
    // However, if exactly ONE of commentRangeStart/End is present without
    // its counterpart, that is non-conformant and should be flagged.
    //
    // This test is ignored because cross-validation of unpaired range
    // markers is not yet implemented. When it is, construct a fixture
    // with a lone commentRangeStart (no matching End) and assert that
    // the structural error is detected.
    // TODO: construct fixture with unpaired commentRangeStart and assert detection
}
