//! Spec-compliance tests: Fields Deep (ISO 29500-1 §17.16, §17.3.3)
//!
//! These tests audit additional field types (PAGE, DATE, SEQ, STYLEREF,
//! nested complex fields) and special inline content (w:sym, w:noBreakHyphen,
//! w:softHyphen, w:cr, w:lastRenderedPageBreak).
//!
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use stemma::{CanonDoc, FieldData, FieldKind, InlineNode, OpaqueKind};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/fields-deep";

// -- helpers ----------------------------------------------------------------
/// Collect all FieldData from OpaqueInline nodes in a paragraph's segments.
fn collect_field_opaques(para: &stemma::ParagraphNode) -> Vec<&FieldData> {
    let mut fields = Vec::new();
    for inline in para.all_inlines() {
        if let InlineNode::OpaqueInline(opaque) = inline
            && let OpaqueKind::Field(ref fd) = opaque.kind
        {
            fields.push(fd);
        }
    }
    fields
}

/// Collect all FieldData across all paragraphs.
fn collect_all_fields(doc: &CanonDoc) -> Vec<&FieldData> {
    let mut fields = Vec::new();
    for para in common::all_paragraphs(doc) {
        fields.extend(collect_field_opaques(para));
    }
    fields
}

// -- PAGE / NUMPAGES field tests --------------------------------------------

/// ISO 29500-1 §17.16.19: PAGE field in fldSimple should be captured.
///
/// PAGE is the most common field in real documents (headers/footers).
/// It should produce a FieldKind::Simple with instruction containing "PAGE".
#[test]
fn spec_page_field_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "page-number-field");

    let fields = collect_all_fields(&doc);
    let page_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("PAGE") && !t.contains("NUMPAGES"))
        })
        .collect();

    assert!(
        !page_fields.is_empty(),
        "should find at least one PAGE field. All fields: {:?}",
        fields
    );

    let fd = page_fields[0];
    assert_eq!(fd.field_kind, FieldKind::Simple);
    assert!(
        fd.result_text.as_deref().is_some(),
        "PAGE field should have result_text (cached page number)"
    );
}

/// ISO 29500-1 §17.16.19: NUMPAGES field should also be captured alongside PAGE.
#[test]
fn spec_numpages_field_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "page-number-field");

    let fields = collect_all_fields(&doc);
    let numpages_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("NUMPAGES"))
        })
        .collect();

    assert!(
        !numpages_fields.is_empty(),
        "should find at least one NUMPAGES field. All fields: {:?}",
        fields
    );
}

// -- DATE field tests -------------------------------------------------------

/// ISO 29500-1 §17.16.5.13: DATE field should be preserved with instruction text.
///
/// The instruction text should contain "DATE" and the format switch.
#[test]
fn spec_date_field_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "date-field");

    let fields = collect_all_fields(&doc);
    let date_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("DATE"))
        })
        .collect();

    assert!(
        !date_fields.is_empty(),
        "should find a DATE field. All fields: {:?}",
        fields
    );

    let fd = date_fields[0];
    let instr = fd.instruction_text.as_deref().unwrap();
    assert!(
        instr.contains("yyyy"),
        "DATE field instruction should contain format switch, got: {instr:?}"
    );
}

/// ISO 29500-1 §17.16.5.13: DATE field should have cached result text.
#[test]
fn spec_date_field_result_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "date-field");

    let fields = collect_all_fields(&doc);
    let date_field = fields
        .iter()
        .find(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("DATE"))
        })
        .expect("should find a DATE field");

    let result = date_field
        .result_text
        .as_deref()
        .expect("DATE field should have result_text with cached date value");
    assert!(
        result.contains("2025"),
        "result text should contain '2025', got: {result:?}"
    );
}

// -- SEQ field tests --------------------------------------------------------

/// ISO 29500-1 §17.16.5.56: SEQ fields should be captured with instruction text.
///
/// Two SEQ fields in separate paragraphs should each produce FieldKind::Simple.
#[test]
fn spec_seq_field_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "seq-field");

    let fields = collect_all_fields(&doc);
    let seq_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("SEQ"))
        })
        .collect();

    assert!(
        seq_fields.len() >= 2,
        "should find at least 2 SEQ fields (Figure 1 and Figure 2), got {}. All fields: {:?}",
        seq_fields.len(),
        fields
    );
}

/// ISO 29500-1 §17.16.5.56: SEQ fields should have sequential result values.
#[test]
fn spec_seq_field_result_values() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "seq-field");

    let fields = collect_all_fields(&doc);
    let seq_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("SEQ"))
        })
        .collect();

    assert!(seq_fields.len() >= 2, "need at least 2 SEQ fields");

    let r1 = seq_fields[0]
        .result_text
        .as_deref()
        .expect("first SEQ should have result_text");
    let r2 = seq_fields[1]
        .result_text
        .as_deref()
        .expect("second SEQ should have result_text");

    assert_eq!(r1, "1", "first SEQ result should be '1', got {r1:?}");
    assert_eq!(r2, "2", "second SEQ result should be '2', got {r2:?}");
}

// -- nested complex field tests ---------------------------------------------

/// ISO 29500-1 §17.16.18: Nested fields should maintain begin/end structure.
///
/// An IF field containing a REF field should produce fldChar opaques for
/// both the outer and inner field boundaries.
#[test]
fn spec_nested_field_structure() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "complex-field-nested");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    // Count begin and end markers — nested fields produce 2 of each
    let begin_count = fields
        .iter()
        .filter(|fd| fd.field_kind == FieldKind::Begin)
        .count();
    let end_count = fields
        .iter()
        .filter(|fd| fd.field_kind == FieldKind::End)
        .count();

    assert!(
        begin_count >= 2,
        "nested fields should produce at least 2 Begin markers, got {begin_count}. Fields: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
    assert!(
        end_count >= 2,
        "nested fields should produce at least 2 End markers, got {end_count}. Fields: {:?}",
        fields.iter().map(|fd| &fd.field_kind).collect::<Vec<_>>()
    );
}

/// ISO 29500-1 §17.16.18: Both instruction texts from nested fields should be captured.
///
/// The outer IF instruction and inner REF instruction should both appear.
#[test]
fn spec_nested_field_instructions() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "complex-field-nested");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");
    let fields = collect_field_opaques(para);

    let instructions: Vec<&str> = fields
        .iter()
        .filter(|fd| fd.field_kind == FieldKind::Instruction)
        .filter_map(|fd| fd.instruction_text.as_deref())
        .collect();

    let has_if = instructions.iter().any(|t| t.contains("IF"));
    let has_ref = instructions.iter().any(|t| t.contains("REF"));

    assert!(
        has_if,
        "should find IF instruction text. Instructions: {instructions:?}"
    );
    assert!(
        has_ref,
        "should find REF instruction text. Instructions: {instructions:?}"
    );
}

// -- STYLEREF field tests ---------------------------------------------------

/// ISO 29500-1 §17.16.5.59: STYLEREF field should be captured with instruction text.
#[test]
fn spec_styleref_field_preserved() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "styleref-field");

    let fields = collect_all_fields(&doc);
    let styleref_fields: Vec<&&FieldData> = fields
        .iter()
        .filter(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("STYLEREF"))
        })
        .collect();

    assert!(
        !styleref_fields.is_empty(),
        "should find a STYLEREF field. All fields: {:?}",
        fields
    );

    let fd = styleref_fields[0];
    let instr = fd.instruction_text.as_deref().unwrap();
    assert!(
        instr.contains("Heading"),
        "STYLEREF instruction should reference a heading style, got: {instr:?}"
    );
}

/// ISO 29500-1 §17.16.5.59: STYLEREF field should capture result text.
#[test]
fn spec_styleref_field_result_text() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "styleref-field");

    let fields = collect_all_fields(&doc);
    let styleref_field = fields
        .iter()
        .find(|fd| {
            fd.field_kind == FieldKind::Simple
                && fd
                    .instruction_text
                    .as_deref()
                    .is_some_and(|t| t.contains("STYLEREF"))
        })
        .expect("should find a STYLEREF field");

    let result = styleref_field
        .result_text
        .as_deref()
        .expect("STYLEREF field should have result_text with the heading text");
    assert!(
        result.contains("Chapter One Title"),
        "result text should contain heading text, got: {result:?}"
    );
}

// -- field display + instruction co-existence tests -------------------------

/// ISO 29500-1 §17.16.19: Both display text and instruction text should be
/// available on a fldSimple field.
#[test]
fn spec_field_display_text_and_instruction() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "date-field");

    let fields = collect_all_fields(&doc);
    let fd = fields
        .iter()
        .find(|fd| fd.field_kind == FieldKind::Simple)
        .expect("should find at least one Simple field");

    assert!(
        fd.instruction_text.is_some(),
        "fldSimple should have instruction_text"
    );
    assert!(
        fd.result_text.is_some(),
        "fldSimple should have result_text"
    );
}

// -- special character tests ------------------------------------------------

/// ISO 29500-1 §17.3.3.30: w:sym should produce an OpaqueInline with Sym variant.
///
/// The sym element represents a symbol character from a specific font. It is
/// classified as a run widget and promoted to OpaqueKind::Sym with decoded
/// font/char data.
#[test]
fn spec_special_chars_sym() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "special-characters");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");

    let sym_data = para.all_inlines().find_map(|inline| {
        if let InlineNode::OpaqueInline(opaque) = inline {
            if let OpaqueKind::Sym(data) = &opaque.kind {
                Some(data.clone())
            } else {
                None
            }
        } else {
            None
        }
    });

    let data = sym_data.expect("w:sym should produce an OpaqueInline with OpaqueKind::Sym variant");
    // Verify the sym data was decoded
    assert!(!data.font.is_empty(), "sym font should not be empty");
    assert!(
        !data.char_code.is_empty(),
        "sym char_code should not be empty"
    );
}

/// ISO 29500-1 §17.3.3.18: w:noBreakHyphen should produce an inline node.
///
/// noBreakHyphen is classified as a run decoration in word_ir.rs and becomes
/// an InlineNode::Decoration.
#[test]
fn spec_special_chars_no_break_hyphen() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "special-characters");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");

    let has_decoration = para
        .all_inlines()
        .any(|inline| matches!(inline, InlineNode::Decoration(_)));

    assert!(
        has_decoration,
        "w:noBreakHyphen should produce a Decoration inline node"
    );
}

/// ISO 29500-1 §17.3.3.29: w:softHyphen should produce a Decoration inline node.
#[test]
fn spec_special_chars_soft_hyphen() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "special-characters");

    // The fixture contains both noBreakHyphen and softHyphen as decorations.
    // We verify that at least two decoration nodes exist (noBreakHyphen,
    // softHyphen, and lastRenderedPageBreak = 3 total).
    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");

    let decoration_count = para
        .all_inlines()
        .filter(|inline| matches!(inline, InlineNode::Decoration(_)))
        .count();

    assert!(
        decoration_count >= 2,
        "should have at least 2 Decoration nodes (noBreakHyphen + softHyphen), got {decoration_count}"
    );
}

/// ISO 29500-1 §17.3.3.4: w:cr should produce a HardBreak inline node.
///
/// cr (carriage return) is handled the same as br (line break).
#[test]
fn spec_special_chars_cr() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "special-characters");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");

    let has_break = para
        .all_inlines()
        .any(|inline| matches!(inline, InlineNode::HardBreak(_)));

    assert!(has_break, "w:cr should produce a HardBreak inline node");
}

/// ISO 29500-1 §17.3.3.13: w:lastRenderedPageBreak should produce a Decoration node.
///
/// lastRenderedPageBreak is classified as a run decoration — a zero-width
/// marker indicating where Word last broke the page.
#[test]
fn spec_special_chars_last_rendered_page_break() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "special-characters");

    let paras = common::all_paragraphs(&doc);
    let para = paras.last().expect("should have at least one paragraph");

    // lastRenderedPageBreak and softHyphen are zero-width decorations. noBreakHyphen
    // is NOT a decoration — it is a visible character (§17.3.3.18), modeled as
    // AtomKind::NoBreakHyphen and projected to U+2011 in the read text.
    // So we expect at least 2 decorations plus a U+2011 text character.
    let decoration_count = para
        .all_inlines()
        .filter(|inline| matches!(inline, InlineNode::Decoration(_)))
        .count();
    assert!(
        decoration_count >= 2,
        "should have at least 2 Decoration nodes (softHyphen + lastRenderedPageBreak), got {decoration_count}"
    );

    let has_nbhyphen = para
        .all_inlines()
        .any(|inline| matches!(inline, InlineNode::Text(t) if t.text.contains('\u{2011}')));
    assert!(
        has_nbhyphen,
        "noBreakHyphen must read as a visible U+2011 character (§17.3.3.18), not a zero-width decoration"
    );
}
