//! Spec-compliance tests: Indentation & Spacing Edge Cases (ISO 29500-1 §17.3.1.12, §17.3.1.33)
//!
//! Tests verify correct behavior for indentation and spacing edge cases including
//! hanging indent with tabs, mirror indent, element-level override, and
//! numbering interaction.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/indent-edge-cases";

// ==========================================================================
// Test 1: Hanging indent preserved with tab characters
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: Hanging indent (first_line < 0) with tab
/// characters in body text. Our runtime absorbs first_line into left
/// when tabs are present (so the CSS tab grid starts at the effective
/// first-line edge). This is an intentional rendering optimization.
///
/// Fixture: w:left="1440" w:hanging="720" → first_line=-720.
/// P0 body text contains a tab → tab absorption collapses to
///   left = effective_edge = 1440 + (-720) = 720, first_line = None.
/// P1 no tabs → original values preserved: left=1440, first_line=-720.
///
/// The effective first-line edge (720) is the same in both cases, just
/// represented differently for rendering.
#[test]
fn spec_hanging_indent_preserved_with_tabs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "hanging-with-tabs");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: hanging indent with tabs → tab absorption collapses indent
    // effective_edge = left + first_line = 1440 + (-720) = 720
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent (hanging with tabs)");
    // After tab absorption: left absorbs first_line to become effective_edge
    let effective_edge_0 =
        indent0.left.unwrap_or(0) + indent0.effective_first_line_twips.unwrap_or(0);
    assert_eq!(
        effective_edge_0, 720,
        "P0 effective first-line edge should be 720 (1440 - 720). \
         Tab absorption may represent this as left=720/first_line=None."
    );

    // P1: control — same indent, no tabs → original values preserved
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 should have indent (control)");
    assert_eq!(
        indent1.left,
        Some(1440),
        "P1 left should be 1440 (no tabs, no absorption)"
    );
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(-720),
        "P1 first_line should be -720 (hanging=720, no tab absorption)"
    );

    // Both paragraphs have the same effective edge
    let effective_edge_1 =
        indent1.left.unwrap_or(0) + indent1.effective_first_line_twips.unwrap_or(0);
    assert_eq!(
        effective_edge_0, effective_edge_1,
        "Both paragraphs should have the same effective first-line edge (720)"
    );
}

// ==========================================================================
// Test 2: Mirror indent — w:start / w:end resolve to left / right
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: w:start and w:end are logical-direction
/// equivalents of w:left and w:right. For LTR text (the default),
/// w:start should map to left and w:end should map to right.
///
/// Fixture: P0 uses w:start="720" w:end="360".
///          P1 uses w:left="720" w:right="360" (control).
/// Both should resolve identically.
#[test]
fn spec_mirror_indent_start_end() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "mirror-indent");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: w:start / w:end
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent from w:start/w:end");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 (from w:start=720 for LTR text)"
    );
    assert_eq!(
        indent0.right,
        Some(360),
        "P0 right should be 360 (from w:end=360 for LTR text)"
    );

    // P1: w:left / w:right (control)
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 should have indent from w:left/w:right");
    assert_eq!(
        indent1.left,
        Some(720),
        "P1 left should be 720 (from w:left=720)"
    );
    assert_eq!(
        indent1.right,
        Some(360),
        "P1 right should be 360 (from w:right=360)"
    );
}

// ==========================================================================
// Test 3: Numbering indent partial override — no hanging leak
// ==========================================================================

/// ISO 29500-1 §17.9.22 + §17.3.1.12: When a paragraph has numbering with
/// level indent (left=1440, hanging=360) and direct w:ind with ONLY
/// w:left="720", per-attribute cascade applies: left from direct,
/// firstLine from numbering.
///
/// Result: left=720, first_line=-360 (numbering hanging cascades through).
#[test]
fn spec_numbering_indent_partial_override_no_leak() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "numbering-indent-partial-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: numbering (left=1440, hanging=360) + direct w:ind w:left="720"
    let indent0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 (from direct w:ind)"
    );
    assert_eq!(
        indent0.effective_first_line_twips,
        Some(-360),
        "P0 first_line should be -360 (per §17.3.1.12 per-attribute cascade: \
         absent in direct, inherited from numbering hanging=360)"
    );

    // P1: numbering only (control)
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 should have indent from numbering level");
    assert_eq!(
        indent1.left,
        Some(1440),
        "P1 left should be 1440 (from numbering level)"
    );
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(-360),
        "P1 first_line should be -360 (from numbering level hanging=360)"
    );
}

// ==========================================================================
// Test 4: Spacing per-attribute inheritance
// ==========================================================================

/// ISO 29500-1 §17.3.1.33: When a paragraph has direct w:spacing with
/// only before="0", the style's after and line values should be inherited
/// via per-attribute merge — each attribute inherits independently.
///
/// This matches §17.3.1.12 (ind) which says "overriden on an individual
/// basis". Word produces partial w:spacing in 99.7% of direct formatting
/// cases, so per-attribute inheritance is required for correct resolution.
#[test]
fn spec_spacing_per_attribute_inheritance() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "spacing-element-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: style only (control)
    let spacing0 = paras[0]
        .spacing
        .as_ref()
        .expect("P0 should have spacing from style");
    assert_eq!(
        spacing0.before,
        Some(240),
        "P0 before should be 240 from FullSpacedStyle"
    );
    assert_eq!(
        spacing0.after,
        Some(120),
        "P0 after should be 120 from FullSpacedStyle"
    );
    assert_eq!(
        spacing0.line,
        Some(276),
        "P0 line should be 276 from FullSpacedStyle"
    );

    // P1: direct w:spacing before="0" — per-attribute inheritance
    let spacing1 = paras[1].spacing.as_ref().expect("P1 should have spacing");
    assert_eq!(
        spacing1.before,
        Some(0),
        "P1 before should be 0 (from direct formatting)"
    );
    // Per-attribute (§17.3.1.33): absent after and line inherit from style.
    assert_eq!(
        spacing1.after,
        Some(120),
        "P1 after should inherit 120 from style (per-attribute, §17.3.1.33)"
    );
    assert_eq!(
        spacing1.line,
        Some(276),
        "P1 line should inherit 276 from style (per-attribute, §17.3.1.33)"
    );
}

// ==========================================================================
// Test 5: Explicit zero indent overrides style
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: Explicit w:left="0" is different from absent
/// w:left. When a style defines left=720, a paragraph with explicit
/// w:left="0" should have left=0, not 720.
///
/// This confirms that the parser distinguishes "present but zero" from
/// "absent" for indent attributes.
#[test]
fn spec_explicit_zero_indent_overrides_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "zero-indent-explicit");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P0: style only — should inherit left=720 from style
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent from style");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 from Indented720 style"
    );

    // P1: style + explicit w:left="0" — element-level override
    let indent1 = paras[1].indent.as_ref();
    match indent1 {
        Some(indent) => {
            assert_eq!(
                indent.left,
                Some(0),
                "P1 left should be 0 (explicit w:left='0' overrides style's 720)"
            );
        }
        None => {
            // Also acceptable: None if optimizer collapses all-zero indent
            // But we should at least not see left=720 from style
        }
    }

    // P2: no style, no indent — should have None
    assert!(
        paras[2].indent.is_none(),
        "P2 should have no indent (no style, no direct formatting). Got: {:?}",
        paras[2].indent
    );
}

// ==========================================================================
// Test 6: firstLine and hanging mutual exclusivity
// ==========================================================================

/// ISO 29500-1 §17.3.1.12: w:firstLine and w:hanging are mutually
/// exclusive on a single w:ind element. When both are present in the
/// XML, the spec says "the firstLine value is ignored" — hanging wins.
///
/// This test verifies the spec-mandated precedence: hanging wins over
/// firstLine when both attributes appear on the same w:ind element.
#[test]
fn spec_firstline_and_hanging_mutual_exclusivity() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "firstline-and-hanging-both-present");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P0: both firstLine=360 and hanging=720 — invalid per spec
    // Per §17.3.1.12: "the firstLine value is ignored" → hanging wins.
    let indent0 = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(indent0.left, Some(1440), "P0 left should be 1440");
    // Per §17.3.1.12: "firstLine and hanging are mutually exclusive,
    // if both are specified, then the firstLine value is ignored."
    // hanging=720 → effective_first_line_twips = -720.
    assert_eq!(
        indent0.effective_first_line_twips,
        Some(-720),
        "P0 first_line should be -720 (hanging wins over firstLine when both present). \
         Per §17.3.1.12: 'the firstLine value is ignored'."
    );

    // P1: only firstLine=360 (control)
    let indent1 = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(indent1.left, Some(1440), "P1 left should be 1440");
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(360),
        "P1 first_line should be 360 (firstLine only)"
    );

    // P2: only hanging=720 (control)
    let indent2 = paras[2].indent.as_ref().expect("P2 should have indent");
    assert_eq!(indent2.left, Some(1440), "P2 left should be 1440");
    assert_eq!(
        indent2.effective_first_line_twips,
        Some(-720),
        "P2 first_line should be -720 (hanging=720 → negative)"
    );
}

// ==========================================================================
// Test 7: Numbering tab with structural (auto) numbering
// ==========================================================================

/// ISO 29500-1 §17.9.22 + §17.3.1.21: Auto-numbered paragraph with
/// numbering-level indent (left=720, hanging=360) and a numbering tab
/// stop at pos=720.
///
/// The numbering level indent creates a hanging indent: the number prefix
/// is placed at the first-line edge (720 - 360 = 360 twips from margin),
/// and body text starts at 720 twips.
///
/// The numbering tab stop at 720 should position the cursor after the
/// number prefix to align with the left margin.
#[test]
fn spec_numbering_tab_with_structural_numbering() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "indent-with-numbering-tab");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: auto-numbered paragraph
    let indent0 = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent from numbering level");
    assert_eq!(
        indent0.left,
        Some(720),
        "P0 left should be 720 (from numbering level)"
    );
    assert_eq!(
        indent0.effective_first_line_twips,
        Some(-360),
        "P0 first_line should be -360 (from numbering level hanging=360)"
    );

    // Verify numbering info is present
    let num0 = paras[0]
        .numbering
        .as_ref()
        .expect("P0 should have numbering info");
    assert_eq!(num0.ilvl, 0, "P0 should be at numbering level 0");

    // P1: second auto-numbered paragraph
    let indent1 = paras[1]
        .indent
        .as_ref()
        .expect("P1 should have indent from numbering level");
    assert_eq!(
        indent1.left,
        Some(720),
        "P1 left should be 720 (from numbering level)"
    );
    assert_eq!(
        indent1.effective_first_line_twips,
        Some(-360),
        "P1 first_line should be -360 (from numbering level hanging=360)"
    );

    let num1 = paras[1]
        .numbering
        .as_ref()
        .expect("P1 should have numbering info");
    assert_eq!(num1.ilvl, 0, "P1 should be at numbering level 0");
}
