//! AUTO-GENERATED by the spec-word-compliance workflow.
//!
//! Area: "Property-change revisions: rPrChange, pPrChange, sectPrChange
//! (reject-restore snapshot semantics)".
//!
//! Each `#[test]` encodes a behavioural constraint mined from ECMA-376 /
//! ISO 29500-1 / MS-OI29500 about property-change revisions. A FAILING
//! assertion here is NOT a flaky test to silence: it encodes a real
//! Word-compliance gap in the stemma engine (divergence from how Microsoft
//! Word reads, accepts/rejects, or round-trips property-change revisions).
//! Fix the engine at the source, never weaken the test.
//!
//! Methodology (consumption vs. save):
//! - `reserialize()` of an UNEDITED doc reflects stemma's verbatim-preservation
//!   contract, NOT Word normalization. xmlContains / "xmlRegex" (ordering)
//!   checks on it are valid only for markup the serializer actively generates,
//!   orders, or restructures, and for opens-clean validity.
//! - Word consumption semantics ("reject restores prior") are asserted on the
//!   READ side: read_accepted()/read_rejected().to_text().

use std::io::{Read, Write};

use stemma::ExportOptions;
use stemma::api::Document;

// ─── Prelude: DOCX zip plumbing (mirrors the shared spec-suite prelude) ───

/// Build a valid minimal `.docx`. `body_xml` is wrapped in
/// `<w:document><w:body>…</w:body></w:document>` (the specs supply their own
/// trailing `<w:sectPr/>`). `extra_parts` are additional `(part_path, xml)`
/// entries (e.g. `("word/styles.xml", "…")`) for which a `[Content_Types].xml`
/// override is synthesized.
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{body_xml}</w:body></w:document>"#,
    );

    fn override_for(part: &str) -> Option<&'static str> {
        if part.ends_with("styles.xml") {
            Some("application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml")
        } else if part.ends_with("numbering.xml") {
            Some("application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml")
        } else {
            None
        }
    }

    let mut overrides = String::from(
        r#"<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>"#,
    );
    for (part, _) in extra_parts {
        let part_name = if part.starts_with('/') {
            part.to_string()
        } else {
            format!("/{part}")
        };
        let ct = override_for(part).unwrap_or_else(|| {
            panic!("make_docx: no content-type override known for extra part {part}")
        });
        overrides.push_str(&format!(
            r#"<Override PartName="{part_name}" ContentType="{ct}"/>"#
        ));
    }

    let content_types = format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>{overrides}</Types>"#
    );
    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#;
    let doc_rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>"#;

    use zip::write::FileOptions;
    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (part, xml) in extra_parts {
            zip.start_file(*part, opts).unwrap();
            zip.write_all(xml.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip a `.docx` and return `word/document.xml` as a String.
fn document_xml_of(docx: &[u8]) -> String {
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(docx)).expect("open docx zip");
    let mut file = zip
        .by_name("word/document.xml")
        .expect("word/document.xml present");
    let mut s = String::new();
    file.read_to_string(&mut s).expect("read document.xml");
    s
}

/// Parse → serialize(default) → return the re-serialized `word/document.xml`.
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("parse");
    let out = doc.serialize(&ExportOptions::default()).expect("serialize");
    document_xml_of(&out)
}

/// Collapse whitespace that sits BETWEEN tags (`>   <` → `><`) and normalize
/// self-closing spacing, so an ordered-`contains` check can stand in for an
/// `\s*` ordering regex (the `regex` crate is not a dev-dependency here).
fn norm_xml(xml: &str) -> String {
    let mut out = String::with_capacity(xml.len());
    let bytes = xml.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i] as char;
        if c == '>' {
            out.push('>');
            let mut j = i + 1;
            while j < bytes.len() && (bytes[j] as char).is_whitespace() {
                j += 1;
            }
            i = j;
            continue;
        }
        out.push(c);
        i += 1;
    }
    out.replace(" />", "/>").replace("/ >", "/>")
}

/// Ordered-subsequence check on normalized XML: every needle appears, in order.
fn contains_in_order(haystack_norm: &str, needles: &[&str]) -> Result<(), String> {
    let mut from = 0usize;
    for (idx, n) in needles.iter().enumerate() {
        match haystack_norm[from..].find(n) {
            Some(rel) => from += rel + n.len(),
            None => {
                return Err(format!(
                    "missing (in order) {:?}; matched prefix {:?}",
                    n,
                    &needles[..idx]
                ));
            }
        }
    }
    Ok(())
}

fn assert_opens_clean(bytes: &[u8], msg: &str) {
    let report = stemma::api::validate(bytes);
    assert!(report.ok, "{msg}\n  validate() issues: {:?}", report.issues);
}

fn assert_not_opens_clean(bytes: &[u8], msg: &str) {
    let report = stemma::api::validate(bytes);
    assert!(!report.ok, "{msg}\n  validate() report: ok={}", report.ok);
}

fn accepted_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_accepted()
        .expect("read_accepted")
        .to_text()
        .trim()
        .to_string()
}

fn rejected_text(bytes: &[u8]) -> String {
    Document::parse(bytes)
        .expect("parse")
        .read_rejected()
        .expect("read_rejected")
        .to_text()
        .trim()
        .to_string()
}

// ─── Tests (one per TestSpec, named exactly) ─────────────────────────────────

#[test]
fn para_mark_rprchange_reject_restores_prior_mark_props() {
    // ECMA-376 §17.13.5.30, ISO 29500-1 §17.13.5.30, §17.13.3.
    let body = r#"<w:p><w:pPr><w:rPr><w:b/><w:i/><w:rPrChange w:id="40" w:author="John Doe" w:date="2006-01-01T12:00:00Z"><w:rPr><w:i/></w:rPr></w:rPrChange></w:rPr></w:pPr><w:r><w:t>Example</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "para_mark_rprchange_reject_restores_prior_mark_props — ECMA-376 §17.13.5.30: \
         CT_ParaRPrChange inside pPr/rPr with a complete prior snapshot is schema-valid and must open without repair.",
    );
    assert_eq!(
        accepted_text(&b),
        "Example",
        "para_mark_rprchange_reject_restores_prior_mark_props — ECMA-376 §17.13.3, §17.13.5.30: \
         a paragraph-mark rPrChange is a property annotation carrying no character content; accepted text is unchanged."
    );
    assert_eq!(
        rejected_text(&b),
        "Example",
        "para_mark_rprchange_reject_restores_prior_mark_props — ECMA-376 §17.13.3, §17.13.5.30: \
         mark-only formatting reverts on reject but the run text never changes."
    );
    assert!(
        reserialize(&b).contains("<w:rPrChange"),
        "para_mark_rprchange_reject_restores_prior_mark_props — ECMA-376 §17.13.5.30: \
         verbatim/round-trip preservation must keep the paragraph-mark rPrChange record inside pPr/rPr. \
         Expected XML to contain <w:rPrChange"
    );
}

#[test]
fn rprchange_reject_restores_removed_prior_bold() {
    // ECMA-376 §17.13.5.31, ISO 29500-1 §17.13.5.31, §17.13.3.
    let body = r#"<w:p><w:r><w:rPr><w:rPrChange w:id="41" w:author="John Doe" w:date="2006-01-01T12:00:00Z"><w:rPr><w:b/></w:rPr></w:rPrChange></w:rPr><w:t>Example</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "rprchange_reject_restores_removed_prior_bold — ECMA-376 §17.13.5.31: \
         an rPrChange whose current rPr has only the trailing rPrChange and a non-null prior snapshot is schema-valid (CT_RPrChange).",
    );
    assert_eq!(
        accepted_text(&b),
        "Example",
        "rprchange_reject_restores_removed_prior_bold — ECMA-376 §17.13.3, §17.13.5.31: \
         accepting a run-property revision keeps the current (non-bold) formatting and changes no character content."
    );
    assert_eq!(
        rejected_text(&b),
        "Example",
        "rprchange_reject_restores_removed_prior_bold — ECMA-376 §17.13.3, §17.13.5.31: \
         rejecting restores the prior bold but the run text is unchanged because the annotation carries no characters."
    );
}

#[test]
fn rprchange_records_removed_formatting_reject_restores_italic() {
    // ECMA-376 §17.13.5.31, ISO 29500-1 §17.13.5.31.
    let body = r#"<w:p><w:r><w:rPr><w:rPrChange w:id="7" w:author="A" w:date="2024-01-01T00:00:00Z"><w:rPr><w:i/></w:rPr></w:rPrChange></w:rPr><w:t>Plain</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "rprchange_records_removed_formatting_reject_restores_italic — ECMA-376 §17.13.5.31, §A.1: \
         a run-level rPrChange whose prior snapshot records the removed italic (current rPr empty, prior rPr has w:i) is schema-valid and must open without repair.",
    );
    assert_eq!(
        accepted_text(&b),
        "Plain",
        "rprchange_records_removed_formatting_reject_restores_italic — ECMA-376 §17.13.5.31: \
         accepting a formatting-only rPrChange keeps current props and removes the record; a property annotation carries no character content."
    );
    assert_eq!(
        rejected_text(&b),
        "Plain",
        "rprchange_records_removed_formatting_reject_restores_italic — ECMA-376 §17.13.5.31: \
         rejecting restores the prior italic formatting but does not alter character content; text remains 'Plain'."
    );
}

#[test]
fn rprchange_literal_explicit_toggle_off_in_prior_snapshot_order() {
    // ECMA-376 §17.13.5.31, §A.1 CT_RPr.
    let body = r#"<w:p><w:r><w:rPr><w:b/><w:rPrChange w:id="8" w:author="A" w:date="2024-01-01T00:00:00Z"><w:rPr><w:b w:val="0"/><w:color w:val="FF0000"/></w:rPr></w:rPrChange></w:rPr><w:t>Sample</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "rprchange_literal_explicit_toggle_off_in_prior_snapshot_order — ECMA-376 §17.13.5.31, §A.1 CT_RPr: \
         current w:b precedes w:rPrChange, and the prior snapshot orders w:b before w:color; a schema-correctly ordered rPrChange opens without repair.",
    );
}

#[test]
fn pprchange_null_prior_reject_removes_all_current_ppr_props() {
    // ECMA-376 §17.13.5.29, ISO 29500-1 §17.13.5.29.
    let body = r#"<w:p><w:pPr><w:spacing w:before="240" w:after="240"/><w:jc w:val="center"/><w:pPrChange w:id="9" w:author="A" w:date="2024-01-01T00:00:00Z"><w:pPr/></w:pPrChange></w:pPr><w:r><w:t>Centered</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "pprchange_null_prior_reject_removes_all_current_ppr_props — ECMA-376 §17.13.5.29, §A.1: \
         CT_PPrBase order (spacing before jc) with pPrChange trailing and an empty prior pPr snapshot is schema-valid and must open without repair.",
    );
    assert_eq!(
        accepted_text(&b),
        "Centered",
        "pprchange_null_prior_reject_removes_all_current_ppr_props — ECMA-376 §17.13.5.29: \
         a pPrChange is formatting-only; accept keeps current props and drops the record, leaving text unchanged."
    );
    assert_eq!(
        rejected_text(&b),
        "Centered",
        "pprchange_null_prior_reject_removes_all_current_ppr_props — ECMA-376 §17.13.5.29: \
         rejecting restores the null prior (removing jc and spacing) but does not change character content; text stays 'Centered'."
    );
}

#[test]
fn para_mark_rprchange_multi_toggle_snapshot_order_and_location() {
    // ECMA-376 §17.13.5.30, §A.1 CT_RPr, ISO 29500-1 §17.13.5.30.
    let body = r#"<w:p><w:pPr><w:rPr><w:b/><w:rPrChange w:id="11" w:author="A" w:date="2024-01-01T00:00:00Z"><w:rPr><w:b/><w:i/><w:color w:val="0000FF"/></w:rPr></w:rPrChange></w:rPr></w:pPr><w:r><w:t>Hello</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "para_mark_rprchange_multi_toggle_snapshot_order_and_location — ECMA-376 §17.13.5.30, §A.1 CT_RPr: \
         current w:b precedes the trailing rPrChange inside pPr/rPr, and the prior snapshot orders b->i->color; the mark rPrChange opens without repair.",
    );
    assert_eq!(
        accepted_text(&b),
        "Hello",
        "para_mark_rprchange_multi_toggle_snapshot_order_and_location — ECMA-376 §17.13.5.30: \
         a paragraph-mark property revision carries no character content; accept leaves text unchanged."
    );
    assert_eq!(
        rejected_text(&b),
        "Hello",
        "para_mark_rprchange_multi_toggle_snapshot_order_and_location — ECMA-376 §17.13.5.30: \
         reject restores the prior mark props without altering character content; text stays 'Hello'."
    );
}

#[test]
fn prchange_track_attrs_id_author_preserved_roundtrip() {
    // ECMA-376 §A.1 CT_Markup (id required), CT_TrackChange (author required); ISO 29500-1 §17.13.5.29.
    let body = r#"<w:p><w:pPr><w:jc w:val="center"/><w:pPrChange w:id="9" w:author="John Doe" w:date="2006-01-01T12:00:00Z"><w:pPr/></w:pPrChange></w:pPr><w:r><w:t>Centered</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "prchange_track_attrs_id_author_preserved_roundtrip — ECMA-376 §A.1 CT_Markup/CT_TrackChange: \
         a pPrChange carrying required w:id and w:author is schema-conformant; Word opens without repair so stemma must report no errors.",
    );
    let xml = reserialize(&b);
    assert!(
        xml.contains(r#"w:id="9""#),
        "prchange_track_attrs_id_author_preserved_roundtrip — ECMA-376 §A.1 CT_Markup (id use=required): \
         stemma must preserve the required w:id verbatim across round-trip. Expected XML to contain w:id=\"9\"\n  XML: {xml}"
    );
    assert!(
        xml.contains(r#"w:author="John Doe""#),
        "prchange_track_attrs_id_author_preserved_roundtrip — ECMA-376 §A.1 CT_TrackChange (author use=required): \
         stemma must preserve the required w:author verbatim across round-trip. Expected XML to contain w:author=\"John Doe\"\n  XML: {xml}"
    );
}

#[test]
fn rprchange_serializes_as_trailing_rpr_child_after_edit_reemit() {
    // ECMA-376 §17.13.5.31, §A.1 CT_RPr, ISO 29500-1 §17.13.3.
    // NOTE: the spec gives this as `xmlRegex`. The `regex` crate is not a
    // dev-dependency, so each regex is translated to an ordered-/contains check
    // on whitespace-normalized XML (`norm_xml`), which is equivalent here:
    //   "<w:rPr>\s*<w:b/>\s*<w:rPrChange\b"  -> ordered: <w:rPr> , <w:b/> , <w:rPrChange
    //   "</w:rPrChange>\s*</w:rPr>"          -> contains "</w:rPrChange></w:rPr>"
    let body = r#"<w:p><w:r><w:rPr><w:b/><w:rPrChange w:id="5" w:author="A" w:date="2006-01-01T12:00:00Z"><w:rPr><w:i/></w:rPr></w:rPrChange></w:rPr><w:t>Example</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    let xml = norm_xml(&reserialize(&b));

    contains_in_order(&xml, &["<w:rPr>", "<w:b/>", "<w:rPrChange"]).unwrap_or_else(|e| {
        panic!(
            "rprchange_serializes_as_trailing_rpr_child_after_edit_reemit — ECMA-376 §17.13.3, §A.1 CT_RPr: \
             current run prop <w:b/> must precede rPrChange inside rPr (rPrChange is the trailing particle). {e}\n  XML: {xml}"
        )
    });
    assert!(
        xml.contains("</w:rPrChange></w:rPr>"),
        "rprchange_serializes_as_trailing_rpr_child_after_edit_reemit — ECMA-376 §A.1 CT_RPr: \
         rPrChange is the LAST child of rPr; rPr must close immediately after </w:rPrChange>. \
         Expected normalized XML to contain </w:rPrChange></w:rPr>\n  XML: {xml}"
    );
    assert_opens_clean(
        &b,
        "rprchange_serializes_as_trailing_rpr_child_after_edit_reemit — ECMA-376 §17.13.5.31: \
         schema-correct CT_RPr ordering with a complete prior snapshot opens without repair.",
    );
}

#[ignore = "open question: CONFIRMED GAP — validate() reports opens-clean (ok=true) for a pPrChange missing the required w:id; id-required enforcement is limited to w:del/w:ins (I-TC-002), diverging from ECMA-376 §17.13.5.29 id row"]
#[test]
fn pprchange_missing_id_is_nonconformant() {
    // ECMA-376 §17.13.5.29, ISO 29500-1 §17.13.5.29.
    // NEGATIVE post-condition: a pPrChange missing the required w:id should be
    // reported non-conformant. If this assertion FAILS (opens-clean passes),
    // that exposes the validator gap (I-TC-002 covers only del/ins) — the gap
    // we are hunting.
    let body = r#"<w:p><w:pPr><w:jc w:val="center"/><w:pPrChange w:author="John Doe" w:date="2006-01-01T12:00:00Z"><w:pPr/></w:pPrChange></w:pPr><w:r><w:t>Centered</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);

    assert_not_opens_clean(
        &b,
        "pprchange_missing_id_is_nonconformant — ECMA-376 §17.13.5.29 (id row: 'If this attribute is omitted, then the document is non-conformant'): \
         a pPrChange missing the required w:id must be reported non-conformant, not opens-clean. opens-clean passing here is the validator gap (I-TC-002 covers only del/ins).",
    );
}

#[ignore = "open question: CONFIRMED GAP — validate() reports opens-clean (ok=true) for a sectPrChange missing the required w:id; same root cause as pPrChange (id-required enforcement limited to w:del/w:ins, I-TC-002 does not cover sectPrChange), diverging from ECMA-376 §17.13.5.32 id row"]
#[test]
fn sectprchange_missing_id_is_nonconformant() {
    // ECMA-376 §17.13.5.32, ISO 29500-1 §17.13.5.32.
    // NEGATIVE post-condition: a sectPrChange missing required w:id should be
    // non-conformant. Failure (opens-clean) exposes that I-TC-002 does not cover
    // sectPrChange.
    let body = r#"<w:p><w:r><w:t>Body</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:sectPrChange w:author="John Doe" w:date="2006-01-01T12:00:00Z"><w:sectPr/></w:sectPrChange></w:sectPr>"#;
    let b = make_docx(body, &[]);

    assert_not_opens_clean(
        &b,
        "sectprchange_missing_id_is_nonconformant — ECMA-376 §17.13.5.32 (id row: 'If this attribute is omitted, then the document is non-conformant'): \
         a sectPrChange missing the required w:id must be reported non-conformant, not opens-clean. opens-clean passing exposes that I-TC-002 does not cover sectPrChange.",
    );
}

#[test]
fn sectprchange_prior_sectpr_word_delta_semantics() {
    // ECMA-376 §17.13.5.32, MS-OI29500 §2.1.348.
    let body = r#"<w:p><w:r><w:t>Body</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:cols w:num="2"/><w:sectPrChange w:id="10" w:author="A" w:date="2024-01-01T00:00:00Z"><w:sectPr><w:pgSz w:w="15840" w:h="12240"/></w:sectPr></w:sectPrChange></w:sectPr>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "sectprchange_prior_sectpr_word_delta_semantics — ECMA-376 §17.13.5.32, §A.1: \
         a sectPr carrying pgSz, cols, and a trailing sectPrChange with a partial prior sectPr snapshot is schema-valid CT_SectPr/CT_SectPrChange and must open without repair.",
    );
    assert_eq!(
        accepted_text(&b),
        "Body",
        "sectprchange_prior_sectpr_word_delta_semantics — ECMA-376 §17.13.5.32: \
         a sectPrChange is formatting-only; accept keeps the current section and drops the record, leaving body text unchanged."
    );
    // reject resolution (Word delta semantics, MS-OI29500 §2.1.348) is an ORACLE
    // question and is intentionally not asserted on the read side here.
}

#[test]
fn sectprchange_prior_sectpr_optional_opens_clean() {
    // ECMA-376 §17.13.5.32, §A.1 CT_SectPrChange (inner sectPr minOccurs=0), ISO 29500-1 §17.13.5.32.
    let body = r#"<w:p><w:r><w:t>Body text.</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:sectPrChange w:id="7" w:author="John Doe" w:date="2006-01-01T12:00:00Z"/></w:sectPr>"#;
    let b = make_docx(body, &[]);

    assert_opens_clean(
        &b,
        "sectprchange_prior_sectpr_optional_opens_clean — ECMA-376 §17.13.5.32, §A.1 CT_SectPrChange: \
         the inner sectPr is minOccurs=0, so a sectPrChange with no prior-sectPr child is schema-valid; Word opens it without repair, so stemma's validator must report no errors.",
    );
}
