//! Spec-compliance tests: Style Toggle Properties & Cascade (ISO 29500-1 §17.7.3)
//!
//! These tests verify toggle property XOR semantics, style cascade resolution,
//! linked style behavior, and doc defaults interactions from the OOXML specification.
//!
//! Key spec references:
//! - §17.7.3: Toggle property XOR semantics across hierarchy levels
//! - §17.7.1: basedOn chain resolution (first-value-encountered for toggles)
//! - §17.7.2: Style hierarchy: docDefaults → table → para → char → direct
//! - §17.7.4.6: Linked style pairs (paragraph + character)
//! - §17.7.4.17: Implicit Normal style for unstyled paragraphs
//! - §17.7.5: docDefaults (rPrDefault/pPrDefault)
//! - MS-OI29500 §2.1.230: Word's toggle behavior with doc defaults
//! - MS-OI29500 §2.1.258: Word resets toggles instead of XORing
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/style-toggle-audit/create_docs.py`.

use stemma::{InlineNode, Mark};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/style-toggle-audit";

// ── helpers ──────────────────────────────────────────────────────────────

fn text_nodes(p: &stemma::ParagraphNode) -> Vec<stemma::TextNode> {
    p.all_inlines_owned()
        .into_iter()
        .filter_map(|i| match i {
            InlineNode::Text(t) => Some(*t),
            _ => None,
        })
        .collect()
}

// ═══════════════════════════════════════════════════════════════════════════
// 1. Toggle XOR between paragraph style and character style (§17.7.3)
//
// ECMA-376 §17.7.3 says: when toggle properties appear at multiple levels
// of the style hierarchy, they are combined with XOR.
// MS-OI29500 §2.1.258 says: Word RESETS the toggle to the value specified
// by the paragraph style (simple override, not XOR).
//
// Our implementation does XOR (resolve_toggle_mark), which follows ECMA
// but diverges from Word.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3: Para style bold=on + char style bold=on.
/// ECMA spec: XOR → on ^ on = off.
/// Word behavior (MS-OI29500 §2.1.258): bold=on (reset, not XOR).
///
/// This test asserts Word-compatible behavior (bold=ON). Our XOR-based
/// resolve_toggle_mark produces bold=OFF, which is a behavioral violation
/// for Word-compatibility but follows the ECMA-376 letter.
#[test]
fn toggle_xor_para_char_both_bold_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-xor-para-char");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Both para and char bold"))
        .expect("should find paragraph with both styles");

    let nodes = text_nodes(p);
    assert!(!nodes.is_empty(), "paragraph should have text nodes");
    let run = &nodes[0];

    // Word behavior: bold=on (reset semantics per MS-OI29500 §2.1.258).
    // Our current ECMA-spec XOR produces bold=off (on ^ on = off).
    // This test documents the Word-compatible expectation.
    assert!(
        run.marks.contains(&Mark::Bold),
        "para style bold=on + char style bold=on should produce bold=ON \
         (Word resets toggle per MS-OI29500 §2.1.258). Our XOR implementation \
         produces bold=OFF which diverges from Word behavior."
    );
}

/// §17.7.3: Para style bold=on with no char style → bold=on (no XOR needed).
#[test]
fn toggle_xor_para_bold_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-xor-para-char");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Para bold only"))
        .expect("should find paragraph with para bold only");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Only paragraph style sets bold, no char style → bold=on (no XOR).
    assert!(
        run.marks.contains(&Mark::Bold),
        "para style bold=on with no char style should produce bold=ON. \
         Only one hierarchy level sets the toggle, so no XOR applies."
    );
}

/// §17.7.3: Char style bold=on with no para style → bold=on.
#[test]
fn toggle_xor_char_bold_only() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-xor-para-char");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Char bold only"))
        .expect("should find paragraph with char bold only");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "char style bold=on with no para style should produce bold=ON. \
         Only one hierarchy level sets the toggle."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 2. Doc defaults bold=on + style bold=off (§17.7.3 + MS-OI29500 §2.1.230)
//
// ECMA §17.7.3: "If the value specified by the document defaults is true,
// the effective value is true." — This means doc defaults on = ALWAYS on.
// MS-OI29500 §2.1.230a: Word's behavior differs — the effective value is
// true only if false for an even number of levels.
//
// Our code shortcuts: if doc_default is On, return On immediately.
// This matches the ECMA letter but prevents styles from turning off bold.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3 + MS-OI29500 §2.1.230: docDefaults bold=on, para style bold=off.
/// The para style explicitly says "not bold" — this should be honored.
///
/// Our shortcut (doc_default On → always On) prevents the style's bold=off
/// from taking effect. This is a behavioral violation against both Word
/// and reasonable user expectations.
#[test]
fn toggle_doc_defaults_on_style_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-doc-defaults-on");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Explicitly not bold"))
        .expect("should find paragraph with StyleNoBold");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Word behavior: the paragraph style's bold=off should win.
    // MS-OI29500 §2.1.230a: Word determines effective value based on
    // even/odd count of levels setting the property.
    // Para style says off → effective is off.
    assert!(
        !run.marks.contains(&Mark::Bold),
        "docDefaults bold=on + para style bold=off should produce bold=OFF. \
         The paragraph style explicitly disables bold. MS-OI29500 §2.1.230a \
         says Word does not unconditionally force doc defaults on. \
         Our shortcut (doc_default On → always On) is wrong here."
    );
}

/// §17.7.5: docDefaults bold=on should apply to unstyled paragraphs.
#[test]
fn toggle_doc_defaults_on_unstyled() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-doc-defaults-on");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Doc defaults bold"))
        .expect("should find unstyled paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    // No style overrides → doc defaults bold=on applies.
    assert!(
        run.marks.contains(&Mark::Bold),
        "unstyled paragraph with docDefaults bold=on should be bold. \
         docDefaults provides base formatting per §17.7.5."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 3. Linked style missing properties (§17.7.4.6)
//
// When a paragraph style (HeadingPara) has w:link to a character style
// (HeadingChar), runs inherit from the linked character style. But if the
// linked char style doesn't set font_size and the para style does, the
// font_size should still be available (from the para style's own rPr).
//
// Our implementation replaces the para style's resolved marks entirely
// with the linked char style's marks, losing properties the char style
// doesn't set.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.6: Linked char style has bold but no font_size. The paragraph
/// style has both bold and font_size=32. Runs should get font_size=32.
///
/// Bug: Our code replaces para_styles[HeadingPara] entirely with
/// char_styles[HeadingChar], which doesn't have font_size. The font_size
/// from HeadingPara's own rPr is lost.
#[test]
fn linked_style_preserves_para_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-style-missing-props");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Heading with linked style"))
        .expect("should find paragraph with HeadingPara style");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    // The paragraph style HeadingPara has sz=32 in its rPr.
    // The linked char style HeadingChar has bold but NO sz.
    // The run should get font_size=32 from HeadingPara.
    assert_eq!(
        run.style_props.font_size,
        Some(32),
        "paragraph with HeadingPara (linked to HeadingChar) should get \
         font_size=32 from HeadingPara's rPr. The linked char style has no \
         sz, so the para style's own font_size should be used. \
         Bug: linked style replacement drops unset properties."
    );
}

/// §17.7.4.6: Run with linked char style applied directly should get bold.
#[test]
fn linked_style_char_applied_directly() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "linked-style-missing-props");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Run with HeadingChar"))
        .expect("should find paragraph with HeadingChar applied");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "run with HeadingChar char style should be bold. \
         HeadingChar sets bold=on in its rPr."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 4. 3-level basedOn chain: first-value-encountered (§17.7.3)
//
// Within a single hierarchy level, the spec says the "first value
// encountered" walking up the basedOn chain is used. This is NOT XOR —
// it's simple child-wins-over-parent.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3: StyleLeaf (bold=on) → StyleMid (bold=off) → StyleRoot (bold=on).
/// First value encountered from StyleLeaf is bold=on (leaf itself).
#[test]
fn toggle_3level_leaf_bold_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-3level-basedOn");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Leaf style run"))
        .expect("should find leaf style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "StyleLeaf sets bold=on — this is the first value encountered \
         in the basedOn chain, so bold should be ON. Per §17.7.3, within \
         a single hierarchy level, the child's value wins."
    );
}

/// §17.7.3: StyleMid (bold=off) → StyleRoot (bold=on).
/// First value encountered from StyleMid is bold=off (mid itself).
#[test]
fn toggle_3level_mid_bold_off() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-3level-basedOn");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Mid style run"))
        .expect("should find mid style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "StyleMid sets bold=off explicitly — this is the first value \
         encountered in the basedOn chain. Per §17.7.3, the resolved \
         value for this level should be bold=OFF."
    );
}

/// §17.7.3: StyleRoot (bold=on). First value is root's own.
#[test]
fn toggle_3level_root_bold_on() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-3level-basedOn");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Root style run"))
        .expect("should find root style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "StyleRoot sets bold=on — direct on the style itself. \
         Should resolve to bold=ON."
    );
}

/// §17.7.1: Italic set at root level should inherit through the chain.
/// StyleMid and StyleLeaf don't set italic, so it persists from StyleRoot.
#[test]
fn toggle_3level_italic_inherited_from_root() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-3level-basedOn");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Leaf style run"))
        .expect("should find leaf style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Italic),
        "StyleRoot sets italic=on. StyleMid and StyleLeaf don't override it. \
         Italic should inherit through the basedOn chain per §17.7.1."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 5. Direct formatting overrides toggle properties (§17.7.3)
//
// "If a toggle property is explicitly set in direct formatting applied to
// a given piece of content, then its value in the direct formatting shall
// be used." — Direct is NOT XOR'd.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3: Direct bold=off overrides para + char style bold=on.
#[test]
fn toggle_direct_off_overrides_styles() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-direct-override");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Direct bold off"))
        .expect("should find direct-off paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "direct bold=off should override para style bold=on + char style bold=on. \
         Per §17.7.3: 'If a toggle property is explicitly set in direct formatting, \
         then its value in the direct formatting shall be used.'"
    );
}

/// §17.7.3: Direct bold=on is also direct (not XOR'd), just happens to match.
#[test]
fn toggle_direct_on_overrides_styles() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-direct-override");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Direct bold on"))
        .expect("should find direct-on paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        run.marks.contains(&Mark::Bold),
        "direct bold=on should produce bold=ON (direct wins per §17.7.3)."
    );
}

/// §17.7.3: Direct bold=off with para style only (no char style).
#[test]
fn toggle_direct_off_no_char_style() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-direct-override");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Direct off no char"))
        .expect("should find direct-off-no-char paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert!(
        !run.marks.contains(&Mark::Bold),
        "direct bold=off should override para style bold=on even without \
         a char style. Per §17.7.3, direct formatting always wins."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 6. Non-toggle property per-field override through deep chain (§17.7.1)
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.1: GrandchildStyle (basedOn ChildStyle basedOn BaseStyle).
/// BaseStyle: sz=24, color=FF0000, italic=on.
/// ChildStyle: sz=28 (overrides). GrandchildStyle: color=0000FF (overrides).
/// Result: sz=28, color=0000FF, italic=on.
#[test]
fn non_toggle_grandchild_inherits_correctly() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "non-toggle-deep-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Grandchild style run"))
        .expect("should find grandchild paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "GrandchildStyle should inherit font_size=28 from ChildStyle \
         (not 24 from BaseStyle). Per §17.7.1, child overrides parent per-property."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "GrandchildStyle sets color=0000FF, overriding BaseStyle's FF0000."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "Italic set at BaseStyle should inherit through to GrandchildStyle. \
         Neither ChildStyle nor GrandchildStyle override it."
    );
}

/// §17.7.1: ChildStyle inherits from BaseStyle.
/// ChildStyle: sz=28 (overrides), color=FF0000 (inherited), italic=on (inherited).
#[test]
fn non_toggle_child_inherits_from_base() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "non-toggle-deep-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Child style run"))
        .expect("should find child paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "ChildStyle overrides font_size to 28."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "ChildStyle inherits color=FF0000 from BaseStyle."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "ChildStyle inherits italic=on from BaseStyle."
    );
}

/// §17.7.1: BaseStyle has all three properties directly.
#[test]
fn non_toggle_base_has_all_props() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "non-toggle-deep-chain");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Base style run"))
        .expect("should find base paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "BaseStyle sets font_size=24."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "BaseStyle sets color=FF0000."
    );
    assert!(
        run.marks.contains(&Mark::Italic),
        "BaseStyle sets italic=on."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 7. Implicit Normal style (§17.7.4.17)
//
// When a paragraph has no explicit pStyle, the default paragraph style
// (w:type="paragraph" w:default="1", typically "Normal") is implied.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.4.17: Paragraph with no pStyle should get Normal's color and font_size.
#[test]
fn implicit_normal_style_applies_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "implicit-normal-style");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Implicit Normal style"))
        .expect("should find implicit-normal paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("008000"),
        "unstyled paragraph should get color=008000 from Normal style. \
         Per §17.7.4.17, when no pStyle is present, the default paragraph \
         style is implied."
    );
}

/// §17.7.4.17: Paragraph with no pStyle should get Normal's font_size.
#[test]
fn implicit_normal_style_applies_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "implicit-normal-style");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Implicit Normal style"))
        .expect("should find implicit-normal paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "unstyled paragraph should get font_size=28 from Normal style. \
         Per §17.7.4.17, the default paragraph style applies implicitly."
    );
}

/// §17.7.4.17: Explicit pStyle=Normal should produce the same result.
#[test]
fn explicit_normal_style_matches_implicit() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "implicit-normal-style");
    let paras = common::all_paragraphs(&doc);

    let p_implicit = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Implicit Normal style"))
        .expect("should find implicit-normal paragraph");
    let p_explicit = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Explicit Normal style"))
        .expect("should find explicit-normal paragraph");

    let implicit_run = &text_nodes(p_implicit)[0];
    let explicit_run = &text_nodes(p_explicit)[0];

    assert_eq!(
        implicit_run.style_props.color, explicit_run.style_props.color,
        "implicit and explicit Normal should produce the same color"
    );
    assert_eq!(
        implicit_run.style_props.font_size, explicit_run.style_props.font_size,
        "implicit and explicit Normal should produce the same font_size"
    );
}

/// §17.7.4.17: Different pStyle should NOT get Normal's properties.
#[test]
fn custom_style_not_normal() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "implicit-normal-style");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Custom para style"))
        .expect("should find custom-style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("0000FF"),
        "CustomPara style sets color=0000FF, not Normal's 008000."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 8. Character style overrides paragraph style rPr (§17.7.2)
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.2: Character style font_size overrides paragraph style font_size.
#[test]
fn char_style_overrides_para_font_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "char-overrides-para-rpr");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Char overrides para size"))
        .expect("should find char-overrides paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(32),
        "SizesChar (char style, sz=32) should override ColorPara (para style, sz=24). \
         Per §17.7.2, character style properties override paragraph style properties."
    );
}

/// §17.7.2: Character style doesn't set color — para style color persists.
#[test]
fn char_style_preserves_para_color() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "char-overrides-para-rpr");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Char overrides para size"))
        .expect("should find char-overrides paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "SizesChar doesn't set color, so ColorPara's color=FF0000 should persist. \
         Per §17.7.2, char style only overrides properties it explicitly sets."
    );
}

/// §17.7.2: Without char style, para style's font_size applies.
#[test]
fn para_style_font_size_without_char() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "char-overrides-para-rpr");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Para style only"))
        .expect("should find para-only paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(24),
        "without char style, para style's font_size=24 should apply."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("FF0000"),
        "without char style, para style's color=FF0000 should apply."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 9. docDefaults rPr + style cascade (§17.7.5)
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.5: Style overrides docDefaults font_size but inherits color.
#[test]
fn doc_defaults_rpr_style_overrides_size() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-rpr-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Override style run"))
        .expect("should find override-style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(28),
        "OverrideStyle sets font_size=28, overriding docDefaults' 20. \
         Per §17.7.5, style properties override document defaults per-property."
    );
}

/// §17.7.5: Style doesn't set color — docDefaults color persists.
#[test]
fn doc_defaults_rpr_color_inherited() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-rpr-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Override style run"))
        .expect("should find override-style paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.color.as_deref(),
        Some("808080"),
        "OverrideStyle doesn't set color — docDefaults' color=808080 should persist. \
         Per §17.7.5, unoverridden document defaults apply."
    );
}

/// §17.7.5: Unstyled run gets docDefaults directly.
#[test]
fn doc_defaults_rpr_unstyled_gets_defaults() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "doc-defaults-rpr-cascade");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Unstyled run"))
        .expect("should find unstyled paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    assert_eq!(
        run.style_props.font_size,
        Some(20),
        "unstyled run should get font_size=20 from docDefaults."
    );
    assert_eq!(
        run.style_props.color.as_deref(),
        Some("808080"),
        "unstyled run should get color=808080 from docDefaults."
    );
}

// ═══════════════════════════════════════════════════════════════════════════
// 10. Multiple toggle properties independent behavior (§17.7.3)
//
// Different toggle properties should behave independently. Bold and italic
// are both toggles, but XOR for bold shouldn't affect italic.
// ═══════════════════════════════════════════════════════════════════════════

/// §17.7.3: Para style bold=on, italic=on + char style bold=on.
/// Bold: XOR para(on) ^ char(on) = off per ECMA, on per Word.
/// Italic: only para sets it → on (no XOR needed).
#[test]
fn toggle_multi_bold_xor_italic_independent() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "toggle-multi-property");
    let paras = common::all_paragraphs(&doc);

    let p = paras
        .iter()
        .find(|p| common::paragraph_text(p).contains("Multi toggle test"))
        .expect("should find multi-toggle paragraph");

    let nodes = text_nodes(p);
    let run = &nodes[0];

    // Italic should be ON regardless of bold XOR behavior.
    // Only para style sets italic, char style doesn't touch it.
    assert!(
        run.marks.contains(&Mark::Italic),
        "italic should be ON — only para style sets it, char style doesn't. \
         Per §17.7.3, each toggle property is independent."
    );

    // Bold: XOR gives off (ECMA), reset gives on (Word).
    // This test documents the Word-compatible expectation.
    assert!(
        run.marks.contains(&Mark::Bold),
        "para style bold=on + char style bold=on should produce bold=ON \
         per Word behavior (MS-OI29500 §2.1.258 reset semantics). \
         ECMA §17.7.3 XOR would give bold=OFF."
    );
}
