//! Spec-compliance tests: titlePg + First-kind Inheritance Interaction
//! (ISO 29500-1 sections 17.10.6 + 17.10.2)
//!
//! These tests verify the interaction between titlePg (which controls only
//! whether the title-page header/footer is DISPLAYED for a section) and
//! per-kind header/footer inheritance across sections.
//!
//! titlePg gates DISPLAY, not file CONTENT: the parsed model carries First-kind
//! refs and stories verbatim regardless of titlePg, and lets the consumer
//! (Word) apply the display rule from `title_page` at render time. Inherited
//! First-kind refs persist through the chain even when sections lack titlePg.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/section-titlepg-interaction/create_fixtures.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, SectionProperties, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-titlepg-interaction";

// -- helpers ----------------------------------------------------------------

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(blocks: &'a [BlockNode], out: &mut Vec<&'a SectionProperties>) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// Fixture 1: titlepg-gap-inheritance
//
// S1 (mid-doc): titlePg=true, Default+First headers+footers
// S2 (mid-doc): no titlePg, no declarations (inherits from S1)
// S3 (body-level): titlePg=true, no declarations (inherits from S2)
//
// After inheritance + filtering:
//   S1: Default+First (titlePg, kept)
//   S2: Default only (no titlePg, First filtered)
//   S3: Default+First (titlePg, kept -- First inherited via S2 before filter)
// ==========================================================================

/// S1 should have both Default and First header refs (titlePg=true).
#[test]
fn gap_s1_has_default_and_first_header_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    assert!(
        sections.len() >= 2,
        "should have at least 2 mid-document sections, got {}",
        sections.len()
    );

    let s1 = sections[0];
    assert_eq!(
        s1.title_page,
        Some(true),
        "S1 should have titlePg=true, got {:?}",
        s1.title_page
    );

    let has_default = s1
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = s1
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S1 should have Default header ref");
    assert!(has_first, "S1 should have First header ref (titlePg=true)");
}

/// S1 should have both Default and First footer refs (titlePg=true).
#[test]
fn gap_s1_has_default_and_first_footer_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let has_default = s1
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = s1
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S1 should have Default footer ref");
    assert!(has_first, "S1 should have First footer ref (titlePg=true)");
}

/// S2 (no titlePg) inherits BOTH Default and First header refs. titlePg gates
/// DISPLAY, not the stored model (ISO 29500-1 §17.10.6), so the inherited First
/// ref is carried verbatim and let Word apply the display rule at render time.
#[test]
fn gap_s2_inherits_default_and_first_header_ref() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    let s2 = sections[1];

    assert!(
        s2.title_page != Some(true),
        "S2 should NOT have titlePg=true, got {:?}",
        s2.title_page
    );

    let has_default = s2
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = s2
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_default,
        "S2 should have inherited Default header ref from S1"
    );
    assert!(
        has_first,
        "S2 should also inherit the First header ref (titlePg gates display, not the stored model)"
    );
}

/// S2 (no titlePg) inherits BOTH Default and First footer refs (titlePg gates
/// display, not the stored model).
#[test]
fn gap_s2_inherits_default_and_first_footer_ref() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    let s2 = sections[1];

    let has_default = s2
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = s2
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_default,
        "S2 should have inherited Default footer ref from S1"
    );
    assert!(
        has_first,
        "S2 should also inherit the First footer ref (titlePg gates display, not the stored model)"
    );
}

/// S3 (body-level, titlePg=true) should have both Default and First header refs,
/// inherited from S1 through S2 (S2 also carries the First ref; titlePg gates
/// display, not the stored model).
#[test]
fn gap_s3_has_default_and_first_header_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S3)");

    assert_eq!(
        body_sp.title_page,
        Some(true),
        "S3 should have titlePg=true, got {:?}",
        body_sp.title_page
    );

    let has_default = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S3 should have inherited Default header ref");
    assert!(
        has_first,
        "S3 (titlePg=true) should have First header ref inherited from S1 through S2"
    );
}

/// S3 (body-level, titlePg=true) should have both Default and First footer refs.
#[test]
fn gap_s3_has_default_and_first_footer_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S3)");

    let has_default = body_sp
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(has_default, "S3 should have inherited Default footer ref");
    assert!(
        has_first,
        "S3 (titlePg=true) should have First footer ref inherited from S1 through S2"
    );
}

/// S3's First header ref should point to S1's First header (same part_path).
#[test]
fn gap_s3_first_header_is_s1s_first_header() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let s1_first_header = s1
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S1 should have First header ref");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S3)");

    let s3_first_header = body_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S3 should have First header ref");

    assert_eq!(
        s1_first_header.part_path, s3_first_header.part_path,
        "S3's First header should be the same as S1's First header (inherited). \
         S1 part_path={}, S3 part_path={}",
        s1_first_header.part_path, s3_first_header.part_path
    );

    // Verify the actual content
    let story = doc
        .headers
        .iter()
        .find(|h| h.part_name == s3_first_header.part_path)
        .expect("First header story should exist in doc.headers");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Header"),
        "S3's First header content should be 'S1 First Header', got: '{text}'"
    );
}

/// S3's First footer ref should point to S1's First footer (same part_path).
#[test]
fn gap_s3_first_footer_is_s1s_first_footer() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let s1_first_footer = s1
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S1 should have First footer ref");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S3)");

    let s3_first_footer = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S3 should have First footer ref");

    assert_eq!(
        s1_first_footer.part_path, s3_first_footer.part_path,
        "S3's First footer should be the same as S1's First footer (inherited). \
         S1 part_path={}, S3 part_path={}",
        s1_first_footer.part_path, s3_first_footer.part_path
    );

    // Verify the actual content
    let story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s3_first_footer.part_path)
        .expect("First footer story should exist in doc.footers");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Footer"),
        "S3's First footer content should be 'S1 First Footer', got: '{text}'"
    );
}

/// Both First-kind header and footer stories should be preserved in doc
/// because S1 and S3 have titlePg=true.
#[test]
fn gap_first_stories_preserved_in_doc() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-gap-inheritance");

    let first_headers: Vec<_> = doc
        .headers
        .iter()
        .filter(|h| h.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_headers.len(),
        1,
        "doc.headers should have exactly 1 First-kind story, got {}",
        first_headers.len()
    );

    let first_footers: Vec<_> = doc
        .footers
        .iter()
        .filter(|f| f.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_footers.len(),
        1,
        "doc.footers should have exactly 1 First-kind story, got {}",
        first_footers.len()
    );
}

// ==========================================================================
// Fixture 2: titlepg-selective-first-kinds
//
// S1 (mid-doc): titlePg=true, Default header + First header +
//               Default footer + First footer
// S2 (body-level): titlePg=true, only Default footer (overrides S1's)
//
// S2 should inherit: Default header, First header, First footer from S1
// S2 should use its own: Default footer
// ==========================================================================

/// S2 should have inherited Default header from S1 (S2 declares no headers).
#[test]
fn selective_s2_inherits_default_header() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-selective-first-kinds");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let default_ref = body_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have inherited Default header ref from S1");

    let story = doc
        .headers
        .iter()
        .find(|h| h.part_name == default_ref.part_path)
        .expect("Default header story should exist");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 Default Header"),
        "S2's Default header should be S1's: 'S1 Default Header', got: '{text}'"
    );
}

/// S2 should have inherited First header from S1 (S2 has titlePg, no own First header).
#[test]
fn selective_s2_inherits_first_header() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-selective-first-kinds");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let first_ref = body_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S2 should have inherited First header ref from S1");

    let story = doc
        .headers
        .iter()
        .find(|h| h.part_name == first_ref.part_path)
        .expect("First header story should exist");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Header"),
        "S2's First header should be S1's: 'S1 First Header', got: '{text}'"
    );
}

/// S2 should have its own Default footer (overrides S1's).
#[test]
fn selective_s2_uses_own_default_footer() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-selective-first-kinds");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let s1_default_footer = s1
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S1 should have Default footer ref");

    let s2_default_footer = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default)
        .expect("S2 should have Default footer ref");

    assert_ne!(
        s1_default_footer.part_path, s2_default_footer.part_path,
        "S2's Default footer should be its own, not inherited from S1. \
         S1 part_path={}, S2 part_path={}",
        s1_default_footer.part_path, s2_default_footer.part_path
    );

    let story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s2_default_footer.part_path)
        .expect("S2's Default footer story should exist");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S2 Default Footer"),
        "S2's Default footer should contain 'S2 Default Footer', got: '{text}'"
    );
}

/// S2 should have inherited First footer from S1 (S2 has titlePg, no own First footer).
#[test]
fn selective_s2_inherits_first_footer() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-selective-first-kinds");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let s1_first_footer = s1
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S1 should have First footer ref");

    let s2_first_footer = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S2 should have inherited First footer ref from S1");

    assert_eq!(
        s1_first_footer.part_path, s2_first_footer.part_path,
        "S2's First footer should be inherited from S1. \
         S1 part_path={}, S2 part_path={}",
        s1_first_footer.part_path, s2_first_footer.part_path
    );

    let story = doc
        .footers
        .iter()
        .find(|f| f.part_name == s2_first_footer.part_path)
        .expect("First footer story should exist");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Footer"),
        "S2's First footer should be S1's: 'S1 First Footer', got: '{text}'"
    );
}

/// S2 should have exactly 2 header refs (Default + First) and 2 footer refs
/// (Default + First).
#[test]
fn selective_s2_ref_counts() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-selective-first-kinds");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        body_sp.header_refs.len(),
        2,
        "S2 should have 2 header refs (Default + First), got {:?}",
        body_sp.header_refs
    );
    assert_eq!(
        body_sp.footer_refs.len(),
        2,
        "S2 should have 2 footer refs (Default + First), got {:?}",
        body_sp.footer_refs
    );
}

// ==========================================================================
// Fixture 3: no-section-has-titlepg-first-stories-removed
//
// S1 (mid-doc): no titlePg, declares Default+First headers+footers
// S2 (body-level): no titlePg, no declarations
//
// No section has titlePg, but First-kind refs and stories are still preserved
// (titlePg gates display, not content); Word applies the display rule.
// ==========================================================================

/// S1 (declares First refs) keeps its First-kind header ref even with no
/// titlePg — titlePg gates DISPLAY, not the stored model (ISO 29500-1 §17.10.6).
#[test]
fn no_titlepg_s1_keeps_first_header_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let sections = section_paragraphs(&doc);
    assert!(
        !sections.is_empty(),
        "should have at least one mid-document section"
    );

    let s1 = sections[0];
    let first_refs: Vec<_> = s1
        .header_refs
        .iter()
        .filter(|r| r.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_refs.len(),
        1,
        "S1's declared First header ref must be preserved even with no titlePg \
         (display is gated by title_page, not by mutating the model), got {first_refs:?}"
    );
}

/// S1 keeps its First-kind footer ref even with no titlePg.
#[test]
fn no_titlepg_s1_keeps_first_footer_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let first_refs: Vec<_> = s1
        .footer_refs
        .iter()
        .filter(|r| r.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_refs.len(),
        1,
        "S1's declared First footer ref must be preserved even with no titlePg, got {first_refs:?}"
    );
}

/// S2 inherits S1's First-kind header ref even with no titlePg (display gating
/// happens at render time, not by mutating the model).
#[test]
fn no_titlepg_s2_inherits_first_header_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let first_refs: Vec<_> = body_sp
        .header_refs
        .iter()
        .filter(|r| r.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_refs.len(),
        1,
        "S2 should inherit S1's First header ref even with no titlePg, got {first_refs:?}"
    );
}

/// S2 inherits S1's First-kind footer ref even with no titlePg.
#[test]
fn no_titlepg_s2_inherits_first_footer_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let first_refs: Vec<_> = body_sp
        .footer_refs
        .iter()
        .filter(|r| r.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_refs.len(),
        1,
        "S2 should inherit S1's First footer ref even with no titlePg, got {first_refs:?}"
    );
}

/// doc.headers preserves the First-kind story even when no section has titlePg
/// — the part exists in the package regardless of display state.
#[test]
fn no_titlepg_first_header_story_preserved_in_doc() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let first_headers: Vec<_> = doc
        .headers
        .iter()
        .filter(|h| h.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_headers.len(),
        1,
        "doc.headers must preserve the First-kind story even when no section has titlePg \
         (the part exists in the package regardless of display), got {} First-kind stories",
        first_headers.len()
    );
}

/// doc.footers preserves the First-kind story even when no section has titlePg.
#[test]
fn no_titlepg_first_footer_story_preserved_in_doc() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let first_footers: Vec<_> = doc
        .footers
        .iter()
        .filter(|f| f.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_footers.len(),
        1,
        "doc.footers must preserve the First-kind story even when no section has titlePg \
         (the part exists in the package regardless of display), got {} First-kind stories",
        first_footers.len()
    );
}

/// S1 should still have Default header ref (only First is filtered).
#[test]
fn no_titlepg_s1_keeps_default_header_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let has_default = s1
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    assert!(has_default, "S1 should still have Default header ref");
}

/// S1 should still have Default footer ref (only First is filtered).
#[test]
fn no_titlepg_s1_keeps_default_footer_ref() {
    let (_rt, doc) =
        common::import_fixture(FIXTURES, "no-section-has-titlepg-first-stories-removed");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let has_default = s1
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    assert!(has_default, "S1 should still have Default footer ref");
}

// ==========================================================================
// Fixture 4: titlepg-only-on-later-section
//
// S1 (mid-doc): no titlePg, declares Default+First headers+footers
// S2 (body-level): titlePg=true, no declarations (inherits from S1)
//
// Both S1 and S2 carry the First refs (titlePg gates display, not content):
// S1 declares them, S2 has titlePg=true. First-kind stories preserved.
// ==========================================================================

/// S1 (declares First refs) keeps its First header ref even with no titlePg —
/// titlePg gates DISPLAY, not the stored model (ISO 29500-1 §17.10.6).
#[test]
fn later_titlepg_s1_keeps_first_header_ref() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let sections = section_paragraphs(&doc);
    assert!(
        !sections.is_empty(),
        "should have at least one mid-document section"
    );

    let s1 = sections[0];
    let has_first = s1
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_first,
        "S1's declared First header ref must be preserved even with no titlePg \
         (display is gated by title_page, not by mutating the model)"
    );
}

/// S1 keeps its First footer ref even with no titlePg.
#[test]
fn later_titlepg_s1_keeps_first_footer_ref() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let has_first = s1
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_first,
        "S1's declared First footer ref must be preserved even with no titlePg \
         (display is gated by title_page, not by mutating the model)"
    );
}

/// S1 should still have Default header ref.
#[test]
fn later_titlepg_s1_keeps_default_header_ref() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let sections = section_paragraphs(&doc);
    let s1 = sections[0];

    let has_default = s1
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    assert!(has_default, "S1 should still have Default header ref");
}

/// S2 should have inherited Default + First header refs (titlePg=true).
#[test]
fn later_titlepg_s2_has_default_and_first_header_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    assert_eq!(
        body_sp.title_page,
        Some(true),
        "S2 should have titlePg=true, got {:?}",
        body_sp.title_page
    );

    let has_default = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .header_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_default,
        "S2 should have inherited Default header ref from S1"
    );
    assert!(
        has_first,
        "S2 (titlePg=true) should have inherited First header ref from S1"
    );
}

/// S2 should have inherited Default + First footer refs (titlePg=true).
#[test]
fn later_titlepg_s2_has_default_and_first_footer_refs() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let has_default = body_sp
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::Default);
    let has_first = body_sp
        .footer_refs
        .iter()
        .any(|r| r.kind == HeaderFooterKind::First);
    assert!(
        has_default,
        "S2 should have inherited Default footer ref from S1"
    );
    assert!(
        has_first,
        "S2 (titlePg=true) should have inherited First footer ref from S1"
    );
}

/// S2's First header should point to S1's First header content.
#[test]
fn later_titlepg_s2_first_header_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let first_ref = body_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S2 should have First header ref");

    let story = doc
        .headers
        .iter()
        .find(|h| h.part_name == first_ref.part_path)
        .expect("First header story should exist in doc.headers");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Header"),
        "S2's First header should be S1's: 'S1 First Header', got: '{text}'"
    );
}

/// S2's First footer should point to S1's First footer content.
#[test]
fn later_titlepg_s2_first_footer_content() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (S2)");

    let first_ref = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::First)
        .expect("S2 should have First footer ref");

    let story = doc
        .footers
        .iter()
        .find(|f| f.part_name == first_ref.part_path)
        .expect("First footer story should exist in doc.footers");
    let text = blocks_text(&story.blocks);
    assert!(
        text.contains("S1 First Footer"),
        "S2's First footer should be S1's: 'S1 First Footer', got: '{text}'"
    );
}

/// doc.headers should STILL have First-kind story (because S2 has titlePg).
#[test]
fn later_titlepg_first_header_story_preserved() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let first_headers: Vec<_> = doc
        .headers
        .iter()
        .filter(|h| h.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_headers.len(),
        1,
        "doc.headers should have 1 First-kind story (S2 has titlePg), got {}",
        first_headers.len()
    );
}

/// doc.footers should STILL have First-kind story (because S2 has titlePg).
#[test]
fn later_titlepg_first_footer_story_preserved() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "titlepg-only-on-later-section");

    let first_footers: Vec<_> = doc
        .footers
        .iter()
        .filter(|f| f.kind == HeaderFooterKind::First)
        .collect();
    assert_eq!(
        first_footers.len(),
        1,
        "doc.footers should have 1 First-kind story (S2 has titlePg), got {}",
        first_footers.len()
    );
}
