//! Spec-compliance tests: Table Border Weight Ranking
//! (MS-OI29500 §2.1.169)
//!
//! These tests verify that the border weight ranking formula correctly assigns
//! ranks to all border styles per the spec's "border number" table, and that
//! dotted/dashed styles always receive weight 1 regardless of border width.
//!
//! Fixture DOCX files are generated by:
//! `testdata/spec-compliance/table-border-weight-ranking/create_docs.py`
//!
//! Constraints covered:
//! 1. Compound/3D/wave styles must use their correct rank (7, 16, 20, etc.)
//! 2. Dotted/dashed styles must always get weight 1 regardless of size

use stemma::{BlockNode, BorderStyle, CanonDoc};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/table-border-weight-ranking";

// -- helpers ------------------------------------------------------------------

fn first_table(doc: &CanonDoc) -> &stemma::TableNode {
    doc.blocks
        .iter()
        .find_map(|b| match &b.block {
            BlockNode::Table(t) => Some(t),
            _ => None,
        })
        .expect("document should contain at least one table")
}

// =============================================================================
// 1. Compound border beats single at equal size
//    MS-OI29500 §2.1.169: thinThickSmallGap has rank 7, single has rank 1.
// =============================================================================

/// Verifies MS-OI29500 §2.1.169: thinThickSmallGap (rank 7) beats single
/// (rank 1) at same size. Weight = sz * rank: 8*7=56 vs 8*1=8.
#[test]
fn spec_compound_border_beats_single_at_equal_size() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "compound-beats-single");
    let table = first_table(&doc);

    // Shared edge between cell (0,0) and cell (0,1).
    // Cell (0,0) right: thinThickSmallGap sz=8 red (rank 7, weight=56)
    // Cell (0,1) left:  single sz=8 blue (rank 1, weight=8)
    // Red should win.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // After conflict resolution, both sides of the shared edge should agree
    // on the winning border (thinThickSmallGap, red).
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (thinThickSmallGap wins) — \
         MS-OI29500 §2.1.169: thinThickSmallGap rank=7 (weight=56) beats \
         single rank=1 (weight=8)"
    );
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border should remain red (winner)"
    );
}

/// MS-OI29500 §2.1.169: wave (rank 16) beats single (rank 1) at same size.
/// Weight = 8*16=128 vs 8*1=8.
#[test]
fn spec_wave_border_beats_single_at_equal_size() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "compound-beats-single");
    let table = first_table(&doc);

    // Shared edge between cell (0,1) and cell (0,2).
    // Cell (0,1) right: wave sz=8 green (rank 16, weight=128)
    // Cell (0,2) left:  single sz=8 blue (rank 1, weight=8)
    // Green should win.
    let cell_01_right = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,1) should have a right border");
    let cell_02_left = table.rows[0].cells[2]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,2) should have a left border");

    // After conflict resolution, both sides should show the wave green border.
    assert_eq!(
        cell_02_left.color.as_deref(),
        Some("00FF00"),
        "cell (0,2) left border should be green (wave wins) — \
         MS-OI29500 §2.1.169: wave rank=16 (weight=128) beats \
         single rank=1 (weight=8)"
    );
    assert_eq!(
        cell_01_right.color.as_deref(),
        Some("00FF00"),
        "cell (0,1) right border should remain green (winner)"
    );
}

// =============================================================================
// 2. Dotted/dashed borders always get weight 1
//    MS-OI29500 §2.1.169: "The borders with dotted and dashed styles shall
//    be assigned the weight 1 regardless of the border width and number."
// =============================================================================

/// Verifies MS-OI29500 §2.1.169: dotted/dashed borders always get weight 1.
/// dotted sz=24 has weight=1, single sz=4 has weight=4. Single wins.
#[test]
fn spec_dotted_border_always_weight_1_loses_to_small_single() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "dotted-dashed-always-weight-1");
    let table = first_table(&doc);

    // Shared edge between cell (0,0) and cell (0,1).
    // Cell (0,0) right: dotted sz=24 red (weight=1 per spec)
    // Cell (0,1) left:  single sz=4 blue (weight=4)
    // Blue single should win because 4 > 1.
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("0000FF"),
        "cell (0,1) left border should be blue (single wins) — \
         MS-OI29500 §2.1.169: dotted always has weight=1 regardless of size, \
         so single sz=4 (weight=4) beats dotted sz=24 (weight=1)"
    );
    assert_eq!(
        cell_01_left.style,
        BorderStyle::Single,
        "cell (0,1) left border style should be Single (winner)"
    );
    assert_eq!(
        cell_01_left.size,
        Some(4),
        "cell (0,1) left border size should be 4 (from winning single border)"
    );
}

// =============================================================================
// 3. threeDEmboss (rank 20) beats double (rank 3) at same size
//    MS-OI29500 §2.1.169: threeDEmboss is ranked 20.
// =============================================================================

/// Verifies MS-OI29500 §2.1.169: threeDEmboss (rank 20) beats double (rank 3)
/// at same size. Weight = 4*20=80 vs 4*3=12.
#[test]
fn spec_3d_emboss_beats_double_at_equal_size() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "3d-emboss-high-rank");
    let table = first_table(&doc);

    // Shared edge between cell (0,0) and cell (0,1).
    // Cell (0,0) right: threeDEmboss sz=4 red (rank 20, weight=80)
    // Cell (0,1) left:  double sz=4 blue (rank 3, weight=12)
    // Red should win.
    let cell_00_right = table.rows[0].cells[0]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.right.as_ref())
        .expect("cell (0,0) should have a right border");
    let cell_01_left = table.rows[0].cells[1]
        .formatting
        .borders
        .as_ref()
        .and_then(|b| b.left.as_ref())
        .expect("cell (0,1) should have a left border");

    // After conflict resolution, both sides should show threeDEmboss red.
    assert_eq!(
        cell_01_left.color.as_deref(),
        Some("FF0000"),
        "cell (0,1) left border should be red (threeDEmboss wins) — \
         MS-OI29500 §2.1.169: threeDEmboss rank=20 (weight=80) beats \
         double rank=3 (weight=12)"
    );
    assert_eq!(
        cell_00_right.color.as_deref(),
        Some("FF0000"),
        "cell (0,0) right border should remain red (winner)"
    );
}
