//! Spec-compliance tests: Numbering + Indent/Spacing Interaction
//!
//! These tests verify the interaction between numbering-level paragraph
//! properties (§17.9.22), paragraph style indent/spacing, and direct
//! paragraph properties (§17.3.1.12).
//!
//! `resolve_effective_indent()` in `styles.rs` does a per-field merge
//! (direct > numbering level > style) per §17.3.1.12 + §17.9.22.
//!
//! Fixture DOCX files are generated by `testdata/spec-compliance/create_docs.py`.

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/numbering-indent";

// ── Direct w:ind partial override with numbering ────────────────

/// ISO 29500-1 §17.3.1.12 + §17.9.22: When a paragraph has numbering with
/// level indent (left=720, hanging=360), and direct w:ind sets only w:left="1440",
/// the direct w:ind should replace the numbering level's indent.
///
/// Per §17.9.22: "Paragraph properties specified on the numbered paragraph
/// itself override the paragraph properties specified by pPr elements within
/// a numbering lvl element."
///
/// The fixture has:
///   P0: numbering level 0 (left=720, hanging=360) + direct w:ind w:left="1440"
///   P1: numbering level 0 (left=720, hanging=360) only (control)
///
/// Expected P0: left=1440, firstLine=-360 (direct left overrides numbering left,
/// but absent firstLine inherits numbering's hanging per §17.3.1.12).
#[test]
fn gap025_direct_ind_partial_override_with_numbering() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-partial-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: numbering + direct w:ind w:left="1440"
    // Per §17.3.1.12, per-attribute cascade: left from direct, firstLine from numbering.
    let p0_indent = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        p0_indent.left,
        Some(1440),
        "P0 left should be 1440 (from direct w:ind)"
    );
    assert_eq!(
        p0_indent.effective_first_line_twips,
        Some(-360),
        "P0 firstLine should be -360: absent in direct, inherited from numbering \
         hanging=360 per §17.3.1.12 per-attribute cascade."
    );
}

/// Control: numbered paragraph with no direct indent gets numbering level indent.
#[test]
fn gap025_control_numbering_only_indent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-partial-override");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P1: numbering only, no direct indent
    let p1_indent = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(
        p1_indent.left,
        Some(720),
        "P1 left should be 720 (from numbering level)"
    );
    assert_eq!(
        p1_indent.effective_first_line_twips,
        Some(-360),
        "P1 firstLine should be -360 (hanging=360 from numbering level)"
    );
}

// ── Direct w:ind w:left="0" zeroing numbering indent ────────────

/// ISO 29500-1 §17.9.22: Direct w:ind w:left="0" on a numbered paragraph
/// should zero out the numbering indent completely.
///
/// The fixture has:
///   P0: numbering level 0 (left=720, hanging=360) + direct w:ind w:left="0"
///   P1: numbering level 0 only (control)
///
/// Expected P0: left=0, firstLine=-360 (direct left=0 overrides numbering left,
/// but absent firstLine inherits numbering hanging per §17.3.1.12).
#[test]
fn gap025_direct_zero_overrides_numbering_indent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "direct-zero-overrides");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: direct w:ind w:left="0" — per-attribute cascade: left from direct, firstLine from numbering.
    let p0_indent = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent (firstLine from numbering)");
    assert_eq!(
        p0_indent.left,
        Some(0),
        "P0 left should be 0 (direct override)"
    );
    assert_eq!(
        p0_indent.effective_first_line_twips,
        Some(-360),
        "P0 firstLine should be -360: absent in direct, inherited from numbering \
         hanging=360 per §17.3.1.12 per-attribute cascade."
    );

    // P1: control — numbering only
    let p1_indent = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(p1_indent.left, Some(720), "P1 left from numbering level");
    assert_eq!(
        p1_indent.effective_first_line_twips,
        Some(-360),
        "P1 firstLine from numbering hanging"
    );
}

// ── Numbering level overrides style indent ───────────────────────────────

/// ISO 29500-1 §17.9.22: Numbering level's pPr takes priority over style indent.
///
/// The fixture has:
///   P0: Style (indent left=360) + numbering level 0 (left=720, hanging=360)
///   P1: Style (indent left=360) only (control)
///
/// Expected P0: left=720, firstLine=-360 (numbering overrides style).
/// Expected P1: left=360.
#[test]
fn numbering_level_overrides_style_indent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "numbering-overrides-style");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: numbering level indent should override style indent
    let p0_indent = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(
        p0_indent.left,
        Some(720),
        "P0 left should be 720 (numbering level overrides style's 360)"
    );
    assert_eq!(
        p0_indent.effective_first_line_twips,
        Some(-360),
        "P0 firstLine should be -360 (from numbering level hanging=360)"
    );

    // P1: style only, no numbering
    let p1_indent = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(
        p1_indent.left,
        Some(360),
        "P1 left should be 360 (from style only)"
    );
}

// ── numPr from deep basedOn style chain ─────────────

/// ISO 29500-1 §17.7.4.3 + §17.7.4.14: numPr defined on StyleA should be
/// inherited through StyleB (basedOn StyleA) and StyleC (basedOn StyleB).
///
/// The fixture has:
///   StyleA: numPr (numId=1, ilvl=0) with numbering level indent left=720, hanging=360
///   StyleB: basedOn StyleA
///   StyleC: basedOn StyleB
///   P0-P2: three paragraphs using StyleC
///
/// Expected: All three paragraphs should have numbering (1., 2., 3.) and
/// indent left=720, firstLine=-360 from the numbering level.
#[test]
fn gap026_numpr_inherited_through_deep_basedon_chain() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "numpr-deep-basedon");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // All paragraphs should have numbering from the style chain
    for (i, p) in paras.iter().take(3).enumerate() {
        let numbering = p.numbering.as_ref();
        assert!(
            numbering.is_some(),
            "P{i} should have numbering info inherited from style chain (StyleC -> StyleB -> StyleA)"
        );

        let num = numbering.unwrap();
        assert_eq!(num.ilvl, 0, "P{i} should be at numbering level 0");

        let expected_prefix = format!("{}.", i + 1);
        assert_eq!(
            num.synthesized_text, expected_prefix,
            "P{i} should have prefix '{expected_prefix}', got '{}'",
            num.synthesized_text
        );
    }

    // Check indent from numbering level
    let p0_indent = paras[0]
        .indent
        .as_ref()
        .expect("P0 should have indent from numbering level");
    assert_eq!(p0_indent.left, Some(720), "P0 left from numbering level");
    assert_eq!(
        p0_indent.effective_first_line_twips,
        Some(-360),
        "P0 firstLine from numbering hanging"
    );
}

// ── lvlOverride with partial attributes ──────────────────────────────────

/// ISO 29500-1 §17.9.8 + §17.9.26: A lvlOverride with only startOverride
/// should preserve the format and indent from the abstract numbering level.
///
/// The fixture has:
///   Abstract level 0: decimal, left=720, hanging=360, start=1
///   numId=1: uses abstract directly
///   numId=2: lvlOverride with startOverride=5 (no full level replacement)
///   P0: numId=1 (should be "1.", indent left=720, firstLine=-360)
///   P1: numId=2 (should be "5.", same indent)
///   P2: numId=2 (should be "6.", same indent)
#[test]
fn lvl_override_start_only_preserves_indent() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "lvl-override-partial");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 3,
        "expected at least 3 paragraphs, got {}",
        paras.len()
    );

    // P0: numId=1, original numbering
    let p0_num = paras[0]
        .numbering
        .as_ref()
        .expect("P0 should have numbering");
    assert!(
        p0_num.synthesized_text.contains('1'),
        "P0 prefix should contain '1', got '{}'",
        p0_num.synthesized_text
    );
    let p0_indent = paras[0].indent.as_ref().expect("P0 should have indent");
    assert_eq!(p0_indent.left, Some(720), "P0 left from abstract level");
    assert_eq!(
        p0_indent.effective_first_line_twips,
        Some(-360),
        "P0 firstLine from abstract level hanging"
    );

    // P1: numId=2, startOverride=5 — indent should be same as abstract
    let p1_num = paras[1]
        .numbering
        .as_ref()
        .expect("P1 should have numbering");
    assert!(
        p1_num.synthesized_text.contains('5'),
        "P1 prefix should contain '5' (startOverride), got '{}'",
        p1_num.synthesized_text
    );
    let p1_indent = paras[1].indent.as_ref().expect("P1 should have indent");
    assert_eq!(
        p1_indent.left,
        Some(720),
        "P1 left should be 720 (from abstract level, startOverride doesn't affect indent)"
    );
    assert_eq!(
        p1_indent.effective_first_line_twips,
        Some(-360),
        "P1 firstLine should be -360 (from abstract level)"
    );

    // P2: numId=2, continuation — should be "6."
    let p2_num = paras[2]
        .numbering
        .as_ref()
        .expect("P2 should have numbering");
    assert!(
        p2_num.synthesized_text.contains('6'),
        "P2 prefix should contain '6', got '{}'",
        p2_num.synthesized_text
    );
    let p2_indent = paras[2].indent.as_ref().expect("P2 should have indent");
    assert_eq!(p2_indent.left, Some(720), "P2 left from abstract level");
}

// ── Numbering + style spacing interaction ───────────────────────

/// ISO 29500-1 §17.9.22 + §17.3.1.33: Numbering levels don't define spacing.
/// Style spacing should apply. Direct w:spacing should override style spacing.
///
/// The fixture has:
///   Style: spacing before=120, after=120
///   Numbering level: indent only (no spacing)
///   P0: Style + numbering, no direct spacing
///   P1: Style + numbering + direct w:spacing w:before="0"
///
/// Expected P0: spacing before=120, after=120 (from style).
/// Expected P1: spacing before=0 (direct override), after may be 120 or absent
///              depending on whole-element vs per-field semantics.
#[test]
fn gap027_numbering_does_not_interfere_with_style_spacing() {
    let (_runtime, doc) = common::import_fixture(FIXTURES, "numbering-spacing-interaction");
    let paras = common::all_paragraphs(&doc);
    assert!(
        paras.len() >= 2,
        "expected at least 2 paragraphs, got {}",
        paras.len()
    );

    // P0: spacing from style (before=120, after=120), numbering doesn't affect spacing
    let p0_spacing = paras[0]
        .spacing
        .as_ref()
        .expect("P0 should have spacing from style");
    assert_eq!(
        p0_spacing.before,
        Some(120),
        "P0 before should be 120 from style"
    );
    assert_eq!(
        p0_spacing.after,
        Some(120),
        "P0 after should be 120 from style"
    );

    // P1: direct w:spacing w:before="0" overrides style before
    let p1_spacing = paras[1].spacing.as_ref().expect("P1 should have spacing");
    assert_eq!(
        p1_spacing.before,
        Some(0),
        "P1 before should be 0 (direct override)"
    );
    // Per-attribute inheritance (§17.3.1.33): absent after inherits from style.
    assert_eq!(
        p1_spacing.after,
        Some(120),
        "P1 after should inherit 120 from style (per-attribute, §17.3.1.33)"
    );
}
