//! Spec-compliance tests: Blank Footer Synthesis (ECMA-376 section 17.10.2)
//!
//! Per ECMA-376 section 17.10.2: when a section has no footerReference for the
//! Default kind, a blank default footer should be synthesized (mirroring
//! blank header synthesis).
//!
//! Tests assert *correct* spec-defined behavior. Failing tests indicate
//! that blank footer synthesis is not implemented.
//!
//! Fixture DOCX files are generated by
//! `testdata/spec-compliance/section-footer-synthesis/create_fixtures.py`.

use stemma::{BlockNode, CanonDoc, HeaderFooterKind, InlineNode, TrackedBlock};

use crate::common;

const FIXTURES: &str = "testdata/spec-compliance/section-footer-synthesis";

// -- helpers ----------------------------------------------------------------

/// Extract plain text from tracked blocks.
fn blocks_text(blocks: &[TrackedBlock]) -> String {
    let mut text = String::new();
    for tb in blocks {
        if let BlockNode::Paragraph(p) = &tb.block {
            for inline in p.all_inlines() {
                if let InlineNode::Text(t) = inline {
                    text.push_str(&t.text);
                }
            }
        }
    }
    text
}

/// Collect all mid-document section properties (from pPr/sectPr).
fn section_paragraphs(doc: &CanonDoc) -> Vec<&stemma::SectionProperties> {
    let mut props = Vec::new();
    collect_section_props_tracked(&doc.blocks, &mut props);
    props
}

fn collect_section_props_tracked<'a>(
    blocks: &'a [TrackedBlock],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for tracked in blocks {
        match &tracked.block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

fn collect_section_props_bare<'a>(
    blocks: &'a [BlockNode],
    out: &mut Vec<&'a stemma::SectionProperties>,
) {
    for block in blocks {
        match block {
            BlockNode::Paragraph(p) => {
                if let Some(ref sp) = p.section_properties {
                    out.push(sp);
                }
            }
            BlockNode::Table(t) => {
                for row in &t.rows {
                    for cell in &row.cells {
                        collect_section_props_bare(&cell.blocks, out);
                    }
                }
            }
            BlockNode::OpaqueBlock(_) => {}
        }
    }
}

// ==========================================================================
// Fixture 1: single-section-no-footer
// ==========================================================================

/// ECMA-376 section 17.10.2: Single-section document with a default header
/// but NO footerReference should get a synthesized blank default footer.
#[test]
fn spec_single_section_no_footer_gets_blank_default() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "single-section-no-footer");

    // Verify the header was imported (sanity check)
    assert!(
        !doc.headers.is_empty(),
        "fixture should have at least one header (the explicit default header)"
    );

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("single-section doc must have body_section_properties");

    // The body section should have a Default footer ref (synthesized blank)
    let default_footer_ref = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default);
    assert!(
        default_footer_ref.is_some(),
        "ECMA-376 section 17.10.2: body section must have a Default footer ref \
         (synthesized blank) when no footerReference is declared. \
         footer_refs = {:?}",
        body_sp.footer_refs
    );

    // The synthesized footer story must exist in doc.footers
    let part_path = &default_footer_ref.unwrap().part_path;
    let story = doc.footers.iter().find(|f| &f.part_name == part_path);
    assert!(
        story.is_some(),
        "ECMA-376 section 17.10.2: synthesized blank footer story must exist \
         in doc.footers (part_path={part_path})"
    );

    // The story should be blank (one paragraph with no text)
    let story = story.unwrap();
    assert_eq!(
        story.blocks.len(),
        1,
        "synthesized blank footer should have exactly one paragraph, got {}",
        story.blocks.len()
    );
    if let BlockNode::Paragraph(p) = &story.blocks[0].block {
        assert!(
            p.all_inlines().next().is_none(),
            "synthesized blank footer paragraph should have no inlines"
        );
    } else {
        panic!("synthesized blank footer story block should be a paragraph");
    }
}

// ==========================================================================
// Fixture 2: first-section-no-footer
// ==========================================================================

/// ECMA-376 section 17.10.2: Multi-section document where the first section
/// has no footerReference. A blank default footer should be synthesized for
/// the first section.
#[test]
fn spec_first_section_no_footer_gets_blank_default() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "first-section-no-footer");

    let mid_sections = section_paragraphs(&doc);
    assert!(
        !mid_sections.is_empty(),
        "fixture should have at least one mid-document section break"
    );

    let first_sp = mid_sections[0];

    // The first section should have a Default footer ref (synthesized blank)
    let default_footer_ref = first_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default);
    assert!(
        default_footer_ref.is_some(),
        "ECMA-376 section 17.10.2: first section must have a Default footer ref \
         (synthesized blank) when no footerReference is declared. \
         footer_refs = {:?}",
        first_sp.footer_refs
    );

    // The synthesized footer story must exist in doc.footers
    let part_path = &default_footer_ref.unwrap().part_path;
    let story = doc.footers.iter().find(|f| &f.part_name == part_path);
    assert!(
        story.is_some(),
        "ECMA-376 section 17.10.2: synthesized blank footer story must exist \
         in doc.footers (part_path={part_path})"
    );

    // The story should be blank (one paragraph with no text)
    let story = story.unwrap();
    assert_eq!(
        story.blocks.len(),
        1,
        "synthesized blank footer should have exactly one paragraph, got {}",
        story.blocks.len()
    );
    if let BlockNode::Paragraph(p) = &story.blocks[0].block {
        assert!(
            p.all_inlines().next().is_none(),
            "synthesized blank footer paragraph should have no inlines"
        );
    } else {
        panic!("synthesized blank footer story block should be a paragraph");
    }

    // Section 2 (body section) should have its own explicit footer
    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("body_section_properties should exist (Section 2)");

    let s2_default_footer = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default);
    assert!(
        s2_default_footer.is_some(),
        "Section 2 should have its own Default footer ref"
    );

    // Section 2's footer should contain the explicit text
    let s2_part_path = &s2_default_footer.unwrap().part_path;
    let s2_story = doc.footers.iter().find(|f| &f.part_name == s2_part_path);
    assert!(
        s2_story.is_some(),
        "Section 2's footer story should exist in doc.footers"
    );
    let s2_text = blocks_text(&s2_story.unwrap().blocks);
    assert!(
        s2_text.contains("Section 2 Footer"),
        "Section 2's footer should contain 'Section 2 Footer', got: '{s2_text}'"
    );
}

// ==========================================================================
// Fixture 3: single-section-no-footer-no-header
// ==========================================================================

/// ECMA-376 section 17.10.2: Single-section document with NO headerReference
/// and NO footerReference. Both a blank default header AND a blank default
/// footer should be synthesized.
#[test]
fn spec_single_section_no_footer_no_header_gets_both_blanks() {
    let (_rt, doc) = common::import_fixture(FIXTURES, "single-section-no-footer-no-header");

    let body_sp = doc
        .body_section_properties
        .as_ref()
        .expect("single-section doc must have body_section_properties");

    // -- Blank header synthesis (already implemented, sanity check) --
    let default_header_ref = body_sp
        .header_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default);
    assert!(
        default_header_ref.is_some(),
        "ECMA-376 section 17.10.2: body section must have a Default header ref \
         (synthesized blank) when no headerReference is declared. \
         header_refs = {:?}",
        body_sp.header_refs
    );

    let header_story = doc
        .headers
        .iter()
        .find(|h| h.part_name == default_header_ref.unwrap().part_path);
    assert!(
        header_story.is_some(),
        "synthesized blank header story must exist in doc.headers"
    );
    assert_eq!(
        doc.headers.len(),
        1,
        "doc.headers should have exactly 1 entry (synthesized blank), got {}",
        doc.headers.len()
    );

    // -- Blank footer synthesis --
    let default_footer_ref = body_sp
        .footer_refs
        .iter()
        .find(|r| r.kind == HeaderFooterKind::Default);
    assert!(
        default_footer_ref.is_some(),
        "ECMA-376 section 17.10.2: body section must have a Default footer ref \
         (synthesized blank) when no footerReference is declared. \
         footer_refs = {:?}",
        body_sp.footer_refs
    );

    let footer_story = doc
        .footers
        .iter()
        .find(|f| f.part_name == default_footer_ref.unwrap().part_path);
    assert!(
        footer_story.is_some(),
        "synthesized blank footer story must exist in doc.footers"
    );
    assert_eq!(
        doc.footers.len(),
        1,
        "doc.footers should have exactly 1 entry (synthesized blank), got {}",
        doc.footers.len()
    );

    // Both stories should be blank (one paragraph, no inlines)
    let header = header_story.unwrap();
    assert_eq!(
        header.blocks.len(),
        1,
        "blank header should have one paragraph"
    );
    if let BlockNode::Paragraph(p) = &header.blocks[0].block {
        assert!(
            p.all_inlines().next().is_none(),
            "blank header paragraph should have no inlines"
        );
    }

    let footer = footer_story.unwrap();
    assert_eq!(
        footer.blocks.len(),
        1,
        "blank footer should have one paragraph"
    );
    if let BlockNode::Paragraph(p) = &footer.blocks[0].block {
        assert!(
            p.all_inlines().next().is_none(),
            "blank footer paragraph should have no inlines"
        );
    }
}
