//! Auto-generated by the spec-word-compliance workflow for area
//! "OPC physical package (ZIP): structural validity, part-name constraints,
//! feature restrictions".
//!
//! Each `#[test]` encodes a normative rule from ISO/IEC 29500-2 (OPC) /
//! ECMA-376 Part 1 §11.2 about the physical ZIP package: item-name mapping,
//! required package items, ZIP feature restrictions (Annex B), and
//! consumption tolerance (data descriptors, archive comments).
//!
//! A FAILING assertion here is a real Word-compliance gap in stemma (the
//! engine diverges from what Word produces or consumes) — do NOT weaken the
//! assertion to make it pass.
//!
//! Coverage spans the OPC physical-package rules end to end: canonical
//! content-type Override for a WML extra part, ASCII part-name positive form,
//! ASCII case-insensitive Default / Override matching, the case-mismatched-part
//! roundtrip-emits-one-entry rule, duplicate-part rejection, and two checks
//! against real Word's open behavior.

use std::io::{Cursor, Read, Write};

use stemma::ExportOptions;
use stemma::api::Document;
use zip::write::FileOptions;

// ---------------------------------------------------------------------------
// Prelude: package plumbing
// ---------------------------------------------------------------------------

const W_NS: &str = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";

fn document_xml_for(body_xml: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="{W_NS}"><w:body>{body_xml}</w:body></w:document>"#
    )
}

fn content_types_for(extra_parts: &[(&str, &str)]) -> String {
    let mut s = String::from(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>"#,
    );
    for (name, _) in extra_parts {
        let content_type = match *name {
            "word/styles.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"
            }
            "word/numbering.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"
            }
            "word/settings.xml" => {
                "application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"
            }
            other => panic!("test plumbing: no content type mapping for extra part {other}"),
        };
        s.push_str(&format!(
            r#"<Override PartName="/{name}" ContentType="{content_type}"/>"#
        ));
    }
    s.push_str("</Types>");
    s
}

fn package_rels() -> &'static str {
    r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>"#
}

fn document_rels(extra_parts: &[(&str, &str)]) -> String {
    let mut s = String::from(
        r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">"#,
    );
    for (i, (name, _)) in extra_parts.iter().enumerate() {
        let (rel_type, target) = match *name {
            "word/styles.xml" => (
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles",
                "styles.xml",
            ),
            "word/numbering.xml" => (
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering",
                "numbering.xml",
            ),
            "word/settings.xml" => (
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings",
                "settings.xml",
            ),
            other => panic!("test plumbing: no relationship mapping for extra part {other}"),
        };
        s.push_str(&format!(
            r#"<Relationship Id="rIdX{i}" Type="{rel_type}" Target="{target}"/>"#
        ));
    }
    s.push_str("</Relationships>");
    s
}

/// Build a minimal valid .docx: [Content_Types].xml, _rels/.rels,
/// word/_rels/document.xml.rels, word/document.xml (+ any extra parts).
fn make_docx(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = document_xml_for(body_xml);
    let content_types = content_types_for(extra_parts);
    let doc_rels = document_rels(extra_parts);

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let opts: zip::write::FileOptions = zip::write::FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(package_rels().as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (name, content) in extra_parts {
            zip.start_file(*name, opts).unwrap();
            zip.write_all(content.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// Unzip `docx` and return the content of the item literally named
/// "word/document.xml" (ISO 29500-2 §7.3.4: part name minus the leading
/// slash). Reading strictly by this name is itself part of the observation:
/// if the writer used any other item name, this panics.
fn document_xml_of(docx: &[u8]) -> String {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(docx))
        .expect("output must be a readable stored/DEFLATE ZIP (ISO 29500-2 §7.3.6 / Annex B)");
    let mut file = archive.by_name("word/document.xml").expect(
        "main document part must live at the ZIP item literally named 'word/document.xml' \
         (part name /word/document.xml minus the leading slash — ISO 29500-2 §7.3.4)",
    );
    let mut s = String::new();
    file.read_to_string(&mut s)
        .expect("word/document.xml must inflate to UTF-8 text");
    s
}

/// Parse -> serialize with default options -> return the re-serialized
/// word/document.xml as a String.
fn reserialize(bytes: &[u8]) -> String {
    let doc = Document::parse(bytes).expect("Document::parse");
    let out = doc
        .serialize(&ExportOptions::default())
        .expect("Document::serialize");
    document_xml_of(&out)
}

/// Assert stemma::api::validate reports no errors for these bytes.
fn assert_opens_clean(bytes: &[u8], rule: &str) {
    let report = stemma::api::validate(bytes);
    assert!(
        report.ok,
        "{rule} — expected validation to report no errors, got issues: {:?}",
        report.issues
    );
}

// ---------------------------------------------------------------------------
// Hand-crafted ZIP writer (streaming/bit-3 entries; not expressible via the
// zip crate's writer, which always back-patches the local header).
// ---------------------------------------------------------------------------

/// Bitwise CRC-32 (IEEE 802.3 polynomial, reflected), as used by ZIP.
fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            if crc & 1 != 0 {
                crc = (crc >> 1) ^ 0xEDB8_8320;
            } else {
                crc >>= 1;
            }
        }
    }
    !crc
}

fn put_u16(buf: &mut Vec<u8>, v: u16) {
    buf.extend_from_slice(&v.to_le_bytes());
}
fn put_u32(buf: &mut Vec<u8>, v: u32) {
    buf.extend_from_slice(&v.to_le_bytes());
}

/// Build a ZIP where every entry is written in streaming mode: general-purpose
/// bit 3 set, crc/sizes zeroed in the local file header, real values in a
/// signed data descriptor (0x08074b50) after the data, and correct values in
/// the central directory. Entries are STORED (method 0 — Annex B Table B.4
/// permits stored alongside DEFLATE).
fn make_zip_with_data_descriptors(entries: &[(&str, &[u8])]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut central: Vec<(String, u32, u32, u32)> = Vec::new(); // name, crc, size, local offset

    for (name, data) in entries {
        let offset = out.len() as u32;
        let crc = crc32(data);
        let size = data.len() as u32;
        // Local file header — bit 3 set, crc/sizes zeroed.
        put_u32(&mut out, 0x0403_4b50);
        put_u16(&mut out, 20); // version needed
        put_u16(&mut out, 0x0008); // general purpose flags: bit 3 (data descriptor)
        put_u16(&mut out, 0); // method: stored
        put_u16(&mut out, 0); // mod time
        put_u16(&mut out, 0); // mod date
        put_u32(&mut out, 0); // crc-32 (zeroed under bit 3)
        put_u32(&mut out, 0); // compressed size (zeroed under bit 3)
        put_u32(&mut out, 0); // uncompressed size (zeroed under bit 3)
        put_u16(&mut out, name.len() as u16);
        put_u16(&mut out, 0); // extra len
        out.extend_from_slice(name.as_bytes());
        out.extend_from_slice(data);
        // Data descriptor with the optional 0x08074b50 signature.
        put_u32(&mut out, 0x0807_4b50);
        put_u32(&mut out, crc);
        put_u32(&mut out, size); // compressed size (stored => equal)
        put_u32(&mut out, size); // uncompressed size
        central.push((name.to_string(), crc, size, offset));
    }

    let cd_offset = out.len() as u32;
    for (name, crc, size, offset) in &central {
        put_u32(&mut out, 0x0201_4b50);
        put_u16(&mut out, 20); // version made by
        put_u16(&mut out, 20); // version needed
        put_u16(&mut out, 0x0008); // flags: bit 3
        put_u16(&mut out, 0); // method: stored
        put_u16(&mut out, 0); // mod time
        put_u16(&mut out, 0); // mod date
        put_u32(&mut out, *crc);
        put_u32(&mut out, *size);
        put_u32(&mut out, *size);
        put_u16(&mut out, name.len() as u16);
        put_u16(&mut out, 0); // extra len
        put_u16(&mut out, 0); // comment len
        put_u16(&mut out, 0); // disk number start
        put_u16(&mut out, 0); // internal attrs
        put_u32(&mut out, 0); // external attrs
        put_u32(&mut out, *offset);
        out.extend_from_slice(name.as_bytes());
    }
    let cd_size = out.len() as u32 - cd_offset;
    // End of central directory.
    put_u32(&mut out, 0x0605_4b50);
    put_u16(&mut out, 0); // disk
    put_u16(&mut out, 0); // disk with CD
    put_u16(&mut out, central.len() as u16);
    put_u16(&mut out, central.len() as u16);
    put_u32(&mut out, cd_size);
    put_u32(&mut out, cd_offset);
    put_u16(&mut out, 0); // comment len
    out
}

/// Build the standard four-part package as a streaming-mode (bit 3 /
/// data-descriptor) ZIP.
fn make_docx_with_data_descriptors(body_xml: &str) -> Vec<u8> {
    let document_xml = document_xml_for(body_xml);
    let content_types = content_types_for(&[]);
    let doc_rels = document_rels(&[]);
    make_zip_with_data_descriptors(&[
        ("[Content_Types].xml", content_types.as_bytes()),
        ("_rels/.rels", package_rels().as_bytes()),
        ("word/_rels/document.xml.rels", doc_rels.as_bytes()),
        ("word/document.xml", document_xml.as_bytes()),
    ])
}

/// Build the standard four-part package with a non-empty EOCD archive comment.
fn make_docx_with_archive_comment(body_xml: &str, comment: &str) -> Vec<u8> {
    let document_xml = document_xml_for(body_xml);
    let content_types = content_types_for(&[]);
    let doc_rels = document_rels(&[]);

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        zip.set_comment(comment);
        let opts: zip::write::FileOptions = zip::write::FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(package_rels().as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn opc_main_document_zip_item_name_no_leading_slash_ascii() {
    // Rule: when producing a package, the Main Document part (part name
    // /word/document.xml) shall be stored as a single ZIP item whose item name
    // is the part name with the leading forward slash removed — exactly the
    // ASCII, forward-slash-separated name 'word/document.xml'.
    // Refs: ISO/IEC 29500-2 §7.3.2, §7.3.3, §7.3.4.
    let bytes = make_docx(
        "<w:p><w:r><w:t>opc item name probe</w:t></w:r></w:p><w:sectPr/>",
        &[],
    );
    let xml = reserialize(&bytes);
    assert!(
        xml.contains("opc item name probe"),
        "§7.3.4: producer shall map part name /word/document.xml to the ZIP item \
         'word/document.xml' (leading '/' removed, ASCII, unique per §7.3.3); the probe text \
         must be readable from the item by exactly that name — expected XML to contain \
         'opc item name probe'"
    );
    assert!(
        xml.contains("<w:document"),
        "§7.3.2: a non-interleaved part is a single ZIP item; the complete main-document \
         stream (starting at its root element) must come back from the single item \
         'word/document.xml' — expected XML to contain '<w:document'"
    );
}

#[test]
fn opc_minimal_wordprocessingml_package_opens_clean() {
    // Rule: a package containing only the content-type item, the package
    // relationship item pointing at one Main Document part, and a Main
    // Document whose body is a single empty paragraph is the MINIMAL
    // conformant WordprocessingML package; a Word-aligned validator shall
    // report no errors for it.
    // Refs: ECMA-376/ISO 29500-1 §11.2, ISO/IEC 29500-2 §7.2.2.
    let bytes = make_docx("<w:p/><w:sectPr/>", &[]);
    assert_opens_clean(
        &bytes,
        "§11.2: the package-relationship item + content-type item + one Main Document part \
         (empty-paragraph body) constitute the minimal conformant WordprocessingML package; \
         Word opens it without repair, so stemma::api::validate must report no errors",
    );
}

#[test]
fn opc_package_production_deflate_or_stored_only_no_encryption() {
    // Rule: a produced ZIP-based package shall not include encryption and
    // shall not use any compression method other than DEFLATE (or stored),
    // so every conforming consumer can fully inflate the main part's stream.
    // Refs: ISO/IEC 29500-2 §7.3.1, §7.3.6, Annex B Tables B.3/B.4.
    let bytes = make_docx(
        "<w:p><w:r><w:t>deflate readability probe</w:t></w:r></w:p><w:sectPr/>",
        &[],
    );
    let xml = reserialize(&bytes);
    assert!(
        xml.contains("deflate readability probe"),
        "§7.3.6: production may use no encryption and no compression except DEFLATE \
         (Annex B Tables B.3/B.4); the reserialized main part must inflate completely with a \
         stored/DEFLATE-only reader and yield the original run text — expected XML to contain \
         'deflate readability probe'"
    );
    assert!(
        xml.contains("</w:document>"),
        "§7.3.6 + Annex B Table B.4: the item's data must be a plain stored/DEFLATE stream \
         (no patched data sets, no Deflate64) so inflation reaches the end of the part — \
         expected XML to contain '</w:document>'"
    );
}

#[test]
fn zip_data_descriptor_entries_open_clean() {
    // Rule: Word opens a DOCX whose ZIP entries were written in streaming mode
    // (general-purpose bit 3 set, crc/sizes zeroed in the local file header,
    // correct values in a data descriptor after the data); stemma must parse
    // and validate such a package cleanly, taking entry metadata from the data
    // descriptor / central directory rather than the zeroed local header.
    // Refs: ISO/IEC 29500-2 Annex B Table B.1 (data descriptor: consumption
    // Yes), Table B.5 (general-purpose bit 3: consumption Yes).
    let bytes =
        make_docx_with_data_descriptors("<w:p><w:r><w:t>Hello OPC</w:t></w:r></w:p><w:sectPr/>");
    assert_opens_clean(
        &bytes,
        "Annex B Tables B.1/B.5: data descriptor and general-purpose bit 3 are \
         consumption=Yes — 'a package implementer shall not fail to read the ZIP file \
         containing this record or field'; a bit-3 streaming package is a conformant \
         physical package and must validate with no errors",
    );
    let doc = Document::parse(&bytes).expect(
        "Annex B Table B.5 bit 3: a conformant consumer shall not fail to read a \
         streaming-mode (data-descriptor) package — Document::parse must succeed",
    );
    let text = doc.read_accepted().expect("read_accepted").to_text();
    assert_eq!(
        text.trim(),
        "Hello OPC",
        "Annex B Table B.5 bit 3: the correct sizes/crc live in the data descriptor \
         following the compressed data; a conformant consumer decodes the entry content \
         regardless, so the document text must read back intact"
    );
}

#[test]
fn zip_eocd_archive_comment_tolerated() {
    // Rule: Word opens a DOCX whose end-of-central-directory record carries a
    // non-empty ZIP file comment; the comment is read-tolerated (and ignored),
    // never a reason to refuse the package.
    // Refs: ISO/IEC 29500-2 Annex B Table B.2 (ZIP file comment: consumption
    // Yes, production No).
    let bytes = make_docx_with_archive_comment(
        "<w:p><w:r><w:t>Hello OPC</w:t></w:r></w:p><w:sectPr/>",
        "repacked by a tool that loves archive comments",
    );
    assert_opens_clean(
        &bytes,
        "Annex B Table B.2: the EOCD ZIP file comment field is consumption=Yes — a \
         commented archive 'shall not fail to read', so validation must report no errors",
    );
    let doc = Document::parse(&bytes).expect(
        "Annex B Table B.2: a consumer shall not fail to read an archive with an EOCD \
         comment — Document::parse must succeed",
    );
    let text = doc.read_accepted().expect("read_accepted").to_text();
    assert_eq!(
        text.trim(),
        "Hello OPC",
        "Annex B Table B.2: the EOCD comment may be ignored but the package contents are \
         unaffected; all parts remain readable, so the accepted text equals the document text"
    );
}

#[test]
fn opc_body_zero_blocks_only_sectpr_opens_clean() {
    // Rule: a main document whose w:body contains zero block-level elements
    // (only the trailing w:sectPr) is schema-valid WordprocessingML
    // (CT_Body: EG_BlockLevelElts minOccurs=0, sectPr optional) inside a
    // conformant OPC package; Word opens it without repair, and the engine
    // must keep the body's final sectPr on re-save.
    // Refs: ECMA-376 Part 1 §11.2, ISO 29500-2 §7.3, wml.xsd CT_Body.
    let bytes = make_docx("<w:sectPr/>", &[]);
    assert_opens_clean(
        &bytes,
        "wml.xsd CT_Body: EG_BlockLevelElts has minOccurs=0, so a body whose only child is \
         w:sectPr is schema-valid; Word opens it without repair (displays one empty \
         paragraph), therefore stemma::api::validate must report no errors",
    );
    let xml = reserialize(&bytes);
    assert!(
        xml.contains("<w:sectPr"),
        "wml.xsd CT_Body sequence ends with an optional sectPr; stemma's serializer \
         model-rebuilds the body-level sectPr and must not drop it (or fail) when the body \
         has zero blocks — expected re-serialized XML to contain '<w:sectPr' (synthesizing \
         an empty w:p alongside it is acceptable; this assertion only pins sectPr survival)"
    );
}

#[test]
fn opc_resave_content_type_item_and_unprefixed_main_part() {
    // Rule: every package the engine saves must remain a conformant OPC ZIP:
    // it contains the content-type item [Content_Types].xml and stores the
    // Main Document part under the slash-free, ASCII, unique ZIP item name
    // word/document.xml, so Word reopens the saved file without repair.
    // Refs: ECMA §11.2, ISO 29500-2 §7.3.3/§7.3.4/§7.3.7, MS-OE376 §2.1.8.
    let bytes = make_docx(
        "<w:p><w:r><w:t>OPC_RT_MARKER</w:t></w:r></w:p><w:sectPr/>",
        &[],
    );
    let doc = Document::parse(&bytes).expect("Document::parse");
    let saved = doc
        .serialize(&ExportOptions::default())
        .expect("Document::serialize");
    let xml = document_xml_of(&saved);
    assert!(
        xml.contains("OPC_RT_MARKER"),
        "ISO 29500-2 §7.3.4: the saved main part must live at ZIP item name \
         'word/document.xml' (leading slash removed, ASCII, unique per §7.3.3); reading the \
         re-serialized package's item by exactly that name must yield the marker text — \
         expected XML to contain 'OPC_RT_MARKER'"
    );
    assert_opens_clean(
        &saved,
        "ECMA §11.2 + ISO 29500-2 §7.3.7: validating the RE-SERIALIZED bytes — the saved \
         package must still contain the package-relationship item, the [Content_Types].xml \
         content-type item (declaring wordprocessingml.document.main+xml per MS-OE376 \
         §2.1.8), and the Main Document part, otherwise Word shows the repair prompt on \
         reopen",
    );
}

#[test]
fn zip_item_name_mapping_strips_leading_slash_on_save() {
    // Rule: when writing a package, the main document part (logical name
    // /word/document.xml) must be stored as the ZIP item 'word/document.xml':
    // leading slash removed, forward-slash separators, ASCII name — so a
    // conforming OPC/Word reader can resolve the part after stemma serializes.
    // Refs: ISO/IEC 29500-2 §7.3.3/§7.3.4, ECMA-376 Part 1 §11.2.
    let bytes = make_docx(
        "<w:p><w:r><w:t>ZipItemNameMarker</w:t></w:r></w:p><w:sectPr/>",
        &[],
    );
    let xml = reserialize(&bytes);
    assert!(
        xml.contains("ZipItemNameMarker"),
        "§7.3.4: the serialized package must store the main document at ZIP item name \
         'word/document.xml' (leading slash stripped, '/' separators, ASCII per §7.3.3); \
         the harness reads the re-serialized part strictly by that name — expected XML to \
         contain 'ZipItemNameMarker'"
    );
    assert_opens_clean(
        &bytes,
        "ECMA-376 Part 1 §11.2: the input is a conformant package (content-type item, \
         package-relationship item, Main Document part); the validator must not flag it",
    );
}

// ---------------------------------------------------------------------------
// Distinct-constraint coverage
// ---------------------------------------------------------------------------

const NUMBERING_CONTENT_TYPE: &str =
    "application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml";

/// True iff `validate` reports no errors (opens clean). The opens-clean tests
/// above use `assert_opens_clean`; the duplicate-part rules below need to assert the
/// NEGATIVE (a package that must NOT open clean), so they need the bool form.
fn opens_clean(bytes: &[u8]) -> bool {
    let report = stemma::api::validate(bytes);
    report.ok && report.issues.is_empty()
}

/// Render a `ValidationReport`'s issues for an assertion message.
fn validation_issues(bytes: &[u8]) -> String {
    let report = stemma::api::validate(bytes);
    format!(
        "ok={} issues={:?}",
        report.ok,
        report
            .issues
            .iter()
            .map(|i| format!("{:?}: {}", i.code, i.message))
            .collect::<Vec<_>>()
    )
}

/// Count ZIP entries with exactly `name`.
fn count_zip_entries_named(bytes: &[u8], name: &str) -> usize {
    let mut archive = zip::ZipArchive::new(Cursor::new(bytes)).expect("open zip");
    let mut count = 0;
    for i in 0..archive.len() {
        let file = archive.by_index(i).expect("zip entry");
        if file.name() == name {
            count += 1;
        }
    }
    count
}

/// Like `make_docx` but the xml Default extension is UPPER-CASE ("XML"). Tests
/// ASCII case-insensitive Default matching (OPC §7.2.3).
fn make_docx_with_upper_xml_default(body_xml: &str, extra_parts: &[(&str, &str)]) -> Vec<u8> {
    let document_xml = document_xml_for(body_xml);
    // content_types_for emits the lower-case xml Default; rewrite it to upper-case.
    let content_types = content_types_for(extra_parts)
        .replace(r#"Default Extension="xml""#, r#"Default Extension="XML""#);
    let doc_rels = document_rels(extra_parts);

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(package_rels().as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        for (name, content) in extra_parts {
            zip.start_file(*name, opts).unwrap();
            zip.write_all(content.as_bytes()).unwrap();
        }
        zip.finish().unwrap();
    }
    buf
}

/// A package whose body part is stored at `word/Document.xml` (upper-case D),
/// content-typed by Override `/word/document.xml` and targeted by the
/// relationship `word/Document.xml`. Tests ASCII case-insensitive Override
/// matching (OPC §7.2.3) and case-equivalent part resolution (OPC §6.2).
fn make_docx_with_uppercase_document_partname(body_xml: &str) -> Vec<u8> {
    let document_xml = document_xml_for(body_xml);
    let content_types = content_types_for(&[]);
    // Relationship target points at the upper-case stored part name.
    let rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/Document.xml"/></Relationships>"#;
    let doc_rels = document_rels(&[]);

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(rels.as_bytes()).unwrap();
        // The document part's rels live alongside it, case-matched.
        zip.start_file("word/_rels/Document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        zip.start_file("word/Document.xml", opts).unwrap();
        zip.write_all(document_xml.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

/// A package physically containing TWO ZIP items both named word/document.xml
/// (the second with different body text). OPC §6.2.2 / §7.3.3 forbid this.
fn make_docx_with_duplicate_document() -> Vec<u8> {
    let doc_a =
        document_xml_for("<w:p><w:r><w:t>First document part.</w:t></w:r></w:p><w:sectPr/>");
    let doc_b =
        document_xml_for("<w:p><w:r><w:t>Second document part.</w:t></w:r></w:p><w:sectPr/>");
    let content_types = content_types_for(&[]);
    let doc_rels = document_rels(&[]);

    let mut buf = Vec::new();
    {
        let mut zip = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts: FileOptions = FileOptions::default();
        zip.start_file("[Content_Types].xml", opts).unwrap();
        zip.write_all(content_types.as_bytes()).unwrap();
        zip.start_file("_rels/.rels", opts).unwrap();
        zip.write_all(package_rels().as_bytes()).unwrap();
        zip.start_file("word/_rels/document.xml.rels", opts)
            .unwrap();
        zip.write_all(doc_rels.as_bytes()).unwrap();
        // First entry.
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(doc_a.as_bytes()).unwrap();
        // Duplicate entry — same name, different content.
        zip.start_file("word/document.xml", opts).unwrap();
        zip.write_all(doc_b.as_bytes()).unwrap();
        zip.finish().unwrap();
    }
    buf
}

#[test]
fn numbering_part_emits_canonical_content_type_override() {
    // Rule: every WML part (e.g. word/numbering.xml) must be content-typed by a
    // matching Override carrying its canonical content type; the generic xml
    // Default is not sufficient, so the package with the numbering Override must
    // open clean. Refs: ECMA-376 Part 1 §11.2/§15.2, OPC §7.2.3.
    let body = r#"<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>First numbered item.</w:t></w:r></w:p><w:sectPr/>"#;
    let numbering = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>"#;
    let b = make_docx(body, &[("word/numbering.xml", numbering)]);
    assert!(
        opens_clean(&b),
        "Every WML part (e.g. word/numbering.xml) must be content-typed by a matching Override \
         carrying its canonical content type ({NUMBERING_CONTENT_TYPE}); the generic xml Default \
         is not sufficient, so the package with the numbering Override must open clean (ECMA-376 \
         Part 1 §11.2/§15.2, OPC §7.2.3). Got: {}",
        validation_issues(&b)
    );
}

#[test]
fn non_ascii_part_names_not_loadable_by_word() {
    // POSITIVE side of the rule: the conformant, Word-loadable form uses
    // ASCII-only part names and must open clean. (The negative — a non-ASCII
    // part name being rejected — is the oracle question recorded on the spec.)
    let body = r#"<w:p><w:r><w:t>All part names in this package are ASCII and Word-loadable.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert!(
        opens_clean(&b),
        "Word will not load a package with non-ASCII part names; the conformant Word-loadable form \
         uses ASCII-only part names and must validate clean (MS-OI29500 §2.1.1749, OPC §7.3.3). \
         Got: {}",
        validation_issues(&b)
    );
}

#[test]
fn content_type_default_extension_match_is_case_insensitive() {
    // Default Extension matching is ASCII case-insensitive, so Default
    // Extension="XML" (upper-case) must cover word/document.xml and
    // word/styles.xml; every part is content-typed and the package opens clean.
    // Refs: OPC §7.2.3, ECMA-376 Part 1 §11.2.
    let body = r#"<w:p><w:r><w:t>Case-insensitive extension match.</w:t></w:r></w:p><w:sectPr/>"#;
    let styles = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"></w:styles>"#;
    let b = make_docx_with_upper_xml_default(body, &[("word/styles.xml", styles)]);
    assert!(
        opens_clean(&b),
        "Default Extension matching is ASCII case-insensitive, so Default Extension=\"XML\" \
         (upper-case) must cover word/document.xml and word/styles.xml; every part is content-typed \
         and the package must open clean — no I-CT-001/002 (OPC §7.2.3, ECMA-376 Part 1 §11.2). \
         Got: {}",
        validation_issues(&b)
    );
}

#[test]
fn content_type_override_match_is_ascii_case_insensitive() {
    // ZIP item stored as word/Document.xml; its Override is /word/document.xml.
    // OPC §7.2.3 mandates ASCII case-insensitive PartName matching, so the part
    // is content-typed and the package opens clean. A case-sensitive validator
    // would falsely report I-CT-001 — that divergence is what this hunts.
    let body = r#"<w:p><w:r><w:t>Body served by a case-mismatched main-document part name.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx_with_uppercase_document_partname(body);
    assert!(
        opens_clean(&b),
        "Override PartName matching is ASCII case-insensitive, so a part stored as \
         word/Document.xml is content-typed by Override /word/document.xml; the package must open \
         clean — no I-CT-001 (OPC §7.2.3, §6.2.2). Got: {}",
        validation_issues(&b)
    );
}

#[test]
fn uppercase_document_partname_roundtrips_without_duplicate_part() {
    // Parse the case-mismatched package and run a full serialize. Part-name
    // resolution is ASCII case-insensitive (OPC §6.2), so the serializer must
    // recognize word/Document.xml as THE main document part: the output must
    // carry exactly one case-equivalent main-document entry, never a lower-case
    // sibling (which would violate part-name uniqueness, OPC §7.3).
    let body = r#"<w:p><w:r><w:t>Case-mismatched main document, full roundtrip.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx_with_uppercase_document_partname(body);
    let doc = Document::parse(&b).expect("a case-mismatched main-document part name must parse");
    let out = doc.serialize(&ExportOptions::default()).expect("serialize");

    let mut archive = zip::ZipArchive::new(Cursor::new(out.as_slice())).expect("open zip");
    let mut equivalent_entries = Vec::new();
    for i in 0..archive.len() {
        let file = archive.by_index(i).expect("zip entry");
        if file.name().eq_ignore_ascii_case("word/document.xml") {
            equivalent_entries.push(file.name().to_string());
        }
    }
    assert_eq!(
        equivalent_entries.len(),
        1,
        "exactly one main-document part after roundtrip (OPC §6.2, §7.3); got {equivalent_entries:?}"
    );
    assert!(
        opens_clean(&out),
        "the roundtripped package must validate clean. Got: {}",
        validation_issues(&out)
    );
}

// DocxArchive read fails loud with DocxError::DuplicatePartName on a duplicate
// ZIP entry name (OPC §6.2.2) rather than silently collapsing to
// last-writer-wins, so validate reports the package as not-clean like Word.
#[test]
fn duplicate_part_name_rejected() {
    // Build a package with TWO ZIP items both named word/document.xml. OPC
    // §6.2.2 / §7.3.3 forbid this; Word reports corruption. CORRECT behaviour is
    // to flag it — so opens_clean must be FALSE. If this assertion FAILS (i.e.
    // opens_clean is true), stemma swallowed the duplicate and diverges.
    let b = make_docx_with_duplicate_document();
    assert!(
        !opens_clean(&b),
        "Two ZIP items named word/document.xml violate part-name uniqueness; Word reports \
         corruption. stemma must NOT report the package as clean — if it does, it silently \
         collapsed the duplicate and diverges from Word (OPC §6.2.2, §7.3.3). Got: {}",
        validation_issues(&b)
    );
}

#[test]
fn duplicate_part_names_are_rejected() {
    // Positive side: a package with exactly ONE word/document.xml entry must
    // validate clean, AND the re-serialized package must emit exactly one
    // word/document.xml entry (the serializer must never duplicate a part on
    // roundtrip).
    let body = r#"<w:p><w:r><w:t>A package with exactly one document part validates clean.</w:t></w:r></w:p><w:sectPr/>"#;
    let b = make_docx(body, &[]);
    assert!(
        opens_clean(&b),
        "A package with exactly one word/document.xml must validate clean (OPC §7.3.3, §6.2.2). \
         Got: {}",
        validation_issues(&b)
    );
    let out = Document::parse(&b)
        .expect("parse")
        .serialize(&ExportOptions::default())
        .expect("serialize");
    let count = count_zip_entries_named(&out, "word/document.xml");
    assert_eq!(
        count, 1,
        "The serializer must emit exactly one word/document.xml entry on roundtrip; emitting two \
         would violate ZIP item-name uniqueness (OPC §7.3.3, §6.2.2). Got {count} entries."
    );
}
